force-app/main/default/objects/Case_Team__c/Case_Team__c.object-meta.xml
<CustomObject>
    <description>Used to identify groups of support techs across all business units.  Not to be confused with the standard Salesforce object CaseTeam.</description>
    <label>Case Team</label>
    <nameField>
        <displayFormat>CTN-{0000}</displayFormat>
        <label>Case Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Productivity__c/Employee_Productivity__c.object-meta.xml
<CustomObject>
    <label>Employee Productivity</label>
    <nameField>
        <label>Employee Productivity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee Productivity</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Productivity__c/fields/Case_Team__c.field-meta.xml
<CustomField>
    <fullName>Case_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Team</label>
    <referenceTo>Case_Team__c</referenceTo>
    <relationshipLabel>Employee Productivity</relationshipLabel>
    <relationshipName>Employee_Productivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Productivity__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee_Productivity__c/fields/Time_Card_Detail__c.field-meta.xml
<CustomField>
    <fullName>Time_Card_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Time Card Detail</label>
    <referenceTo>Time_Card_Details__c</referenceTo>
    <relationshipLabel>Employee Productivity</relationshipLabel>
    <relationshipName>Employee_Productivity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Productivity__c/fields/Week_Begin__c.field-meta.xml
<CustomField>
    <fullName>Week_Begin__c</fullName>
    <label>Week Begin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Card__c/Time_Card__c.object-meta.xml
<CustomObject>
    <label>Time Card</label>
    <nameField>
        <label>Time Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Card_Details__c/Time_Card_Details__c.object-meta.xml
<CustomObject>
    <label>Time Card Details</label>
    <nameField>
        <label>Time Card Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Card Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Card_Details__c/fields/Time_Card__c.field-meta.xml
<CustomField>
    <fullName>Time_Card__c</fullName>
    <label>Time Card</label>
    <referenceTo>Time_Card__c</referenceTo>
    <relationshipName>Time_Card_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestEmployeeProductivityController.cls
@isTest(SeeAllData = true)
public With Sharing class TestEmployeeProductivityController
{
    public static testmethod  void verifyMethods()
    {
        
        Savepoint sp = Database.setSavepoint();
        Time_Card__c testTimeCard = TimeCardExtension.createTestTimeCard();
        Time_Card_Details__c tcd = [select id from Time_Card_Details__c where Time_Card__c =: testTimeCard.id];
        
        //  create an emp record here so that the controller can query something
        Employee_Productivity__c testEmp = new Employee_Productivity__c();
        testEmp.Time_Card_Detail__c = tcd.id;
        testEmp.Case_Team__c = TimeCardExtension.createTestCaseTeam().id;
        testEmp.day__c = date.today();
        testEmp.week_begin__c = date.today();
        
        database.insert(testEmp);
        
        EmployeeProductivityController testEmpProd = new EmployeeProductivityController();
        String BusinessUnit;
        
        Boolean isLead = testEmpProd.isLead;
        User loggedInUser = testEmpProd.loggedInUser;
        Case_Team__c loggedInCaseTeam = testEmpProd.loggedInUserCaseTeam;
        
        testEmpProd.businessUnitUserChoice = 'All';
        System.AssertEquals(testEmpProd.variablePageBlockSectionTitle,'Omnitracs / XRS');
        
        testEmpProd.businessUnitUserChoice =  'Omnitracs';
        System.AssertEquals(testEmpProd.variablePageBlockSectionTitle,'Omnitracs');
        
        testEmpProd.businessUnitUserChoice =  'XRS';
        System.AssertEquals(testEmpProd.variablePageBlockSectionTitle,'XRS');
        
        testEmpProd.businessUnitUserChoice =  'Others';
        System.AssertEquals(testEmpProd.variablePageBlockSectionTitle,'Omnitracs');
        
        isLead = true;
        testEmpProd.refresh();
        
        testEmpProd.businessUnitUserChoice = 'All';
        testEmpProd.refresh();
        
        List<Employee_Productivity__c> lstCumulativeData = new List<Employee_Productivity__c>();
        
        lstCumulativeData = testEmpProd.roadnetPrimarySupport;
        lstCumulativeData = testEmpProd.roadnetStrategicSupport;
        lstCumulativeData = testEmpProd.RobinsonTier1;
        lstCumulativeData = testEmpProd.RobinsonTier2;
        lstCumulativeData = testEmpProd.loweTier1;
        lstCumulativeData = testEmpProd.loweTier2;
        lstCumulativeData = testEmpProd.featherTier1;
        lstCumulativeData = testEmpProd.featherTier2;
        lstCumulativeData = testEmpProd.jacobsTier0;
        lstCumulativeData = testEmpProd.jacobsTier1;
        lstCumulativeData = testEmpProd.jacobsTier2;
        lstCumulativeData = testEmpProd.bolhmanTier1;
        lstCumulativeData = testEmpProd.bolhmanTier2;
        
        testEmpProd.verifyUserIsApartOfCaseTeam();
        
        Database.rollback(sp);
        
        
    }
}