force-app/main/default/objects/SpringCMApiEnvironment__mdt/fields/AuthEndpoint__c.field-meta.xml
<CustomField>
    <fullName>AuthEndpoint__c</fullName>
    <description>https://auth[environment].springcm.com/oauth/[version]/token/sfaccesstoken</description>
    <inlineHelpText>Ensure to include fully qualified URL</inlineHelpText>
    <label>AuthEndpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SpringCMApiEnvironment.cls
public class SpringCMApiEnvironment {
    public static SpringCMApiEnvironment__mdt getApiEnvironment() {
        SpringCMEos.RetrieveEnvironment environment = new SpringCMEos.RetrieveEnvironment();
        String environmentPrefix = environment.getEnvironmentPrefix();

        //Default to Prod if for some reason its blank        
        String environmentqueryname = 'PROD';

        String prefix;
        if (String.isNotBlank(environmentPrefix)) 
            prefix = environmentPrefix.substringBefore('.').toLowerCase();

        if (Test.isRunningTest())
            environmentqueryname = 'TEST';

        else if (prefix=='na11' || prefix=='na21' || prefix=='www')
            environmentqueryname = 'PROD';

        else if (prefix=='uatna11' || prefix=='uat' || prefix=='cpqclm')
            environmentqueryname = 'UAT';

        else if (prefix=='qana11' || prefix=='qana21' || prefix=='qa')
            environmentqueryname = 'QA';

        else if (prefix=='qarna11')
            environmentqueryname = 'QAR';
        
        return [SELECT Client_Id__c, Client_Secret__c, AuthEndpoint__c
                FROM SpringCMApiEnvironment__mdt
                WHERE DeveloperName =: environmentqueryname];
    }
}