force-app/main/default/objects/Requirements__c/Requirements__c.object-meta.xml
<CustomObject>
    <description>Once User Stories are established, what are the next steps? Requirements, both functional and technical, are captured in this object, and provide the next steps, after User Stories are captured, and enable the progression of defining what is necessary to enable success.</description>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>User Stories capture initial, high-level objectives and outcomes that are desired. 

User Stories captures what a user does or needs to do as part of his or her job function.

User Stories captures the &apos;who&apos;, &apos;what&apos; and &apos;why&apos; of a requirement in a simple, concise way.

User Stories serve as the foundation from which all requirements will be built off of.</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/User_Story_Requirement__c.object-meta.xml
<CustomObject>
    <label>User Story Requirement</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story_Requirement__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewRequirement_Ctrl.cls
public class NewRequirement_Ctrl{
    public Requirements__c req {get;set;}
    
    public NewRequirement_Ctrl(){
        req = new Requirements__c();
    }
    
    public PageReference save(){
        try{
            insert req;
            User_Story_Requirement__c reqJunction = new User_Story_Requirement__c(Requirement__c = req.Id, 
                                                                                         User_Story__c = ApexPages.currentPage().getParameters().get('Id'));
            insert reqJunction;
            return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
        }catch(DMLException ex){
            ApexPages.addMessages(ex);
            return null;
        }
    }
    
    public PageReference saveAndNew(){
        try{
            insert req;
            User_Story_Requirement__c reqJunction = new User_Story_Requirement__c(Requirement__c = req.Id, 
                                                                                         User_Story__c = ApexPages.currentPage().getParameters().get('Id'));
            insert reqJunction;
            req = new Requirements__c();
            return new PageReference('/apex/NewRequirement?id=' + ApexPages.currentPage().getParameters().get('Id'));
        }catch(DMLException ex){    
            ApexPages.addMessages(ex);
            return null;
        }
    }
    
    public PageReference cancel(){
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
}