force-app/main/default/objects/Requirements__c/Requirements__c.object-meta.xml
<CustomObject>
    <description>Once User Stories are established, what are the next steps? Requirements, both functional and technical, are captured in this object, and provide the next steps, after User Stories are captured, and enable the progression of defining what is necessary to enable success.</description>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirements__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirements__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Engineering / R&amp;D</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales, Inside</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>User Stories capture initial, high-level objectives and outcomes that are desired. 

User Stories captures what a user does or needs to do as part of his or her job function.

User Stories captures the &apos;who&apos;, &apos;what&apos; and &apos;why&apos; of a requirement in a simple, concise way.

User Stories serve as the foundation from which all requirements will be built off of.</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/User_Story_Requirement__c.object-meta.xml
<CustomObject>
    <label>User Story Requirement</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story_Requirement__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <formula>TEXT( Requirement__r.Track__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Track</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Requirement__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ViewUserStory_Ext_Test.cls
@isTest
public class ViewUserStory_Ext_Test {

    public static testMethod void testAssociateReqs() {
        User_Story__c s = new User_Story__c();
        insert s;
        
        Requirements__c r1 = new Requirements__c(Title__c = 'Test 1', Track__c = 'Customer Support');
        Requirements__c r2 = new Requirements__c(Title__c = 'Test 2', Track__c = 'Sales');
        insert r1;
        insert r2;
        
        User_Story_Requirement__c j = new User_Story_Requirement__c(User_Story__c = s.Id, Requirement__c = r1.Id);
        insert j;
        
        Test.startTest();
        
        Test.setCurrentPage(Page.ViewUserStory);
        ApexPages.currentPage().getParameters().put('id',s.Id);
        ApexPages.StandardController con = new ApexPages.StandardController(s);
        ViewUserStory_Ext storyPage = new ViewUserStory_Ext(con);
        
        System.assert(true, storyPage.assignedReqsList[0].getValue() == r1.Id);
        System.assert(true, storyPage.unassignedReqsList[0].getValue() == r2.Id);
        
        List<SelectOption> newAssigned = new List<SelectOption>();
        List<SelectOption> newUnassigned = new List<SelectOption>();
        newAssigned.add(new SelectOption(r2.Id, r2.Title__c));
        newUnassigned.add(new SelectOption(r1.Id, r1.Title__c));
        
        storyPage.assignedReqsList = newAssigned;
        storyPage.unassignedReqsList = newUnassigned;
        
        storyPage.doSave();
        
        List<User_Story_Requirement__c> newJunctions = [SELECT Id, Requirement__c FROM User_Story_Requirement__c];
        
        System.assertEquals(1,newJunctions.size());
        System.assert(true, newJunctions[0].Requirement__c == r2.Id);
        
        storyPage.refreshFilter();
        
        Test.stopTest();
    }

}