force-app/main/default/objects/Requirements__c/Requirements__c.object-meta.xml
<CustomObject>
    <description>Once User Stories are established, what are the next steps? Requirements, both functional and technical, are captured in this object, and provide the next steps, after User Stories are captured, and enable the progression of defining what is necessary to enable success.</description>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirements__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirements__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Engineering / R&amp;D</fullName>
            </value>
            <value>
                <fullName>Executive</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales, Inside</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>CPQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>User Stories capture initial, high-level objectives and outcomes that are desired. 

User Stories captures what a user does or needs to do as part of his or her job function.

User Stories captures the &apos;who&apos;, &apos;what&apos; and &apos;why&apos; of a requirement in a simple, concise way.

User Stories serve as the foundation from which all requirements will be built off of.</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/User_Story_Requirement__c.object-meta.xml
<CustomObject>
    <label>User Story Requirement</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story_Requirement__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <formula>TEXT( Requirement__r.Track__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Track</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story_Requirement__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ViewUserStory_Ext.cls
public class ViewUserStory_Ext {

    private User_Story__c s;
    
    public List<Requirements__c> unassignedReqs {get; set;}
    private List<Requirements__c> assignedReqs;
    
    private List<User_Story_Requirement__c> junctions;
    
    public List<SelectOption> unassignedReqsList {get; set;}
    public List<SelectOption> assignedReqsList {get; set;}
    
    public List<SelectOption> filterOptions {get; set;}
    public String selectedFilter {get; set;}
    
    public Boolean canAccess {get; private set;}

    public ViewUserStory_Ext(ApexPages.StandardController std) {
        this.s = (User_Story__c)std.getRecord();
        
        //TODO: Store this ID in a Custom Setting or admin config
        List<PermissionSetAssignment> permSets = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId =: UserInfo.getUserId() AND PermissionSetId = '0PSW000000009Xo'];
        if (permsets.size() == 1) {
            this.canAccess = true;
        }
        else {
            this.canAccess = false;
        }
        
        unassignedReqs = new List<Requirements__c>();
        assignedReqs = new List<Requirements__c>();
        unassignedReqsList = new List<SelectOption>();
        assignedReqsList = new List<SelectOption>();
        
        unassignedReqs = [SELECT Id, Title__c FROM Requirements__c WHERE Id NOT IN (SELECT Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c =: this.s.Id)];

        assignedReqs = [SELECT Id, Title__c FROM Requirements__c WHERE Id IN (SELECT Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c =: this.s.Id)];
    
        for (Requirements__c r : unassignedReqs) {
            unassignedReqsList.add(new SelectOption(r.Id, r.Title__c));
        }
        
        for (Requirements__c r : assignedReqs) {
            assignedReqsList.add(new SelectOption(r.Id, r.Title__c));
        }
        
        junctions = new List<User_Story_Requirement__c>();
        junctions = [SELECT Id, Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c = :this.s.Id];
        
        List<Schema.PicklistEntry> trackValues = Requirements__c.Track__c.getDescribe().getPicklistValues();
        filterOptions = new List<SelectOption>();
        filterOptions.add(new SelectOption('All Tracks', 'All Tracks'));
        for (Schema.PicklistEntry pe : trackValues) {
            filterOptions.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        selectedFilter = 'All Tracks';
    }

    public PageReference doSave() {
        List<User_Story_Requirement__c> junctionsToInsert = new List<User_Story_Requirement__c>();
        List<User_Story_Requirement__c> junctionsToDelete = new List<User_Story_Requirement__c>();
        
        if (junctions.size() > 0) {
            delete junctions;
            junctions.clear();
        }
        
        // Determine Requirements that have been assigned
        for (SelectOption req : assignedReqsList) {
            junctionsToInsert.add(new User_Story_Requirement__c(Requirement__c = req.getValue(), User_Story__c = this.s.Id));
        }
        
        if (junctionsToInsert.size() > 0) {
            insert junctionsToInsert;
        }
        
        PageReference p = new PageReference('/apex/ViewUserStory?id=' + s.Id);
        p.setRedirect(true);
        
        return p;
    }

    public PageReference refreshFilter() {
        if (selectedFilter != 'All Tracks') {
            unassignedReqs = [SELECT Id, Title__c FROM Requirements__c WHERE Id NOT IN (SELECT Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c =: this.s.Id) AND Track__c =: selectedFilter];
        }
        else {
            unassignedReqs = [SELECT Id, Title__c FROM Requirements__c WHERE Id NOT IN (SELECT Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c =: this.s.Id)];
        }
        
        this.unassignedReqsList = new List<SelectOption>();
        for (Requirements__c r : unassignedReqs) {
            Boolean found = false;
            for (SelectOption r2 : assignedReqsList) {
                if (r2.getValue() == r.Id) {
                    found = true;
                }
            }
            if (!found) {
                this.unassignedReqsList.add(new SelectOption(r.Id, r.Title__c));
            }
        }
        
        return null;
    }

}