force-app/main/default/objects/AccountRecordTypes__c/AccountRecordTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Record Types of the account. Mainly referred in AllAccountUtils Class.</description>
    <label>AccountRecordTypes</label>
</CustomObject>

force-app/main/default/objects/AllAccountUtils__c/AllAccountUtils__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in AllAccountUtils class mainly for the Calculation Data Quality Score and generate Data Quality Description for the account.</description>
    <label>AllAccountUtils</label>
</CustomObject>

force-app/main/default/objects/Request_Form__c/Request_Form__c.object-meta.xml
<CustomObject>
    <label>Request Form</label>
    <nameField>
        <label>Request Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Form__c/fields/Confidential_Information_Contractors__c.field-meta.xml
<CustomField>
    <fullName>Confidential_Information_Contractors__c</fullName>
    <label>Confidential Information Contractors</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Confidential_Information_Parties__c.field-meta.xml
<CustomField>
    <fullName>Confidential_Information_Parties__c</fullName>
    <label>Confidential Information Parties</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Just Omnitracs</fullName>
            </value>
            <value>
                <fullName>Both/All Parties</fullName>
            </value>
            <value>
                <fullName>Just the other party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Include_affiliates__c.field-meta.xml
<CustomField>
    <fullName>Include_affiliates__c</fullName>
    <label>Include affiliates</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Primary_reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_reason__c</fullName>
    <label>Primary reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technology Evaluation: Make v. Buy</fullName>
            </value>
            <value>
                <fullName>Potential Acquisition of a company or its assets or patents</fullName>
            </value>
            <value>
                <fullName>Other: (explain below)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Request_For_Amendment__c.field-meta.xml
<CustomField>
    <fullName>Request_For_Amendment__c</fullName>
    <label>Request For Amendment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/Request_Form_Contact__c.object-meta.xml
<CustomObject>
    <label>Request Form Contact</label>
    <nameField>
        <label>Request Form Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Form Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Form_Contact__c/fields/Account_Associated__c.field-meta.xml
<CustomField>
    <fullName>Account_Associated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Associated</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Request Form Contacts</relationshipLabel>
    <relationshipName>Request_Form_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Contact_Associated__c.field-meta.xml
<CustomField>
    <fullName>Contact_Associated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Associated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Request Form Contacts</relationshipLabel>
    <relationshipName>Request_Form_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Multiparty__c.field-meta.xml
<CustomField>
    <fullName>Multiparty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Multiparty</label>
    <referenceTo>Request_Form__c</referenceTo>
    <relationshipLabel>Multiparties</relationshipLabel>
    <relationshipName>Multiparties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Last Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Request_Form__c.field-meta.xml
<CustomField>
    <fullName>Request_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>Request_Form__c</referenceTo>
    <relationshipLabel>Requestors</relationshipLabel>
    <relationshipName>Requestors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NDA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/State_Province_PL__c.field-meta.xml
<CustomField>
    <fullName>State_Province_PL__c</fullName>
    <label>State/Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Street_1__c.field-meta.xml
<CustomField>
    <fullName>Street_1__c</fullName>
    <label>Street 1</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/To_Create__c.field-meta.xml
<CustomField>
    <fullName>To_Create__c</fullName>
    <defaultValue>false</defaultValue>
    <label>To Create</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requestor</fullName>
            </value>
            <value>
                <fullName>First Party</fullName>
            </value>
            <value>
                <fullName>Additional Employee</fullName>
            </value>
            <value>
                <fullName>Second Party</fullName>
                <isActive>false</isActive>
                <label>Second Party</label>
            </value>
            <value>
                <fullName>Third Party</fullName>
                <isActive>false</isActive>
                <label>Third Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <label>Zipcode</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAssociateRequestFormController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAssociateRequestFormController {

    static testMethod void associateAccountsContactsTest() {
        PSAEnhancementTestData objPSAEnhancementTestData= new PSAEnhancementTestData();   
        List<AccountRecordTypes__c> lstRecordType= objPSAEnhancementTestData.customSettingsAccountRecordTypes();
        List<AllAccountUtils__c> lstCustomSettingsAccountUtils= objPSAEnhancementTestData.customSettingsAccountUtils();
        insert lstRecordType;     
        insert lstCustomSettingsAccountUtils;    
        Account accnt=objPSAEnhancementTestData.createAccount(lstRecordType); //insertion of the account record 
        accnt.Segment__c = 'Services';                     
        insert accnt;                
                                    
        Contact cntct=objPSAEnhancementTestData.createContact(accnt.Id);   //insertion of the Contact record  
        insert cntct;  
         
        Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Request_Form_Contact__c.getRecordTypeInfosByName();
        
        Request_Form__c rf = new Request_Form__c();
        rf.Primary_reason__c = 'Technology Evaluation: Make v. Buy';
        rf.Request_For_Amendment__c = 'Yes';
        rf.Confidential_Information_Parties__c = 'Just Omnitracs';
        rf.Confidential_Information_Contractors__c = 'Yes';
        rf.Include_affiliates__c = 'Yes';
        insert rf;
        
        Request_Form_Contact__c rfc = new Request_Form_Contact__c();
        rfc.recordTypeId=rtMapByName.get('Multi Party').getRecordTypeId();
        rfc.Multiparty__c = rf.Id;
        rfc.company__c = accnt.Name;
        rfc.First_name__c = 'Test';
        rfc.name__c = 'RFC1';
        rfc.Request_Type__c = 'NDA';
        rfc.Street_1__c = 'Test Street 1';
        rfc.City__c = 'Frisco';
        rfc.State_Province_PL__c = 'TX';
        rfc.Zipcode__c = '75035';
        rfc.Type__c = 'First Party';
        rfc.Account_associated__c = accnt.Id;
        rfc.contact_associated__c = cntct.Id;
        
        Request_Form_Contact__c rfc1 = new Request_Form_Contact__c();
        rfc1.recordTypeId=rtMapByName.get('Multi Party').getRecordTypeId();
        rfc1.Multiparty__c = rf.Id;
        rfc1.company__c = accnt.Name;
        rfc1.First_name__c = 'Test';
        rfc1.name__c = 'RFC2';
        rfc1.Request_Type__c = 'NDA';
        rfc1.Street_1__c = 'Test Street 1';
        rfc1.City__c = 'Frisco';
        rfc1.State_Province_PL__c = 'TX';
        rfc1.Zipcode__c = '75035';
        rfc1.Type__c = 'First Party';
        rfc1.To_Create__c = true;
        
        Request_Form_Contact__c rfc2 = new Request_Form_Contact__c();
        rfc2.recordTypeId=rtMapByName.get('Multi Party').getRecordTypeId();
        rfc2.Multiparty__c = rf.Id;
        rfc2.company__c = accnt.Name;
        rfc2.First_name__c = 'Test';
        rfc2.name__c = 'RFC3';
        rfc2.Request_Type__c = 'NDA';
        rfc2.Street_1__c = 'Test Street 1';
        rfc2.City__c = 'Frisco';
        rfc2.State_Province_PL__c = 'TX';
        rfc2.Zipcode__c = '75035';
        rfc2.Type__c = 'First Party';
        rfc.Account_associated__c = accnt.Id;
        rfc2.To_Create__c = true;
        
        List<Request_Form_Contact__c> rfcList = new List<Request_Form_Contact__c> {rfc, rfc1, rfc2};
        insert rfcList;
        
        AssociateRequestFormController arfc = new AssociateRequestFormController(new Apexpages.StandardController(rf)); 
        List<Account> accntList = [select Id from Account];
        List<Contact> cntctList = [select Id from Contact];
        System.assertEquals(1, accntList.size());
        System.assertEquals(1, cntctList.size());
        arfc.createAccountRFC();
        accntList = [select Id from Account];
       // System.assertEquals(3, accntList.size());
        
        Request_Form_Contact__c rfcTemp = [select Id,Account_associated__c, Contact_associated__c from Request_Form_Contact__c where Id = :rfcList.get(0).Id];
        System.assert(rfcTemp.Account_associated__c != null);
        
        arfc.createContactRFC();
        cntctList = [select Id from Contact];
      //  System.assertEquals(3, accntList.size());
        
        arfc.updateAccountRFC();
        arfc.updateContactRFC();
        arfc.cancel();
        
    }
}