force-app/main/default/objects/AccountRecordTypes__c/AccountRecordTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Record Types of the account. Mainly referred in AllAccountUtils Class.</description>
    <label>AccountRecordTypes</label>
</CustomObject>

force-app/main/default/objects/AllAccountUtils__c/AllAccountUtils__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in AllAccountUtils class mainly for the Calculation Data Quality Score and generate Data Quality Description for the account.</description>
    <label>AllAccountUtils</label>
</CustomObject>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>provide Information about the class,Instructor of the class and all the courses that class Contains</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Class Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_Code__c.field-meta.xml
<CustomField>
    <fullName>Class_Code__c</fullName>
    <externalId>true</externalId>
    <label>Class Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>unique name of the class.</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Class_Schedule__c</fullName>
    <description>To know when the class is scheduled.</description>
    <label>Class Schedule</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>used to select the course of the class</description>
    <label>Course</label>
    <referenceTo>Course_Catalog__c</referenceTo>
    <relationshipLabel>classes</relationshipLabel>
    <relationshipName>classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Instructor__c.field-meta.xml
<CustomField>
    <fullName>Instructor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Instructor of the class belongs to contacts.</description>
    <label>Instructor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>classes</relationshipLabel>
    <relationshipName>classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/Course_Catalog__c.object-meta.xml
<CustomObject>
    <description>Used to store information related to the Courses and class Containing these courses.</description>
    <label>Course Catalog</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Course Catalog Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Catalog__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <externalId>true</externalId>
    <label>Course Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>name of the course and no two courses having same Name.</description>
    <label>Course Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/fields/Course_Type__c.field-meta.xml
<CustomField>
    <fullName>Course_Type__c</fullName>
    <description>used to select the type of the course</description>
    <label>Course Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Learning Lab</fullName>
            </value>
            <value>
                <fullName>Onsite Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Contains more information about the course.</description>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>used to check the status of the course.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_History__c/Training_History__c.object-meta.xml
<CustomObject>
    <label>Training History</label>
    <nameField>
        <displayFormat>TH-{00000}</displayFormat>
        <label>Training History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_History__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the class</description>
    <label>Class Name</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Training Histories</relationshipLabel>
    <relationshipName>Training_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Provides information about when training completes</description>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Completion_Status__c.field-meta.xml
<CustomField>
    <fullName>Completion_Status__c</fullName>
    <description>Status of the training.</description>
    <label>Completion Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Attempted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Histories</relationshipLabel>
    <relationshipName>Training_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <description>tracks information about when registration happened for training.</description>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <description>information about  Registration status of the training.</description>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Dropped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Training_History_Code__c.field-meta.xml
<CustomField>
    <fullName>Training_History_Code__c</fullName>
    <description>format of cod is UserName»CourseCode»ClassCode</description>
    <externalId>true</externalId>
    <label>Training History Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestPsaRelatedTrainingHistoryController.cls
@isTest(seeAllData=false)
public class TestPsaRelatedTrainingHistoryController
{
  public static Contact objContact{get;set;}
  public static Training_History__c objTrainingHistory{get;set;} 
  
    public TestPsaRelatedTrainingHistoryController()
    {
      
    }     
    public static testMethod  void insertDataAndExcecuteScenario()  //start of test method
    { 
           insertTestData();
           PageReference pageRef=Page.PsaRelatedTrainingHistory;
           Test.setCurrentPage(pageRef);
           ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(objContact); 
           PsaRelatedTrainingHistoryController objPsaRelatedTrainingHistoryController=new PsaRelatedTrainingHistoryController(sc); 
           ApexPages.currentPage().getParameters().put('TrainingHistoryId',objTrainingHistory.id);  
           objPsaRelatedTrainingHistoryController.deleteRecord();
           objPsaRelatedTrainingHistoryController.trainingHistoryHelp();
           PsaRelatedTrainingHistoryController objPsaRelatedTrainingHistoryController1=new PsaRelatedTrainingHistoryController(sc); 
                             
      } //end of test method

      public static void insertTestData()
      {
        PSAEnhancementTestData objPSAEnhancementTestData= new PSAEnhancementTestData();                                       
        List<AccountRecordTypes__c> lstRecordType= objPSAEnhancementTestData.customSettingsAccountRecordTypes();
        List<AllAccountUtils__c> lstCustomSettingsAccountUtils= objPSAEnhancementTestData.customSettingsAccountUtils();        
        insert lstRecordType;         
        insert lstCustomSettingsAccountUtils;
                 
        Account objAccount=objPSAEnhancementTestData.createAccount(lstRecordType); //insertion of the account record
        insert objAccount;                    
                                    
         objContact=objPSAEnhancementTestData.createContact(objAccount.Id);   //insertion of the Contact record  
         insert objContact;                   
                   
          Course_Catalog__c objCourseCatalog=new Course_Catalog__c();
          objCourseCatalog.Course_Name__c='TestCoursecatalog';
          objCourseCatalog.Course_Type__c='Webinar';
          objCourseCatalog.Description__c='test';
          objCourseCatalog.Status__c='Active';
          objCourseCatalog.Course_Code__c='testcourse1';
          insert objCourseCatalog;
          
          Class__c objClass=new Class__c();
          objClass.Class_Name__c='TestClass';
          objClass.Class_Schedule__c=Date.newInstance(2016 , 01 ,01);
          objClass.Instructor__c=objContact.id;
          objClass.Course__c=objCourseCatalog.id;
          objClass.Class_Code__c='testcode1';
           insert objClass;                      
          
           objTrainingHistory=new Training_History__c();
           objTrainingHistory.Class_Name__c=objClass.id;
           objTrainingHistory.Completion_Date__c=Date.newInstance(2016 , 01 ,02);
           objTrainingHistory.Completion_Status__c='Completed';
           objTrainingHistory.Contact__c=objContact.id;
           objTrainingHistory.Registration_Date__c=Date.newInstance(2016 , 01 ,01);
           objTrainingHistory.Registration_Status__c='Registered';
           objTrainingHistory.Training_History_Code__c='testhistorycode';
           insert objTrainingHistory;                      
      }            
}