force-app/main/default/objects/AccountRecordTypes__c/AccountRecordTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Record Types of the account. Mainly referred in AllAccountUtils Class.</description>
    <label>AccountRecordTypes</label>
</CustomObject>

force-app/main/default/objects/AccountRecordTypes__c/fields/RecordTypeID__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeID__c</fullName>
    <description>Salesforce ID of the Record Types belonging to Account Object</description>
    <label>RecordTypeID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/Shipment_Line__c.object-meta.xml
<CustomObject>
    <label>Shipment Line</label>
    <nameField>
        <displayFormat>SL-{0000}</displayFormat>
        <label>Shipment Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipment Lines</relationshipLabel>
    <relationshipName>R00N50000001gPInEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/fields/Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Item_ID__c</fullName>
    <label>Item ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Type</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Shipment Lines</relationshipLabel>
    <relationshipName>R00N50000001gCkvEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/fields/Line_Id__c.field-meta.xml
<CustomField>
    <fullName>Line_Id__c</fullName>
    <externalId>true</externalId>
    <label>Line Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/fields/Oracle_Sales_Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Sales_Order_ID__c</fullName>
    <label>Oracle Sales Order ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>B2B 82</fullName>
            </value>
            <value>
                <fullName>BETA 82</fullName>
            </value>
            <value>
                <fullName>EVAL 82</fullName>
            </value>
            <value>
                <fullName>INTERCO EUROPE 82</fullName>
            </value>
            <value>
                <fullName>INTERNAL 82</fullName>
            </value>
            <value>
                <fullName>INTRA 87</fullName>
            </value>
            <value>
                <fullName>LAB 82</fullName>
            </value>
            <value>
                <fullName>LOAN 82</fullName>
            </value>
            <value>
                <fullName>METRO CONT 82</fullName>
            </value>
            <value>
                <fullName>REFURB 82</fullName>
            </value>
            <value>
                <fullName>RENT 82</fullName>
            </value>
            <value>
                <fullName>RMA 82</fullName>
            </value>
            <value>
                <fullName>RMA 87</fullName>
            </value>
            <value>
                <fullName>RMA 87 I</fullName>
            </value>
            <value>
                <fullName>RTS 82</fullName>
            </value>
            <value>
                <fullName>RTS 86</fullName>
            </value>
            <value>
                <fullName>SALE 82</fullName>
            </value>
            <value>
                <fullName>SAMP 82</fullName>
            </value>
            <value>
                <fullName>SURPLUS SALE 82</fullName>
            </value>
            <value>
                <fullName>T&amp;L CONT 82</fullName>
            </value>
            <value>
                <fullName>WEB 82</fullName>
            </value>
            <value>
                <fullName>WEB SC 82</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Line__c/fields/Requested_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Ship_Date__c</fullName>
    <label>Requested Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ShipmentTxnLog__c/ShipmentTxnLog__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to hold the information of Order Type, Event Type related to Shipment Line and TXN Log Objects.</description>
    <label>ShipmentTxnLog</label>
</CustomObject>

force-app/main/default/objects/ShipmentTxnLog__c/fields/EventType__c.field-meta.xml
<CustomField>
    <fullName>EventType__c</fullName>
    <label>EventType</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ShipmentTxnLog__c/fields/OrderType__c.field-meta.xml
<CustomField>
    <fullName>OrderType__c</fullName>
    <label>OrderType</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXN_Log__c/TXN_Log__c.object-meta.xml
<CustomObject>
    <description>Transaction Log table which will hold all the Customer Asset&apos;s transactions from the UpStream systems like ERP, AUTO etc.</description>
    <label>TXN Log</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>TXN Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TXN Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ShipmentTransactionLogTrigger_Test.cls
/* 
    Description: Test Class for ShipmentTransactionLogTrigger trigger.
    Author: Antharao Chirumamilla.
    Date: 08/23/2018
    Objects: Shipment Line and TXN Log.
*/

@isTest(SeeAlldata=true)
private class ShipmentTransactionLogTrigger_Test{

    static testMethod void PositiveTest(){
        test.starttest();
        // Insert Shipment Custom setting data
        ShipmentTxnLog__c stvs= new ShipmentTxnLog__c(name='testDate',EventType__c='ERP_RECEIPT',OrderType__c='RMA 82'); 
        insert  stvs; 
        /*
        // insert AccountRecordTypes__c
        
        AccountRecordTypes__c ars = new AccountRecordTypes__c(
            Name='TL_SALES_ACCOUNT_RECORD_TYPE_ID',
            RecordTypeID__c='01250000000DQBAAA4'
        );
        insert ars;
        */
        // Insert Account
        
        Account newAccount = new Account( 
            Name = 'test acct', 
            QWBS_Market__c = 'T&L Eastern Region',
            BillingStreet = '123 Main', 
            BillingCity = 'San Diego', 
            BillingState = 'CA', 
            BillingCountry = 'USA',
            CTS_Customer_ID__c = '18sa1k0ajna',
            QWBS_Cust_ID__c='asdaa1sda'
        );
        insert newAccount;
        
        // Insert Product
        
        Product2 p1 = TestUtils.getProduct('ut prod1', 'family');
        p1.External_ID__c ='aad1';
        insert p1;
        
        // Insert Shipment Line
        Shipment_Line__c slia = new Shipment_Line__c(
            Account__c=newAccount.id, 
            Event_Type__c='ERP_RECEIPT',
            Item_ID__c='a1dadaa',
            Item_Type__c=p1.id, 
            Line_Id__c='dq1dwsda',
            Oracle_Sales_Order_ID__c='asdasdasa3',
            Order_Type__c='RMA 82',
            Requested_Ship_Date__c=System.today().addDays(1),
            Shipped_Quantity__c=1
            
        ); 
        
        insert slia;
        
        System.assertEquals(1,[select id from TXN_Log__c limit 1].size());
        test.stoptest();
    }
    
    static testMethod void NegativeTest(){
        test.starttest();
        // Insert Shipment Custom setting data
        ShipmentTxnLog__c stvs= new ShipmentTxnLog__c(name='testDate',EventType__c='ERP_RECEIPT',OrderType__c='RMA 82'); 
        insert  stvs; 
        
        // Insert Account
        
        Account newAccount = new Account( 
            Name = 'test acct', 
            QWBS_Market__c = 'T&L Eastern Region',
            BillingStreet = '123 Main', 
            BillingCity = 'San Diego', 
            BillingState = 'CA', 
            BillingCountry = 'USA',
            CTS_Customer_ID__c = '18sa1k0ajna',
            QWBS_Cust_ID__c='asdaa1sda'
        );
        insert newAccount;
        
        // Insert Product
        
        Product2 p1 = TestUtils.getProduct('ut prod1', 'family');
        p1.External_ID__c ='aad1';
        insert p1;
        
        // Insert Shipment Line
        Shipment_Line__c slia = new Shipment_Line__c(
            Account__c=newAccount.id, 
            Item_ID__c='a1dadaa',
            Item_Type__c=p1.id, 
            Line_Id__c='dq1dwsda',
            Oracle_Sales_Order_ID__c='asdasdasa3',
            Order_Type__c='RMA 82',
            Requested_Ship_Date__c=System.today().addDays(1),
            Shipped_Quantity__c=1
            
        ); 
        try{
            insert slia;
        } catch (exception ex){
        }
        
        
        test.stoptest();
    }
}