force-app/main/default/objects/AccountRecordTypes__c/AccountRecordTypes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Record Types of the account. Mainly referred in AllAccountUtils Class.</description>
    <label>AccountRecordTypes</label>
</CustomObject>

force-app/main/default/objects/AllAccountUtils__c/AllAccountUtils__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used in AllAccountUtils class mainly for the Calculation Data Quality Score and generate Data Quality Description for the account.</description>
    <label>AllAccountUtils</label>
</CustomObject>

force-app/main/default/objects/Request_Form__c/Request_Form__c.object-meta.xml
<CustomObject>
    <label>Request Form</label>
    <nameField>
        <label>Request Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Form</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Form__c/fields/Confidential_Information_Contractors__c.field-meta.xml
<CustomField>
    <fullName>Confidential_Information_Contractors__c</fullName>
    <label>Confidential Information Contractors</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Confidential_Information_Parties__c.field-meta.xml
<CustomField>
    <fullName>Confidential_Information_Parties__c</fullName>
    <label>Confidential Information Parties</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Just Omnitracs</fullName>
            </value>
            <value>
                <fullName>Both/All Parties</fullName>
            </value>
            <value>
                <fullName>Just the other party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Include_affiliates__c.field-meta.xml
<CustomField>
    <fullName>Include_affiliates__c</fullName>
    <label>Include affiliates</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Primary_reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_reason__c</fullName>
    <label>Primary reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Technology Evaluation: Make v. Buy</fullName>
            </value>
            <value>
                <fullName>Potential Acquisition of a company or its assets or patents</fullName>
            </value>
            <value>
                <fullName>Other: (explain below)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form__c/fields/Request_For_Amendment__c.field-meta.xml
<CustomField>
    <fullName>Request_For_Amendment__c</fullName>
    <label>Request For Amendment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/Request_Form_Contact__c.object-meta.xml
<CustomObject>
    <label>Request Form Contact</label>
    <nameField>
        <label>Request Form Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Form Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_Form_Contact__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Last Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/fields/Request_Form__c.field-meta.xml
<CustomField>
    <fullName>Request_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>Request_Form__c</referenceTo>
    <relationshipLabel>Requestors</relationshipLabel>
    <relationshipName>Requestors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_Form_Contact__c/recordTypes/Requestor.recordType-meta.xml
<RecordType>
    <fullName>Requestor</fullName>
    <active>true</active>
    <label>Requestor</label>
</RecordType>

force-app/main/default/classes/TestRequestFormController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestRequestFormController {

    static testMethod void testRequestForm() {
        
        PSAEnhancementTestData objPSAEnhancementTestData= new PSAEnhancementTestData();   
        List<AccountRecordTypes__c> lstRecordType= objPSAEnhancementTestData.customSettingsAccountRecordTypes();
        List<AllAccountUtils__c> lstCustomSettingsAccountUtils= objPSAEnhancementTestData.customSettingsAccountUtils();
        insert lstRecordType;     
        insert lstCustomSettingsAccountUtils;    
        Account accnt=objPSAEnhancementTestData.createAccount(lstRecordType); //insertion of the account record                      
        insert accnt;                
                                    
        Contact cntct=objPSAEnhancementTestData.createContact(accnt.Id);   //insertion of the Contact record  
        insert cntct;  
         
        RequestFormController rfc = new RequestFormController();
        rfc.init();
        
        List<Request_form__c> rfList = [select Id from Request_form__c];
        System.assertEquals(0, rfList.size());
        List<Request_form_Contact__c> rfcList = [select Id from Request_form_Contact__c];
        System.assertEquals(0, rfcList.size());
        
        rfc.requestForm.Primary_reason__c = 'Technology Evaluation: Make v. Buy';
        rfc.requestForm.Request_For_Amendment__c = 'Yes';
        rfc.requestForm.Confidential_Information_Parties__c = 'Just Omnitracs';
        rfc.requestForm.Confidential_Information_Contractors__c = 'Yes';
        rfc.requestForm.Include_affiliates__c = 'Yes';
        
        rfc.requestor.name__c = 'test1';
        rfc.addAdditionalEmployees();
        rfc.additionalEmployees.get(0).name__c = 'test2';
       
        rfc.firstparty.name__c = 'test3';
        rfc.numberOfOtherContacts = 2;
        rfc.addOtherPartyContacts();
        rfc.otherPartyContacts.get(0).first_name__c = cntct.FirstName;
        rfc.otherPartyContacts.get(0).name__c = cntct.LastName;
        rfc.otherPartyContacts.get(0).company__c = accnt.name;
        
        rfc.submit();
        
        rfList = [select Id from Request_form__c];
        System.assertEquals(1, rfList.size());
        rfcList = [select Id from Request_form_Contact__c];
        System.assertEquals(4, rfcList.size());
    }
}