force-app/main/default/objects/Competitive_Knowledge__c/Competitive_Knowledge__c.object-meta.xml
<CustomObject>
    <description>Object to track Targeted Accounts and existing contracts with competitors.</description>
    <label>zCompetitive Knowledge</label>
    <nameField>
        <displayFormat>TA - {0000}</displayFormat>
        <label>Competitive Knowledge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Knowledge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_And_Country_Code__c/Country_And_Country_Code__c.object-meta.xml
<CustomObject>
    <description>Contains countries and country codes</description>
    <label>Country And Country Code</label>
    <nameField>
        <label>Country And Country Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries And Country Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sharing_Partner__c/Data_Sharing_Partner__c.object-meta.xml
<CustomObject>
    <label>Data Sharing Partner</label>
    <nameField>
        <label>Data Sharing Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sharing Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interface_Users__c/Interface_Users__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Interface Users</label>
</CustomObject>

force-app/main/default/objects/PartnerMasterOwnerAccount__c/PartnerMasterOwnerAccount__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains account id .Based on the value of this custom setting the accounts will be visible in the drop down when account owners are transferred for Partner Master Owner.</description>
    <label>PartnerMasterOwnerAccount</label>
</CustomObject>

force-app/main/default/objects/PRMAcctQueueCombination__c/PRMAcctQueueCombination__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>stores the queue ids specific to account</description>
    <label>PRMAcctQueueCombination</label>
</CustomObject>

force-app/main/default/objects/PRMAcctQueueCombination__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Store the account id</description>
    <label>AccountId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRMAcctQueueCombination__c/fields/QueueIds__c.field-meta.xml
<CustomField>
    <fullName>QueueIds__c</fullName>
    <description>Store queIds separated by  a comma &apos; , &apos;</description>
    <label>QueueIds</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRMMasterLeadQueue__c/PRMMasterLeadQueue__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store master queue data</description>
    <label>PRMMasterLeadQueue</label>
</CustomObject>

force-app/main/default/objects/SIC__c/SIC__c.object-meta.xml
<CustomObject>
    <label>SIC</label>
    <nameField>
        <label>SIC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIC__c/fields/Description_Detailed__c.field-meta.xml
<CustomField>
    <fullName>Description_Detailed__c</fullName>
    <label>Description Detailed</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIC__c/fields/Description_General__c.field-meta.xml
<CustomField>
    <fullName>Description_General__c</fullName>
    <label>Description General</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADMINISTRATION OF ECONOMIC PROGRAMS</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATION OF ENVIRONMENTAL QUALITY AND HOUSING PROGRAMS</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATION OF HUMAN RESOURCE PROGRAMS</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL PRODUCTION - CROPS</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL PRODUCTION - LIVESTOCK AND ANIMAL SPECIALTIES</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL SERVICES</fullName>
            </value>
            <value>
                <fullName>AMUSEMENT AND RECREATION SERVICES</fullName>
            </value>
            <value>
                <fullName>APPAREL AND ACCESSORY STORES</fullName>
            </value>
            <value>
                <fullName>APPAREL, FINISHED PRDCTS FROM FABRICS &amp; SIMILAR MATERIALS</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVE DEALERS AND GASOLINE SERVICE STATIONS</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVE REPAIR, SERVICES AND PARKING</fullName>
            </value>
            <value>
                <fullName>BUILDING CNSTRCTN - GENERAL CONTRACTORS &amp; OPERATIVE BUILDERS</fullName>
            </value>
            <value>
                <fullName>BUILDING MATRIALS, HRDWR, GARDEN SUPPLY &amp; MOBILE HOME DEALRS</fullName>
            </value>
            <value>
                <fullName>BUSINESS SERVICES</fullName>
            </value>
            <value>
                <fullName>CHEMICALS AND ALLIED PRODUCTS</fullName>
            </value>
            <value>
                <fullName>COAL MINING</fullName>
            </value>
            <value>
                <fullName>COMMUNICATIONS</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION - SPECIAL TRADE CONTRACTORS</fullName>
            </value>
            <value>
                <fullName>DEPOSITORY INSTITUTIONS</fullName>
            </value>
            <value>
                <fullName>EATING AND DRINKING PLACES</fullName>
            </value>
            <value>
                <fullName>EDUCATIONAL SERVICES</fullName>
            </value>
            <value>
                <fullName>ELECTRIC, GAS AND SANITARY SERVICES</fullName>
            </value>
            <value>
                <fullName>ELECTRONIC, ELCTRCL EQPMNT &amp; CMPNTS, EXCPT COMPUTER EQPMNT</fullName>
            </value>
            <value>
                <fullName>ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT &amp; RELATED SVCS</fullName>
            </value>
            <value>
                <fullName>EXECUTIVE, LEGISLATIVE &amp; GENERAL GOVERNMENT, EXCEPT FINANCE</fullName>
            </value>
            <value>
                <fullName>FABRICATED METAL PRDCTS, EXCEPT MACHINERY &amp; TRANSPORT EQPMNT</fullName>
            </value>
            <value>
                <fullName>FISHING, HUNTING AND TRAPPING</fullName>
            </value>
            <value>
                <fullName>FOOD AND KINDRED PRODUCTS</fullName>
            </value>
            <value>
                <fullName>FOOD STORES</fullName>
            </value>
            <value>
                <fullName>FORESTRY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIC__c/fields/Reporting__c.field-meta.xml
<CustomField>
    <fullName>Reporting__c</fullName>
    <label>Reporting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X3rd_Party_Contract_Service__c/X3rd_Party_Contract_Service__c.object-meta.xml
<CustomObject>
    <label>3rd Party Contracted Product / Service</label>
    <nameField>
        <displayFormat>3rd-{0000}</displayFormat>
        <label>3rd Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3rd Party Contracted Products / Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AllLeadTriggerTest_8.cls
/***********************************************************************************
Author: Vignesh Nayak S, Salesforce.com Developer
Tata Consultancy Services Limited
Description : Test Class written for Lead Object for Trigger(AllLeadTrigger)
************************************************************************************/
@istest(SeeAllData= True)
public class AllLeadTriggerTest_8
{
   /* Static LeadTestData dataPreparation = new LeadTestData();
    Static List<Account> lstAccount = new List<Account>();
    Static List<Contact> lstContact = new list<Contact>();
    Static List<User> lstUser = new List<User>(); 
    Static List<SIC__c> lstSic = new list<SIC__c>();
    Static List<X3rd_Party_Contract_Service__c> lstX3rdPartyContractService = new list<X3rd_Party_Contract_Service__c>();
    Static List<Competitive_Knowledge__c> lstCompetitiveKnowledge = new list<Competitive_Knowledge__c>();
    Static List<Data_Sharing_Partner__c> lstDataSharaPartner = new List<Data_Sharing_Partner__c>();
    Static Country_And_Country_Code__c objCountry; // United States country Insertion
    Static List<Group> lsttestGroup; // Group for Custom Setting
    Static List<String> userType = new List<String>(); // User Type like FSR, MKTG, ISR, Partner
    Static PRMAcctQueueCombination__c prmAccntQueueCombinationInstance; // Custom Setting of Account and Queue
    Static PRMMasterLeadQueue__c PRMMasterLeadQueueInstance; // Custom Setting of PRMMasterLeadQueue
    Static PartnerMasterOwnerAccount__c PartnerMasterOwnerAccountInstance; // Custom Setting of PartnerMasterOwnerAccount
    Static String queueIdValue; // Queue id w.r.t Account from custom Setting
    Static String accountIdValue;
    Static Interface_Users__c InterfaceUsers= new Interface_Users__c();
    
    Public static void EnvDataCreation()
    {
        Test.startTest();
        
        lstAccount = [Select id, name from Account where Primary_Business_Unit__c = 'RoadNet' and Account_Status__c='Active' limit 5];
        
        lsttestGroup = [Select id, name from Group where type='Queue' limit 1];
        
        prmAccntQueueCombinationInstance = dataPreparation.CustomSettingDataInsertion(lstAccount[4], lsttestGroup[0], 1);
        Insert prmAccntQueueCombinationInstance;
        
        
        lstContact = [Select id, name from Contact  limit 4];
        
        
        lstUser = [Select Id, name,ContactId, Usertype ,IsPortalEnabled from User where isActive = true limit 1 ];
        
        
        lstSic = [Select Id, name,Description_General__c,Description_Detailed__c, Reporting__c
                  from SIC__c limit 1];
        
        lstDataSharaPartner = [Select id, name from Data_Sharing_Partner__c limit 1];
        
        objCountry=[Select id, name from Country_And_Country_Code__c limit 1];
        
        userType = dataPreparation.UsersUserType();
        Test.stopTest();
    } 
    // Vaidation of Test data creation. 
    Public static TestMethod void  EnvDataValidation()
    {
        EnvDataCreation();
        
        
        PRMAcctQueueCombination__c insertedValue= PRMAcctQueueCombination__c.getInstance('TestData1');
        queueIdValue=insertedValue.QueueIds__c;
        accountIdValue = insertedValue.AccountId__c;
        System.assert(queueIdValue.length()>1);
        System.assertEquals(queueIdValue, lsttestGroup[0].Id,'Queue ID in custom setting');
        System.assertEquals(accountIdValue, lstAccount[4].Id,'Account ID in custom setting');
    }
    
    Public static TestMethod void GroupLeadInsertUpdation() //00QW0000003ReS4
    {   
        
        EnvDataValidation();
        System.runAs(new User(Id = Userinfo.getUserId()))
        {   
            
            //QueuesObject testQueue = dataPreparation.QueueCreation(lsttestGroup[0]); //lsttestGroup[0] = QueueIdValue
            QueuesObject testQueue = new QueueSObject(QueueID = lsttestGroup[0].id, SObjectType = 'Lead');
            Insert testQueue;
            QueuesObject queueInserted = [select id, SObjectType from QueuesObject limit 1];
            
            list<Lead> lstLeadInsert= [select id from lead where isConverted = false limit 1];
            GroupMember objGmInsert = dataPreparation.AddPRMMasterLeadQueueMember(lstUser[0].Id);
            Insert objGmInsert;
            for(Lead L :lstLeadInsert)
            {
                L.ownerId = lstUser[0].Id;
            }
            //Insert lstLeadInsert;
            for(Lead L :lstLeadInsert)
            {
                L.ownerId = QueueIdvalue;
            }
            Update lstLeadInsert;
            List<Lead> lstLeadInsert1 = [Select id, name, Assigned_From_VAR__c, Assigned_From_VAR_Date__c,
                                         Assigned_To_VAR_From_MPQ_QES__c ,Last_Assigned_From_MPQ_to_Partner_Date__c,
                                         Last_Assigned_From_MPQ_to_Partner__c from lead where id =:lstLeadInsert ];
            
           
            
         }
                
    }*/
    }