force-app/main/default/objects/Competitive_Knowledge__c/Competitive_Knowledge__c.object-meta.xml
<CustomObject>
    <description>Object to track Targeted Accounts and existing contracts with competitors.</description>
    <label>zCompetitive Knowledge</label>
    <nameField>
        <displayFormat>TA - {0000}</displayFormat>
        <label>Competitive Knowledge Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Knowledge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_And_Country_Code__c/Country_And_Country_Code__c.object-meta.xml
<CustomObject>
    <description>Contains countries and country codes</description>
    <label>Country And Country Code</label>
    <nameField>
        <label>Country And Country Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries And Country Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sharing_Partner__c/Data_Sharing_Partner__c.object-meta.xml
<CustomObject>
    <label>Data Sharing Partner</label>
    <nameField>
        <label>Data Sharing Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sharing Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interface_Users__c/Interface_Users__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Interface Users</label>
</CustomObject>

force-app/main/default/objects/PartnerMasterOwnerAccount__c/PartnerMasterOwnerAccount__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting contains account id .Based on the value of this custom setting the accounts will be visible in the drop down when account owners are transferred for Partner Master Owner.</description>
    <label>PartnerMasterOwnerAccount</label>
</CustomObject>

force-app/main/default/objects/PRMAcctQueueCombination__c/PRMAcctQueueCombination__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>stores the queue ids specific to account</description>
    <label>PRMAcctQueueCombination</label>
</CustomObject>

force-app/main/default/objects/PRMMasterLeadQueue__c/PRMMasterLeadQueue__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store master queue data</description>
    <label>PRMMasterLeadQueue</label>
</CustomObject>

force-app/main/default/objects/SIC__c/SIC__c.object-meta.xml
<CustomObject>
    <label>SIC</label>
    <nameField>
        <label>SIC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SIC__c/fields/Description_Detailed__c.field-meta.xml
<CustomField>
    <fullName>Description_Detailed__c</fullName>
    <label>Description Detailed</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SIC__c/fields/Description_General__c.field-meta.xml
<CustomField>
    <fullName>Description_General__c</fullName>
    <label>Description General</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADMINISTRATION OF ECONOMIC PROGRAMS</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATION OF ENVIRONMENTAL QUALITY AND HOUSING PROGRAMS</fullName>
            </value>
            <value>
                <fullName>ADMINISTRATION OF HUMAN RESOURCE PROGRAMS</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL PRODUCTION - CROPS</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL PRODUCTION - LIVESTOCK AND ANIMAL SPECIALTIES</fullName>
            </value>
            <value>
                <fullName>AGRICULTURAL SERVICES</fullName>
            </value>
            <value>
                <fullName>AMUSEMENT AND RECREATION SERVICES</fullName>
            </value>
            <value>
                <fullName>APPAREL AND ACCESSORY STORES</fullName>
            </value>
            <value>
                <fullName>APPAREL, FINISHED PRDCTS FROM FABRICS &amp; SIMILAR MATERIALS</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVE DEALERS AND GASOLINE SERVICE STATIONS</fullName>
            </value>
            <value>
                <fullName>AUTOMOTIVE REPAIR, SERVICES AND PARKING</fullName>
            </value>
            <value>
                <fullName>BUILDING CNSTRCTN - GENERAL CONTRACTORS &amp; OPERATIVE BUILDERS</fullName>
            </value>
            <value>
                <fullName>BUILDING MATRIALS, HRDWR, GARDEN SUPPLY &amp; MOBILE HOME DEALRS</fullName>
            </value>
            <value>
                <fullName>BUSINESS SERVICES</fullName>
            </value>
            <value>
                <fullName>CHEMICALS AND ALLIED PRODUCTS</fullName>
            </value>
            <value>
                <fullName>COAL MINING</fullName>
            </value>
            <value>
                <fullName>COMMUNICATIONS</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION - SPECIAL TRADE CONTRACTORS</fullName>
            </value>
            <value>
                <fullName>DEPOSITORY INSTITUTIONS</fullName>
            </value>
            <value>
                <fullName>EATING AND DRINKING PLACES</fullName>
            </value>
            <value>
                <fullName>EDUCATIONAL SERVICES</fullName>
            </value>
            <value>
                <fullName>ELECTRIC, GAS AND SANITARY SERVICES</fullName>
            </value>
            <value>
                <fullName>ELECTRONIC, ELCTRCL EQPMNT &amp; CMPNTS, EXCPT COMPUTER EQPMNT</fullName>
            </value>
            <value>
                <fullName>ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT &amp; RELATED SVCS</fullName>
            </value>
            <value>
                <fullName>EXECUTIVE, LEGISLATIVE &amp; GENERAL GOVERNMENT, EXCEPT FINANCE</fullName>
            </value>
            <value>
                <fullName>FABRICATED METAL PRDCTS, EXCEPT MACHINERY &amp; TRANSPORT EQPMNT</fullName>
            </value>
            <value>
                <fullName>FISHING, HUNTING AND TRAPPING</fullName>
            </value>
            <value>
                <fullName>FOOD AND KINDRED PRODUCTS</fullName>
            </value>
            <value>
                <fullName>FOOD STORES</fullName>
            </value>
            <value>
                <fullName>FORESTRY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SIC__c/fields/Reporting__c.field-meta.xml
<CustomField>
    <fullName>Reporting__c</fullName>
    <label>Reporting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/X3rd_Party_Contract_Service__c/X3rd_Party_Contract_Service__c.object-meta.xml
<CustomObject>
    <label>3rd Party Contracted Product / Service</label>
    <nameField>
        <displayFormat>3rd-{0000}</displayFormat>
        <label>3rd Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3rd Party Contracted Products / Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AllLeadTriggerTest_6.cls
/***********************************************************************************
Author: Vignesh Nayak S, Salesforce.com Developer
Tata Consultancy Services Limited
Description : Test Class written for Lead Object for Trigger(AllLeadTrigger)
************************************************************************************/
 
@istest(SeeAllData = true)
public class AllLeadTriggerTest_6
{
    /*Static LeadTestData dataPreparation = new LeadTestData();
    Static List<Account> lstAccount = new List<Account>();
    Static List<Contact> lstContact = new list<Contact>();
    Static List<User> lstUser = new List<User>(); 
    Static List<SIC__c> lstSic = new list<SIC__c>();
    Static List<X3rd_Party_Contract_Service__c> lstX3rdPartyContractService = new list<X3rd_Party_Contract_Service__c>();
    Static List<Competitive_Knowledge__c> lstCompetitiveKnowledge = new list<Competitive_Knowledge__c>();
    Static List<Data_Sharing_Partner__c> lstDataSharaPartner = new List<Data_Sharing_Partner__c>();
    Static Country_And_Country_Code__c objCountry; // United States country Insertion
    Static List<Group> lsttestGroup; // Group for Custom Setting
    Static List<String> userType = new List<String>(); // User Type like FSR, MKTG, ISR, Partner
    Static PRMAcctQueueCombination__c prmAccntQueueCombinationInstance; // Custom Setting of Account and Queue
    Static PRMMasterLeadQueue__c PRMMasterLeadQueueInstance; // Custom Setting of PRMMasterLeadQueue
    Static PartnerMasterOwnerAccount__c PartnerMasterOwnerAccountInstance; // Custom Setting of PartnerMasterOwnerAccount
    Static String queueIdValue; // Queue id w.r.t Account from custom Setting
    Static String accountIdValue;
    Static Interface_Users__c InterfaceUsers= new Interface_Users__c();
    
    Public static void EnvDataCreation()
    {
        List<Account> lstAccountToBeInserted = dataPreparation.AccountCreation();
        Insert lstAccountToBeInserted;
        lstAccount = [Select id, name from Account where id =: lstAccountToBeInserted];
        
        List<Group> lstGroupToBeInserted = dataPreparation.InsertGroup();
        Insert lstGroupToBeInserted;
        lsttestGroup = [Select id, name from Group where id =: lstGroupToBeInserted];
        
        prmAccntQueueCombinationInstance = dataPreparation.CustomSettingDataInsertion(lstAccount[4], lsttestGroup[0], 1);
        Insert prmAccntQueueCombinationInstance;
        Test.startTest();
        List<Contact> lstContactToBeInserted = dataPreparation.ContactCreation(lstAccount);
        Insert lstContactToBeInserted;
        
        lstContact = [Select id, name from Contact where id =: lstContactToBeInserted];
        
        List<User> lstUserToBeInserted = dataPreparation.UserCreation(lstContact);
        Insert lstUserToBeInserted;
        lstUser = [Select Id, name,ContactId, Usertype ,IsPortalEnabled from User where id =: lstUserToBeInserted];
        Test.stopTest();        
        List<SIC__c> lstSicToBeInserted = dataPreparation.SICCreation();
        Insert lstSicToBeInserted;
        lstSic = [Select Id, name,Description_General__c,Description_Detailed__c, Reporting__c
                  from SIC__c where id =: lstSicToBeInserted];
        
        List<Data_Sharing_Partner__c> lstDataSharaPartnerToBeInserted = dataPreparation.DataSharaPartnerInsert(lstAccount);
        Insert lstDataSharaPartnerToBeInserted;
        lstDataSharaPartner = [Select id, name from Data_Sharing_Partner__c where id =: lstDataSharaPartnerToBeInserted];
        Test.startTest();
        Country_And_Country_Code__c objCountryToBeInserted = dataPreparation.InsertCountryAndCountryCode();
        Insert objCountryToBeInserted;
        objCountry=[Select id, name from Country_And_Country_Code__c where id = : objCountryToBeInserted.Id];
        
        userType = dataPreparation.UsersUserType();
        
    }*/
 }