force-app/main/default/objects/Requirement_System_Field_Relationship__c/Requirement_System_Field_Relationship__c.object-meta.xml
<CustomObject>
    <description>Junction object between Requirement &amp; System Fields.</description>
    <label>Related System Field</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Requirement &amp; System Field ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related System Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement_System_Field_Relationship__c/fields/Requirements__c.field-meta.xml
<CustomField>
    <fullName>Requirements__c</fullName>
    <label>Requirements</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipName>Requirements_System_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement_System_Field_Relationship__c/fields/System_Field__c.field-meta.xml
<CustomField>
    <fullName>System_Field__c</fullName>
    <label>System Field</label>
    <referenceTo>System_Field__c</referenceTo>
    <relationshipName>Requirements_System_Fields</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirements__c/Requirements__c.object-meta.xml
<CustomObject>
    <description>Once User Stories are established, what are the next steps? Requirements, both functional and technical, are captured in this object, and provide the next steps, after User Stories are captured, and enable the progression of defining what is necessary to enable success.</description>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Field__c/System_Field__c.object-meta.xml
<CustomObject>
    <description>MIBOS Requirements App: The fields that need to be configured to support requirements.</description>
    <label>System Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Campaign Member</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Case Comment</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ViewRequirement_Ext.cls
public class ViewRequirement_Ext {

    private Requirements__c r;
    
    public List<System_Field__c> unassignedFields {get; set;}
    private List<System_Field__c> assignedFields;
    
    private List<Requirement_System_Field_Relationship__c> junctions;
    
    public List<SelectOption> unassignedFieldsList {get; set;}
    public List<SelectOption> assignedFieldsList {get; set;}
    
    public Boolean canAccess{get; private set;}
    
    public List<SelectOption> filterOptions {get; set;}
    public String selectedFilter {get; set;}

    public ViewRequirement_Ext(ApexPages.StandardController std) {
        this.r = (Requirements__c)std.getRecord();
        
        //TODO: Store this ID in a Custom Setting or admin config
        List<PermissionSetAssignment> permSets = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId =: UserInfo.getUserId() AND PermissionSetId = '0PSW000000009Xo'];
        if (permsets.size() == 1) {
            this.canAccess = true;
        }
        else {
            this.canAccess = false;
        }
        
        List<Schema.PicklistEntry> trackValues = System_Field__c.Object__c.getDescribe().getPicklistValues();
        filterOptions = new List<SelectOption>();
        //filterOptions.add(new SelectOption('All Tracks', 'All Tracks'));
        for (Schema.PicklistEntry pe : trackValues) {
            filterOptions.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        if (filterOptions.size() > 0) {
            selectedFilter = filterOptions[0].getValue();
        }
        else {
            selectedFilter = 'All Objects';
        }
        
        unassignedFields = new List<System_Field__c>();
        assignedFields = new List<System_Field__c>();
        unassignedFieldsList = new List<SelectOption>();
        assignedFieldsList = new List<SelectOption>();
        if (selectedFilter != 'All Objects') {
            unassignedFields = [SELECT Id, Name FROM System_Field__c WHERE Id NOT IN (SELECT System_Field__c FROM Requirement_System_Field_Relationship__c WHERE Requirements__c =: this.r.Id) AND Object__c =: selectedFilter ORDER BY Name];
        }
        else {
            unassignedFields = [SELECT Id, Name FROM System_Field__c WHERE Id NOT IN (SELECT System_Field__c FROM Requirement_System_Field_Relationship__c WHERE Requirements__c =: this.r.Id) ORDER BY Name];
        }
        assignedFields = [SELECT Id, Name FROM System_Field__c WHERE Id IN (SELECT System_Field__c FROM Requirement_System_Field_Relationship__c WHERE Requirements__c =: this.r.Id) ORDER BY Name];
    
        for (System_Field__c f : unassignedFields) {
            unassignedFieldsList.add(new SelectOption(f.Id, f.Name));
        }
        
        for (System_Field__c f : assignedFields) {
            assignedFieldsList.add(new SelectOption(f.Id, f.Name));
        }
        
        junctions = new List<Requirement_System_Field_Relationship__c>();
        junctions = [SELECT Id, System_Field__c FROM Requirement_System_Field_Relationship__c WHERE Requirements__c = :this.r.Id];
    }

    public PageReference doSave() {
        List<Requirement_System_Field_Relationship__c> junctionsToInsert = new List<Requirement_System_Field_Relationship__c>();
        List<Requirement_System_Field_Relationship__c> junctionsToDelete = new List<Requirement_System_Field_Relationship__c>();
        
        if (junctions.size() > 0) {
            delete junctions;
            junctions.clear();
        }
        
        // Determine Requirements that have been assigned
        for (SelectOption f : assignedFieldsList) {
            junctionsToInsert.add(new Requirement_System_Field_Relationship__c(System_Field__c = f.getValue(), Requirements__c = this.r.Id));
        }
        
        if (junctionsToInsert.size() > 0) {
            insert junctionsToInsert;
        }
        
        PageReference p = new PageReference('/apex/ViewRequirement?id=' + r.Id);
        p.setRedirect(true);
        
        return p;
    }

    public PageReference refreshFilter() {
        if (selectedFilter != 'All Objects') {
            unassignedFields = [SELECT Id, Name FROM System_Field__c WHERE Id NOT IN (SELECT System_Field__c FROM Requirement_System_Field_Relationship__c WHERE Requirements__c =: this.r.Id) AND Object__c =: selectedFilter ORDER BY Name];
        }
        else {
            unassignedFields = [SELECT Id, Name FROM System_Field__c WHERE Id NOT IN (SELECT System_Field__c FROM Requirement_System_Field_Relationship__c WHERE Requirements__c =: this.r.Id) ORDER BY Name];
        }
        
        this.unassignedFieldsList = new List<SelectOption>();
        for (System_Field__c f : unassignedFields) {
            Boolean found = false;
            for (SelectOption f2 : assignedFieldsList) {
                if (f2.getValue() == f.Id) {
                    found = true;
                }
            }
            if (!found) {
                this.unassignedFieldsList.add(new SelectOption(f.Id, f.Name));
            }
        }
        
        return null;
    }

}