force-app/main/default/objects/Requirement_System_Field_Relationship__c/Requirement_System_Field_Relationship__c.object-meta.xml
<CustomObject>
    <description>Junction object between Requirement &amp; System Fields.</description>
    <label>Related System Field</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Requirement &amp; System Field ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related System Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement_System_Field_Relationship__c/fields/Requirements__c.field-meta.xml
<CustomField>
    <fullName>Requirements__c</fullName>
    <label>Requirements</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipName>Requirements_System_Fields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement_System_Field_Relationship__c/fields/System_Field__c.field-meta.xml
<CustomField>
    <fullName>System_Field__c</fullName>
    <label>System Field</label>
    <referenceTo>System_Field__c</referenceTo>
    <relationshipName>Requirements_System_Fields</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirements__c/Requirements__c.object-meta.xml
<CustomObject>
    <description>Once User Stories are established, what are the next steps? Requirements, both functional and technical, are captured in this object, and provide the next steps, after User Stories are captured, and enable the progression of defining what is necessary to enable success.</description>
    <label>Requirement</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Field__c/System_Field__c.object-meta.xml
<CustomObject>
    <description>MIBOS Requirements App: The fields that need to be configured to support requirements.</description>
    <label>System Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Field__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Campaign Member</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Case Comment</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ViewRequirement_Ext_Test.cls
@isTest
public class ViewRequirement_Ext_Test {

    public static testMethod void testAssociateFields() {
        Requirements__c r = new Requirements__c();
        insert r;
        
        System_Field__c f1 = new System_Field__c(Name = 'Test 1', Object__c = 'Account');
        System_Field__c f2 = new System_Field__c(Name = 'Test 2', Object__c = 'Account');
        insert f1;
        insert f2;
        
        Requirement_System_Field_Relationship__c j = new Requirement_System_Field_Relationship__c(Requirements__c = r.Id, System_Field__c = f1.Id);
        insert j;
        
        Test.startTest();
        
        Test.setCurrentPage(Page.ViewRequirement);
        ApexPages.currentPage().getParameters().put('id',r.Id);
        ApexPages.StandardController con = new ApexPages.StandardController(r);
        ViewRequirement_Ext reqPage = new ViewRequirement_Ext(con);
        
        System.assert(true, reqPage.assignedFieldsList[0].getValue() == f1.Id);
        System.assert(true, reqPage.unassignedFieldsList[0].getValue() == f2.Id);
        
        List<SelectOption> newAssigned = new List<SelectOption>();
        List<SelectOption> newUnassigned = new List<SelectOption>();
        newAssigned.add(new SelectOption(f2.Id, f2.Name));
        newUnassigned.add(new SelectOption(f1.Id, f1.Name));
        
        reqPage.assignedFieldsList = newAssigned;
        reqPage.unassignedFieldsList = newUnassigned;
        
        reqPage.doSave();
        
        List<Requirement_System_Field_Relationship__c> newJunctions = [SELECT Id, System_Field__c FROM Requirement_System_Field_Relationship__c];
        
        System.assertEquals(1,newJunctions.size());
        System.assert(true, newJunctions[0].System_Field__c == f2.Id);
        
        reqPage.refreshFilter();
        
        Test.stopTest();
    }

}