force-app/main/default/objects/System_Master__c/System_Master__c.object-meta.xml
<CustomObject>
    <description>To store systems at different levels along with their parent systems</description>
    <label>System Master</label>
    <nameField>
        <label>System Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Master__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Store the level of each system in a dependency tree</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level - 0</fullName>
            </value>
            <value>
                <fullName>Level - 1</fullName>
            </value>
            <value>
                <fullName>Level - 2</fullName>
            </value>
            <value>
                <fullName>Level - 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Master__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent system of a subsystem</description>
    <label>Parent</label>
    <referenceTo>System_Master__c</referenceTo>
    <relationshipLabel>System Master</relationshipLabel>
    <relationshipName>System_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/System_Outage__c.object-meta.xml
<CustomObject>
    <description>Custom object to store System Outage information related to Cases.</description>
    <label>System Outage</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>System Outage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Outages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Outage__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>System_Outage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time (PST/PDT)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time (PST/PDT)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Subsystem_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Subsystem_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Master. This will be mapped to subsystem picklist on the page</description>
    <label>Subsystem</label>
    <referenceTo>System_Master__c</referenceTo>
    <relationshipLabel>System Outages (Subsystem)</relationshipLabel>
    <relationshipName>System_Outages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/System_Lookup__c.field-meta.xml
<CustomField>
    <fullName>System_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>System</label>
    <referenceTo>System_Master__c</referenceTo>
    <relationshipLabel>System Outages</relationshipLabel>
    <relationshipName>System_Outages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Degraded Service</fullName>
            </value>
            <value>
                <fullName>Planned Downtime</fullName>
            </value>
            <value>
                <fullName>Unplanned Downtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestSystemOutageController.cls
@isTest(SeeAllData = true)
public class TestSystemOutageController{
  @isTest
  public static void testFetch(){
      System_Master__c systemMaster = new System_Master__c();
      insert systemMaster;
        
      //insert new System_Master__c(level__c = 'level - 1',inactive__c = false,Parent__c = systemMaster.Id);
      insert new System_Master__c(level__c = 'level - 2',inactive__c = false,Parent__c = systemMaster.Id);
      insert new System_Master__c(level__c = 'Level - 3',inactive__c = false,Parent__c = systemMaster.Id);    
  
      Case cse = new Case();
      insert cse;
            
      System_Outage__c systemOutage = new System_Outage__c(System_Lookup__c=systemMaster.Id,Subsystem_Lookup__c=systemMaster.Id,type__c='Unplanned Downtime',Case__c=cse.Id,Start_Time__c=System.Now(),End_Time__c=System.Now());
      insert systemOutage;
        
      //PageReference pageRef = Page.SystemOutageDetails;    
      //Test.setCurrentPage(pageRef);
      
      ApexPages.currentPage().getParameters().put('id', systemOutage.id);
      ApexPages.currentPage().getParameters().put('CF00N50000001caGA_lkid',cse.Id);  
      ApexPages.currentPage().getParameters().put('clone', 'false');
          
      ApexPages.StandardController stdController = new ApexPages.StandardController(systemOutage);
      SystemOutageController testController = new SystemOutageController(stdController );
      
      PageReference page = testController.cancelProcess();    
      System.assertEquals('/'+cse.Id,page.getURL());

      page = testController.getDefaultTypes();
      System.assertEquals(null,page);

      /*testController.fetchSystems();
    
      testController.fetchL1Systems();    
      testController.CancelProcess();*/
        testController.BackToCase();
        testController.RedirectToOutageList();
        testController.CancelUpdate();
        testController.deleteHeader();
        testController.isUpdate = false;
        testController.getDependencies();
        //testController.getDefaultTypes();
        testController.saveRecords();
        try{
            testController.saveHeader();
            }
        catch (Exception e)
                  {
                    System.debug(e.getMessage());
                  }     
        testController.saveSummary();
        testController.editRecords();
       // testController.CloneObj();
        testController.getMoreList();
  }
  
  @isTest
  public static void testSaceRecords(){
  
      Case cse = new Case();
      insert cse;
                  
      System_Outage__c systemOutage = new System_Outage__c(type__c='Unplanned Downtime',Case__c=cse.Id,Start_Time__c=System.Now(),End_Time__c=System.Now());
      insert systemOutage;
        
      //PageReference pageRef = Page.SystemOutageDetails;    
      //Test.setCurrentPage(pageRef);
      
      ApexPages.currentPage().getParameters().put('id', systemOutage.id);
      ApexPages.currentPage().getParameters().put('CF00N50000001caGA_lkid',cse.Id);  
      ApexPages.currentPage().getParameters().put('clone', 'false');
          
      ApexPages.StandardController stdController = new ApexPages.StandardController(systemOutage);
      SystemOutageController testController = new SystemOutageController(stdController );
    
      testController.saveRecords();
     
    }


    @isTest
    public static void testInitial(){
  
      Case cse = new Case();
      insert cse;
      
      System_Outage__c systemOutage = new System_Outage__c(type__c='Unplanned Downtime',Case__c=cse.Id,Start_Time__c=System.Now(),End_Time__c=System.Now());
      
      insert new System_Master__c(level__c = 'level - 0',inactive__c = false);
      
      //PageReference pageRef = Page.SystemOutageDetails;    
     // Test.setCurrentPage(pageRef);
      
      ApexPages.currentPage().getParameters().put('id', systemOutage.Id);
      ApexPages.currentPage().getParameters().put('CF00N50000001caGA_lkid',cse.Id);  
      ApexPages.currentPage().getParameters().put('clone', 'false');
          
      ApexPages.StandardController stdController = new ApexPages.StandardController(systemOutage);
      SystemOutageController testController = new SystemOutageController(stdController);
      
      }
    
    @isTest
    public static void testReadOnlyMode(){
  
      Case cse = new Case();
      insert cse;
      
      System_Outage__c systemOutage = new System_Outage__c(type__c='Unplanned Downtime',Case__c=cse.Id);
      insert systemOutage;
      
      //insert new System_Master__c(level__c = 'level - 0',inactive__c = false);
      
      //PageReference pageRef = Page.SystemOutageDetails;    
      //Test.setCurrentPage(pageRef);
      
      ApexPages.currentPage().getParameters().put('id', systemOutage.Id);
     // ApexPages.currentPage().getParameters().put('CF00N50000001caGA_lkid',null);  
     // ApexPages.currentPage().getParameters().put('clone', 'false');
          
      ApexPages.StandardController stdController = new ApexPages.StandardController(systemOutage);
      SystemOutageController testController = new SystemOutageController(stdController);        
      
      }
    
    @isTest
    public static void testReadOnlyModeWithSystemLookup(){
  
      Case cse = new Case();
      insert cse;
    
      System_Master__c systemMaster = new System_Master__c();
      insert systemMaster;
          
      System_Outage__c systemOutage = new System_Outage__c(type__c='Unplanned Downtime',Case__c=cse.Id,System_Lookup__c=systemMaster.Id,Subsystem_Lookup__c=systemMaster.Id,Start_Time__c=System.Now(),End_Time__c=System.Now());
      insert systemOutage;
      
      insert new System_Master__c(level__c = 'level - 0',inactive__c = false);
      
      //PageReference pageRef = Page.SystemOutageDetails;    
      //Test.setCurrentPage(pageRef);
      
      ApexPages.currentPage().getParameters().put('id', systemOutage.Id);
     // ApexPages.currentPage().getParameters().put('CF00N50000001caGA_lkid',null);  
     // ApexPages.currentPage().getParameters().put('clone', 'true');
          
      ApexPages.StandardController stdController = new ApexPages.StandardController(systemOutage);
      SystemOutageController testController = new SystemOutageController(stdController);        
    
      //testController.saveHeader();
      testController.CloneObj();
  
      }
        
    
        /*public static void testCancelProcess(){    
      Case cse = new Case();
      insert cse;
      
      System_Outage__c systemOutage = new System_Outage__c(type__c='Unplanned Downtime',Case__c=cse.Id);
      insert systemOutage;
        
      //PageReference pageRef = Page.SystemOutageDetails;    
      Test.setCurrentPage(Page.SystemOutageDetails);
  
      ApexPages.currentPage().getParameters().put('id', systemOutage.Id);
      ApexPages.currentPage().getParameters().put('CF00N50000001caGA_lkid',cse.Id);
      
      ApexPages.StandardController stdController = new ApexPages.StandardController(systemOutage);
      SystemOutageController testController = new SystemOutageController(stdController);
        
      PageReference page = testController.cancelProcess();    
      System.assertEquals('/'+cse.Id,page.getURL());
    }*/

}