force-app/main/default/objects/System_Master__c/System_Master__c.object-meta.xml
<CustomObject>
    <description>To store systems at different levels along with their parent systems</description>
    <label>System Master</label>
    <nameField>
        <label>System Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Master__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Store the level of each system in a dependency tree</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level - 0</fullName>
            </value>
            <value>
                <fullName>Level - 1</fullName>
            </value>
            <value>
                <fullName>Level - 2</fullName>
            </value>
            <value>
                <fullName>Level - 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage__c/System_Outage__c.object-meta.xml
<CustomObject>
    <description>Custom object to store System Outage information related to Cases.</description>
    <label>System Outage</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>System Outage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Outages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Outage__c/fields/Calculated_Downtime__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Downtime__c</fullName>
    <formula>IF ( Calculated_Downtime_Calc__c &gt; 0, Text(FLOOR((End_Time__c- Start_Time__c) * 24)) &amp;&quot;:&quot;&amp;Text(FLOOR(((End_Time__c- Start_Time__c) * 24 - FLOOR((End_Time__c -Start_Time__c) * 24))* 60)) &amp;&quot;:&quot;&amp;Text(FLOOR((((End_Time__c - Start_Time__c) * 24 - FLOOR((End_Time__c - Start_Time__c) * 24 ))* 60 - FLOOR(((End_Time__c - Start_Time__c) * 24 - FLOOR((End_Time__c -Start_Time__c) * 24 )) * 60 )) * 60 )),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>System_Outage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time (PST/PDT)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time (PST/PDT)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Subsystem_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Subsystem_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Master. This will be mapped to subsystem picklist on the page</description>
    <label>Subsystem</label>
    <referenceTo>System_Master__c</referenceTo>
    <relationshipLabel>System Outages (Subsystem)</relationshipLabel>
    <relationshipName>System_Outages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/SubSystems__c.field-meta.xml
<CustomField>
    <fullName>SubSystems__c</fullName>
    <label>SubSystems-old</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>System__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA&amp;D</fullName>
            </value>
            <value>
                <fullName>AAA</fullName>
            </value>
            <value>
                <fullName>AmberWatch</fullName>
            </value>
            <value>
                <fullName>Asset Tracker</fullName>
            </value>
            <value>
                <fullName>AT&amp;T – Frame Relay</fullName>
            </value>
            <value>
                <fullName>BGW (EU)</fullName>
            </value>
            <value>
                <fullName>BGW (US)</fullName>
            </value>
            <value>
                <fullName>BGW200</fullName>
            </value>
            <value>
                <fullName>CARDIONET</fullName>
            </value>
            <value>
                <fullName>CDS - Content Delivery Service</fullName>
            </value>
            <value>
                <fullName>CER - Critical Event Reporting</fullName>
            </value>
            <value>
                <fullName>CNR OVM - AEF Portal</fullName>
            </value>
            <value>
                <fullName>CS - Common Services</fullName>
            </value>
            <value>
                <fullName>DE - Driver Email</fullName>
            </value>
            <value>
                <fullName>DN – Driver Notification</fullName>
            </value>
            <value>
                <fullName>DW - Driver Workflow</fullName>
            </value>
            <value>
                <fullName>EGGW200</fullName>
            </value>
            <value>
                <fullName>EMGW200 - GPRS</fullName>
            </value>
            <value>
                <fullName>EOMNI200/EMGW200-GPRS</fullName>
            </value>
            <value>
                <fullName>EOMNI200 - GPRS</fullName>
            </value>
            <value>
                <fullName>Europe200</fullName>
            </value>
            <value>
                <fullName>Europe200/EGGW200-GTE</fullName>
            </value>
            <value>
                <fullName>Fleetvisor (EU)</fullName>
            </value>
            <value>
                <fullName>GGW200</fullName>
            </value>
            <value>
                <fullName>Ghos/Qhos/Guava</fullName>
            </value>
            <value>
                <fullName>GlobalTRACS/Europe</fullName>
            </value>
            <value>
                <fullName>GlobalTRACSWeb</fullName>
            </value>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GSS - Geo Spatial Services</fullName>
            </value>
            <value>
                <fullName>IES Mobile/ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <label>System-old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Providers</fullName>
            </value>
            <value>
                <fullName>NMC</fullName>
            </value>
            <value>
                <fullName>NMC - Hosted</fullName>
            </value>
            <value>
                <fullName>QDC</fullName>
            </value>
            <value>
                <fullName>QSP (Mex)</fullName>
            </value>
            <value>
                <fullName>QSP (US)</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/System_Lookup__c.field-meta.xml
<CustomField>
    <fullName>System_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>System</label>
    <referenceTo>System_Master__c</referenceTo>
    <relationshipLabel>System Outages</relationshipLabel>
    <relationshipName>System_Outages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Degraded Service</fullName>
            </value>
            <value>
                <fullName>Planned Downtime</fullName>
            </value>
            <value>
                <fullName>Unplanned Downtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage_Line__c/System_Outage_Line__c.object-meta.xml
<CustomObject>
    <description>Object for storing outage lines</description>
    <label>System Outage Line</label>
    <nameField>
        <displayFormat>OutageLine-{00000}</displayFormat>
        <label>System Outage Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Outage Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Outage_Line__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Level of the subsystem in the dependency line</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Level - 2</fullName>
            </value>
            <value>
                <fullName>Level - 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage_Line__c/fields/Outage_Type__c.field-meta.xml
<CustomField>
    <fullName>Outage_Type__c</fullName>
    <description>Outage type for the system in the dependency line</description>
    <label>Outage Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Unplanned</fullName>
            </value>
            <value>
                <fullName>Degraded</fullName>
            </value>
            <value>
                <fullName>No Impact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage_Line__c/fields/System_Master__c.field-meta.xml
<CustomField>
    <fullName>System_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>System which is a lookup to System Master</description>
    <label>System Master</label>
    <referenceTo>System_Master__c</referenceTo>
    <relationshipLabel>System Outage Lines</relationshipLabel>
    <relationshipName>System_Outage_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Outage_Line__c/fields/System_Outage_Header__c.field-meta.xml
<CustomField>
    <fullName>System_Outage_Header__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to System Outage header object</description>
    <label>System Outage Header</label>
    <referenceTo>System_Outage__c</referenceTo>
    <relationshipLabel>System Outage Lines</relationshipLabel>
    <relationshipName>System_Outage_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OutageListClass.cls
public class OutageListClass{
public list<System_Outage__c> OutageList {get; set;}
public String Case_num{get; set;}
String OutageID;
public list<System_Outage_Line__c> OutageLineList {get;set;}
public Boolean asce {get; set;}
public String current_Value {get; set;}
public String CaseId{get;set;}
public String alphabet{get;set;}
public Boolean isAlphaBar{get;set;}
public Integer INNERLIST_SIZE{get;set;}
public Integer OUTERLIST_SIZE{get;set;}
public string id1 {get;set;}
public integer counter {get;set;}

//Contructor for the class
public  OutageListClass(ApexPages.StandardController controller)
{
    CaseId = Apexpages.currentPage().getParameters().get('Id');
    //system.debug('OutageID:'+outageID);
    asce = false;
    isAlphaBar = true;
    counter=0;
    current_value = 'name';
    RedirectToOutageList();
}

//Method for displaying the list of System Outage with their dependencies
public pageReference RedirectToOutageList(){
    /*if(outageID != null)
    {
        CaseId = [Select Id, Case__c from System_Outage__c Where Id =:outageID limit 1].Case__c;
    }
    system.debug('CaseId:'+caseID);*/
    if(CaseId!=null)
    {
        try{
        Case_num = [select CaseNumber from case where Id =: CaseId].CaseNumber;
        OutageList = [select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,System_Lookup__c,Type__c,System__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =: CaseId limit 1000];
        system.debug('Outage List:'+OutageList);
        List<Id> IdList = new list<Id>();
        for(integer i=0;i<OutageList.size();i++){
            IdList.add(OutageList[i].Id);
        }
        OutageLineList = [Select s.System_Outage_Header__c, s.System_Master__c, s.Outage_Type__c, s.Level__c, s.Id From System_Outage_Line__c s Where s.System_Outage_Header__c IN :IdList limit 1000 ];
        system.debug('Before add:'+OutageLineList );
        system.debug('after add');
        if(OutageList.size()>0)
        {
            OUTERLIST_SIZE = OutageList.size();
        }
        else
        {
            OUTERLIST_SIZE = 0;
        }
        
        if(OutageLineList.size()>0)
        {
            INNERLIST_SIZE = OutageLineList.size();
        }
        else
        {
            INNERLIST_SIZE = 0;
        }
    
        //INNERLIST_SIZE = OutageLineList.size();
        //OUTERLIST_SIZE = OutageList.size();
    }
    catch(Exception e)
    {
        system.debug('Exception inside Redirect to Outage List');
    }
}

    return null;

}


public PageReference ChangeOrder()
{
    try{
    if(current_value == 'Start_Time__c' || current_value == 'End_Time__c')
    {
        isAlphaBar =false;
    }
    else
    {
        isAlphaBar = true;
    }
    String prev_value;
    system.debug('before if');
    //system.debug('prev value:'+prev_value);
    /*if(prev_value != null && prev_value != current_value)
    {
        system.debug('inside chnage asce');
        asce = false;
    }
    else{*/
    if(asce == false)
    {
        system.debug('Ascending');
        asce =true;
        if(current_value == 'system')
        {
            OutageList = [select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,Type__c,System__c,System_Lookup__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =: CaseId order by System_Lookup__r.name asc limit 1000];
                    }
        else if(current_value == 'subsystem')
        {
            system.debug('inside subsystem');
            OutageList = [select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,Type__c,System__c,System_Lookup__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =: CaseId order by Subsystem_Lookup__r.name asc limit 1000];
            
        }
        else
        {
            system.debug('inside else');
            String strsql = 'select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,Type__c,System__c,System_Lookup__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =' + '\'' + CaseId + '\'';
            String subsql = ' order by ' + current_value +' asc limit 1000';
            strsql = strsql + subsql;
            system.debug('strsql:'+strsql);
            OutageList = database.query(strsql);
            
        }
        system.debug('Value:'+OutageList);

    }
    else if(asce == true)
    {
        system.debug('Inside change Records');
        asce = false;
        system.debug('again:'+current_value);
        if(current_value == 'system')
        {
            OutageList = [select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,Type__c,System__c,System_Lookup__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =: CaseId order by System_Lookup__r.name desc limit 1000];
        }
        else if(current_value == 'subsystem')
        {
            system.debug('inside subsystem');
            OutageList = [select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,Type__c,System__c,System_Lookup__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =: CaseId order by Subsystem_Lookup__r.name desc limit 1000];
        }
        else
        {
            system.debug('inside else');
            String strsql = 'select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,Type__c,System__c,System_Lookup__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =' + '\'' + CaseId + '\'';
            String subsql = ' order by ' + current_value +' desc limit 1000';
            strsql = strsql + subsql;
            system.debug('strsql:'+strsql);
            OutageList = database.query(strsql);
        }
        system.debug('OutageLsit'+OutageList);

    }
    prev_value=current_value;
    system.debug('prev_value:'+prev_value+'current_value:'+current_value);
    if(OutageList.size()>0)
    {
        OUTERLIST_SIZE = OutageList.size();
    }
    else
    {
        OUTERLIST_SIZE = 0;
    }
    }
    //}
    catch(Exception e)
    {
        system.debug('Error in Change Order');
    }
    return null;
}

public PageReference alphabet_Ordering()
{
    String selected_value = current_value;
    system.debug('alphabet:'+alphabet);
    try{
    if(alphabet == 'All')
    {
        system.debug('All:');
        OutageList = [select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,System_Lookup__c,Type__c,System__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =: CaseId limit 1000];
    }
    else
    {
        if(current_value == 'system')
        {
            selected_value = 'System_Lookup__r.name';
        }
        else if(current_value == 'CreatedById')
        {
            selected_value ='createdBy.Name';
        }
        else if(current_value == 'LastModifiedById')
        {
            selected_value = 'LastModifiedBy.Name';
        }
        else if(current_value == 'subsystem')
        {
            system.debug('inside subsystem');
            selected_value = 'Subsystem_Lookup__r.name';
        }
        

            String strsql = 'select id,name,Subsystem_Lookup__c,Start_Time__c,End_Time__c,Type__c,System__c,System_Lookup__c,SubSystems__c,Calculated_Downtime__c,CreatedById,LastModifiedById from System_Outage__c where Case__c =' + '\'' + CaseId + '\'';
            string subsql1='and '+ selected_value +' like ' +'\'' + alphabet + '%\'';
            String subsql = ' order by ' + selected_value +' asc limit 1000';
            strsql = strsql + subsql1 + subsql;
            system.debug('strsql:'+strsql);
            OutageList = database.query(strsql);
            

    }
    if(OutageList.size()>0)
    {
        OUTERLIST_SIZE = OutageList.size();
    }
    else
    {
        OUTERLIST_SIZE = 0;
    }
    
    }
    catch(Exception e){
    system.debug('Error in alphbet ordering');
    }
    
    return null;
}


}