force-app/main/default/objects/VCG_CPQ_Pricing_Access_Sequence__c/VCG_CPQ_Pricing_Access_Sequence__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Pricing Access Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Pricing Access Sequences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Pricing_Access_Sequence__c/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <description>If set, this is the field we want to assign the result value to in the current object (Quote or Quote Line Item). Only Quote &amp; Quote Product records will be assigned, if the same Access Sequence is used for Assets, the asset record will not be modified, even in memory.</description>
    <label>Assign To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Access_Sequence__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select to turn on debug output for this access sequence. (Debug output to SF debug logs with log level ERROR.)</inlineHelpText>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Access_Sequence__c/fields/Needs_Fields__c.field-meta.xml
<CustomField>
    <fullName>Needs_Fields__c</fullName>
    <label>Needs Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/VCG_CPQ_Pricing_Condition__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Pricing Condition</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Pricing Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Calculation__c.field-meta.xml
<CustomField>
    <fullName>Calculation__c</fullName>
    <description>In the future this will be the formula that is entered, it will be parsed when the record is saved and converted into the compiled version automatically. For now, it is just a nice to read version that should match the compiled version.</description>
    <inlineHelpText>Currently this is just a nice-to-read version of the compiled calculation formula</inlineHelpText>
    <label>Calculation (Readable)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Calculation_Compiled__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Compiled__c</fullName>
    <label>Calculation (Compiled)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Data_Key_Definition__c.field-meta.xml
<CustomField>
    <fullName>Data_Key_Definition__c</fullName>
    <label>Data Key Definition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Data_Scale_Field_1__c.field-meta.xml
<CustomField>
    <fullName>Data_Scale_Field_1__c</fullName>
    <label>Data Scale Field 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Data_Scale_Field_2__c.field-meta.xml
<CustomField>
    <fullName>Data_Scale_Field_2__c</fullName>
    <label>Data Scale Field 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Data_Scale_Field_3__c.field-meta.xml
<CustomField>
    <fullName>Data_Scale_Field_3__c</fullName>
    <label>Data Scale Field 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Is_Pricing_Related__c.field-meta.xml
<CustomField>
    <fullName>Is_Pricing_Related__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in Oracle integration. Informatica script will look at this field to determine which pricing condition data records should be truncated on a nighly basis. If TRUE, they will be truncated.</description>
    <inlineHelpText>If pricing condition, TRUE. Otherwise, FALSE.</inlineHelpText>
    <label>Is Pricing Related?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Condition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Static</fullName>
            </value>
            <value>
                <fullName>Scaled</fullName>
            </value>
            <value>
                <fullName>Scaled Cumulative</fullName>
            </value>
            <value>
                <fullName>Percent of Core</fullName>
            </value>
            <value>
                <fullName>Maintenance Price</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Surcharge</fullName>
            </value>
            <value>
                <fullName>Statistical</fullName>
            </value>
            <value>
                <fullName>Calculation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure__c/VCG_CPQ_Pricing_Procedure__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Pricing Procedure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Pricing Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure__c/fields/Quote_Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Type__c</fullName>
    <inlineHelpText>&apos;Header&apos; pricing procedures are applied to the quote as a whole. &apos;All&apos; pricing procedures are applied to all line items -- &apos;New&apos;, &apos;Renewal&apos;, etc.</inlineHelpText>
    <label>Quote Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Decommission</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence in which the Pricing Procedure record should be executed. Allows for a mix of header calculations and line item calculations.</description>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure_Sequence__c/VCG_CPQ_Pricing_Procedure_Sequence__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Pricing Procedure Sequence</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Pricing Procedure Sequences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure_Sequence__c/fields/Access_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Access_Sequence__c</fullName>
    <label>Access Sequence</label>
    <referenceTo>VCG_CPQ_Pricing_Access_Sequence__c</referenceTo>
    <relationshipLabel>Procedure Sequences</relationshipLabel>
    <relationshipName>Procedure_Sequences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure_Sequence__c/fields/Pricing_Procedure__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Procedure__c</fullName>
    <label>Pricing Procedure</label>
    <referenceTo>VCG_CPQ_Pricing_Procedure__c</referenceTo>
    <relationshipLabel>Procedure Sequences</relationshipLabel>
    <relationshipName>Procedure_Sequences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure_Sequence__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <inlineHelpText>The sort order for processing the Access Sequences</inlineHelpText>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VCG_CPQ_ExportConfigController_Test.cls
/**
 * Test class for VCG_CPQ_ExportConfigController
 *
 * @author  Lawrence Coffin <lawrence.coffin@cloudsherpas.com>
 * @since   4.May.2015
 */
@isTest
public class VCG_CPQ_ExportConfigController_Test {
    
    /**
     * Base test
     *
     * @author  Lawrence Coffin <lawrence.coffin@cloudsherpas.com>
     * @since   4.May.2015
     */
    static testMethod void testExportConfigController()
    {
        Test.startTest();
        //Insert VCG_CPQ_Pricing_Procedure__c
        VCG_CPQ_Pricing_Procedure__c PricingProcedure = new VCG_CPQ_Pricing_Procedure__c();

        PricingProcedure.Name = 'Test Pricing Procedure';
        PricingProcedure.Active__c = true;
        PricingProcedure.Description__c = 'Test Pricing Procedure';
        PricingProcedure.Needs_Fields__c = 'Test Pricing Procedure';
        PricingProcedure.Quote_Line_Type__c = 'New';
        PricingProcedure.Sequence__c = 12345;
        
        Insert PricingProcedure;
        //Insertion complete
        //Insert VCG_CPQ_Pricing_Access_Sequence__c
        VCG_CPQ_Pricing_Access_Sequence__c PricingAccessSequence = new VCG_CPQ_Pricing_Access_Sequence__c();

        PricingAccessSequence.Name = 'Test Pricing Access Sequence';
        PricingAccessSequence.Assign_To__c = 'Test User';
        PricingAccessSequence.Comments__c = 'Test Comment';
        PricingAccessSequence.Debug__c = true;
        PricingAccessSequence.Description__c = 'Test Description';
        PricingAccessSequence.Needs_Fields__c = 'Test Need';
        
        Insert PricingAccessSequence;
        //Insertion Complete
        //Insert VCG_CPQ_Pricing_Condition__c
        VCG_CPQ_Pricing_Condition__c PricingCondition = new VCG_CPQ_Pricing_Condition__c();

        PricingCondition.Calculation_Compiled__c = 'Test Pricing Condition';
        PricingCondition.Calculation__c = 'Test Pricing Condition';
        PricingCondition.Data_Key_Definition__c = 'Test Pricing Procedure';
        PricingCondition.Data_Scale_Field_1__c = 'Test Data Scale 1';
        PricingCondition.Data_Scale_Field_2__c = 'Test Data Scale 2';
        PricingCondition.Data_Scale_Field_3__c = 'Test Data Scale 3';
        PricingCondition.Description__c = 'Test Pricing Condition';
        PricingCondition.Is_Pricing_Related__c = true;
        PricingCondition.Needs_Fields__c = 'Test Pricing Condition';
        PricingCondition.Type__c = 'Static';
        
        Insert PricingCondition;
        //Insertion Complete
        //Insert VCG_CPQ_Pricing_Procedure_Sequence__c
        VCG_CPQ_Pricing_Procedure_Sequence__c PricingProcedureSequence = new VCG_CPQ_Pricing_Procedure_Sequence__c();
        PricingProcedureSequence.Name = 'Test Pricing Procedure Sequence';
        PricingProcedureSequence.Pricing_Procedure__c = PricingProcedure.Id;
        PricingProcedureSequence.Access_Sequence__c = PricingAccessSequence.Id;
        PricingProcedureSequence.Sequence__c = 12345;
        Insert PricingProcedureSequence;
        //Insertion Complete
        VCG_CPQ_ExportConfigController controller = new VCG_CPQ_ExportConfigController();
        controller.generateConfigXML();
        
        System.assertNotEquals(null, controller.configXML);
        System.assertNotEquals('', controller.configXML);
        
        Test.stopTest();
    }
}