force-app/main/default/objects/Call_Report__c/Call_Report__c.object-meta.xml
<CustomObject>
    <description>Object to store Call Reports</description>
    <label>Call Report</label>
    <nameField>
        <displayFormat>CRPT-{0000}</displayFormat>
        <label>Call Report #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>A Call Report is only created in &apos;Draft&apos; status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Report__c/fields/Type_of_Competitor__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Competitor__c</fullName>
    <description>The type of Competitor is defined with respect to call report</description>
    <inlineHelpText>Enter the type of competitor</inlineHelpText>
    <label>Type of Competitor</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Competitor</fullName>
            </value>
            <value>
                <fullName>Competitive Takeaway</fullName>
            </value>
            <value>
                <fullName>Competitive Threat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/Competitive_Summary__c.object-meta.xml
<CustomObject>
    <description>The Competitive Summary object is a custom object created to summarize the Competitive Intelligence records according to a Account - Competitor - Opportunity/Call Report combination.</description>
    <label>Competitive Summary</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Competitive Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitive_Summary__c/fields/Call_Report__c.field-meta.xml
<CustomField>
    <fullName>Call_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Respective Call Report for the Record</description>
    <label>Call Report</label>
    <referenceTo>Call_Report__c</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ValidateCallReportCompetitor.cls
/*******************************************************************************
 * File:        ValidateCallReportCompetitor.cls
 * Date:        September 11th, 2018
 * Author:      Sai Krishna Kakani
 * Description: Competitors as required when changing the CallReport Status
 * Called onto CallReportAll trigger
 * *******************************************************************************/
public class ValidateCallReportCompetitor {
     public void CRVal (Map<id,Call_Report__c> newMap, Map<id,Call_Report__c> oldMap)  {
    
           id id1 = userinfo.getProfileId();    
           profile p =[select Name from profile where id = :id1];
           
           if(p.Name != 'System Administrator' || test.isrunningtest()) {
           
            list<Competitive_Summary__c> commpsummarylist = new list<Competitive_Summary__c> ();
            Map<id,list<Competitive_Summary__c>> compsummaryMap = new map<id,list<Competitive_Summary__c>> ();
            commpsummarylist = [select id,Call_Report__c from Competitive_Summary__c where Call_Report__c IN:newMap.keyset()];
            
        for(Competitive_Summary__c cs : commpsummarylist) {
            
            List<Competitive_Summary__c> cslist = new list<Competitive_Summary__c> ();
            if(compsummaryMap.get(cs.Call_Report__c) != null ) {
            cslist = compsummaryMap.get(cs.Call_Report__c);
            }
            if(userinfo.getUserId()!=Label.S2S_User_Id){
            cslist.add(cs);
            compsummaryMap.put(cs.Call_Report__c,cslist);
            }
        }
        
        for(Call_Report__c cr : newMap.values()) {
        
         if ((cr.id != null) && (cr.status__c != oldMap.get(cr.id).status__c) && (cr.Type_of_Competitor__c!= 'No Competitor') && (oldMap.get(cr.id).Type_of_Competitor__c== cr.Type_of_Competitor__c)) {
            boolean isError = false;
            
            if(compsummaryMap == null || compsummaryMap.size() == 0) {
                isError = true;
            } 
            
            else if(!compsummaryMap.containskey(cr.id)) {
                isError = true;
            } 
            
            if(isError && !Test.isrunningtest()) {
              cr.addError('You cannot advance this call report until competitor information is completed. Please change the Status field back to Draft, click Save and then update the Competitor Information.');
            }
        }
        
       }
       
      }
      
    }
}