force-app/main/default/objects/Critical_Success_Factor__c/Critical_Success_Factor__c.object-meta.xml
<CustomObject>
    <label>Critical Success Factor</label>
    <nameField>
        <displayFormat>CSF-{0000}</displayFormat>
        <label>CSF #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critical Success Factors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Critical_Success_Factor__c/fields/CSF__c.field-meta.xml
<CustomField>
    <fullName>CSF__c</fullName>
    <description>Used to outline the critical success factors for each strategic account.</description>
    <label>Critical Success Factor</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Critical_Success_Factor__c/fields/Strategic_Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Account_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategic Account Profile</label>
    <referenceTo>Strategic_Account_Profile__c</referenceTo>
    <relationshipName>Critical_Success_Factor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/Strategic_Account_Profile__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the profile information on strategic accounts for the T&amp;L Organization</description>
    <label>Strategic Account Profile</label>
    <nameField>
        <label>Strategic Account Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Strategic_Account_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Business_Plan__c</fullName>
    <label>Business Plans</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_CSF__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_CSF__c</fullName>
    <label>Critical Success Factors</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Date_Time__c</fullName>
    <label>SAP Last Modified Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestUpdateCSF.cls
@isTest(SeeAllData = true)
public class TestUpdateCSF
{
/***************************************************************************************************************
Date: 01/19/2009
Author: Divya Hegde, Salesforce.com Consultant
        Tata Consultancy Services Limited

Purpose: Test Method to validate the functionality of Trigger "UpdateCSF" on Critical Success Factor.
**************************************************************************************************************************************************************/
 static testMethod void testTriggerCSF()
  {
   Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
   Account acc = GenericTestClass.insertAccount();
   
   NewSAP.Account__c =acc.id ;
   NewSAP.Last_Modified_Business_Plan__c =datetime.valueOf('2008-12-04 13:52:00');
   NewSAP.Last_Modified_CSF__c=datetime.valueOf('2008-12-05 13:52:00');
    NewSAP.Last_Modified_Date_Time__c=datetime.valueOf('2008-12-03 13:51:00');
   insert NewSAP;
   Critical_Success_Factor__c CSFnew =new Critical_Success_Factor__c();
   CSFnew .Strategic_Account_Profile__c = NewSAP.Id;
   CSFnew .CSF__c='test123';
   insert CSFnew ;
  }
  static testMethod void UpdateBP()
  {
   Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
   Account acc = GenericTestClass.insertAccount();
   
   NewSAP.Account__c =acc.id ;
   insert NewSAP;
   Critical_Success_Factor__c CSFnew =new Critical_Success_Factor__c();
   CSFnew .Strategic_Account_Profile__c = NewSAP.Id;
    CSFnew .CSF__c='test123';
   insert CSFnew ;
   update NewSAP;
  }
}