force-app/main/default/objects/Sales_Order_Request__c/Sales_Order_Request__c.object-meta.xml
<CustomObject>
    <label>Sales Order Request</label>
    <nameField>
        <displayFormat>SOR{0000}</displayFormat>
        <label>SOR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order Requests</relationshipLabel>
    <relationshipName>Sales_Order_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Order Requests</relationshipLabel>
    <relationshipName>Sales_Order_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Request__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Eval</fullName>
            </value>
            <value>
                <fullName>Sample</fullName>
            </value>
            <value>
                <fullName>Refurb</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Request__c/fields/Requested_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Ship_Date__c</fullName>
    <defaultValue>Today() + 2</defaultValue>
    <label>Requested Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestPopulateSalesAdmin.cls
@isTest(SeeAllData = true)
public class TestPopulateSalesAdmin {
    static testmethod void testPopulateSalesAdmin() {
        
      Account sampleCustomerAcct = GenericTestClass.insertAccount();
      Contact sampleContact = GenericTestClass.insertContact(sampleCustomerAcct.Id);
      
      Sales_Order_Request__c SOR = new Sales_Order_Request__c(
                                  Account__c = sampleCustomerAcct.Id,
                                  Order_Type__c = 'Eval', 
                                  Contact__c = sampleContact.Id,
                                  Requested_Ship_Date__c = System.Today()
                                 
                                                                   );
      insert SOR;      

    }
}