force-app/main/default/objects/AR_Call_History__c/AR_Call_History__c.object-meta.xml
<CustomObject>
    <label>AR Call History</label>
    <nameField>
        <displayFormat>ARCH-{00000}</displayFormat>
        <label>ARCH#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR Call History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AR_Call_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AR Call History</relationshipLabel>
    <relationshipName>AR_Call_History</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/AR_Call_History__c/fields/Call_Details__c.field-meta.xml
<CustomField>
    <fullName>Call_Details__c</fullName>
    <label>Call Details</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AR_Call_History__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Call_History__c/fields/Outbound_Type__c.field-meta.xml
<CustomField>
    <fullName>Outbound_Type__c</fullName>
    <label>Outbound Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Collection Call</fullName>
            </value>
            <value>
                <fullName>Follow-up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Call_History__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Messaging</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AR_Call_History__c/fields/Subject_Details__c.field-meta.xml
<CustomField>
    <fullName>Subject_Details__c</fullName>
    <label>Subject Details</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ARCallHistoryUtilsTest.cls
@isTest
public class ARCallHistoryUtilsTest {
    private static VistaAssetHelperUtil util = new VistaAssetHelperUtil();
	
	@testSetup
	static void SetupData() {
		TestUtils.defineCustomSettings();
	}
	
	public static testMethod void TestCallAR(){
        Account acct = util.createAccount('SurveyUtils Test Account');
        List<AR_Call_History__c> ARCallInsertList = new List<AR_Call_History__c>();
        AR_Call_History__c ARCallInsert = new AR_Call_History__c();
        ARCallInsert.Account__c = acct.Id;
        ARCallInsert.Call_Type__c = 'Outbound';
        ARCallInsert.Outbound_Type__c = 'Follow-up';
        ARCallInsert.Subject__c = 'Test Subject';
        ARCallInsert.Subject_Details__c = 'Subject - Testing';
        ARCallInsert.Call_Details__c = 'Email Body - Testing';
        ARCallInsertList.add(ARCallInsert);
		Test.startTest();
		Integer emailcount = Limits.getEmailInvocations();
        insert ARCallInsertList;
        System.assertNotEquals(emailcount, Limits.getEmailInvocations());
        Test.stopTest();
    }
}