force-app/main/default/objects/Case_Event__c/Case_Event__c.object-meta.xml
<CustomObject>
    <description>Case Event object from Roadnet</description>
    <label>Case Event</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Event__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Events</relationshipLabel>
    <relationshipName>Case_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Event__c/fields/Communication_Type__c.field-meta.xml
<CustomField>
    <fullName>Communication_Type__c</fullName>
    <label>Communication Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Event__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Event__c/fields/Display_in_Customer_Portal__c.field-meta.xml
<CustomField>
    <fullName>Display_in_Customer_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display in Customer Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ReOpenCaseExtension.cls
/*******************************************************************************
 * File:  ReOpenCaseExtension.cls
 * Date:  November 26th, 2013
 * Author:  Joseph Hutchins
 *
 * The use, disclosure, reproduction, modification, transfer, or transmittal of
 * this work for any purpose in any form or by any means without the written 
 * permission of United Parcel Service is strictly prohibited.
 *
 * Confidential, unpublished property of United Parcel Service.
 * Use and distribution limited solely to authorized personnel.
 *
 * Copyright 2009, UPS Logistics Technologies, Inc.  All rights reserved.
 *  *******************************************************************************/
public with sharing class ReOpenCaseExtension
{
    public Case theCase{get;set;}
    public String reason {get;set;}
    
    public ReOpenCaseExtension(apexpages.standardcontroller stdcontroller)
    {
        theCase = [select id, status, start_time__c, IsClosed, CaseNumber from case where id =: stdController.getId()];
    }
    public pageReference reOpenCase()
    {
        if (theCase.IsClosed && reason != '' && reason.length() > 1) {
            theCase.Status = 'RE-OPENED';
            theCase.Substatus__c = '';
            theCase.Start_Time__c = null;
            update theCase;
            
            Case_Event__c ce = new Case_Event__c();
            ce.Case__c = theCase.id;
            ce.Display_in_Customer_Portal__c = false;
            ce.Communication_Type__c = 'Internal';
            
            ce.Subject__c = 'Case Re-opened';
            ce.Details__c   = 'Case Re-open Reason: ' + reason;
            insert ce;
            
            PageReference pr = new PageReference('/' + theCase.id);
            pr.setRedirect(true);
            return pr;
        }
        else {
            if (reason == '') {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please provide a reason for re-opening the Case.'));
            }
            else if (reason.length() == 1) {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please provide a longer reason for re-opening the Case.'));
            }
            else {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Re-opening a case that is not closed is not allowed.'));
            }
            return null;
        }
    }
    public static ApexPages.StandardController generateController(Case theCase )
    {
        pagereference pageRef=new pagereference('Page.CaseTypeSupportPage');
        test.setcurrentpage(pageRef);       
        return new ApexPages.standardController(theCase);
    }
}