force-app/main/default/objects/Current_Year_Objective__c/Current_Year_Objective__c.object-meta.xml
<CustomObject>
    <description>Used to outline the Current Year Objectives for a strategic account</description>
    <label>Current Year Objective</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Current Year Objective #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Current Year Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Current_Year_Objective__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Current_Year_Objective__c/fields/Strategic_Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Account_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategic Account Profile</label>
    <referenceTo>Strategic_Account_Profile__c</referenceTo>
    <relationshipName>Current_Year_Objective</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/Strategic_Account_Profile__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the profile information on strategic accounts for the T&amp;L Organization</description>
    <label>Strategic Account Profile</label>
    <nameField>
        <label>Strategic Account Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Strategic_Account_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_CSF__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_CSF__c</fullName>
    <label>Critical Success Factors</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_Current_Year_Objective__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Current_Year_Objective__c</fullName>
    <label>Current Year Objectives</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Date_Time__c</fullName>
    <label>SAP Last Modified Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestUpdateCYO.cls
@isTest(SeeAllData = true)
public class TestUpdateCYO 
{
/***************************************************************************************************************
Date: 01/19/2009
Author: Divya Hegde, Salesforce.com Consultant
        Tata Consultancy Services Limited

Purpose: Test Method to validate the functionality of Trigger "UpdateCYO" on Current Year Objective.
**************************************************************************************************************************************************************/
 static testMethod void testTriggerCYO()
  {
   Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
   Account acc=[select id from account limit 1];
   NewSAP.Account__c =acc.id ;
  NewSAP.Last_Modified_Current_Year_Objective__c =datetime.valueOf('2008-12-03 13:52:00');
  NewSAP.Last_Modified_CSF__c=datetime.valueOf('2008-12-03 13:52:00');
  NewSAP.Last_Modified_Date_Time__c=datetime.valueOf('2008-12-03 13:51:00');
   insert NewSAP;
   Current_Year_Objective__c CYOnew =new Current_Year_Objective__c();
   CYOnew .Strategic_Account_Profile__c = NewSAP.Id;
   CYOnew .Objective__c='test1234';
   insert CYOnew ;
  }
  static testMethod void UpdateCYO()
  {
   Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
   Account acc=[select id from account limit 1];
   NewSAP.Account__c =acc.id ;
   insert NewSAP;
  Current_Year_Objective__c CYOnew =new Current_Year_Objective__c();
   CYOnew .Strategic_Account_Profile__c = NewSAP.Id;
   CYOnew .Objective__c='test1234';
   insert CYOnew ;
   update NewSAP;
  }
}