force-app/main/default/objects/Shipping_Estimate__c/Shipping_Estimate__c.object-meta.xml
<CustomObject>
    <label>Shipping Estimate</label>
    <nameField>
        <displayFormat>ShipEst-{0}</displayFormat>
        <label>Shipping Estimate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Estimate__c/fields/Shipping_Summary__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Summary__c</fullName>
    <label>Shipping Summary</label>
    <referenceTo>Shipping_Estimate_Summary__c</referenceTo>
    <relationshipLabel>Shipping Estimates</relationshipLabel>
    <relationshipName>Shipping_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Estimate_Summary__c/Shipping_Estimate_Summary__c.object-meta.xml
<CustomObject>
    <description>Rollup summary object for estimated and actual shipping items.</description>
    <label>Shipping Estimate Summary</label>
    <nameField>
        <displayFormat>ShipEstSum-{0}</displayFormat>
        <label>Shipping Estimate Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Estimates Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ShippingEstimateTriggerTest.cls
/**
 * Test for the ShippingEstimateTrigger.
 */

@IsTest
private class ShippingEstimateTriggerTest {
    static testMethod void testShippingEstimate() {
        Shipping_Estimate_Summary__c ses = new Shipping_Estimate_Summary__c();
        insert ses;

        Shipping_Estimate__c se = new Shipping_Estimate__c();
        se.Shipping_Summary__c = ses.Id;
        
        Test.startTest();
        insert se;
        Test.stopTest();
    }
}