force-app/main/default/objects/At_Risk__c/At_Risk__c.object-meta.xml
<CustomObject>
    <label>At Risk</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>At Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>At Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/At_Risk__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>At Risk</relationshipLabel>
    <relationshipName>At_Risk</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/At_Risk__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this At Risk item will populate the At Risk Alert pop-up at the Account level.</description>
    <inlineHelpText>If checked, this At Risk item will populate the At Risk Alert pop-up at the Account level.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/At_Risk__c/fields/Problem_Statement__c.field-meta.xml
<CustomField>
    <fullName>Problem_Statement__c</fullName>
    <description>Brief statement of the problem (255 character limit).</description>
    <inlineHelpText>Brief statement of the problem (255 character limit). For cancellations please include why the customer is leaving, if known.</inlineHelpText>
    <label>Problem Statement</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/At_Risk__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Select the current status for this Alert or At Risk event</description>
    <inlineHelpText>Select the current status for this Alert or At Risk event</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AtRiskUtility.cls
public without sharing class AtRiskUtility {

    // when an At Risk record is made Primary, need to uncheck the Primary box on all other At Risk records on the Account
    public static void makePrimary(List<At_Risk__c> newAlerts) {
        List<Id> accIdsToClear = new List<Id>();
        List<Id> newAlertIds = new List<Id>();
        for (At_Risk__c a : newAlerts) {
            if (a.Primary__c) {
                accIdsToClear.add(a.Account__c);
                newAlertIds.add(a.Id);
            }
        }
        
        List<At_Risk__c> alertsToClear = [SELECT Id FROM At_Risk__c WHERE Account__c IN :accIdsToClear AND Primary__c = TRUE AND Id NOT IN :newAlertIds];
        for (At_Risk__c a : alertsToClear) {
            a.Primary__c = false;
        }
        update alertsToClear;
    }
    
    // copies Primary alerts to Account level alert text
    public static void copyAlertToAccount(List<At_Risk__c> newAlerts) {
        Map<Id, String> mapAccountToAlertText = new Map<Id, String>();                
        for (At_Risk__c a : newAlerts) {            
            if (a.Primary__c && a.Account__c != null) {
                if (a.Status__c == 'Open') {
                    mapAccountToAlertText.put(a.Account__c, 'At Risk Alert: ' + a.Problem_Statement__c);
                }
                else {
                    mapAccountToAlertText.put(a.Account__c, '');
                }
            }
        }
        
        List<Account> accsToUpdate = new List<Account>();
        for (Id accId : mapAccountToAlertText.keySet()) {
            accsToUpdate.add(new Account(Id = accId, Alert_Text__c = mapAccountToAlertText.get(accId)));
        }
        update accsToUpdate;
    }
    
    // copies Primary alerts to Account level alert text
    public static void updateCopyAlertToAccount(List<At_Risk__c> newAlerts, Map<Id, At_Risk__c> oldMapAlerts) {
        Map<Id, String> mapAccountToAlertText = new Map<Id, String>();                
        for (At_Risk__c a : newAlerts) {            
            if (a.Primary__c && a.Account__c != null) {
                if (a.Status__c == 'Open') {
                    mapAccountToAlertText.put(a.Account__c, 'At Risk Alert: ' + a.Problem_Statement__c);
                }
                else {
                    mapAccountToAlertText.put(a.Account__c, '');
                }
            }
            if (oldMapAlerts.containsKey(a.Id)){
                if(oldMapAlerts.get(a.Id).Primary__c != a.Primary__c && a.Primary__c == false && a.Account__c != null){
                    mapAccountToAlertText.put(a.Account__c, '');
                }
            }
        }
        
        List<Account> accsToUpdate = new List<Account>();
        for (Id accId : mapAccountToAlertText.keySet()) {
            accsToUpdate.add(new Account(Id = accId, Alert_Text__c = mapAccountToAlertText.get(accId)));
        }
        update accsToUpdate;
    }

}