force-app/main/default/objects/At_Risk__c/At_Risk__c.object-meta.xml
<CustomObject>
    <label>At Risk</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>At Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>At Risk</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/At_Risk__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>At Risk</relationshipLabel>
    <relationshipName>At_Risk</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/At_Risk__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, this At Risk item will populate the At Risk Alert pop-up at the Account level.</description>
    <inlineHelpText>If checked, this At Risk item will populate the At Risk Alert pop-up at the Account level.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/At_Risk__c/fields/Problem_Statement__c.field-meta.xml
<CustomField>
    <fullName>Problem_Statement__c</fullName>
    <description>Brief statement of the problem (255 character limit).</description>
    <inlineHelpText>Brief statement of the problem (255 character limit). For cancellations please include why the customer is leaving, if known.</inlineHelpText>
    <label>Problem Statement</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/At_Risk__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Select the current status for this Alert or At Risk event</description>
    <inlineHelpText>Select the current status for this Alert or At Risk event</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AtRiskUtility_Test.cls
@isTest(SeeAllData=True)
public with sharing class AtRiskUtility_Test {

    static testMethod void testPrimaryAlerts() {
        Account testAcc = new Account(Name = 'Test');
        
        insert testAcc;
        
        At_Risk__c testAlert1 = new At_Risk__c(Account__c = testAcc.Id, Status__c = 'Open', Problem_Statement__c = 'Problem 1', Primary__c = true);
        At_Risk__c testAlert2 = new At_Risk__c(Account__c = testAcc.Id, Status__c = 'Open', Problem_Statement__c = 'Problem 2', Primary__c = false);
        
        Test.startTest();
        
        insert testAlert1;
        insert testAlert2;
        
        System.assertEquals(true, [SELECT Primary__c FROM At_Risk__c WHERE Id = :testAlert1.Id].Primary__c);
        System.assertEquals(false, [SELECT Primary__c FROM At_Risk__c WHERE Id = :testAlert2.Id].Primary__c);
        
        testAlert2.Primary__c = true;
        update testAlert2;
        
        System.assertEquals(false, [SELECT Primary__c FROM At_Risk__c WHERE Id = :testAlert1.Id].Primary__c);
        System.assertEquals(true, [SELECT Primary__c FROM At_Risk__c WHERE Id = :testAlert2.Id].Primary__c);
        
        Test.stopTest();
    } 

    static testMethod void testCopyAlertToAccount() {
        Account testAcc = new Account(Name = 'Test');
        
        insert testAcc;
        
        At_Risk__c testAlert1 = new At_Risk__c(Account__c = testAcc.Id, Status__c = 'Open', Problem_Statement__c = 'Problem 1', Primary__c = true);
        
        Test.startTest();
        
        insert testAlert1;
        
        System.assertNotEquals('', [SELECT Alert_Text__c FROM Account WHERE Id = :testAlert1.Account__c].Alert_Text__c);
        
        Test.stopTest();
    }

}