force-app/main/default/objects/Customer_Idea__c/Customer_Idea__c.object-meta.xml
<CustomObject>
    <label>Customer Idea</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Customer Idea #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Ideas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Idea__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Ideas</relationshipLabel>
    <relationshipName>Customer_Ideas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Idea__c/fields/Idea__c.field-meta.xml
<CustomField>
    <fullName>Idea__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Idea</label>
    <referenceTo>Idea</referenceTo>
    <relationshipName>Customer_Ideas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestAllIdeaController.cls
@isTest(seealldata=true)
private class TestAllIdeaController
{
    static list<Customer_Idea__c> lstCustomerIdea = new list<Customer_Idea__c>();
    public static void insertCustomerIdea()
    {
        Account newAccount = new Account();
        newAccount.Name = 'SFDC';
        newAccount.Type = 'Other';
        newAccount.BillingStreet = 'Test Address';
        newAccount.BillingCity = 'Test City';
        newAccount.BillingCountry = 'Test Country';
        insert newAccount;
        
        Idea newIdea = new Idea();
        newIdea.title = 'Test Idea';
        newIdea.communityId = '09a500000008aK5';
        //insert newIdea;
        //list<Customer_Idea__c> lstCustomerIdea = new list<Customer_Idea__c>();
        for(integer i=0;i<50;i++)
        {
            Customer_Idea__c newAcctIdea = new Customer_Idea__c();
            newAcctIdea.Account__c = newAccount.Id;
            newAcctIdea.Idea__c = newIdea.Id;
            lstCustomerIdea.add(newAcctIdea);
        }
        insert lstCustomerIdea; 
    }
    public static testmethod void testIdeasAccountController()
    {
        insertCustomerIdea();
        ShowIdeasAccountController newObj = new ShowIdeasAccountController();
        newObj.alphabetOrdering();
        newObj.changeOrder();
        newObj.pagination();
        newObj.next();
        newObj.previous();
    }
    
    public static testmethod void testNewIdea()
    {
        test.startTest();
        insertCustomerIdea();
        Customer_Idea__c newAcctIdea = new Customer_Idea__c();        
        ApexPages.StandardController sdtCon;
        if(!lstCustomerIdea.isEmpty())
        {
            Idea newIdea = new Idea();
            newIdea.title = 'Test Idea';
            Id communityId = [select Id from Community limit 1].Id;
            newIdea.communityId = communityId;
            //insert newIdea;
            newIdea = [Select id from Idea limit 1];
                        
            newAcctIdea = [Select id,idea__c,account__c from Customer_Idea__c where id =:lstCustomerIdea[0].id limit 1];
            newAcctIdea.Idea__c = newIdea.Id; 
            update newAcctIdea; 
            sdtCon = new ApexPages.StandardController(newAcctIdea);
            
        }
            
        
        NewAccountIdeaLinkController newObj = new NewAccountIdeaLinkController(sdtCon);
        newObj.acctID = newAcctIdea.account__c;
        newObj.Save();
        newObj.SaveandNew();
        newObj.acctID = newAcctIdea.account__c;
        newObj.findTotalUnits();
        newOBj.redirectionOnEdit();
        test.stopTest();
    }
}