force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>provide Information about the class,Instructor of the class and all the courses that class Contains</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Class Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_Code__c.field-meta.xml
<CustomField>
    <fullName>Class_Code__c</fullName>
    <externalId>true</externalId>
    <label>Class Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Class__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>unique name of the class.</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>used to select the course of the class</description>
    <label>Course</label>
    <referenceTo>Course_Catalog__c</referenceTo>
    <relationshipLabel>classes</relationshipLabel>
    <relationshipName>classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/Course_Catalog__c.object-meta.xml
<CustomObject>
    <description>Used to store information related to the Courses and class Containing these courses.</description>
    <label>Course Catalog</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Course Catalog Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Catalog__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <externalId>true</externalId>
    <label>Course Code</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>name of the course and no two courses having same Name.</description>
    <label>Course Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MockHttpResponseGeneratorPsa.cls
@isTest
global class MockHttpResponseGeneratorPsa implements HttpCalloutMock {
 
    // Implement this interface method
    global HTTPResponse respond(HTTPRequest req) {        
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type',  'text/csv');

        res.setHeader('Location', 'url');
        
        string body;
       
     body = 'testbody';
         res.setBody(body);

        res.setStatusCode(200);
        return res;
    }
    
    
    public String courseCatalogObj()
    {
     system.debug('****** Inside mock courseCatalogObj');
    
      String body; 
       
         body = '\n'+
                '"Analytics Manager Sales Training","Analytics Manager Sales Training","OLT","Active","course_description","","","","","","","","","","","","22506846641","",""\n'+
                '"QTRACS Portal for Administrators","QTRACS Portal for Administrators","ILT","Active","course_description","","","","","","","","","","","","22506983353","",""\n'+
                '"QTRACS Portal for Administrators1","QTRACS Portal for Administrators1","UDT","Active","course_description1","","","","","","","","","","","","22506983354","",""\n'+             
                '"VAR: MCP50 Quiz","VAR: MCP50 Quiz","UDT","Inactive","course_description","","","","","","","","","","","","22507155041","",""\n';
              
      return body;
    }
    public String classObj()
    {
      
        Course_Catalog__c courseObj = new Course_Catalog__c();
       
        courseObj.Course_Code__c ='test course code';
        courseObj.Course_Name__c ='test name';
        insert courseObj;
        
        Class__c classObj = new Class__c();
        classObj.Class_Name__c='testClass2';
        classObj.Class_Code__c ='test class code';
        classObj.Course__c = courseObj.Id;
        insert classObj;
      
      String body;  
           body = '\n'+
                 '"","2090170036","","","","","Analytics Manager Sales Training","","","","","","","","","","","","","","","01/01/0001","","","","jmetcalf@omnitracs.com","","","22509365236","test course code","","","","","", "","",""\n'+
                 '"","2090170036","","","","","Analytics Manager Sales Training","","","","","","","","","","","","","","","01/01/0001","","","","jmetcalf@omnitracs2.com","","","22509365236","test course code","","","","","", "","",""\n'+
                 '"","2090170037","","","","","QTRACS Portal for Administrators","","","","","","","","","","","","","","","01/01/0002","","","","jmetcalf@omnitracs.com","","","22509365237","test course code","","","","","", "","",""\n'+               
                 '"","2090170038","","","","","QTRACS Portal for Administrators1","","","","","","","","","","","","","","","01/01/0002","","","","jmetcalf@omnitracs4.com","","","22509365238","22506983354","","","","","", "","",""\n'+
                 '"","2090178037","","","","","VAR: MCP50 Quiz","","","","","","","","","","","","","","","01/01/0003","","","","jmetcalf@omnotracs2.com","","","22509365737","test course code2","","","","","", "","",""';
      return body;
    }
      
       public String trainingHistoryObj()
    {
    
     Course_Catalog__c courseObj = new Course_Catalog__c();
        courseObj.Course_Code__c ='test course code';
        courseObj.Course_Name__c ='test name';
        insert courseObj;
        
        Class__c classObj = new Class__c();
        classObj.Class_Name__c='testClass1';
        classObj.Class_Code__c ='test class code';
        classObj.Course__c = courseObj.Id;
        insert classObj;
        
      String body;  
          body = '\n'+ 
                 '"","jmetcalf@omnitracs.com","","","","","","","","","","","","","","","01/05/2016"," ","01/08/2016","Completed","","Expired","","22507083797","test class code","","","",""\n'+
                 '"","jmetcalf@omnitracs.com","","","","","","","","","","","","","","","01/05/2016"," ","01/12/2016","Completed","","Enrolled","","22507201647","test class code2","","","",""\n'+
                 '"","jmetcalf@omnitracs2.com","","","","","","","","","","","","","","","01/05/2016"," ","01/13/2016","Completed","","Enrolled","","22507083797","test class code1","","","",""\n'+                
                 '"","jmetcalf@omnitracs4.com","","","","","","","","","","","","","","","01/05/2016"," ","01/13/2016","Completed","","Enrolled","","22507083797","22509365238","","","",""\n'+ 
                 '"","jmetcalf@omnitracs3.com","","","","","","","","","","","","","","","01/05/2016"," ","01/13/2016","Completed","","Enrolled","","22507083797","test class code2","","","",""';  
                 
      
                   return body;
    }
    
       public String contactObj()
    {
      String body;  
           body = body = '\n'+ 
                 '"819c846c-0e70-4dda-8404-34961a7ca4bc","jmetcalf@omnitracs.com","Active","","","","","","","","","","","","","","","","","","","","","",""\n'+
                 '"ae1d778c-a933-4e4d-ac75-874719b3327d","jmetcalf@omnitracs2.com","Inactive","","","","","","","","","","","","","","","","","","","","","",""\n'+
                 '"2770842e-ad2b-4f1a-9ffc-d0b1051fdbd8","jmetcalf@omnitracs3.com","Active","","","","","","","","","","","","","",""," ","","","","","","",""';
           
            return body;
    }
    
    
}