force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <description>provide Information about the class,Instructor of the class and all the courses that class Contains</description>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Class Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>unique name of the class.</description>
    <label>Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>used to select the course of the class</description>
    <label>Course</label>
    <referenceTo>Course_Catalog__c</referenceTo>
    <relationshipLabel>classes</relationshipLabel>
    <relationshipName>classes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Catalog__c/Course_Catalog__c.object-meta.xml
<CustomObject>
    <description>Used to store information related to the Courses and class Containing these courses.</description>
    <label>Course Catalog</label>
    <nameField>
        <displayFormat>CT-{000000}</displayFormat>
        <label>Course Catalog Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_History__c/Training_History__c.object-meta.xml
<CustomObject>
    <label>Training History</label>
    <nameField>
        <displayFormat>TH-{00000}</displayFormat>
        <label>Training History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_History__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the class</description>
    <label>Class Name</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Training Histories</relationshipLabel>
    <relationshipName>Training_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Provides information about when training completes</description>
    <label>Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Histories</relationshipLabel>
    <relationshipName>Training_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <description>tracks information about when registration happened for training.</description>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training_History__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <description>refers the instructor name of the class</description>
    <formula>Class_Name__r.Instructor__r.FirstName &amp;&quot;,&quot;&amp; Class_Name__r.Instructor__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trainer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training_Information__c/Training_Information__c.object-meta.xml
<CustomObject>
    <description>Store information needed for training.</description>
    <label>Training Information</label>
    <nameField>
        <label>Training Information</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Information__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Information</relationshipLabel>
    <relationshipName>Training_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training_Information__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>end date for Webinar/Learning lab</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training_Information__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>start date for webinar/learning lab</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training_Information__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Training_Information__c/recordTypes/Webinar.recordType-meta.xml
<RecordType>
    <fullName>Webinar</fullName>
    <active>true</active>
    <description>Webinar</description>
    <label>Webinar</label>
</RecordType>

force-app/main/default/classes/PSATrainingDetailController.cls
/*
Author : TCS Banglore offshore Team
Summary:This page act as a controller for the PSATrainingDetail vf page,which displays the training information and training history of a particular contact 
*/

public with sharing class PSATrainingDetailController 
{

      public Contact contactDetail {get;set;} 
      
      public List<Training_Information__c> webinarList{get; set;}
  
      public List<Training_Information__c> learninglabList{get; set;}
    
      public List<Training_History__c> trainingHistoryList{get; set;}
      
      public Boolean webinarFlag{get; set;}
      public Boolean learninglabFlag{get; set;}
      public Boolean trainingHistoryFlag{get; set;}
      
      public Boolean webinarMsgFlag{get; set;}
      public Boolean learninglabMsgFlag{get; set;}
      public Boolean trainingHistoryMsgFlag{get; set;}      
          
  public PSATrainingDetailController(ApexPages.StandardController stdController) 
  {
     
      webinarFlag=True;
      learninglabFlag=True;
      trainingHistoryFlag=True;
      
      webinarMsgFlag=False;
      learninglabMsgFlag=False;
      trainingHistoryMsgFlag=False;            
      
     this.contactDetail= (Contact)stdController.getRecord();
      Id cid= contactDetail.Id;                 
      contactDetail = [SELECT Id, LastName,User_Status__c, FirstName, AccountId, Email, MobilePhone, Phone, Department, Fax, ReportsTo.Name, 
                       OtherPhone, Description, CreatedById, LastModifiedById FROM Contact WHERE Id =: cid];
        
         If(cid!=null)
        {
         detail(cid);
        }

     }
     
    public void detail(Id cid)
    {
               
      webinarList=[SELECT Id, Name, Start_Date__c, End_Date__c, Status__c FROM Training_Information__c Where (Training_Information__c.Contact__r.Id =: cid)AND(RecordType.Name='Webinar')];

      learninglabList=[SELECT Id, Name, Start_Date__c, End_Date__c, Status__c FROM Training_Information__c Where (Training_Information__c.Contact__r.Id =: cid)AND(RecordType.Name='Learning Lab')];

      trainingHistoryList =[Select Id, Name, Registration_Date__c, Completion_Date__c, Trainer__c, Training_History__c.Class_Name__r.Class_Name__c, Training_History__c.Class_Name__r.Id, 
                            Training_History__c.Class_Name__r.Course__r.Course_Type__c From Training_History__c 
                            where Training_History__c.Contact__r.Id =:cid ORDER BY Completion_Date__c DESC NULLS LAST] ;
                                               
        If(webinarList.size()==0)
        {
          webinarFlag=False;
          webinarMsgFlag=True;
   
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,'No record found.');
           ApexPages.addMessage(myMsg);
        }
        
        If(learninglabList.size()==0)
        {
           learninglabFlag=False;
           learninglabMsgFlag=True;
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,'No record found.');
           ApexPages.addMessage(myMsg);
        }
        
        If(trainingHistoryList.size()==0)
        {
           trainingHistoryFlag=False;
           trainingHistoryMsgFlag=True;
           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Info,'No record found.');
           ApexPages.addMessage(myMsg);
        }

    }  
}