force-app/main/default/objects/OAuth_Connection_Details__c/OAuth_Connection_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>OAuth Connection Details for Case details</description>
    <label>OAuth Connection Details</label>
</CustomObject>

force-app/main/default/objects/OAuth_Connection_Details__c/fields/Client_Id_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Id_Secret__c</fullName>
    <label>Client Id Secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OAuth_Connection_Details__c/fields/Token_Endpoint_Url__c.field-meta.xml
<CustomField>
    <fullName>Token_Endpoint_Url__c</fullName>
    <label>Token Endpoint Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/OAuth_Connection_Details__c/fields/Token_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Token_Updated_Time__c</fullName>
    <label>Token Updated Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OAuth_Connection_Details__c/fields/Username_Password__c.field-meta.xml
<CustomField>
    <fullName>Username_Password__c</fullName>
    <label>Username Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TokenUpdateSchedule.cls
/***************************************************************************************************
 Created by: Yasir Arafat
 Date: 09/07/2020
 Service to update Access Token for Case Sync
****************************************************************************************************/
global class TokenUpdateSchedule implements Database.Batchable<OAuth_Connection_Details__c>, Database.Stateful, Database.AllowsCallouts, Schedulable {
    
    public boolean isAnyError = false;
    public String errorContent = '';
    public TokenUpdateSchedule(){}
        
    global List<OAuth_Connection_Details__c> start(Database.BatchableContext BC){
        List<OAuth_Connection_Details__c> outhConnList = new List<OAuth_Connection_Details__c>();
        OAuth_Connection_Details__c oauthConn = OAuth_Connection_Details__c.getOrgDefaults();
        outhConnList.add(oauthConn);
        return outhConnList;
    }
        
    global void execute(Database.BatchableContext BC, List<OAuth_Connection_Details__c> outhConnList) {
        try{
            OAuth_Connection_Details__c oauthConn = outhConnList.get(0);
            HttpRequest req = new HttpRequest();
            req.setMethod('POST');
            req.setEndpoint(oauthConn.Token_Endpoint_Url__c + oauthConn.Client_Id_Secret__c + oauthConn.Username_Password__c);
            Http http = new Http();
            HTTPResponse res = http.send(req);
            System.debug('Status Code: ' + res.getStatusCode() + '. Response Body: ' + res.getBody());
            isAnyError = res.getStatusCode() == 200 ? false : true;
            if(res.getStatusCode() == 200){
                Map<String, Object> respMap = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
                oauthConn.Instance_Url__c = String.valueOf(respMap.get('instance_url'));
                oauthConn.Access_Token__c = String.valueOf(respMap.get('access_token'));
                oauthConn.Token_Updated_Time__c = DateTime.NOW();
                update oauthConn;
                System.debug('TokenUpdateSchedule successful');
            }else{
                isAnyError = true;
                errorContent = 'Error Occured while updating Access Token for Case Custom Adapter Service: ' + res.getBody();
                System.debug('TokenUpdateSchedule failed');
            }
        }catch(Exception e){
            isAnyError = true;
            errorContent = 'Error Occured while updating Access Token for Case Custom Adapter Service: ' + e.getMessage();
        }
    }
    
    //System.schedule('TokenUpdateSchedule', '0 0 0,4,8,12,16,20 * * ?', new TokenUpdateSchedule());    // Schedule to run evry 4 hours
    global void execute(SchedulableContext sc){
        Database.executeBatch(this, 1);
    }
     
    global void finish(Database.BatchableContext BC){
        if(isAnyError){
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setSenderDisplayName('Token Update Schedule Error');
            String[] toAddresses = new List<String> {UserInfo.getUserEmail()};
            String[] ccAddresses = new List<String> {'yarafat@omnitracs.com'};
            email.setSubject('Token Update Schedule Error');       
            email.setToAddresses(toAddresses);
            email.setCcAddresses(ccAddresses);
            email.setPlainTextBody(errorContent);
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }
    }
}