force-app/main/default/objects/Connection_Type__c/Connection_Type__c.object-meta.xml
<CustomObject>
    <label>Connection Type</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Connection Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connection Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Type__c/fields/Connection_Type__c.field-meta.xml
<CustomField>
    <fullName>Connection_Type__c</fullName>
    <label>Connection Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALK</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>Bill Back Dial In</fullName>
            </value>
            <value>
                <fullName>CDS</fullName>
            </value>
            <value>
                <fullName>CER</fullName>
            </value>
            <value>
                <fullName>Dial In 800</fullName>
            </value>
            <value>
                <fullName>Dial In LOCAL</fullName>
            </value>
            <value>
                <fullName>Driver Email</fullName>
            </value>
            <value>
                <fullName>Driver Notification</fullName>
            </value>
            <value>
                <fullName>Driver Workflow</fullName>
            </value>
            <value>
                <fullName>Frame Relay</fullName>
            </value>
            <value>
                <fullName>GTracs/Web</fullName>
            </value>
            <value>
                <fullName>InCab Scanning</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MPLS</fullName>
            </value>
            <value>
                <fullName>Navigation</fullName>
            </value>
            <value>
                <fullName>OMNI1</fullName>
            </value>
            <value>
                <fullName>PPP 800</fullName>
            </value>
            <value>
                <fullName>PPP LOCAL</fullName>
            </value>
            <value>
                <fullName>PPTP</fullName>
            </value>
            <value>
                <fullName>QHOS Sub</fullName>
            </value>
            <value>
                <fullName>QMASS</fullName>
            </value>
            <value>
                <fullName>QTRACS/Services Portal</fullName>
            </value>
            <value>
                <fullName>QTracs/Web</fullName>
            </value>
            <value>
                <fullName>RVG</fullName>
            </value>
            <value>
                <fullName>Shared Frame Relay</fullName>
            </value>
            <value>
                <fullName>STRACS/Services Portal</fullName>
            </value>
            <value>
                <fullName>T2/Services Portal</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>TPMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Connection_Type__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>Connection_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/NMC_Account__c.object-meta.xml
<CustomObject>
    <label>NMC Account</label>
    <nameField>
        <label>NMC Account Name / Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NMC Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <description>NMC Account #</description>
    <label>NMC Account #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/Serialized_Units__c.object-meta.xml
<CustomObject>
    <label>Serialized Unit</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Units__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>R00N50000001d4DsEAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestOutageContactWizardController.cls
/*********************************************************************
Name    : TestOutageContactWizardController
Author  : Shruti Karn
Date    : 12 April 2011

Usage   : Test class for OutageContactWizardController


*********************************************************************/
@isTest(SeeAllData=true)
private class TestOutageContactWizardController{   
static OutageContactWizardController newObj = new OutageContactWizardController();
static Account Acct = GenericTestClass.insertAccount();
static NMC_Account__c NMC = GenericTestClass.insertNMCAccount(Acct.ID);
private static testmethod void runTest(){
   
      
        newObj.redirectToStep2();
        newObj.redirectToStep3();
        list<selectOption> lstContactTypes = newObj.getContactTypes();
        newObj.retrieveNMCSystemValues();
        newObj.lstSelected_nmc_system_hardware  = new String[] {'1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16'};
        selectHardware();
        selectNMCSystems();
        selectPoratlSystem();
        redirecttostep4();
       
} 
    private static void selectHardware(){
        newObj.retrieveHardwarePicklistValues();
        String[] hardwareSelections = new String[] {'GT','GTL','OT','OV','OV2','OVM','OVT','OX','OX2','T2','MCP110','TT210'};
        newObj.setlstSelected_hardware(hardwareSelections);
        newObj.strNotification_topic = System.Label.HARDWARE_VALUE;
        Serialized_Units__c serUnit = GenericTestClass.insertSerUnit(Acct.ID);
        newObj.findSerUnit();
        newObj.findNMCAcct();
        newObj.findContact();
       
    }
    
     private static void selectNMCSystems(){
        newObj.strNotification_topic = System.Label.NMC_SYSTEM_VALUE;
        newObj.findNMCAcct();
        newObj.findContact();
     }
        
    private static void selectPoratlSystem()
    {
        newObj.strNotification_topic = System.Label.PORTAL_AND_SERVICES_VALUE;
        Connection_Type__c connType = GenericTestClass.insertConnType(NMC.Id);
    }
    
    private static void redirecttostep4()
    {
        String[] contactTypeSelections = new String[]{'Battery Alert', 'Downtime/Degraded', 'Newsletter', 'Portal Services Platform', 'Press', 'Product Information', 'RMA Initiator', 'Seminars/Conferences', 'SFM, Sr. Management', 'SSO Portal Administrator', 'Time Change'};
        newObj.setLstSelected_contact_types(contactTypeSelections);
        contactTypeSelections = newObj.getLstSelected_contact_types();
         newObj.alphabet = 'All';
         newObj.findContact();
         newObj.alphabetOrdering();
         newObj.redirectToStep5();
         newObj.findContact();
         newObj.next();
         newObj.previous();
         Contact cnt = GenericTestClass.insertContact(Acct.ID);
         String cntName = [Select id,name from Contact where id= : cnt.ID limit 1].name;
         newObj.search_value = cntName;
         newObj.SearchContact();
         newObj.asce = true; 
         newObj.changeOrder();
         newObj.asce = false;
         newObj.changeOrder();
         newObj.redirectToStep1();
         newObj.redirectToStep4();
         newObj.redirectToStep6();
         newObj.findConnectionType();
         newObj.findNMCAcct();
         newObj.findContact();
         newObj.updateContactRecords();
         newObj.showMsg();
         newObj.insertCampaign();
         newObj.uploadFile();
         newObj.ExporttoExcel();
         newObj.findSelContacts();
         newObj.clearFile();
         
    }
}