force-app/main/default/objects/Connection_Type__c/Connection_Type__c.object-meta.xml
<CustomObject>
    <label>Connection Type</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Connection Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connection Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Type__c/fields/Connection_Type__c.field-meta.xml
<CustomField>
    <fullName>Connection_Type__c</fullName>
    <label>Connection Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALK</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>Bill Back Dial In</fullName>
            </value>
            <value>
                <fullName>CDS</fullName>
            </value>
            <value>
                <fullName>CER</fullName>
            </value>
            <value>
                <fullName>Dial In 800</fullName>
            </value>
            <value>
                <fullName>Dial In LOCAL</fullName>
            </value>
            <value>
                <fullName>Driver Email</fullName>
            </value>
            <value>
                <fullName>Driver Notification</fullName>
            </value>
            <value>
                <fullName>Driver Workflow</fullName>
            </value>
            <value>
                <fullName>Frame Relay</fullName>
            </value>
            <value>
                <fullName>GTracs/Web</fullName>
            </value>
            <value>
                <fullName>InCab Scanning</fullName>
            </value>
            <value>
                <fullName>MMS</fullName>
            </value>
            <value>
                <fullName>MPLS</fullName>
            </value>
            <value>
                <fullName>Navigation</fullName>
            </value>
            <value>
                <fullName>OMNI1</fullName>
            </value>
            <value>
                <fullName>PPP 800</fullName>
            </value>
            <value>
                <fullName>PPP LOCAL</fullName>
            </value>
            <value>
                <fullName>PPTP</fullName>
            </value>
            <value>
                <fullName>QHOS Sub</fullName>
            </value>
            <value>
                <fullName>QMASS</fullName>
            </value>
            <value>
                <fullName>QTRACS/Services Portal</fullName>
            </value>
            <value>
                <fullName>QTracs/Web</fullName>
            </value>
            <value>
                <fullName>RVG</fullName>
            </value>
            <value>
                <fullName>Shared Frame Relay</fullName>
            </value>
            <value>
                <fullName>STRACS/Services Portal</fullName>
            </value>
            <value>
                <fullName>T2/Services Portal</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>TPMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Connection_Type__c/fields/Last_Originating_Number_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Originating_Number_Change__c</fullName>
    <description>This field will be updated by Apex Code whenever an Originating Number child record changes.  The intent is to trigger the workflow rule that will send the Outbound Message to TIBCO.</description>
    <label>Last Originating Number Change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Connection_Type__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>Connection_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/NMC_Account__c.object-meta.xml
<CustomObject>
    <label>NMC Account</label>
    <nameField>
        <label>NMC Account Name / Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NMC Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <description>NMC Account #</description>
    <label>NMC Account #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Originating_Number__c/Originating_Number__c.object-meta.xml
<CustomObject>
    <label>Originating Number</label>
    <nameField>
        <displayFormat>ON-{0000}</displayFormat>
        <label>Originating Number ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Originating Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Originating_Number__c/fields/Connection_Type__c.field-meta.xml
<CustomField>
    <fullName>Connection_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Connection Type</label>
    <referenceTo>Connection_Type__c</referenceTo>
    <relationshipLabel>Originating Numbers</relationshipLabel>
    <relationshipName>R00N50000001caH8EAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Originating_Number__c/fields/Originating_Number__c.field-meta.xml
<CustomField>
    <fullName>Originating_Number__c</fullName>
    <label>Originating Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/TestOrigNumUpdate.cls
@isTest(SeeAllData = true)
public class TestOrigNumUpdate {
    static testmethod void testOrigNumUpdateConnectionType() {
        
//Select c.Id, c.Last_Originating_Number_Change__c, c.NMC_Account__c from Connection_Type__c c WHERE c.Id = 'a06500000016ZInAAM'
//Select o.Connection_Type__c, o.Id, o.Name from Originating_Number__c o LIMIT 1
      Originating_Number__c origNum = new Originating_Number__c();
      Account Acct = GenericTestClass.insertAccount();
      NMC_Account__c NMC = GenericTestClass.insertNMCAccount(Acct.Id);
      Connection_Type__c connType = GenericTestClass.insertConnType(NMC.Id);
      origNum.Connection_Type__c = connType.Id;
      insert origNum;
      origNum = [Select o.Connection_Type__c, o.Id, o.Name,Originating_Number__c from Originating_Number__c o where id =:origNum.Id LIMIT 1];       
      origNum.Originating_Number__c  = '(555) 555-5555';
      
      update origNum;
      
      //Parent connection type should've been updated with Last_Originating_Number_Change__c timestamp
      Connection_Type__c updatedConnType = [Select c.Id, c.Last_Originating_Number_Change__c, c.NMC_Account__c from Connection_Type__c c WHERE c.Id = :origNum.Connection_Type__c];      
      Datetime yesterday = System.now() - 1; 
      System.assert(updatedConnType.Last_Originating_Number_Change__c > yesterday);
    }
} //end class TestOrigNumUpdate