force-app/main/default/objects/Connection_Type__c/Connection_Type__c.object-meta.xml
<CustomObject>
    <label>Connection Type</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Connection Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connection Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connection_Type__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>Connection_Types</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connection_Type__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Disaster Recovery</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Restoral</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Request__c/Contract_Request__c.object-meta.xml
<CustomObject>
    <label>Contract Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contract Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Requests</relationshipLabel>
    <relationshipName>R00N50000001eJHTEA2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Use this Request Type only if no other Request Type fits your needs.</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/NMC_Account__c/NMC_Account__c.object-meta.xml
<CustomObject>
    <label>NMC Account</label>
    <nameField>
        <label>NMC Account Name / Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NMC Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NMC_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NMC Accounts</relationshipLabel>
    <relationshipName>NMC_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <description>NMC Account #</description>
    <label>NMC Account #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account_Name__c</fullName>
    <label>NMC Account Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary__c/Serialized_Unit_Summary__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for CustomObject.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Serialized Unit Summary</label>
    <nameField>
        <label>SU Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Unit Summarys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Unit Summarys</relationshipLabel>
    <relationshipName>SU_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/Serialized_Units__c.object-meta.xml
<CustomObject>
    <label>Serialized Unit</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Units__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account related to this Serialized Unit</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Units</relationshipLabel>
    <relationshipName>R00N50000001eVUXEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>R00N50000001d4DsEAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Support_Alert__c/Support_Alert__c.object-meta.xml
<CustomObject>
    <label>Support Alert</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Support Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Alert__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Support Alerts</relationshipLabel>
    <relationshipName>Support_Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Support_Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/System_Outage__c.object-meta.xml
<CustomObject>
    <description>Custom object to store System Outage information related to Cases.</description>
    <label>System Outage</label>
    <nameField>
        <displayFormat>SO-{0000}</displayFormat>
        <label>System Outage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Outages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Outage__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>System_Outage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time (PST/PDT)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/SubSystems__c.field-meta.xml
<CustomField>
    <fullName>SubSystems__c</fullName>
    <label>SubSystems-old</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>System__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AA&amp;D</fullName>
            </value>
            <value>
                <fullName>AAA</fullName>
            </value>
            <value>
                <fullName>AmberWatch</fullName>
            </value>
            <value>
                <fullName>Asset Tracker</fullName>
            </value>
            <value>
                <fullName>AT&amp;T – Frame Relay</fullName>
            </value>
            <value>
                <fullName>BGW (EU)</fullName>
            </value>
            <value>
                <fullName>BGW (US)</fullName>
            </value>
            <value>
                <fullName>BGW200</fullName>
            </value>
            <value>
                <fullName>CARDIONET</fullName>
            </value>
            <value>
                <fullName>CDS - Content Delivery Service</fullName>
            </value>
            <value>
                <fullName>CER - Critical Event Reporting</fullName>
            </value>
            <value>
                <fullName>CNR OVM - AEF Portal</fullName>
            </value>
            <value>
                <fullName>CS - Common Services</fullName>
            </value>
            <value>
                <fullName>DE - Driver Email</fullName>
            </value>
            <value>
                <fullName>DN – Driver Notification</fullName>
            </value>
            <value>
                <fullName>DW - Driver Workflow</fullName>
            </value>
            <value>
                <fullName>EGGW200</fullName>
            </value>
            <value>
                <fullName>EMGW200 - GPRS</fullName>
            </value>
            <value>
                <fullName>EOMNI200/EMGW200-GPRS</fullName>
            </value>
            <value>
                <fullName>EOMNI200 - GPRS</fullName>
            </value>
            <value>
                <fullName>Europe200</fullName>
            </value>
            <value>
                <fullName>Europe200/EGGW200-GTE</fullName>
            </value>
            <value>
                <fullName>Fleetvisor (EU)</fullName>
            </value>
            <value>
                <fullName>GGW200</fullName>
            </value>
            <value>
                <fullName>Ghos/Qhos/Guava</fullName>
            </value>
            <value>
                <fullName>GlobalTRACS/Europe</fullName>
            </value>
            <value>
                <fullName>GlobalTRACSWeb</fullName>
            </value>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GSS - Geo Spatial Services</fullName>
            </value>
            <value>
                <fullName>IES Mobile/ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <label>System-old</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Providers</fullName>
            </value>
            <value>
                <fullName>NMC</fullName>
            </value>
            <value>
                <fullName>NMC - Hosted</fullName>
            </value>
            <value>
                <fullName>QDC</fullName>
            </value>
            <value>
                <fullName>QSP (Mex)</fullName>
            </value>
            <value>
                <fullName>QSP (US)</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Outage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Degraded Service</fullName>
            </value>
            <value>
                <fullName>Planned Downtime</fullName>
            </value>
            <value>
                <fullName>Unplanned Downtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenericTestClass.cls
public with sharing class GenericTestClass {
    public static Integer custID = 12101986;
    public static Integer NMCAccount = 12101986;
    // Insert Account Record        
        public static Account insertAccount()
        {
            Account newAccount = new Account();
            newAccount.Name = 'SFDC';
            newAccount.Type = 'Other';
            newAccount.BillingStreet = 'BillingStreet';
            newAccount.BillingCity = 'BillingCity';
            newAccount.BillingState = 'BillingState';
            newAccount.BillingPostalCode = '12345';
            newAccount.BillingCountry = 'BillingCountry';
            newAccount.Fleet_Size__c = 5;
            newAccount.Segment__c = 'TL';
            newAccount.QWBS_Cust_ID__c = String.valueOf(custID);
            custID++; 
            insert newAccount;
            return newAccount;
        }
    //Insert Contact Record
        public static Contact insertContact(Id AcctId)
        {
            Contact newCnt=new Contact();
            newCnt.FirstName='SFDC';
            newCnt.LastName='Salesforce';
            newCnt.AccountId = AcctId;
            newCnt.MailingState = 'CA';
system.debug('newCnt:'+newCnt);
            insert newCnt;
            return newCnt;
        }
    
    //Insert NMC Account Record
        public static NMC_Account__c insertNMCAccount(Id AcctId)
        {
            NMC_Account__c newNMCAcct  = new NMC_Account__c();
            newNMCAcct.Account__c = AcctId;
            newNMCAcct.NMC_Account_Name__c = 'Test NMC Acct';
            newNMCAcct.NMC_Account__c = String.valueOf(NMCAccount);
            NMCAccount++;
            insert newNMCAcct;
            return newNMCAcct;
        }
        
    //Insert Group Record   
        public static Group insertGroup()     
        {
            Group newGroup = new Group();
            newGroup.name = 'Test Queue';
            insert newGroup;
            return newGroup;
        }
        
    //Insert 'Support Alert' Record
        public static Support_Alert__c insertSupportAlert(ID accountid)
        {
            Support_Alert__c newSuppalert = new Support_Alert__c();
            newSuppalert.Account__c = accountid;
            newSuppalert.Description__c = 'Test Descritpion';
            newSuppalert.End_Date__c =  date.today()+4;
            insert newSuppalert;
            return newSuppalert;
        }      
    //Insert 'System Outage' Record
        public static System_Outage__c insertSystemOutage(ID caseid)
        {
          System_Outage__c newSysOut = new System_Outage__c();
          newSysOut.Case__c = caseid;
          newSysOut.Type__c = 'Degraded Service';
          newSysOut.System__c = 'NMC';
          newSysOut.SubSystems__c = 'BGW200';
          newSysOut.Start_Time__c = system.now();
          insert newSysOut;
          return newSysOut;
        }
    // Insert Serialized Unit Summary Record
        public static Serialized_Unit_Summary__c insertSerUnitSumm(Id AcctId)
        {
            Serialized_Unit_Summary__c newSerUnit = new Serialized_Unit_Summary__c();
            newSerUnit.Account__c = AcctId;
            insert newSerUnit;
            return newSerUnit;
        }
        
    // Insert Serialized Unit Summary Record
        public static Serialized_Units__c insertSerUnit(Id AcctId)
        {
            Serialized_Units__c newSerUnit = new Serialized_Units__c();
            newSerUnit.Account__c = AcctId;
            newSerUnit.NMC_Account__c = GenericTestClass.insertNMCAccount(AcctId).ID;
            insert newSerUnit;
            return newSerUnit; 
        }
        
    //Insert Connection Type Record
        public static Connection_Type__c insertConnType(Id NMCId)
        {
            Connection_Type__c newConnType = new Connection_Type__c();
            newConnType.NMC_Account__c = NMCId;
            insert newConnType;
            return newConnType;
        }
        
    //Insert Case Record
    public static Case insertCase(String AcctId, String ContId)
    {
        Case newCase = new Case();
        if(AcctId != null && AcctId != '')
            newCase.AccountID = AcctID;
        if(ContId != null && ContId != '')
            newCase.ContactId = ContId;
        insert newCase;
        return newCase;
    }
    
    // Insert User
    public static User insertUser(Profile userProf, UserRole role)
    {
        if(userProf == null)
            userProf = [Select p.Id From Profile p limit 1];
        if(role == null)
            role = [Select u.Id From UserRole u limit 1];
        User NewUser = new user();
        NewUser.ProfileId = userProf.Id;
        NewUser.UserRoleId = role.Id;
        NewUser.email = 'test@test.com';
        NewUser.Username = 'test@test.com.12101986';
        NewUser.IsActive = true;
        NewUser.TimeZoneSidKey = 'America/Los_Angeles';
        NewUser.LocaleSidKey = 'en_US';
        NewUser.LastName = '12101986';
        NewUser.LanguageLocaleKey = 'en_US';
        NewUser.EmailEncodingKey = 'ISO-8859-1';
        NewUser.Alias = '12101986';
        
        insert NewUser;
        return NewUser;
    } 
    
    public static Contract_Request__c insertContReq(String AcctId)
    {
        Contract_Request__c newConReq = new Contract_Request__c();
        newConReq.Account__c = AcctID;
        newConReq.No_Approvals_Required__c = true;
        insert newConReq;
        return newConReq;
    }
    
    /*public static SIGN_Agreement__c insertSignedAgree(String AcctID,String contId)
    {
        SIGN_Agreement__c newAgreement = new SIGN_Agreement__c();
        newAgreement.Account__c = AcctId;
        //newAgreement.Recipient__c = contId;
        insert newAgreement;
        return newAgreement;
    }*/
    
}