force-app/main/default/objects/Implementation_Status_Update__c/Implementation_Status_Update__c.object-meta.xml
<CustomObject>
    <description>Object used to store information about the implementation status updates.</description>
    <label>Implementation &amp; Manage Services Summary</label>
    <nameField>
        <displayFormat>ISU-{0000}</displayFormat>
        <label>ISU #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation &amp; Manage Services Summary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Status_Update__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Implementation_Status_Updates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestImplementationStatusAll.cls
/***********************************************************************************
Date: 11 Janaury 2011 
Author: Shruti Karn

Description:  Test class for trigger "ImplementationStatusAll"  on 
              Implementation_Status_Update__c on Object
************************************************************************************/
@isTest(SeeAllData=True)
private class TestImplementationStatusAll
{
    static testMethod void insertImplementationStatus(){
        Account newAccount = new Account(); 
        newAccount.Name = 'SFDC'; 
        newAccount.Type = 'Other'; 
        newAccount.BillingStreet = 'Test Address'; 
        newAccount.BillingCity = 'Test City'; 
        newAccount.BillingCountry = 'Test Country'; 
        newAccount.QWBS_Cust_ID__c = '4567';
        insert newAccount;
        Implementation_Status_Update__c newImplemetnationRec = new Implementation_Status_Update__c();
        newImplemetnationRec.Account__c = newAccount.Id;
        insert newImplemetnationRec;
        Implementation_Status_Update__c newImplemetnationRec1 = new Implementation_Status_Update__c();
        newImplemetnationRec1.Account__c = newAccount.Id;
        insert newImplemetnationRec1;
       
    }
}