force-app/main/default/objects/ByPassTrigger__c/ByPassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ByPass Trigger</label>
</CustomObject>

force-app/main/default/objects/ByPassTrigger__c/fields/isDisabled__c.field-meta.xml
<CustomField>
    <fullName>isDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BypassTriggerUtility.cls
public with sharing class BypassTriggerUtility {
/* BypassTriggerUtility class

  Check custom setting for disable trigger flag for user 'System Admin - Data'.  
  If the isDisabled flag is checked,  the trigger logic will be 
  bypass.  (The trigger modules will reference this utiliity to optain the flag).  
  The flag is to be turn on when the Data Admin user needs to do mass upload and wants    
  to bypass the trigger.

*/
    public Boolean isDisabled;
    
    public BypassTriggerUtility () {

        ByPassTrigger__c bt = ByPassTrigger__c.getInstance();
        Boolean result = bt.isDisabled__c; 
        this.isDisabled = result;

    }
  
    public Boolean isTriggerBypassed() { 

        System.debug ('--> UserName is: ' + UserInfo.getName());
        System.debug ('--> UserId is: ' + UserInfo.getUserId());
        System.debug ('--> bt.isDisabled__c is : ' + isDisabled);
        if (this.isDisabled || UserInfo.getUserId() == label.S2S_User_Id)
            return true;
        else
            return false;
    }
}