force-app/main/default/objects/ByPassTrigger__c/ByPassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ByPass Trigger</label>
</CustomObject>

force-app/main/default/objects/ByPassTrigger__c/fields/isDisabled__c.field-meta.xml
<CustomField>
    <fullName>isDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>A summarization of the Steelbrick Subscriptions and Steelbrick Assets for the Customer.</description>
    <label>Customer Asset</label>
    <nameField>
        <label>Customer Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Assets</relationshipLabel>
    <relationshipName>Customer_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/fields/Annual_Recurring_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Annual_Recurring_Revenue__c</fullName>
    <inlineHelpText>The annual recurring revenue for the product. If product is usage based, ARR is the greater of $0 or the contracted minimum.</inlineHelpText>
    <label>Annual Recurring Revenue(hidden)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/fields/Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Status__c</fullName>
    <label>Asset Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Signed, Not Delivered</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Pending Decommission</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Link to the related product
.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Customer Assets</relationshipLabel>
    <relationshipName>Customer_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Quantity owned.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/fields/Total_One_Time_Fee_s__c.field-meta.xml
<CustomField>
    <fullName>Total_One_Time_Fee_s__c</fullName>
    <description>Net price of the related non-recurring product. API Name: Total_One_Time_Fee_s</description>
    <inlineHelpText>Net price of the related non-recurring product.</inlineHelpText>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/Customer_Asset_Shipping_Actual__c.object-meta.xml
<CustomObject>
    <label>Customer Asset Shipping Actual</label>
    <nameField>
        <displayFormat>ASA-{0}</displayFormat>
        <label>Shipping Actual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>customer Asset Shipping Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/fields/Actual_Shipped_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Shipped_Date__c</fullName>
    <label>Actual Shipped Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/fields/Actual_Shipped_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Actual_Shipped_Quantity__c</fullName>
    <label>Actual Shipped Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/fields/Customer_Asset_Shipping_Summary__c.field-meta.xml
<CustomField>
    <fullName>Customer_Asset_Shipping_Summary__c</fullName>
    <label>Customer Asset Shipping Summary</label>
    <referenceTo>Customer_Asset_Shipping_Summary__c</referenceTo>
    <relationshipLabel>Customer Asset Shipping Actuals</relationshipLabel>
    <relationshipName>Customer_Asset_Shipping_Actuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Estimate__c/Customer_Asset_Shipping_Estimate__c.object-meta.xml
<CustomObject>
    <label>Customer Asset Shipping Estimate</label>
    <nameField>
        <displayFormat>ASE-{0}</displayFormat>
        <label>Customer Asset Shipping Estimate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Asset Shipping Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset_Shipping_Estimate__c/fields/Customer_Asset_Shipping_Summary__c.field-meta.xml
<CustomField>
    <fullName>Customer_Asset_Shipping_Summary__c</fullName>
    <label>Customer Asset Shipping Summary</label>
    <referenceTo>Customer_Asset_Shipping_Summary__c</referenceTo>
    <relationshipLabel>Customer Asset Shipping Estimates</relationshipLabel>
    <relationshipName>Customer_Asset_Shipping_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Estimate__c/fields/Estimated_Shipping_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Shipping_Date__c</fullName>
    <label>Estimated Shipping Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Estimate__c/fields/Estimated_Shipping_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Shipping_Quantity__c</fullName>
    <label>Estimated Shipping Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Summary__c/Customer_Asset_Shipping_Summary__c.object-meta.xml
<CustomObject>
    <label>Customer Asset Shipping Summary</label>
    <nameField>
        <displayFormat>ASU-{0}</displayFormat>
        <label>Custmer Asset Shipping Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Asset Shipping Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset_Shipping_Summary__c/fields/Actual_Shipped_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Actual_Shipped_Quantity__c</fullName>
    <label>Actual Shipped Quantity</label>
    <summarizedField>Customer_Asset_Shipping_Actual__c.Actual_Shipped_Quantity__c</summarizedField>
    <summaryForeignKey>Customer_Asset_Shipping_Actual__c.Customer_Asset_Shipping_Summary__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Summary__c/fields/Customer_Asset__c.field-meta.xml
<CustomField>
    <fullName>Customer_Asset__c</fullName>
    <label>Customer Asset</label>
    <referenceTo>Customer_Asset__c</referenceTo>
    <relationshipLabel>Customer Asset Shipping Summaries</relationshipLabel>
    <relationshipName>Customer_Asset_Shipping_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Summary__c/fields/Estimated_Shipping_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Shipping_Quantity__c</fullName>
    <label>Estimated Shipping Quantity</label>
    <summarizedField>Customer_Asset_Shipping_Estimate__c.Estimated_Shipping_Quantity__c</summarizedField>
    <summaryForeignKey>Customer_Asset_Shipping_Estimate__c.Customer_Asset_Shipping_Summary__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/RevenueForecastHandlerTest.cls
/**
 * Test class for the Revenue Forecast Handler
 */

@isTest
public class RevenueForecastHandlerTest {

    public static testMethod void testEmpty() {
        Test.startTest();
        RevenueForecastHandler rfh = new RevenueForecastHandler();
        Test.stopTest();
    }

    /* ARMAN: public static VistaAssetHelperUtil util = new VistaAssetHelperUtil();

    @isTest
    public static void testCalculateCustomerAssetFinancialsHardware() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');


        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Hardware', '', 'Once', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }

    @isTest
    public static void testCalculateCustomerAssetFinancialsSoftwareApplications() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');


        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Software', 'Applications', 'Fixed Price', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }

    @isTest
    public static void testCalculateCustomerAssetFinancialsSoftwareServicePlans() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');

        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Software', 'Service Plans', 'Fixed Price', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }

    @isTest
    public static void testCalculateCustomerAssetFinancialsSoftwareOther() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');

        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Software', 'Other', 'Fixed Price', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }

    @isTest
    public static void testCalculateCustomerAssetFinancialsHardwareOnce() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');


        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Hardware', '', 'Once', 'Monthly', 'Once'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }

    @isTest
    public static void testCalculateCustomerAssetFinancialsSoftwareApplicationsOnce() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');


        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Software', 'Applications', 'Fixed Price', 'Monthly', 'Once'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }

    @isTest
    public static void testCalculateCustomerAssetFinancialsSoftwareServicePlansOnce() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');

        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Software', 'Service Plans', 'Fixed Price', 'Monthly', 'Once'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }

    @isTest
    public static void testCalculateCustomerAssetFinancialsSoftwareOtherOnce() {

        insert new ByPassTrigger__c(SetupOwnerId = UserInfo.getOrganizationId(), isDisabled__c = true, Name = 'Testing Bypass');

        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.BillingCountry = 'USA';
        insert newAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Software', 'Other', 'Fixed Price', 'Monthly', 'Once'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);

        Customer_Asset__c newAsset = new Customer_Asset__c();
        newAsset.Name = 'Test Asset';
        newAsset.Quantity__c = 1;
        newAsset.Total_One_Time_Fee_s__c = 1.00;
        newAsset.Annual_Recurring_Revenue__c = 1.00;
        newAsset.Product__c = productList[0].Id;
        newAsset.Term_Start_Date__c = System.today();
        newAsset.Term_End_Date__c = System.today().addMonths(12);
        newAsset.Account__c = newAccount.Id;
        newAsset.Asset_Status__c = 'Active';
        insert newAsset;

        Customer_Asset_Shipping_Summary__c ss = new Customer_Asset_Shipping_Summary__c();
        ss.Customer_Asset__c = newAsset.Id;
        insert ss;

        List<Customer_Asset_Shipping_Actual__c> al = new List<Customer_Asset_Shipping_Actual__c>();
        Customer_Asset_Shipping_Actual__c sa = new Customer_Asset_Shipping_Actual__c();
        sa.Actual_Shipped_Date__c = System.today();
        sa.Actual_Shipped_Quantity__c = 1;
        sa.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa);

        Customer_Asset_Shipping_Actual__c sa1 = new Customer_Asset_Shipping_Actual__c();
        sa1.Actual_Shipped_Date__c = System.today();
        sa1.Actual_Shipped_Quantity__c = 1;
        sa1.Customer_Asset_Shipping_Summary__c = ss.Id;
        al.add(sa1);

        insert al;

        List<Customer_Asset_Shipping_Estimate__c> el = new List<Customer_Asset_Shipping_Estimate__c>();
        Customer_Asset_Shipping_Estimate__c se = new Customer_Asset_Shipping_Estimate__c();
        se.Customer_Asset_Shipping_Summary__c = ss.Id;
        se.Estimated_Shipping_Date__c = System.today();
        se.Estimated_Shipping_Quantity__c = 1;
        el.add(se);

        Customer_Asset_Shipping_Estimate__c se1 = new Customer_Asset_Shipping_Estimate__c();
        se1.Customer_Asset_Shipping_Summary__c = ss.Id;
        se1.Estimated_Shipping_Date__c = System.today();
        se1.Estimated_Shipping_Quantity__c = 1;
        el.add(se1);

        insert el;

        Test.startTest();
        RevenueForecastHandler.calculateCustomerAssetFinancials(newAsset.Id);
        Test.stopTest();

    }*/
}