force-app/main/default/objects/ByPassTrigger__c/ByPassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ByPass Trigger</label>
</CustomObject>

force-app/main/default/objects/ByPassTrigger__c/fields/isDisabled__c.field-meta.xml
<CustomField>
    <fullName>isDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Customer_Asset__c/Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>A summarization of the Steelbrick Subscriptions and Steelbrick Assets for the Customer.</description>
    <label>Customer Asset</label>
    <nameField>
        <label>Customer Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Assets</relationshipLabel>
    <relationshipName>Customer_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/Customer_Asset_Shipping_Actual__c.object-meta.xml
<CustomObject>
    <label>Customer Asset Shipping Actual</label>
    <nameField>
        <displayFormat>ASA-{0}</displayFormat>
        <label>Shipping Actual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>customer Asset Shipping Actuals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/fields/Actual_Shipped_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Shipped_Date__c</fullName>
    <label>Actual Shipped Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/fields/Actual_Shipped_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Actual_Shipped_Quantity__c</fullName>
    <label>Actual Shipped Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Actual__c/fields/Customer_Asset_Shipping_Summary__c.field-meta.xml
<CustomField>
    <fullName>Customer_Asset_Shipping_Summary__c</fullName>
    <label>Customer Asset Shipping Summary</label>
    <referenceTo>Customer_Asset_Shipping_Summary__c</referenceTo>
    <relationshipLabel>Customer Asset Shipping Actuals</relationshipLabel>
    <relationshipName>Customer_Asset_Shipping_Actuals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Summary__c/Customer_Asset_Shipping_Summary__c.object-meta.xml
<CustomObject>
    <label>Customer Asset Shipping Summary</label>
    <nameField>
        <displayFormat>ASU-{0}</displayFormat>
        <label>Custmer Asset Shipping Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Asset Shipping Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Asset_Shipping_Summary__c/fields/Actual_Shipped_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Actual_Shipped_Quantity__c</fullName>
    <label>Actual Shipped Quantity</label>
    <summarizedField>Customer_Asset_Shipping_Actual__c.Actual_Shipped_Quantity__c</summarizedField>
    <summaryForeignKey>Customer_Asset_Shipping_Actual__c.Customer_Asset_Shipping_Summary__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Customer_Asset_Shipping_Summary__c/fields/Customer_Asset__c.field-meta.xml
<CustomField>
    <fullName>Customer_Asset__c</fullName>
    <label>Customer Asset</label>
    <referenceTo>Customer_Asset__c</referenceTo>
    <relationshipLabel>Customer Asset Shipping Summaries</relationshipLabel>
    <relationshipName>Customer_Asset_Shipping_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CustomerAssetShippingActualTriggerTest.cls
/**
 * Test for the CustomerAssetShippingEstimateTrigger.
 */

@IsTest
private class CustomerAssetShippingActualTriggerTest {

    static testMethod void createNewCustomerShippingActual() {
        ByPassTrigger__c byPassTrigger = new ByPassTrigger__c(SetupOwnerId=UserInfo.getOrganizationId(), isDisabled__c=true, Name='Testing Bypass');
        insert byPassTrigger;

        VistaAssetHelperUtil utils = new VistaAssetHelperUtil();
        Account account = utils.createAccount('Test Account');
        Customer_Asset__c asset = new Customer_Asset__c(Account__c=account.Id, Term_Start_Date__c=Date.today());
        insert asset;

        Customer_Asset_Shipping_Summary__c summary = new Customer_Asset_Shipping_Summary__c(Customer_Asset__c=asset.Id);
        insert summary;

        delete byPassTrigger;

        Customer_Asset_Shipping_Actual__c actual = new Customer_Asset_Shipping_Actual__c(Customer_Asset_Shipping_Summary__c=summary.Id, Actual_Shipped_Date__c=Date.today(), Actual_Shipped_Quantity__c=50);
        insert actual;

        Test.startTest();

        actual.Actual_Shipped_Date__c = Date.today().addDays(5);
        actual.Actual_Shipped_Quantity__c = 100;

        try {
            update actual;
        } catch(Exception eek) {
            System.debug('Failed to update estimate: ' + eek.getMessage());
        }

        try {
            delete actual;
        } catch(Exception eek) {
            System.debug('Failed to update estimate: ' + eek.getMessage());
        }
        Test.stopTest();
    }
}