force-app/main/default/objects/ByPassTrigger__c/ByPassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ByPass Trigger</label>
</CustomObject>

force-app/main/default/objects/ByPassTrigger__c/fields/isDisabled__c.field-meta.xml
<CustomField>
    <fullName>isDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_Accounts__c/Related_Accounts__c.object-meta.xml
<CustomObject>
    <description>This object is created for Contract Management.</description>
    <label>Related Account</label>
    <nameField>
        <displayFormat>RAN-{0000000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Related_Accounts__c/fields/Child_Account__c.field-meta.xml
<CustomField>
    <fullName>Child_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Created for Contract Management.</description>
    <label>Child Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Accounts</relationshipLabel>
    <relationshipName>Parent_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Related_Accounts__c/fields/Child_Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Child_Relationship_Type__c</fullName>
    <label>Child Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Assingnor</fullName>
            </value>
            <value>
                <fullName>Authorized Reseller</fullName>
            </value>
            <value>
                <fullName>BD Team Linked</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Business Unit/Segment</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Buyer&apos;s Agent</fullName>
            </value>
            <value>
                <fullName>Co-Lessor</fullName>
            </value>
            <value>
                <fullName>Committee</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Consortium/Group</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consulting Services Beneficiary</fullName>
            </value>
            <value>
                <fullName>Custodian/Trustee</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Division</fullName>
            </value>
            <value>
                <fullName>Duplicate Accounts</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Financing Company</fullName>
            </value>
            <value>
                <fullName>Former Employee</fullName>
            </value>
            <value>
                <fullName>Former Employer</fullName>
            </value>
            <value>
                <fullName>Founder</fullName>
            </value>
            <value>
                <fullName>Group Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_Accounts__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Related_Accounts__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Accounts</relationshipLabel>
    <relationshipName>Child_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Related_Accounts__c/fields/Relationship_Type__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Type__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Relationship Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Assignee</fullName>
            </value>
            <value>
                <fullName>Assingnor</fullName>
            </value>
            <value>
                <fullName>Authorized Reseller</fullName>
            </value>
            <value>
                <fullName>BD Team Linked</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Business Unit/Segment</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Buyer&apos;s Agent</fullName>
            </value>
            <value>
                <fullName>Co-Lessor</fullName>
            </value>
            <value>
                <fullName>Committee</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Consortium/Group</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Consulting Services Beneficiary</fullName>
            </value>
            <value>
                <fullName>Custodian/Trustee</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Division</fullName>
            </value>
            <value>
                <fullName>Duplicate Accounts</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Financing Company</fullName>
            </value>
            <value>
                <fullName>Former Employee</fullName>
            </value>
            <value>
                <fullName>Former Employer</fullName>
            </value>
            <value>
                <fullName>Founder</fullName>
            </value>
            <value>
                <fullName>Group Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Estimate__c/Shipping_Estimate__c.object-meta.xml
<CustomObject>
    <label>Shipping Estimate</label>
    <nameField>
        <displayFormat>ShipEst-{0}</displayFormat>
        <label>Shipping Estimate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Estimate__c/fields/Default_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Default_Estimate__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Flag to determine if this estimate was autogenerated by the system.</description>
    <label>Default Estimate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Estimate__c/fields/Shipping_Summary__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Summary__c</fullName>
    <label>Shipping Summary</label>
    <referenceTo>Shipping_Estimate_Summary__c</referenceTo>
    <relationshipLabel>Shipping Estimates</relationshipLabel>
    <relationshipName>Shipping_Estimates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Estimate_Summary__c/Shipping_Estimate_Summary__c.object-meta.xml
<CustomObject>
    <description>Rollup summary object for estimated and actual shipping items.</description>
    <label>Shipping Estimate Summary</label>
    <nameField>
        <displayFormat>ShipEstSum-{0}</displayFormat>
        <label>Shipping Estimate Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Estimates Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Estimate_Summary__c/fields/Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Group</label>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipName>Shipping_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteLineGroupHandlerTest.cls
/**
 * Created by CrutchfieldJody on 11/23/2016.
 */
@isTest
public with sharing class QuoteLineGroupHandlerTest {

    public static VistaAssetHelperUtil util = new VistaAssetHelperUtil();

    @isTest
    public static void testRollupQLGQuantities_AfterInsert(){

        insert new ByPassTrigger__c(SetupOwnerId=UserInfo.getOrganizationId(), isDisabled__c=true, Name='Testing Bypass');

        Account account = util.createAccount('ABC Test Account');
        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Hardware', '', 'Fixed Price', 'Once'));
        productList.addAll(util.initProductSet(1, 'Software', 'Service Plans', 'Fixed Price', 'Monthly'));
        productList.addAll(util.initProductSet(1, 'Software', 'Applications', 'Fixed Price', 'Monthly'));
        productList.addAll(util.initProductSet(1, 'Software', 'Other', 'Fixed Price', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);
        Opportunity opportunity = util.createNewOpportunity('Test Opportunity 1', account, 'Products, Services and Maintenance', 'New');
        SBQQ__Quote__c sbQuote = util.createSBQuote(opportunity, account, Date.today(), true);
        List<SBQQ__Quoteline__c> sbQuoteLines = util.createSBQuoteLines(sbQuote, pricebookEntries, false, 2);
        SBQQ__QuoteLineGroup__c qlGroup = new SBQQ__QuoteLineGroup__c();
        qlGroup.Name = 'Group1';
        qlGroup.SBQQ__Quote__c = sbQuote.Id;
        insert qlGroup;

        Test.startTest();

        List<SBQQ__Quoteline__c> qlUpdates = new List<SBQQ__Quoteline__c>();
        for(SBQQ__Quoteline__c ql : sbQuoteLines){
            ql.SBQQ__Group__c = qlGroup.Id;
            qlUpdates.add(ql);
        }
        if(qlUpdates.size() > 0){
            update qlUpdates;
        }

        List<Id> qlgIdList = new List<Id>();
        qlgIdList.add(qlGroup.Id);

        QuoteLineGroupHandler.rollupQLGQuantities(qlgIdList);

        Test.stopTest();
    }

    @isTest
    public static void testRollupQLGQuantities_AfterUpdate(){

        insert new ByPassTrigger__c(SetupOwnerId=UserInfo.getOrganizationId(), isDisabled__c=true, Name='Testing Bypass');

        Account account = util.createAccount('ABC Test Account');
        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Hardware', '', 'Fixed Price', 'Once'));
        productList.addAll(util.initProductSet(1, 'Software', 'Service Plans', 'Fixed Price', 'Monthly'));
        productList.addAll(util.initProductSet(1, 'Software', 'Applications', 'Fixed Price', 'Monthly'));
        productList.addAll(util.initProductSet(1, 'Software', 'Other', 'Fixed Price', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);
        Opportunity opportunity = util.createNewOpportunity('Test Opportunity 1', account, 'Products, Services and Maintenance', 'New');
        SBQQ__Quote__c sbQuote = util.createSBQuote(opportunity, account, Date.today(), true);
        List<SBQQ__Quoteline__c> sbQuoteLines = util.createSBQuoteLines(sbQuote, pricebookEntries, false, 2);
        SBQQ__QuoteLineGroup__c qlGroup = new SBQQ__QuoteLineGroup__c();
        qlGroup.Name = 'Group1';
        qlGroup.SBQQ__Quote__c = sbQuote.Id;
        insert qlGroup;

        List<SBQQ__Quoteline__c> qlUpdates = new List<SBQQ__Quoteline__c>();
        for(SBQQ__Quoteline__c ql : sbQuoteLines){
            ql.SBQQ__Group__c = qlGroup.Id;
            qlUpdates.add(ql);
        }
        if(qlUpdates.size() > 0){
            update qlUpdates;
        }

        QuoteLineGroupRecursiveTriggerHandler.isFirstTime = true; //RESET

        Test.startTest();
        qlGroup.SBQQ__Account__c = account.Id;
        update qlGroup;
        Test.stopTest();
    }

    @isTest
    public static void testRollupQLGQuantities_AfterUpdate_AffiliateAcct(){

        insert new ByPassTrigger__c(SetupOwnerId=UserInfo.getOrganizationId(), isDisabled__c=true, Name='Testing Bypass');

        Account account = util.createAccount('ABC Test Account');
        Account childAcct = util.createAccount('XYZ Child Account');

        Related_Accounts__c relAccount = new Related_Accounts__c  (   Parent_Account__c = account.Id,
                Child_Account__c = childAcct.Id,
                Description__c = childAcct.Name+' was acquired by '+account.Name+ ' on '+ Date.today(),
                Relationship_Type__c = 'Purchaser',
                Child_Relationship_Type__c = 'Acquired'
        );
        insert relAccount;

        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Hardware', '', 'Fixed Price', 'Once'));
        productList.addAll(util.initProductSet(1, 'Software', 'Service Plans', 'Fixed Price', 'Monthly'));
        productList.addAll(util.initProductSet(1, 'Software', 'Applications', 'Fixed Price', 'Monthly'));
        productList.addAll(util.initProductSet(1, 'Software', 'Other', 'Fixed Price', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);
        Opportunity opportunity = util.createNewOpportunity('Test Opportunity 1', account, 'Products, Services and Maintenance', 'New');
        SBQQ__Quote__c sbQuote = util.createSBQuote(opportunity, account, Date.today(), true);
        List<SBQQ__Quoteline__c> sbQuoteLines = util.createSBQuoteLines(sbQuote, pricebookEntries, false, 2);
        SBQQ__QuoteLineGroup__c qlGroup = new SBQQ__QuoteLineGroup__c();
        qlGroup.Name = 'Group1';
        qlGroup.SBQQ__Quote__c = sbQuote.Id;
        qlGroup.SBQQ__Account__c = account.Id;
        insert qlGroup;

        List<SBQQ__Quoteline__c> qlUpdates = new List<SBQQ__Quoteline__c>();
        for(SBQQ__Quoteline__c ql : sbQuoteLines){
            ql.SBQQ__Group__c = qlGroup.Id;
            qlUpdates.add(ql);
        }
        if(qlUpdates.size() > 0){
            update qlUpdates;
        }
        QuoteLineGroupRecursiveTriggerHandler.isFirstTime = true; //RESET

        Test.startTest();
        qlGroup.SBQQ__Description__c = 'TEST AfterUpdate new AffiliateAccount';
        qlGroup.Affiliate_Account2__c = relAccount.Id;
        update qlGroup;
        Test.stopTest();
    }

        /* ARMAN: @isTest
        public static void QuoteLineGroupHandlerBuildDefaultEstimatesTest(){

            insert new ByPassTrigger__c(SetupOwnerId=UserInfo.getOrganizationId(), isDisabled__c=true, Name='Testing Bypass');

            Account account = util.createAccount('ABC Test Account');
            List<Product2> productList = new List<Product2>();
            //subPricingType = 'Fixed Price' or 'Percent Of Total'
            productList.addAll(util.initProductSet(1, 'Hardware', '', 'Fixed Price', 'Monthly'));
            productList.addAll(util.initProductSet(1, 'Software', 'Service Plans', 'Fixed Price', 'Monthly'));
            productList.addAll(util.initProductSet(1, 'Software', 'Applications', 'Fixed Price', 'Monthly'));
            productList.addAll(util.initProductSet(1, 'Software', 'Other', 'Fixed Price', 'Monthly'));
            Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
            pricebookEntries = util.initPricebook(productList);
            Opportunity opportunity = util.createNewOpportunity('Test Opportunity 1', account, 'Products, Services and Maintenance', 'New');
            SBQQ__Quote__c sbQuote = util.createSBQuote(opportunity, account, Date.today(), true);
            List<SBQQ__Quoteline__c> sbQuoteLines = util.createSBQuoteLines(sbQuote, pricebookEntries, false, 2);
            SBQQ__QuoteLineGroup__c qlGroup = new SBQQ__QuoteLineGroup__c();
            qlGroup.Name = 'Group1';
            qlGroup.SBQQ__Quote__c = sbQuote.Id;
            insert qlGroup;

            SBQQ__QuoteLineGroup__c qlGroup2 = new SBQQ__QuoteLineGroup__c();
            qlGroup2.Name = 'Group2';
            qlGroup2.SBQQ__Quote__c = sbQuote.Id;
            insert qlGroup2;

            Shipping_Estimate_Summary__c sum = new Shipping_Estimate_Summary__c();
            sum.Quote_Line_Group__c = qlGroup2.Id;
            insert sum;

            Shipping_Estimate__c shippingEstimate = new Shipping_Estimate__c();
            shippingEstimate.Shipping_Summary__c = sum.Id;
            shippingEstimate.Default_Estimate__c = true;
            insert shippingEstimate;

            Test.startTest();

            List<SBQQ__Quoteline__c> qlUpdates = new List<SBQQ__Quoteline__c>();
            for(SBQQ__Quoteline__c ql : sbQuoteLines){
                ql.SBQQ__Group__c = qlGroup.Id;
                qlUpdates.add(ql);
            }
            if(qlUpdates.size() > 0){
                update qlUpdates;
            }

            List<SBQQ__QuoteLineGroup__c> qlgList = new List<SBQQ__QuoteLineGroup__c>();
            qlgList.add(qlGroup);
            qlgList.add(qlGroup2);

            QuoteLineGroupHandler.buildDefaultEstimates(qlgList);

            Test.stopTest();
        } */
}