force-app/main/default/objects/Provision__c/Provision__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Provision</label>
    <nameField>
        <displayFormat>PFN-{000000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Provisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Provision__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Provisions</relationshipLabel>
    <relationshipName>Provisions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Provision__c/fields/Price_Increase_Cap__c.field-meta.xml
<CustomField>
    <fullName>Price_Increase_Cap__c</fullName>
    <label>Price Increase Cap</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ProvisionAfterTriggerHandler.cls
/***
Case #02275674 -- Created - Sripathi Gullapalli
***/
public with sharing class ProvisionAfterTriggerHandler {
    
 	//Method to update Cap % on Contract, when Provision "Price Increase Cap" field is changed
    public static void updateContract(Map<Id,Provision__c> newMap, Map<Id,Provision__c> oldMap){
		Boolean isInsert = (oldMap == null || oldMap.size() == 0)?true:false;
		Map<Id, Contract> updateContractMap = new Map<Id, Contract>();
		try{
	    	for (Provision__c newProv : newMap.values()){
	    		Provision__c oldProv = isInsert ? null : oldMap.get(newProv.Id);
			 	if(newProv.Contract__c != null && String.isNotBlank(newProv.Price_Increase_Cap__c) && (isInsert || (oldProv != null && newProv.Price_Increase_Cap__c != oldProv.Price_Increase_Cap__c))){
			 		updateContractMap.put(newProv.Contract__c, new Contract(Id=newProv.Contract__c, Cap_Percentage__c = newProv.Price_Increase_Cap__c));
			 	}
		    }
		    
		    if(updateContractMap.size() > 0){
		    	Database.Update(updateContractMap.values());
		    }
		}catch(Exception e){
			System.debug('******************EXCEPTION OCCURED WHILE UPDATING CONTRACT IN PROVISION -- '+e.getMessage());
		}
	}
	
}