force-app/main/default/objects/QES_Unity_Category_Group__c/QES_Unity_Category_Group__c.object-meta.xml
<CustomObject>
    <description>Custom object defined to include category group to be rendered on QES Unity PKB site. Records from this object will be used to feed &lt;categoryList&gt; VF tag.</description>
    <label>QES Unity Category Group</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>QES Unity PKB Category Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QES Unity Category Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Ancestors_Of__c.field-meta.xml
<CustomField>
    <fullName>Ancestors_Of__c</fullName>
    <description>In case root node is not specified an ancestor value could be used. This would include every value up to root.</description>
    <label>Ancestors Of</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Category_Group_Label__c.field-meta.xml
<CustomField>
    <fullName>Category_Group_Label__c</fullName>
    <description>Label to be used on UI if required</description>
    <inlineHelpText>Label to be used on UI if required</inlineHelpText>
    <label>Category Group Label</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Category_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Category_Group_Name__c</fullName>
    <description>Category group name to be included in PKB site. This will be the unique internal name of data category group</description>
    <inlineHelpText>Category group name to be included in PKB site. This will be the unique internal name of data category group</inlineHelpText>
    <label>Category Group Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Active or inactive indicator. Only active records are used for rendering</description>
    <inlineHelpText>Active or inactive indicator. Only active records are used for rendering</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Level_or_Depth__c.field-meta.xml
<CustomField>
    <fullName>Level_or_Depth__c</fullName>
    <defaultValue>-1</defaultValue>
    <description>The level up to which category values are to be rendered. A value of -1 means everything.</description>
    <label>Level or Depth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Ordinal__c</fullName>
    <description>order of rendering if there are more than one</description>
    <inlineHelpText>order of rendering if there are more than one</inlineHelpText>
    <label>Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/QES_Unity_Site_Setup__c.field-meta.xml
<CustomField>
    <fullName>QES_Unity_Site_Setup__c</fullName>
    <label>QES Unity Site Setup</label>
    <referenceTo>QES_Unity_Site_Setup_del__c</referenceTo>
    <relationshipLabel>QES Unity Category Group</relationshipLabel>
    <relationshipName>QES_Unity_Category_Group</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Root_Category__c.field-meta.xml
<CustomField>
    <fullName>Root_Category__c</fullName>
    <description>Root value to be passed to categoryList VF tag.</description>
    <inlineHelpText>Root value to be passed to categoryList VF tag.</inlineHelpText>
    <label>Root Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Show_On_Navbar__c.field-meta.xml
<CustomField>
    <fullName>Show_On_Navbar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this category to be displayed on navbar for quick search</description>
    <inlineHelpText>Indicate if this category to be displayed on navbar for quick search</inlineHelpText>
    <label>Show On Navbar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/QES_Unity_Site_Setup_del__c.object-meta.xml
<CustomObject>
    <description>Object used to configure QES Unity  public knowledge base site setup</description>
    <label>QES Unity Site Setup</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>QES Unity Site Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QES Unity Site Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this configuration is active or inactive</description>
    <inlineHelpText>Indicate if this configuration is active or inactive</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/fields/Page_size__c.field-meta.xml
<CustomField>
    <fullName>Page_size__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Page Size refers to number of articles to be displayed in a knoweldge base search.Currently not being used anywhere but can be used in future for changing the number of article search results dynamically by referring this field in code.</description>
    <inlineHelpText>Page Size refers to number of articles to be displayed in a knoweldge base search.</inlineHelpText>
    <label>Page size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <description>Name of the site to which this configuration applies to. Make sure value in this field exactly matches that of Site name</description>
    <inlineHelpText>Name of the site to which this configuration applies to. Make sure value in this field exactly matches that of Site name</inlineHelpText>
    <label>Site Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/fields/Site_Title__c.field-meta.xml
<CustomField>
    <fullName>Site_Title__c</fullName>
    <description>Title for the site landing page</description>
    <inlineHelpText>Title for the site landing page</inlineHelpText>
    <label>Site Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QESPKBModelerTest.cls
@isTest 
private class QESPKBModelerTest
{
 public static testMethod void QESPKBModelerTest()
 {
    QES_Unity_Site_Setup_del__c testQUSiteSetUp = new QES_Unity_Site_Setup_del__c();
    testQUSiteSetUp.Site_Title__c = 'TestSite'; 
    testQUSiteSetUp.Site_Name__c = 'TestSite';
    testQUSiteSetUp.Page_size__c = 12;
    insert testQUSiteSetUp;
    QESPKBModeler testclass = new QESPKBModeler();
    
  /*  QES_Unity_PKB_Article_Type__c testQUPArticleType = new QES_Unity_PKB_Article_Type__c();
    testQUPArticleType.Ordinal__c = 1;
    testQUPArticleType.Article_Object_Name__c = 'Test';
    testQUPArticleType.Article_Type_Name__c ='Documentation';
    insert testQUPArticleType;
    */
    QES_Unity_Category_Group__c  testQUCategoryGrp = new  QES_Unity_Category_Group__c(); 
         
    testQUCategoryGrp.Root_Category__c = 'All';
    testQUCategoryGrp.Ordinal__c =1;
    testQUCategoryGrp.Level_or_Depth__c =1;
    testQUCategoryGrp.Category_Group_Name__c = 'Application';
    testQUCategoryGrp.Category_Group_Label__c ='Application';
    testQUCategoryGrp.Ancestors_Of__c ='All';
    testQUCategoryGrp.Show_On_Navbar__c = true;
    testQUCategoryGrp.QES_Unity_Site_Setup__c = testQUSiteSetUp.Id;
    insert testQUCategoryGrp;
     
   /*  QESUnityTopArticle testQESUPTopArticle = new QESUnityTopArticle();
    //testQESUPTopArticle.Ordinal__c = 110;
    //testQESUPTopArticle.Article_Type__c = 'Documentation';
    testQESUPTopArticle.Inactive__c = false;
    testQESUPTopArticle.Article_Name__c = 'test';
    testQESUPTopArticle.Article_Id__c = 'kA050000000GmtG';
    testQESUPTopArticle.Article_Summary__c = 'test';
    insert testQESUPTopArticle ; */
      
    QESPKBModeler testObj = new QESPKBModeler ();
    testObj.currentKeyword = 'Search Answer Center';
    testObj.doQESSearch();
    testObj.redirectToSearchUnity();    
    //testObj.addToCurrentCategoryFilter('Application');
    testObj.clearAllFilters();
    testObj.getFiltersFound();
    testObj.getQESSearchUrl();
    testObj.getQESListViewUrl(); 
                                       
    QESPKBModeler testObj1 = new QESPKBModeler ();
    testObj1.currentKeyword = 'Search Answer Center';
    testObj1.doQESSearch();
    testObj1.currentKeyword = null;
    testObj1.currentCategory = null;
    testObj1.getFiltersFound();
    
    ApexPages.StandardController sc;
    testObj1 = new QESPKBModeler();    
    testObj1.getQESCurrentCategory();  
    testObj1.getCategoryFilters(); 
    String noFilterLabel = testObj1.noFilterLabel;
    String noFilterValue = testObj1.noFilterValue;
    String articleBaseUrl = testObj1.articleBaseUrl;
    String siteUrl = testObj1.siteUrl;
    Integer QESCurrentPageNumber = testObj1.QESCurrentPageNumber;
    testObj1.searchPerformed = true;
    QESCurrentPageNumber = testObj1.QESCurrentPageNumber;
    testObj1.currentCategory = 'TestFilterValue';
    String getCategoryFilters = testObj1.getCategoryFilters();
    testObj1.setCategoryFilters('TestFilter');
    
  /*  QES_Unity_Portal_Notification__c testUnityPortal = new QES_Unity_Portal_Notification__c();
    testUnityPortal.Name = 'newTest';
    testUnityPortal.Notification_1__c = 'NewTestNotification1';
    testUnityPortal.Notification_2__c = 'NewTestNotification2';
    testUnityPortal.Notification_4__c = 'NewTestNotification4';
    insert testUnityPortal;
    testObj1 = new QESPKBModeler();
    testUnityPortal.Notification_3__c = 'test notification';
    testUnityPortal.Notification_5__c = 'test notification ';
    update testUnityPortal;
    testObj1 = new QESPKBModeler();
    testUnityPortal.Notification_3__c = ' ';
    testUnityPortal.Notification_5__c = ' ';
    update testUnityPortal;
    testObj1 = new QESPKBModeler(); */
    
    
    PageReference pageRef = Page.Support;
    Test.setCurrentPage(pageRef);
    QESPKBModeler testObj2 = new QESPKBModeler();
    String sortByClause = testObj2.sortByClause;
    testObj2.currentKeyword = 'TestingForNotNull';
    sortByClause = testObj2.sortByClause;
    testObj2.currentCategory = 'TestingForNotNull';
    Set<String> selectedCategoryNames = testObj2.selectedCategoryNames;
    //List<QESUnityTopArticle> listPKBTopArticles = QESPKBModeler.listPKBTopArticles;
    
    testObj2.searchCriteria = 'Test Search: Criteria:None';
    pageRef = testObj2.doQESSearch();
    testObj2.showTopArtciles = true;
    testObj2.searchCriteria = 'NONE:NONE';
    pageRef = testObj2.doQESSearch();
    testObj2.searchMap.put('NONE','NONE');
    pageRef = testObj2.doQESSearch();
    testObj2.searchkeyword = 'Search Answer Center';
    pageRef = testObj2.redirectToSearchUnity();
    
        
    PageReference pageRef1 = ApexPages.currentPage();
    pageRef1.getParameters().put('k', 'k');
    QESPKBModeler testObj3 = new QESPKBModeler();
    
    
    //nextPage = controller.save().getUrl();
  
    //Verify that the success page displays
    //System.assertEquals('/apex/success', nextPage);
    
 }
}