force-app/main/default/objects/QES_Unity_Category_Group__c/QES_Unity_Category_Group__c.object-meta.xml
<CustomObject>
    <description>Custom object defined to include category group to be rendered on QES Unity PKB site. Records from this object will be used to feed &lt;categoryList&gt; VF tag.</description>
    <label>QES Unity Category Group</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>QES Unity PKB Category Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QES Unity Category Group</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Ancestors_Of__c.field-meta.xml
<CustomField>
    <fullName>Ancestors_Of__c</fullName>
    <description>In case root node is not specified an ancestor value could be used. This would include every value up to root.</description>
    <label>Ancestors Of</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Category_Group_Label__c.field-meta.xml
<CustomField>
    <fullName>Category_Group_Label__c</fullName>
    <description>Label to be used on UI if required</description>
    <inlineHelpText>Label to be used on UI if required</inlineHelpText>
    <label>Category Group Label</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Category_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Category_Group_Name__c</fullName>
    <description>Category group name to be included in PKB site. This will be the unique internal name of data category group</description>
    <inlineHelpText>Category group name to be included in PKB site. This will be the unique internal name of data category group</inlineHelpText>
    <label>Category Group Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Level_or_Depth__c.field-meta.xml
<CustomField>
    <fullName>Level_or_Depth__c</fullName>
    <defaultValue>-1</defaultValue>
    <description>The level up to which category values are to be rendered. A value of -1 means everything.</description>
    <label>Level or Depth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Ordinal__c</fullName>
    <description>order of rendering if there are more than one</description>
    <inlineHelpText>order of rendering if there are more than one</inlineHelpText>
    <label>Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/QES_Unity_Site_Setup__c.field-meta.xml
<CustomField>
    <fullName>QES_Unity_Site_Setup__c</fullName>
    <label>QES Unity Site Setup</label>
    <referenceTo>QES_Unity_Site_Setup_del__c</referenceTo>
    <relationshipLabel>QES Unity Category Group</relationshipLabel>
    <relationshipName>QES_Unity_Category_Group</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Root_Category__c.field-meta.xml
<CustomField>
    <fullName>Root_Category__c</fullName>
    <description>Root value to be passed to categoryList VF tag.</description>
    <inlineHelpText>Root value to be passed to categoryList VF tag.</inlineHelpText>
    <label>Root Category</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Category_Group__c/fields/Show_On_Navbar__c.field-meta.xml
<CustomField>
    <fullName>Show_On_Navbar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicate if this category to be displayed on navbar for quick search</description>
    <inlineHelpText>Indicate if this category to be displayed on navbar for quick search</inlineHelpText>
    <label>Show On Navbar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/QES_Unity_Site_Setup_del__c.object-meta.xml
<CustomObject>
    <description>Object used to configure QES Unity  public knowledge base site setup</description>
    <label>QES Unity Site Setup</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>QES Unity Site Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QES Unity Site Setup</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/fields/Page_size__c.field-meta.xml
<CustomField>
    <fullName>Page_size__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Page Size refers to number of articles to be displayed in a knoweldge base search.Currently not being used anywhere but can be used in future for changing the number of article search results dynamically by referring this field in code.</description>
    <inlineHelpText>Page Size refers to number of articles to be displayed in a knoweldge base search.</inlineHelpText>
    <label>Page size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <description>Name of the site to which this configuration applies to. Make sure value in this field exactly matches that of Site name</description>
    <inlineHelpText>Name of the site to which this configuration applies to. Make sure value in this field exactly matches that of Site name</inlineHelpText>
    <label>Site Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QES_Unity_Site_Setup_del__c/fields/Site_Title__c.field-meta.xml
<CustomField>
    <fullName>Site_Title__c</fullName>
    <description>Title for the site landing page</description>
    <inlineHelpText>Title for the site landing page</inlineHelpText>
    <label>Site Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestSrSearchArticalModeller.cls
@isTest(SeeAllData = true)
private class TestSrSearchArticalModeller{
    private static testMethod void testArticlemodeller()
    {
        QES_Unity_Site_Setup_del__c testQUSiteSetUp = new QES_Unity_Site_Setup_del__c();
        testQUSiteSetUp.Site_Title__c = 'TestSite'; 
        testQUSiteSetUp.Site_Name__c = 'TestSite';
        testQUSiteSetUp.Page_size__c = 12;
        insert testQUSiteSetUp;
        QES_Unity_Category_Group__c  testQUCategoryGrp = new  QES_Unity_Category_Group__c(); 
        testQUCategoryGrp.Root_Category__c = 'All';
        testQUCategoryGrp.Ordinal__c =1;
        testQUCategoryGrp.Level_or_Depth__c =1;
        testQUCategoryGrp.Category_Group_Name__c = 'Application';
        testQUCategoryGrp.Category_Group_Label__c ='Application';
        testQUCategoryGrp.Ancestors_Of__c ='All';
        testQUCategoryGrp.Show_On_Navbar__c = true;
        testQUCategoryGrp.QES_Unity_Site_Setup__c = testQUSiteSetUp.Id;
        insert testQUCategoryGrp;
        
        SrSearchArticalModeller testObj = new SrSearchArticalModeller ();
        testObj.currentKeyword = 'Search Answer Center';
        testObj.doQESSearch();
        testObj.clearAllFilters();
        testObj.getFiltersFound();
       
       
       
       SrSearchArticalModeller testObj1 = new SrSearchArticalModeller();
        testObj1.currentKeyword = 'Type Questions or Keywords';
        testObj1.doQESSearch();
        testObj1.currentKeyword = null;
        testObj1.currentCategory = null;
        testObj1.getFiltersFound();
       
       
       SrSearchArticalModeller testObj2 = new SrSearchArticalModeller();
       
       testObj2.currentKeyword = 'TestingForNotNull';
      
       testObj2.currentCategory = 'TestingForNotNull';
       testObj2.setCategoryFilters('Application');
       testObj2.getCategoryFilters();
       Set<String> selectedCategoryNames = testObj2.selectedCategoryNames;
       testObj2.searchCriteria = 'Test Search: Criteria:None';
       testObj2.doQESSearch();
       testObj2.searchCriteria = 'NONE:NONE';
       testObj2.doQESSearch();
       testObj2.searchMap.put('NONE','NONE');
       testObj2.searchMap.put('application','all');
       testObj2.incrementPageNumber();
       testObj2.decrementPageNumber(); 
       
       PageReference pageRef1 = ApexPages.currentPage();
       pageRef1.getParameters().put('k', 'k');
       SrSearchArticalModeller testObj3 = new SrSearchArticalModeller(); 
        
        
    } 
}