force-app/main/default/objects/Competitive_Summary__c/Competitive_Summary__c.object-meta.xml
<CustomObject>
    <description>The Competitive Summary object is a custom object created to summarize the Competitive Intelligence records according to a Account - Competitor - Opportunity/Call Report combination.</description>
    <label>Competitive Summary</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Competitive Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitive_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the account appropriate for Competitive information</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Competitive_Intelligence__c.field-meta.xml
<CustomField>
    <fullName>Competitive_Intelligence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Competitive Intelligence record created with exact Account/Competitor Combination</description>
    <inlineHelpText>Select the appropriate Competitive Intelligence record created with Account/Competitor Combination</inlineHelpText>
    <label>Competitive Intelligence</label>
    <referenceTo>Competitive_Threat__c</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Competitor appropriate to this Competitor Summary</inlineHelpText>
    <label>Competitor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <formula>Competitive_Intelligence__r.Competitor_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Competitor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Competitor_Type__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Type__c</fullName>
    <description>Competitor type particular to the record</description>
    <inlineHelpText>Type of Competitor is entered with respect to particular Opportunity/Call Report</inlineHelpText>
    <label>Competitor Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Name</description>
    <inlineHelpText>Select the appropriate opportunity corresponding to the record</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/Competitive_Threat__c.object-meta.xml
<CustomObject>
    <label>Competitive Intelligence</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Competitive Intelligence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Intelligence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitive_Threat__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Select the account this competitive information is for.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitive Intelligence (Account)</relationshipLabel>
    <relationshipName>Competitive_Threat</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you don&apos;t find the competitor you are looking for, send an email to competitor.list@omnitracs.com to have it added.</inlineHelpText>
    <label>Competitor Name</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitive Intelligence</relationshipLabel>
    <relationshipName>Competitive_Threats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/fields/Competitor_Status__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Status__c</fullName>
    <label>Competitor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Existing Account – Competitor Soliciting</fullName>
                <label>Existing Account - Competitor Soliciting</label>
            </value>
            <value>
                <fullName>Existing Account - Talking to Competitor</fullName>
            </value>
            <value>
                <fullName>Existing Account - Meeting with Competitor</fullName>
            </value>
            <value>
                <fullName>Existing Account - Evaluating Competitor</fullName>
            </value>
            <value>
                <fullName>Existing Account - Reviewing Contracts</fullName>
            </value>
            <value>
                <fullName>Existing Account - Lost Business to Competitor</fullName>
            </value>
            <value>
                <fullName>Existing Account - Competitor Eliminated from Consideration</fullName>
            </value>
            <value>
                <fullName>Prospect - Talking to Prospect</fullName>
            </value>
            <value>
                <fullName>Prospect - Meeting with Prospect</fullName>
            </value>
            <value>
                <fullName>Prospect - Evaluating with Omnitracs</fullName>
            </value>
            <value>
                <fullName>Prospect - Contract Review</fullName>
            </value>
            <value>
                <fullName>Prospect - Lost Opportunity - Stayed with Competitor</fullName>
            </value>
            <value>
                <fullName>Prospect - Won Opportunity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Callback</fullName>
                <isActive>false</isActive>
                <label>Callback</label>
            </value>
            <value>
                <fullName>Contract out for signature</fullName>
                <isActive>false</isActive>
                <label>Contract out for signature</label>
            </value>
            <value>
                <fullName>Email update</fullName>
                <isActive>false</isActive>
                <label>Email update</label>
            </value>
            <value>
                <fullName>Evaluation</fullName>
                <isActive>false</isActive>
                <label>Evaluation</label>
            </value>
            <value>
                <fullName>Happy with Competition</fullName>
                <isActive>false</isActive>
                <label>Happy with Competition</label>
            </value>
            <value>
                <fullName>Long term contract with competitor</fullName>
                <isActive>false</isActive>
                <label>Long term contract with competitor</label>
            </value>
            <value>
                <fullName>Looking at Functionality</fullName>
                <isActive>false</isActive>
                <label>Looking at Functionality</label>
            </value>
            <value>
                <fullName>On--site Meeting</fullName>
                <isActive>false</isActive>
                <label>On--site Meeting</label>
            </value>
            <value>
                <fullName>Price negotiations</fullName>
                <isActive>false</isActive>
                <label>Price negotiations</label>
            </value>
            <value>
                <fullName>Solution offered</fullName>
                <isActive>false</isActive>
                <label>Solution offered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/fields/Has_Product_Solution_Today__c.field-meta.xml
<CustomField>
    <fullName>Has_Product_Solution_Today__c</fullName>
    <inlineHelpText>Does the account have a competitor product/solution today?</inlineHelpText>
    <label>Has Competitor Product/Solution Today?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don&apos;t Know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Opportunity Name</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Competitive Intelligence</relationshipLabel>
    <relationshipName>Competitive_Intelligence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>This is where all competitive information is stored, including
		links to Knock-Out List Reports</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor__c/fields/Competitive_takeaway__c.field-meta.xml
<CustomField>
    <fullName>Competitive_takeaway__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Competitive_takeaway</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Competitors</relationshipLabel>
    <relationshipName>Competitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <inlineHelpText>If you don&apos;t see a competitor listed, please send an email to competitor.list@omnitracs.com for assistance.</inlineHelpText>
    <label>Competitor Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>@Road</fullName>
            </value>
            <value>
                <fullName>123Loadboard</fullName>
            </value>
            <value>
                <fullName>Alda Digital</fullName>
            </value>
            <value>
                <fullName>AlertDriving</fullName>
            </value>
            <value>
                <fullName>AMA</fullName>
            </value>
            <value>
                <fullName>Apacheta</fullName>
            </value>
            <value>
                <fullName>Astrum Satelital (Proeza TI)</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Axon</fullName>
            </value>
            <value>
                <fullName>Axon Development Corporation</fullName>
            </value>
            <value>
                <fullName>Big Roads</fullName>
            </value>
            <value>
                <fullName>Bolt</fullName>
            </value>
            <value>
                <fullName>Cadec</fullName>
            </value>
            <value>
                <fullName>CanHAUL.com</fullName>
            </value>
            <value>
                <fullName>CarrierWeb</fullName>
            </value>
            <value>
                <fullName>Central de Alarmas</fullName>
            </value>
            <value>
                <fullName>CEPA</fullName>
            </value>
            <value>
                <fullName>Control Track</fullName>
            </value>
            <value>
                <fullName>Cooltrax</fullName>
            </value>
            <value>
                <fullName>Copiloto Satelital</fullName>
            </value>
            <value>
                <fullName>Descartes Systems Group, Inc.</fullName>
            </value>
            <value>
                <fullName>Discrete Wireless</fullName>
            </value>
            <value>
                <fullName>Dispatch Track</fullName>
            </value>
            <value>
                <fullName>DriveCam</fullName>
            </value>
            <value>
                <fullName>DriverCare/GE</fullName>
            </value>
            <value>
                <fullName>Driving Dynamics/PHH</fullName>
            </value>
            <value>
                <fullName>DSi Mobile</fullName>
            </value>
            <value>
                <fullName>Elitesat Networks</fullName>
            </value>
            <value>
                <fullName>Encontrack</fullName>
            </value>
            <value>
                <fullName>Express Technologies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/fields/Competitor_Status__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Status__c</fullName>
    <label>Competitor Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CompetitorSelectListController.cls
/*******************************************************************************
 * File:  CompetitorSelectListController.cls
 * Date:  July 1st, 2018
 * Author:  Dennis Le & Sai Krishna Kakani
 * Description: Multi select list option for Competitors name in Opportunities 
 * *******************************************************************************/
public class CompetitorSelectListController {
   
    
    public Opportunity theOpportunity{get;set;}
    public String disableValue { get; set; }
    public Boolean disabledType { get; set; }
    public Boolean displayInputputText {get;set;}
    public Boolean saveAfterdisplay {get;set;}
    public String input {get; set{input = value; Find();}}
    public String CompetitorType {get;set;}
    map<String, Competitor__c> LeftOptionMap = new map<String, Competitor__c>();
    map<String, Competitor__c> RightOptionMap = new map<String, Competitor__c>();
    public Static map<Id, String> staticCompetitorsMap {get;set;}
    public list<String> LeftSelectedList {get;set;}
    public list<String> RightSelectedList {get;set;}
    public list<Competitive_Threat__c> competitivelistofopty {get;set;}
        
    public CompetitorSelectListController(ApexPages.StandardController stdController) {
        System.debug('StandardController constructor');
        theOpportunity = queryOpportunity(stdController.getId());
        LeftSelectedList = new list<String>();
        RightSelectedList = new list<String>();
        CompetitorType = theOpportunity.Type_of_Competitor__c;
        getCurrentCompetitors();
       
         if(CompetitorType == 'Competitive Takeaway'){
            displayInputputText = true;
            saveAfterdisplay = true;
            disabledType = true;
            disableValue = 'enabled';
        }
        
        else if(CompetitorType == 'Competitive Threat'){
            displayInputputText = true;
            saveAfterdisplay = true;
            disabledType = true;
            disableValue = 'enabled';
        }
        
        else {
            displayInputputText = false;
            saveAfterdisplay = false;
            disabledType = false;
            disableValue = 'disabled';
            
        }
       
        queryIntelligenceData ();
    }

    public void queryIntelligenceData () {
         competitivelistofopty = [select id, Competitor_Name__r.Name, Name, Competitor_Status__c, Has_Product_Solution_Today__c, CreatedDate from Competitive_Threat__c where Opportunity__c =:theOpportunity.id];
       
    }

    public CompetitorSelectListController () {
        System.debug('CompetitorSelectListController constructor');
    }
    
    public PageReference save() {
     
        staticCompetitorsMap = new map<Id, String>();
        
        List<Competitor__c> l_selectOptions = new List<Competitor__c>();
    //    List<SObject> scope = [Select Id, Name, Competitive_takeaway__c From Competitor__c where Competitive_takeaway__c = :theOpportunity.Id];
        List<SObject> scope = [Select Id, Name From Competitor__c];
                
        if(scope.size() > 0 || scope != null) {  
            try {           
                for (SObject obj : scope) {
                    Competitor__c rec = (Competitor__c) obj;
                    Competitor__c comp = new Competitor__c(Id = rec.Id);
                    l_selectOptions.add(comp);  
                }
                update l_selectOptions;
                
            }catch(DmlException e) {
                System.debug('An unexpected error has occurred updated l_selectOptions: ' + e.getMessage());
            } 
        }
        
        // delete and refresh
        List<Competitive_Threat__c>  competitorThreatlist = new list<Competitive_Threat__c> ();
        List<Competitive_Summary__c> cmpetitorSummaryList =  new list<Competitive_Summary__c> ();
        List<Competitive_Threat__c> competitiorThreatToDelete = new List<Competitive_Threat__c> ();
        List<Competitive_Summary__c> competitiorSummaryToDelete = new List<Competitive_Summary__c> ();
        
        set<id> competitorIDSet = new set<id> ();
        set<id> competitorIDToIgnore = new set<id> ();
        set<id> competitorSumaryIDset = new set<id> ();
        set<id> competitorSummaryIDSetToIgnore = new set<id> ();
        
        Map<id,Competitive_Threat__c> competitorThreatMap = new Map<id,Competitive_Threat__c> ();

        
        competitorThreatlist  = [select id,Account__c,Competitor_Name__c from Competitive_Threat__c where Account__c = :theOpportunity.AccountId];
        cmpetitorSummaryList = [SELECT Id,Competitive_Intelligence__r.Competitor_Name__c,Competitive_Intelligence__c,Opportunity__c FROM Competitive_Summary__c where  Opportunity__c=:theopportunity.id];
        
        for(Competitive_Threat__c ct : competitorThreatlist) {
            competitorIDSet.add(ct.Competitor_Name__c);
            competitorThreatMap.put(ct.Competitor_Name__c,ct);
        }
        
        for (Competitive_Summary__c cmps : cmpetitorSummaryList) {
           competitorSumaryIDset.add(cmps.Competitive_Intelligence__r.Competitor_Name__c);
        }
        
        List<Competitor__c> selected_list = new List<Competitor__c>();    
        List<Competitive_Threat__c> c_Intelligence = new List<Competitive_Threat__c>();   
        for (Competitor__c value : RightOptionMap.values()) {
            staticCompetitorsMap.put(value.Id, value.Name);
           // Competitor__c ct = new Competitor__c (Id = value.Id, Competitive_takeaway__c = theOpportunity.Id);
          //selected_list.add(ct);
           
            if(!competitorIDSet.contains(value.Id)){

                Competitive_Threat__c cthd = new Competitive_Threat__c(Account__c = theOpportunity.AccountId, Competitor_Name__c = value.Id, Opportunity__c = theopportunity.id);
                c_Intelligence.add(cthd);
            } else {
                competitorIDToIgnore.add(value.id);
            }
        }
        for(Competitive_Threat__c ct : competitorThreatlist) {
            if(!competitorIDToIgnore.contains(ct.Competitor_Name__c)) {
                competitiorThreatToDelete.add(ct);
            }
        }
        try {
            for(Competitive_Threat__c ct : competitiorThreatToDelete) {
              competitorThreatMap.remove(ct.Competitor_Name__c);
            }
            //delete competitiorThreatToDelete;
            
        } catch (DmlException e) {
            System.debug('An unexpected error has occurred updated l_selectOptions: ' + e.getMessage());
        }
        
        try {
            if (selected_list.size() > 0 ) {
                update selected_list;
            }   
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }   
        
        try {
            if (c_Intelligence.size() > 0 ) {
                insert c_Intelligence;
                for(Competitive_Threat__c ct : c_Intelligence) {
                    competitorThreatMap.put(ct.Competitor_Name__c,ct);
                }
            }   
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }   
        
        List<Competitive_Summary__c> compSumaryListToInsert = new List<Competitive_Summary__c> ();
        for (Competitor__c value : RightOptionMap.values()) {
            
            if(!competitorSumaryIDset.contains(value.Id)){

                Competitive_Summary__c cts = new Competitive_Summary__c(Competitive_Intelligence__c = competitorThreatMap.get(value.id).id,Account__c = theOpportunity.AccountId, Opportunity__c= theopportunity.Id, Competitor_Type__c = theOpportunity.Type_of_Competitor__c,Competitor__c=value.id);
                compSumaryListToInsert.add(cts);
            } else {
                competitorSummaryIDSetToIgnore.add(value.id);
            }
        }
        for (Competitive_Summary__c cmps : cmpetitorSummaryList) {
            if(!competitorSummaryIDSetToIgnore.contains(cmps.Competitive_Intelligence__r.Competitor_Name__c)) {
                competitiorSummaryToDelete.add(cmps);
            }
        }
        try {
            if(competitiorSummaryToDelete.size() > 0)
            delete competitiorSummaryToDelete;
            
        } catch (DmlException e) {
            System.debug('An unexpected error has occurred updated l_selectOptions: ' + e.getMessage());
        }  
        
        try {
            if (compSumaryListToInsert.size() > 0 ) {
                insert compSumaryListToInsert;
              
            }   
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
        }   
        

        theOpportunity.Type_of_Competitor__c = competitortype;
        update theOpportunity;
        LeftOptionMap.clear();
        input = '';
        queryIntelligenceData ();
        PageReference reference = new PageReference('/apex/CompetitorSelectListController?id=' + theOpportunity.Id);
        reference.setRedirect(false);
  
        return reference;
    }
    
    public void removeMembers() {
        if (!RightSelectedList.isEmpty()) {
            for (String s : RightSelectedList) {
                if (RightOptionMap.containsKey(s)) {
                    LeftOptionMap.put(s, RightOptionMap.get(s));        
                }
                RightOptionMap.remove(s);
            }
        }
    }
    
    public void addMembers() {     
        for(String s : LeftSelectedList) {
            if (LeftOptionMap.containsKey(s)) {
                RightOptionMap.put(s, LeftOptionMap.get(s));        
            }
            LeftOptionMap.remove(s);
        } 
    }
    
    public list<SelectOption> getSelectedOptionValues() {
        list<SelectOption> TempOptionList = new list<SelectOption>();
        list<Competitor__c> TempValueList;
 
        TempValueList = RightOptionMap.values();
        TempValueList.sort();  // sort by name
        for (Competitor__c T : TempValueList) { 
            TempOptionList.add(new SelectOption(T.Id, T.Name));
        }   
        
        return TempOptionList;
    }

    public void Find() {
        
        String SearchText = null; 
        List<Competitor__c> compList = new List<Competitor__c>();   
        
        if (input.length() > 1) { 
            SearchText = '%'+input+'%';
            compList = [SELECT Id, Name FROM Competitor__c where Name like :SearchText limit 100];
            if (compList.size() > 0 || compList != null)
                LeftOptionMap.clear();        
        }
        
        if (compList != null && compList.size() > 0) {
            for (Competitor__c Co : compList) {
                if (!RightOptionMap.containsKey(Co.Id)) {
                LeftOptionMap.put(Co.Id, Co);
                }
            }
            saveAfterdisplay = true;
            disabledType = true;
        }  
    }  
    
    public list<SelectOption> getUnSelectedValues() {
        
        list<SelectOption> TempOptionList = new list<SelectOption>();
        list<Competitor__c> TempValueList; 
  
        TempValueList = LeftOptionMap.values();
        TempValueList.sort(); 
        for (Competitor__c O : TempValueList) { 
            TempOptionList.add(new SelectOption(O.Id, O.Name));
        }
        return TempOptionList;
    }  
       
         
    public PageReference getCurrentCompetitors() {  
        List<Competitor__c> theOppCompetitors;
        List<Competitive_Summary__c> currentCompetitiveSummaryList = new List<Competitive_Summary__c> ();
        currentCompetitiveSummaryList = [select id,Competitive_Intelligence__r.Competitor_Name__c from Competitive_Summary__c
                                         where Opportunity__c =:theOpportunity.Id];
        set<id> competitorIDSet = new set<id> ();
        for(Competitive_Summary__c cs : currentCompetitiveSummaryList) {
            competitorIDSet.add(cs.Competitive_Intelligence__r.Competitor_Name__c);
        }
        
        theOppCompetitors = [Select Id, Name From Competitor__c where id IN : competitorIDSet];
        
        LeftOptionMap.clear();
        if ( theOppCompetitors.size() > 0) {
            for (Competitor__c cObject : theOppCompetitors) {
                RightOptionMap.put(cObject.Id, cObject);
            }
        }
        
        PageReference oppPage = new PageReference('/apex/CompetitorSelectListController?id=' + theOpportunity.Id);
        oppPage.setRedirect(true);
          
        return oppPage;
    }  
 
    private static Opportunity queryOpportunity(id OppId)
    {
        return [select id, name, AccountId,Type_of_Competitor__c from Opportunity where id =: OppId];
    }
    
    public PageReference Cancel()
    {   
        disabledType = false;
        PageReference m_stc = new PageReference('/apex/CompetitorSelectListController?id=' + ApexPages.currentPage().getParameters().get('Id'));
        m_stc.setRedirect(true);
        
        return m_stc;
    }   
    
    public PageReference competitorLink() {
        
        PageReference competitor_pageRef;
        
        if (!disabledType) {
            for (String s : RightSelectedList) {
                if (RightOptionMap.containsKey(s)) {
                    competitor_pageRef = new PageReference('/' + RightOptionMap.get(s).Id);
                }
            }           
            return competitor_pageRef;
            
        } else {
            PageReference reference = new PageReference('/apex/CompetitorSelectListController?id=' + theOpportunity.Id);
            reference.setRedirect(false);
            return reference;
        }               
        
    }
     
}