force-app/main/default/objects/Competitive_Summary__c/Competitive_Summary__c.object-meta.xml
<CustomObject>
    <description>The Competitive Summary object is a custom object created to summarize the Competitive Intelligence records according to a Account - Competitor - Opportunity/Call Report combination.</description>
    <label>Competitive Summary</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Competitive Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitive_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the account appropriate for Competitive information</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Competitive_Intelligence__c.field-meta.xml
<CustomField>
    <fullName>Competitive_Intelligence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Competitive Intelligence record created with exact Account/Competitor Combination</description>
    <inlineHelpText>Select the appropriate Competitive Intelligence record created with Account/Competitor Combination</inlineHelpText>
    <label>Competitive Intelligence</label>
    <referenceTo>Competitive_Threat__c</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Competitor__c.field-meta.xml
<CustomField>
    <fullName>Competitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the Competitor appropriate to this Competitor Summary</inlineHelpText>
    <label>Competitor</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <formula>Competitive_Intelligence__r.Competitor_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Competitor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Competitive_Summary__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Name</description>
    <inlineHelpText>Select the appropriate opportunity corresponding to the record</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Competitive Summary</relationshipLabel>
    <relationshipName>Competitive_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/Competitive_Threat__c.object-meta.xml
<CustomObject>
    <label>Competitive Intelligence</label>
    <nameField>
        <displayFormat>CT-{0000}</displayFormat>
        <label>Competitive Intelligence ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitive Intelligence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitive_Threat__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Select the account this competitive information is for.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Competitive Intelligence (Account)</relationshipLabel>
    <relationshipName>Competitive_Threat</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>If you don&apos;t find the competitor you are looking for, send an email to competitor.list@omnitracs.com to have it added.</inlineHelpText>
    <label>Competitor Name</label>
    <referenceTo>Competitor__c</referenceTo>
    <relationshipLabel>Competitive Intelligence</relationshipLabel>
    <relationshipName>Competitive_Threats</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitive_Threat__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Opportunity Name</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Competitive Intelligence</relationshipLabel>
    <relationshipName>Competitive_Intelligence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Competitor__c/Competitor__c.object-meta.xml
<CustomObject>
    <description>This is where all competitive information is stored, including
		links to Knock-Out List Reports</description>
    <label>Competitor</label>
    <nameField>
        <label>Competitor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Competitor__c/fields/Competitor_Name__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name__c</fullName>
    <inlineHelpText>If you don&apos;t see a competitor listed, please send an email to competitor.list@omnitracs.com for assistance.</inlineHelpText>
    <label>Competitor Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>@Road</fullName>
            </value>
            <value>
                <fullName>123Loadboard</fullName>
            </value>
            <value>
                <fullName>Alda Digital</fullName>
            </value>
            <value>
                <fullName>AlertDriving</fullName>
            </value>
            <value>
                <fullName>AMA</fullName>
            </value>
            <value>
                <fullName>Apacheta</fullName>
            </value>
            <value>
                <fullName>Astrum Satelital (Proeza TI)</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Axon</fullName>
            </value>
            <value>
                <fullName>Axon Development Corporation</fullName>
            </value>
            <value>
                <fullName>Big Roads</fullName>
            </value>
            <value>
                <fullName>Bolt</fullName>
            </value>
            <value>
                <fullName>Cadec</fullName>
            </value>
            <value>
                <fullName>CanHAUL.com</fullName>
            </value>
            <value>
                <fullName>CarrierWeb</fullName>
            </value>
            <value>
                <fullName>Central de Alarmas</fullName>
            </value>
            <value>
                <fullName>CEPA</fullName>
            </value>
            <value>
                <fullName>Control Track</fullName>
            </value>
            <value>
                <fullName>Cooltrax</fullName>
            </value>
            <value>
                <fullName>Copiloto Satelital</fullName>
            </value>
            <value>
                <fullName>Descartes Systems Group, Inc.</fullName>
            </value>
            <value>
                <fullName>Discrete Wireless</fullName>
            </value>
            <value>
                <fullName>Dispatch Track</fullName>
            </value>
            <value>
                <fullName>DriveCam</fullName>
            </value>
            <value>
                <fullName>DriverCare/GE</fullName>
            </value>
            <value>
                <fullName>Driving Dynamics/PHH</fullName>
            </value>
            <value>
                <fullName>DSi Mobile</fullName>
            </value>
            <value>
                <fullName>Elitesat Networks</fullName>
            </value>
            <value>
                <fullName>Encontrack</fullName>
            </value>
            <value>
                <fullName>Express Technologies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Competitor__c/recordTypes/Competitor.recordType-meta.xml
<RecordType>
    <fullName>Competitor</fullName>
    <active>true</active>
    <description>New competitor custom object to track all consolidated company comptetitors</description>
    <label>Competitor</label>
</RecordType>

force-app/main/default/classes/CompetitorSelectListControllerTest.cls
/*******************************************************************************
 * File:  		CompetitorSelectListControllerTest.cls
 * Date:  		September 20th, 2018
 * Author:  	Sai Krishna Kakani
 * Description: test class for apex class CompetitorSelectListController
 * *******************************************************************************/
@istest(SeeAllData=True) 
public class CompetitorSelectListControllerTest {
	public static testMethod void TestOppCompetitor() {
		Account a = TestUtils.getAccount('ut1 Acc');
        insert a;

        Contract ctrct = TestUtils.getContract(a);
        insert ctrct;
        
        Competitor__c cmp = new Competitor__c ();
        cmp.Name = 'Test Competitor';
        insert cmp;
        
       
       
        Opportunity oppth = new Opportunity(Name = 'CompTestSept20-1',
        Contract__c = ctrct.id,
        Type = 'New Customer',
        CloseDate = system.today(),
        Order_Type__c = 'New',
        StageName = 'Sales Acceptance',
        Type_of_Competitor__c='Competitive Threat');
        insert oppth;
        
        
        Opportunity opptn = new Opportunity(Name = 'CompTestSept2-2',
        Contract__c = ctrct.id,
        Type = 'New Customer',
        CloseDate = system.today(),
        Order_Type__c = 'New',
        StageName = 'Sales Acceptance',
        Type_of_Competitor__c='No Competitor');
        insert opptn;
        
        Opportunity oppty = new Opportunity(Name = 'CompTestSept20',
        Contract__c = ctrct.id,
        Type = 'New Customer',
        CloseDate = system.today(),
        Order_Type__c = 'New',
        StageName = 'Sales Acceptance',
        Type_of_Competitor__c='Competitive Takeaway');
        insert oppty;
        
        Competitive_Threat__c cIS = new Competitive_Threat__c ();
        cIS.Competitor_Name__c = cmp.id;
        cIS.Account__c = a.id;
        insert cIS;
        
         Competitive_Summary__c csm = new Competitive_Summary__c ();
        csm.Opportunity__c = oppty.id;
        csm.Competitive_Intelligence__c = cIS.Id;
        insert csm;
        
        Test.startTest();
        ApexPages.StandardController SC = new ApexPages.StandardController(oppty);
        ApexPages.StandardController SCh = new ApexPages.StandardController(oppth);
        ApexPages.StandardController SCn = new ApexPages.StandardController(opptn);
        CompetitorSelectListController controller = new CompetitorSelectListController(SC);
        CompetitorSelectListController controllerh = new CompetitorSelectListController(SCh);
        CompetitorSelectListController controllern = new CompetitorSelectListController(SCn);
        CompetitorSelectListController controllerT = new CompetitorSelectListController ();
        PageReference pageRef = Page.CompetitorSelectListController;
        pageRef.getParameters().put('id', String.valueOf(oppty.Id));
        system.Test.setCurrentPage(pageRef);
        controller.save(); 
        list<string> stringlist  =  new list<string> ();
        stringlist.add('test');
        controller.rightselectedlist = stringlist;
		controller.removeMembers();
		controller.addMembers();
		controller.getSelectedOptionValues();
        controller.input = 'Test';
		controller.find();
		controller.getUnSelectedValues();
		controller.getCurrentCompetitors();
		//controller.queryOpportunity();
		controller.cancel();
		controller.competitorLink();
        controller.disabledType = true;
        controller.competitorLink();
        
        controller.competitorLink();
        test.stoptest();
    }
}