force-app/main/default/objects/SystemIds__c/SystemIds__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>System IDs</label>
</CustomObject>

force-app/main/default/objects/SystemIds__c/fields/RecordTypeId_Case_Engineering__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId_Case_Engineering__c</fullName>
    <label>RecordTypeId_Case_Engineering</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/JIRAConnectorWebserviceCallout_Test.cls
@isTest(seeAllData=true)
public class JIRAConnectorWebserviceCallout_Test{
    public static testMethod void testJIRACallout(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSuccess());
        Id escalateRecordType = SystemIds__c.getInstance().RecordTypeId_Case_Engineering__c;
        Case testCase = new Case(subject = 'testCase', JIRA_Issue__c = '1');
        insert testCase;
        testCase.recordTypeId = escalateRecordType;
        testCase.JIRA_Issue__c = '2';
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorSuccess());
        JIRAConnectorWebserviceCallout.createIssue(testCase.Id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorFail());
        JIRAConnectorWebserviceCallout.createIssue(testCase.Id);
    }
}