force-app/main/default/objects/NMC_Account__c/NMC_Account__c.object-meta.xml
<CustomObject>
    <label>NMC Account</label>
    <nameField>
        <label>NMC Account Name / Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NMC Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NMC_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NMC Accounts</relationshipLabel>
    <relationshipName>NMC_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <description>NMC Account #</description>
    <label>NMC Account #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account_Name__c</fullName>
    <label>NMC Account Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/Serialized_Units__c.object-meta.xml
<CustomObject>
    <label>Serialized Unit</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Units__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account related to this Serialized Unit</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Units</relationshipLabel>
    <relationshipName>R00N50000001eVUXEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>R00N50000001d4DsEAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestNMCAll.cls
/**
 * This class contains unit tests for validating the behavior of all NMC Apex classes
 * and triggers.
 
 */
@isTest(SeeAllData=True)
private class TestNMCAll{

    static testMethod void TestAllNMCTriggers() {
        test.startTest();
        Account testAccount1 = GenericTestClass.insertAccount();
        NMC_Account__C testNMCAcct = GenericTestClass.insertNMCAccount(testAccount1.Id);
        testNMCAcct.Account__c = null;
        update testNMCAcct;
        
        Account testAccount2 = GenericTestClass.insertAccount();
        testNMCAcct.Account__c = testAccount2.Id;
        
        Case testCase = GenericTestClass.insertCase(testAccount2.Id, null);
        testCase.NMC_Account_Number__c = testNMCAcct.NMC_Account__c;
        
        testNMCAcct.Name = 'Test123';
        update testNMCAcct;
        
        testNMCAcct.Name = '';
        testNMCAcct.NMC_Account_Name__c  = '';
        
        try{
        update testNMCAcct;
        }
        
        catch(Exception e){
        System.assert( e.getMessage().contains('Update failed. First exception on row 0 with id '+testNMCAcct.Id+'; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, NMC Account Name / Number cannot be modified. Please press Cancel to cancel your changes.'),e.getMessage() );
        }
        
        Serialized_Units__c serUnit = GenericTestClass.insertSerUnit(testAccount1.Id);
        Serialized_Units__c unit1= [select Id,Account__c,NMC_Account__c from Serialized_Units__c where id =: serUnit.Id limit 1];
        unit1.NMC_Account__c = testNMCAcct.ID;
        update unit1;
        
        Account account = [select Id from Account where Id<>:unit1.Account__c limit 1];
    
        NMC_Account__c nmcAccount = [select Id,Account__c,name,NMC_Account__c from NMC_Account__c where id= :testNMCAcct.Id Limit 1];//a08500000016dOz
        nmcAccount.Account__c=account.Id;
        update nmcAccount;
        
        test.stopTest();
    }
}