force-app/main/default/objects/NMC_Account__c/NMC_Account__c.object-meta.xml
<CustomObject>
    <label>NMC Account</label>
    <nameField>
        <label>NMC Account Name / Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NMC Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NMC_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NMC Accounts</relationshipLabel>
    <relationshipName>NMC_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <description>NMC Account #</description>
    <label>NMC Account #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account_Name__c</fullName>
    <label>NMC Account Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/Serialized_Units__c.object-meta.xml
<CustomObject>
    <label>Serialized Unit</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Units__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account related to this Serialized Unit</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Units</relationshipLabel>
    <relationshipName>R00N50000001eVUXEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>R00N50000001d4DsEAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestSerializedUnitAll.cls
/**
 *
 * @author Avinash Kaltari, SF Developer, TCS

 * @date Sep 19, 2011
 
 * @description :   This is a Test class that contains the test method for the Serialized_Unit__c Trigger (after insert, after update, after delete).

 */

@isTest(SeeAllData=true)
private class TestSerializedUnitAll 
{
    static testMethod void validateTestSerializedUnitTrigger() 
    {
    
    
        User olduser=[select Id,ContactId from  User where IsPortalEnabled=true and IsActive = true limit 1];
        Contact userContact=[select AccountId from Contact where Id= :olduser.ContactId];
        Account contactAccount=[select RecordTypeId from Account where Id= :userContact.AccountID];
        RecordType rp=[select ID from RecordType where Name='Partner Account (Reseller)'];
        contactAccount.RecordTypeId=rp.Id;
        update contactAccount;
        update userContact;
        update olduser;
        Serialized_Units__c testSerializedUnit=new Serialized_Units__c();
        testSerializedUnit.OwnerId=olduser.Id;
        List<Serialized_Units__c> lstSerializedUnits = new List<Serialized_Units__c>();
        lstSerializedUnits.add(testSerializedUnit);
        insert lstSerializedUnits;
        
        Profile p = [select id from profile where name='Standard User'];
        User newuser = new User(alias = 'standt', email='standarduser@omnitracs.com',
                          emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                          localesidkey='en_US', profileid = p.Id,
                          timezonesidkey='America/Los_Angeles', username='standarduser123@omnitracs.com');
        insert newuser;
        testSerializedUnit.OwnerId=newuser.Id;
        
        NMC_Account__c nmc = new NMC_Account__c();
        
        nmc = [select name from NMC_Account__c limit 1];
        
        //nmc.Account__c = contactAccount.id;
        //nmc.NMC_Account_Name__c = 'ABCDE'; //contactAccount.name;
        //insert nmc;
        
        if(nmc.id != null || nmc.id != '')
            testSerializedUnit.NMC_Account__c = nmc.id;
        
        PartnerScorecardHelper.blnUpdateDateUnitMoved = true;
        update lstSerializedUnits;
        
        delete lstSerializedUnits;
    }
}