force-app/main/default/objects/NMC_Account__c/NMC_Account__c.object-meta.xml
<CustomObject>
    <label>NMC Account</label>
    <nameField>
        <label>NMC Account Name / Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NMC Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NMC_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NMC Accounts</relationshipLabel>
    <relationshipName>NMC_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Auto_Number__c</fullName>
    <description>Auto Number is created for Outage Contact Wizard as a solution for Apex Governor Limit.</description>
    <displayFormat>{000000}</displayFormat>
    <label>Auto Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/NMC_Account__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <description>NMC Account #</description>
    <label>NMC Account #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/Serialized_Units__c.object-meta.xml
<CustomObject>
    <label>Serialized Unit</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Units__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account related to this Serialized Unit</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Units</relationshipLabel>
    <relationshipName>R00N50000001eVUXEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/Auto_Number__c.field-meta.xml
<CustomField>
    <fullName>Auto_Number__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Auto Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/FirstRecord__c.field-meta.xml
<CustomField>
    <fullName>FirstRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hidden field used for Serialized Unit Updates when NMC Account is modified</description>
    <label>FirstRecord</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/NMC_Account__c.field-meta.xml
<CustomField>
    <fullName>NMC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NMC Account</label>
    <referenceTo>NMC_Account__c</referenceTo>
    <relationshipName>R00N50000001d4DsEAI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/UpdateFromNMC__c.field-meta.xml
<CustomField>
    <fullName>UpdateFromNMC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hidden field used when NMC Account is changed</description>
    <label>UpdateFromNMC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateAccountInSU.cls
global class UpdateAccountInSU {
/************************************************************
Modifications done:
1. Removed the recursive call for finding all the Serialized Units
as the governor limits are increased. 
2. Removed @future call as it was throwing Exception because of 
Serialized Unit's @future method.
**************************************************************/

 @future

public static void updateAccountInSU(Map<Id, id> mapNmcAccountsToAccountIds)
{

    List<Serialized_Units__c> updatedAccount = new List<Serialized_Units__c>();
    updatedAccount = [SELECT id, Account__c,NMC_Account__c,Auto_Number__c,FirstRecord__c,UpdateFromNMC__c FROM Serialized_Units__c WHERE  NMC_Account__c in :mapNmcAccountsToAccountIds.keySet() limit 10000];
    if(!(updatedAccount.isEmpty()))
    {
        for(integer i=0;i<updatedAccount.size();i++)
        {
              if(i==0)
                  updatedAccount[i].FirstRecord__c = true;
              ID parentAccount = mapNmcAccountsToAccountIds.get(updatedAccount[i].NMC_Account__c);
              updatedAccount[i].Account__c = parentAccount;
              updatedAccount[i].UpdateFromNMC__c = true;
              //updatedAccount.add(Units);
        }//End of for condition
    }

    if(!updatedAccount.isEmpty())
    {
            QESConstants.CALLED_FROM_NMC= true;
            QESConstants.SERIALIZEDUNIT_SIZE = updatedAccount.size();
system.debug('QESConstants.SERIALIZEDUNIT_SIZE:'+QESConstants.SERIALIZEDUNIT_SIZE+'updatedAccount.size():'+updatedAccount.size());
            update updatedAccount;
            
    }
     
    
}

  }