force-app/main/default/objects/X3rd_Party_Contract_Service__c/X3rd_Party_Contract_Service__c.object-meta.xml
<CustomObject>
    <label>3rd Party Contracted Product / Service</label>
    <nameField>
        <displayFormat>3rd-{0000}</displayFormat>
        <label>3rd Party ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>3rd Party Contracted Products / Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/X3rd_Party_Contract_Service__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>3rd Party Contracted Products / Services (Account)</relationshipLabel>
    <relationshipName>X3rd_Party_Contract_Service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/X3rd_Party_Contract_Service__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>3rd Party Contracted Products / Services</relationshipLabel>
    <relationshipName>X3rd_Party_Contracted_Products_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Createx3rdPartyServiceExtension.cls
public class Createx3rdPartyServiceExtension
{
 private X3rd_Party_Contract_Service__c x3rdPartyService;

 public Createx3rdPartyServiceExtension(ApexPages.standardController scontroller)
 {
  x3rdPartyService = (X3rd_Party_Contract_Service__c )(scontroller.getRecord()); 
 }
 
 public pageReference save3rdPartyService()
 {
  try{
      insert x3rdPartyService;  
  }
  catch(exception e)
  {       
       x3rdPartyService.addError(e.getMessage());
       return null;
  }
  System.debug('********* x3rdPartyService.Lead__c' + x3rdPartyService.Lead__c);
   System.debug('********* x3rdPartyService.Account__c ' + x3rdPartyService.Account__c );
  PageReference pg ;
  if(x3rdPartyService.Lead__c != null && (x3rdPartyService.Lead__c+ '') != '')
  pg = new PageReference ('/'+x3rdPartyService.Lead__c);
  else if (x3rdPartyService.Account__c != null && (x3rdPartyService.Account__c  + '') != '')
  pg = new PageReference ('/'+x3rdPartyService.Account__c );
  
  System.debug('********* pg  ' + pg  );
  
  return pg;
  
 }
 
 
 
}