force-app/main/default/objects/Contract_Request__c/Contract_Request__c.object-meta.xml
<CustomObject>
    <label>Contract Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contract Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Requests</relationshipLabel>
    <relationshipName>R00N50000001eJHTEA2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact was not found in the account associated with the Contract request.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contract Requests</relationshipLabel>
    <relationshipName>R00N50000001eJHbEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Contracts_Administrator_to_Send__c.field-meta.xml
<CustomField>
    <fullName>Contracts_Administrator_to_Send__c</fullName>
    <label>Contracts Administrator to Send</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/No_Approvals_Required__c.field-meta.xml
<CustomField>
    <fullName>No_Approvals_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked proceed to next section.</inlineHelpText>
    <label>No Approvals Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>R00N50000001eJHgEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Product_Reduced_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Reduced_Price__c</fullName>
    <inlineHelpText>This must be specified if the Product List Price checkbox is not checked.</inlineHelpText>
    <label>Product Reduced Price</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract Request Pending</fullName>
                <default>true</default>
                <label>Contract Request Pending</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Contract sent to Customer</fullName>
                <label>Sent for Signature</label>
            </value>
            <value>
                <fullName>Contract received - OT signature pending</fullName>
                <label>Sent for Counter Signature</label>
            </value>
            <value>
                <fullName>Hold: Credit Approval</fullName>
            </value>
            <value>
                <fullName>Hold: Finance Approval</fullName>
            </value>
            <value>
                <fullName>Hold: Needs Approval</fullName>
            </value>
            <value>
                <fullName>Hold: See Notes</fullName>
            </value>
            <value>
                <fullName>Signed by Omnitracs</fullName>
                <label>Signed</label>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Pending NMC Setup</fullName>
            </value>
            <value>
                <fullName>Set-up Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Requested_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Completion_Date__c</fullName>
    <inlineHelpText>Minimum three days preferred and is subject to terms and approvals being in place.</inlineHelpText>
    <label>Requested Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/System_Is_Future__c.field-meta.xml
<CustomField>
    <fullName>System_Is_Future__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by @future methods to negate recursive calls... Set programmatically.</description>
    <label>System Is Future</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/System_Status__c.field-meta.xml
<CustomField>
    <fullName>System_Status__c</fullName>
    <description>Used to hold the Contract Request &quot;Request Status&quot; field to be used for approval process</description>
    <label>System Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that appears in output</description>
    <inlineHelpText>Contact that appears in output</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quote_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestApprovalProcessUtils.cls
/*******************************************************************************
Date    : 27 July 2010
Author  : David Ragsdale
Overview: Test Class for ApprovalProcess Utils...  
   Utils are fired from UpdateFieldsForApprovalWorkflow trigger

Modified By: Shruti Karn for adding 'GenericTestClass' methods.

Modified By  : Rittu Roy
Modified Date: 10/18/15
Purpose      : Added testmethod for submitProcessApprovalRequest method
*******************************************************************************/
@isTest(SeeAllData=True)
private class TestApprovalProcessUtils {

    static testmethod void TestApprovalProcessUtils() {

      Test.StartTest();        
      Account AcctId = GenericTestClass.insertAccount();
      Contact contID = GenericTestClass.insertContact(AcctId.Id);
      Account sampleCustomerAcct = [SELECT Id, Name FROM Account where id = : AcctId.Id limit 1];
      Contact sampleContact = [SELECT Id, Name FROM Contact where id = :contID.Id limit 1];  
      Contract_Request__c CR = new Contract_Request__c(
                                  Account__c = sampleCustomerAcct.Id,
                                  Description__c = 'Test', 
                                  Contact__c = sampleContact.Id,
                                  Contracts_Administrator_to_Send__c = 'No',
                                  No_Approvals_Required__c = true,
                                  Product_Reduced_Price__c = '5.00',
                                  Requested_Completion_Date__c = (System.Today()+30),
                                  Request_Status__c = 'Submitted', 
                                  System_Status__c = 'Submitted', 
                                  System_Is_Future__c = false
                                 );
      insert CR; 
   
      CR.Request_Status__c = 'Pending Approval';
      update CR;   
      Test.StopTest();
      
      List<Contract_Request__c> insertedCR = [SELECT Request_Status__c, System_Status__c, System_Is_Future__c 
        FROM Contract_Request__c WHERE Id = :CR.Id];
     
      for (Contract_Request__c ContReq : insertedCR)
      {
        System.assertEquals('Pending Approval', ContReq.System_Status__c);
        System.assertEquals(false, ContReq.System_Is_Future__c);
      }
      
    }
    
    static testmethod void testSubmitProcessApprovalRequest() {
        Opportunity testOppty = new Opportunity(Name='Test',StageName='Sales Complete',CloseDate=System.Today());
        insert testOppty;

        VCG_CPQ_Quote__C testQuote = new VCG_CPQ_Quote__C(Is_Primary__c = true,Opportunity__c = testOppty.Id);
        insert testQuote;
        
        ApprovalProcessUtils.submitProcessApprovalRequest(testQuote.Id);
    }
}