force-app/main/default/objects/Contract_Request__c/Contract_Request__c.object-meta.xml
<CustomObject>
    <label>Contract Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contract Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Requests</relationshipLabel>
    <relationshipName>R00N50000001eJHTEA2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact was not found in the account associated with the Contract request.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contract Requests</relationshipLabel>
    <relationshipName>R00N50000001eJHbEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Contracts_Administrator_to_Send__c.field-meta.xml
<CustomField>
    <fullName>Contracts_Administrator_to_Send__c</fullName>
    <label>Contracts Administrator to Send</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/No_Approvals_Required__c.field-meta.xml
<CustomField>
    <fullName>No_Approvals_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked proceed to next section.</inlineHelpText>
    <label>No Approvals Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Product_Reduced_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Reduced_Price__c</fullName>
    <inlineHelpText>This must be specified if the Product List Price checkbox is not checked.</inlineHelpText>
    <label>Product Reduced Price</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Requested_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Completion_Date__c</fullName>
    <inlineHelpText>Minimum three days preferred and is subject to terms and approvals being in place.</inlineHelpText>
    <label>Requested Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Use this Request Type only if no other Request Type fits your needs.</description>
    <label>Other</label>
</RecordType>

force-app/main/default/classes/TestPopulateAssignedTo.cls
@isTest(SeeAllData = true)
public class TestPopulateAssignedTo {
    static testmethod void testPopulateAssignedTo() {
        
        Account newAccount = new Account();         
            newAccount.Name = 'SFDC';         
            newAccount.Type = 'Other';         
            newAccount.BillingStreet = 'Test Address';         
            newAccount.BillingCity = 'Test City';         
            newAccount.BillingCountry = 'Test Country';
        	newAccount.BillingState = 'Test State';
        	newAccount.BillingPostalCode = 'Test ZipCode';
        	newAccount.Segment__c = 'TL';
        	newAccount.Fleet_Size__c = 25;
            newAccount.QWBS_Cust_ID__c = '4567';        
        
        insert newAccount;
        
        Contact newContact=new Contact();
        newContact.FirstName='SFDC';
        newContact.LastName='Salesforce';
        newContact.Email = 'c_skarn@qualcomm.com'; 
        newContact.AccountId = newAccount.Id;
        
        insert newContact;
      
        Contract_Request__c CR = new Contract_Request__c(
                                  Account__c = newAccount.Id,
                                  Description__c = 'Test', 
                                  Contact__c = newContact.Id,
                                  Contracts_Administrator_to_Send__c = 'No',
                                  No_Approvals_Required__c = true,
                                  Product_Reduced_Price__c = '5.00',
                                  Requested_Completion_Date__c = (System.Today()+30)
                                 );
        insert CR;      
    }
}