force-app/main/default/objects/Contract_Request__c/Contract_Request__c.object-meta.xml
<CustomObject>
    <label>Contract Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contract Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Requests</relationshipLabel>
    <relationshipName>R00N50000001eJHTEA2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact was not found in the account associated with the Contract request.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contract Requests</relationshipLabel>
    <relationshipName>R00N50000001eJHbEAM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Contracts_Administrator_to_Send__c.field-meta.xml
<CustomField>
    <fullName>Contracts_Administrator_to_Send__c</fullName>
    <label>Contracts Administrator to Send</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/No_Approvals_Required__c.field-meta.xml
<CustomField>
    <fullName>No_Approvals_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked proceed to next section.</inlineHelpText>
    <label>No Approvals Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Product_Reduced_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Reduced_Price__c</fullName>
    <inlineHelpText>This must be specified if the Product List Price checkbox is not checked.</inlineHelpText>
    <label>Product Reduced Price</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Contract Request Pending</fullName>
                <default>true</default>
                <label>Contract Request Pending</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
                <label>In Review</label>
            </value>
            <value>
                <fullName>Contract sent to Customer</fullName>
                <label>Sent for Signature</label>
            </value>
            <value>
                <fullName>Contract received - OT signature pending</fullName>
                <label>Sent for Counter Signature</label>
            </value>
            <value>
                <fullName>Hold: Credit Approval</fullName>
            </value>
            <value>
                <fullName>Hold: Finance Approval</fullName>
            </value>
            <value>
                <fullName>Hold: Needs Approval</fullName>
            </value>
            <value>
                <fullName>Hold: See Notes</fullName>
            </value>
            <value>
                <fullName>Signed by Omnitracs</fullName>
                <label>Signed</label>
            </value>
            <value>
                <fullName>Distributed</fullName>
            </value>
            <value>
                <fullName>Pending NMC Setup</fullName>
            </value>
            <value>
                <fullName>Set-up Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Requested_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Completion_Date__c</fullName>
    <inlineHelpText>Minimum three days preferred and is subject to terms and approvals being in place.</inlineHelpText>
    <label>Requested Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/System_Is_Future__c.field-meta.xml
<CustomField>
    <fullName>System_Is_Future__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by @future methods to negate recursive calls... Set programmatically.</description>
    <label>System Is Future</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting for State Name as key and State code as value.</description>
    <label>State</label>
</CustomObject>

force-app/main/default/objects/TIS_Detail__c/TIS_Detail__c.object-meta.xml
<CustomObject>
    <label>TIS Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TIS Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TIS_Detail__c/fields/Contract_Request__c.field-meta.xml
<CustomField>
    <fullName>Contract_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Request</label>
    <referenceTo>Contract_Request__c</referenceTo>
    <relationshipLabel>TIS Detail</relationshipLabel>
    <relationshipName>TIS_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TIS_Detail__c/fields/Date_Time_Out__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Out__c</fullName>
    <label>Date/Time Out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TIS_Detail__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <formula>IF(State__c = &quot;Closed&quot;, 0, if( ISNULL(Date_Time_Out__c),((FLOOR( NOW() - Date_Time_In__c )) ) , ((FLOOR(Date_Time_Out__c - Date_Time_In__c )) ) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TIS_Detail__c/fields/Hrs__c.field-meta.xml
<CustomField>
    <fullName>Hrs__c</fullName>
    <formula>IF(State__c = &quot;Closed&quot;, 
0, 
if( ISNULL(Date_Time_Out__c), 
FLOOR( 
24 * ( 
(NOW() - Date_Time_In__c ) 
- 
FLOOR(NOW() - Date_Time_In__c ) )), 
FLOOR( 24 * ( 
(Date_Time_Out__c - Date_Time_In__c ) 
- 
FLOOR(Date_Time_Out__c - Date_Time_In__c ) 
) 
) 
) 
)</formula>
    <label>Hrs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TIS_Detail__c/fields/Mins__c.field-meta.xml
<CustomField>
    <fullName>Mins__c</fullName>
    <formula>IF(State__c = &quot;Closed&quot;, 0,IF( ISNULL(Date_Time_Out__c ),(ROUND(60 * (ROUND( 24 * ( (NOW() - Date_Time_In__c ) - FLOOR(NOW() - Date_Time_In__c ) ),8) - FLOOR(ROUND( 24 * ( (NOW() - Date_Time_In__c ) - FLOOR(NOW() - Date_Time_In__c ) ),8)) ),0) ), (ROUND(60 * (ROUND( 24 * ( (Date_Time_Out__c - Date_Time_In__c ) - FLOOR(Date_Time_Out__c - Date_Time_In__c ) ),8) - FLOOR(ROUND( 24 * ( (Date_Time_Out__c - Date_Time_In__c ) - FLOOR(Date_Time_Out__c - Date_Time_In__c ) ),8)) ),0) )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TIS_Summary__c/TIS_Summary__c.object-meta.xml
<CustomObject>
    <label>TIS Summary</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TIS Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TIS_Summary__c/fields/Contract_Request__c.field-meta.xml
<CustomField>
    <fullName>Contract_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Request</label>
    <referenceTo>Contract_Request__c</referenceTo>
    <relationshipLabel>TIS Summary</relationshipLabel>
    <relationshipName>TIS_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TIS_Summary__c/fields/Hrs__c.field-meta.xml
<CustomField>
    <fullName>Hrs__c</fullName>
    <label>Hrs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TIS_Summary__c/fields/Mins__c.field-meta.xml
<CustomField>
    <fullName>Mins__c</fullName>
    <label>Mins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestContractAll.cls
/**
 * This class contains unit tests for validating the behavior of all Contract Apex classes
 * and triggers.
 *
 
 */
@isTest(SeeAllData=True)
private class TestContractAll
{
    
    /***************Common Data Initialization**************/
    
    static Account Acct = GenericTestClass.insertAccount();
    static Contact Cont = GenericTestClass.insertContact(Acct.Id);
    static Account sampleAccount = [SELECT Id, Name FROM Account where id = : Acct.ID limit 1];
    static Contact sampleContact = [SELECT Id, Name FROM Contact where id = : Cont.Id limit 1];
   
    /*******************************************************/
    
    
    /******************TestContractRequestTIS******************************/
    public static testmethod void TestContractRequestTISControllerExtension()
    {
        Contract_Request__c CRNew = new Contract_Request__c();
        CRNew.Account__c = sampleAccount.id;
        CRNew.Description__c = 'Test Contract';
        CRNew.Contact__c = sampleContact.Id;
        CRNew.Contracts_Administrator_to_Send__c = 'No';
        CRNew.No_Approvals_Required__c = true;
        CRNew.Product_Reduced_Price__c = '5.00';
        CRNew.Requested_Completion_Date__c = (System.Today()+30);
        CRNew.Request_Status__c = 'Submitted';
        
        insert CRNew;
        
    // Add parameters to the page URL
        System.currentPageReference().getParameters().put('id', CRNew.Id);
    
    //Create a new instance fo the controller class
        ApexPages.StandardController standardcontroller = new ApexPages.StandardController(CRNew);
        ContractRequestTISControllerExtension Controller = new ContractRequestTISControllerExtension(standardcontroller);
    
        Controller.setState('Request Status');
    
        String RequestState = Controller.getState();
            
        System.assertEquals(RequestState ,'Request Status');
        
        list<TIS_Summary__c> TISSum = new list<TIS_Summary__c>();
        TISSum = Controller.getTISSummary();
        
        
        list<TIS_Detail__c> TISDetail = new list<TIS_Detail__c>();
        TISDetail = Controller.getTISDetail();
    
        String result = CreateTIS.CreateTISRecord('Contract_Request__c',CRNew.Id, 'Request Status', 'Assigned', UserInfo.getUserId(),false);
        
        List<SelectOption> options = new List<SelectOption>();
        options = Controller.getItems();
                
        String VFContractRequestPage = controller.ReturntoContractRequest().getUrl();
        String ContractRequestPage = '/' + CRNew.Id + '';
        System.assertEquals(ContractRequestPage, VFContractRequestPage);
        
        //Modified by Shruti Karn for CR# 22542
        Controller.TrueToggleShowDetail();
        Controller.FalseToggleShowDetail();
      }
      /************ End TestContractRequestTIS*************************/

    /*************************TestContractRequestTISDetail ***************************************/
    static testmethod void TestByCreateUpdateOfContractRequest() 
 {
 
    Contract_Request__c ContractRequestObj = new Contract_Request__c(
                                      Account__c = sampleAccount.Id,
                                      Description__c = 'Test', 
                                      Contact__c = sampleContact.Id,                                      
                                      Contracts_Administrator_to_Send__c = 'No',
                                      No_Approvals_Required__c = true,
                                      Product_Reduced_Price__c = '5.00',
                                      Requested_Completion_Date__c = (System.Today()+30),
                                      Request_Status__c = 'Submitted',
                                      //12 August 2010 - Added to prevent @future limits being exceeded
                                      System_Is_Future__c = true
                                     );
    insert ContractRequestObj;  
    System.debug('Contract Request created with SID :' + ContractRequestObj.Id);
    
    ContractRequestObj.Request_Status__c = 'Contract Request Pending';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Assigned';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Contract sent to Customer';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Contract received - QC signature pending';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Finance Hold';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Pending Approval';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Cancelled';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Pending NMC Setup';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Rejected';
    update ContractRequestObj;
    
    ContractRequestObj.Request_Status__c = 'Set-up Complete';
    update ContractRequestObj;
  
    //Modified by Shruti Karn for CR# 22542
      
    TIS_Detail__c newTISDetail = new TIS_Detail__c();
    newTISDetail.Contract_Request__c = ContractRequestObj.Id;
    newTISDetail.State__c = 'Set-up Complete';
    newTISDetail.Name = 'Request Status';
    newTISDetail.Date_Time_In__c = system.now()-1; 
    newTISDetail.Date_Time_Out__c = system.now();
    insert newTISDetail;
    list<TIS_Summary__c> lstTISSum = new list<TIS_Summary__c>();
    TIS_Summary__c newTISSum = new TIS_Summary__c();
    newTISSum.Contract_Request__c = newTISDetail.Contract_Request__c;
    newTISSum.Name = newTISDetail.Name;
    newTISSum.State__c = newTISDetail.State__c;
    newTISSum.Mins__c = 60;
    newTISSum.Hrs__c = 120;
    newTISSum.Days__c = 1;
    insert newTISSum;
    
    TIS_Summary__c newTISSum1 = new TIS_Summary__c();
    newTISSum1.Contract_Request__c = newTISDetail.Contract_Request__c;
    newTISSum1.Name = newTISDetail.Name;
    newTISSum1.State__c = newTISDetail.State__c;
    newTISSum1.Mins__c = 120;
    newTISSum1.Hrs__c = 48;
    newTISSum1.Days__c = 1;
    insert newTISSum1;
    newTISDetail.Date_Time_Out__c = system.now();
    update newTISDetail;
    newTISSum1.Hrs__c = 48;
    update newTISSum;
    update newTISDetail;
    newTISSum.Hrs__c = 16;
    update newTISSum;
    update newTISDetail;
    newTISSum.Hrs__c = 24;
    update newTISSum;
    update newTISDetail;    
 }
    
    
    
    /*************************End TestContractRequestTISDetail ***************************************/
    /************************* TestContractSoftwareOnAccount ***************************************/
      static testmethod void ContractSoftwareOnAccount()
      {
           account acct1 = [Select id ,QWBS_Status__c,QWBS_Market__c,Contract_Expiration__c from Account where Id = : acct.ID limit 1];
           try {update acct1;} catch (system.dmlexception e)
           {
               system.assert(e.getmessage().contains('Contract Expiration must be'),e.getmessage());
           }    
            acct1.QWBS_Status__c = 'MSA Customer';
            acct1.QWBS_Market__c = 'T&L';
            acct1.Contract_Expiration__c = NULL;
            try {update acct1;} catch (system.dmlexception e){
              system.assert(e.getmessage().contains('Contract Expiration must be'),e.getmessage());
            }
        try {update acct1;} catch (system.dmlexception e){
              system.assert(e.getmessage().contains('Contract Expiration must be'),e.getmessage());
            }    
      }
 /*************************End TestContractSoftwareOnAccount ***************************************/



}