force-app/main/default/objects/Contract_Request__c/Contract_Request__c.object-meta.xml
<CustomObject>
    <label>Contract Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Contract Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person on the Contracts team to which this request is assigned.</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N50000001eMi6EAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/FRA_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>FRA_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FRA Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/fields/Sales_Director__c.field-meta.xml
<CustomField>
    <fullName>Sales_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contract_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Request__c/recordTypes/FleetRisk_Advisors_Agreement.recordType-meta.xml
<RecordType>
    <fullName>FleetRisk_Advisors_Agreement</fullName>
    <active>false</active>
    <description>FleetRisk Advisors Agreement Contract Request Form</description>
    <label>FleetRisk Advisors Agreement</label>
</RecordType>

force-app/main/default/classes/ContractRequestUtils.cls
public class ContractRequestUtils{
     
       
    // to update the value of AssignedTo and Sales Director with the Contract Request's Account's
    // Sales Director and Contract Administrator.
    public static void updateContractRequest(map<Id, Contract_Request__c> mapContReq)
    { 
        Id contReqRecType = [Select r.Id, r.DeveloperName From RecordType r where DeveloperName = 'FleetRisk_Advisors_Agreement' and SobjectType= 'Contract_Request__c' limit 1 ].ID;
        Id acctRecType = [Select r.Id, r.DeveloperName From RecordType r where DeveloperName = 'FleetRisk_Advisors_Accounts' and SobjectType= 'Account' limit 1 ].ID;
        
        list<Account> lstAccount = [Select Id, Account_Manager__c, FRA_Account_Manager__c, Sales_Director__c, Contracts_Administrator__c,FRA_Contracts_Administrator__c,RecordTypeId FROM Account WHERE Id in : mapContReq.keySet() limit 10000];
        
        for(integer i=0;i<lstAccount.size();i++)
        {            
             //Populate Sales Director
             mapContReq.get(lstAccount[i].Id).Sales_Director__c = lstAccount[i].Sales_Director__c;
             
             //if account rec type = fleetseek advisors - update the FRA Acount Manager to Account Manager on Account record
             if(lstAccount[i].RecordTypeId == acctRecType)
             {
                mapContReq.get(lstAccount[i].Id).FRA_Account_Manager__c = lstAccount[i].Account_Manager__c;
             //else update Conatract request FRA Account manger = FRA account manager on the account    
             }else{
                mapContReq.get(lstAccount[i].Id).FRA_Account_Manager__c = lstAccount[i].FRA_Account_Manager__c;
             }
             
             //Check account rec type against contact rec type / Not FRA Account rec type / list value for FRA_Contact_Administrator is not null
             if((mapContReq.get(lstAccount[i].Id).RecordTypeId == contReqRecType) && (lstAccount[i].RecordTypeId != acctRecType) && (lstAccount[i].FRA_Contracts_Administrator__c != null))
             {
                //Update Assigned To field
                mapContReq.get(lstAccount[i].Id).Assigned_To__c = lstAccount[i].FRA_Contracts_Administrator__c;
             }
             else
             {
                //if no assigned to value
                if(mapContReq.get(lstAccount[i].Id).Assigned_To__c == NULL)
                { 
                    mapContReq.get(lstAccount[i].Id).Assigned_To__c = lstAccount[i].Contracts_Administrator__c;
                }
                   
             } 
        }
    }
}