force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>Used to support surveys and survey data via ClickTools.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Additional_comments_on_support_exp__c.field-meta.xml
<CustomField>
    <fullName>Additional_comments_on_support_exp__c</fullName>
    <label>Additional comments on support exp</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Contact_survey_lookup__c.field-meta.xml
<CustomField>
    <fullName>Contact_survey_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used as a lookup relationship to Contacts for surveys.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Customer_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Customer_Feedback__c</fullName>
    <label>Customer Feedback</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Dissatisfied</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PostChatController.cls
public class PostChatController {

    public ID contactID {get;set;}
    public ID accountID {get;set;}
    public ID caseID {get;set;}
    public ID agentID {get;set;}
    public String feedback {get;set;}
    public String cAdditionalFeedback {get;set;}
    
    public PostChatController() {
        String attachedRecords = ApexPages.currentPage().getParameters().get('attachedRecords');
        String chatDetails = ApexPages.currentPage().getParameters().get('chatDetails');
        if(String.isnotBlank(attachedRecords)){
            contactID = JSON2Apex.parse(attachedRecords).contactID;
            accountID = JSON2Apex.parse(attachedRecords).accountID;
            caseId = JSON2Apex.parse(attachedRecords).caseID;
        }
        if(String.isnotBlank(chatDetails)){
            agentID = JSON2Apex.parse(chatDetails).AgentID;
        }
    }
    
    public void submitFeedback(){
        Survey__c nSurvey = new Survey__c(Account__c=accountID, Contact_survey_lookup__c = contactID, Case__c = caseID, Agent__c = agentId,
                                          Customer_Feedback__c=feedback,Additional_comments_on_support_exp__c=cAdditionalFeedback);
        insert nSurvey;
        return;
    }
    
}