force-app/main/default/objects/VCG_CPQ_Quote_Product__c/VCG_CPQ_Quote_Product__c.object-meta.xml
<CustomObject>
    <description>An individual line item on a quote</description>
    <label>Quote Product</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Add_on_Source_Quote_Product__c.field-meta.xml
<CustomField>
    <fullName>Add_on_Source_Quote_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Add-on Source Quote Product</label>
    <referenceTo>VCG_CPQ_Quote_Product__c</referenceTo>
    <relationshipLabel>Add On Quote Products</relationshipLabel>
    <relationshipName>Add_On_Quote_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteProductUtil.cls
/*
Author - Abhishek Dey
Date - 5/13/2015
Desciption : After cloning the Add- On quote products, this trigger will update the Add-On Source field to corresponsing Quote.

*/
public with sharing class QuoteProductUtil {

         Public void UpdateSourceAddOn(List<VCG_CPQ_Quote_Product__c> newQP)
          {
                List<VCG_CPQ_Quote_Product__c> triggerNewDummy = [select id,Add_on_Source_Quote_Product__c,Quote__c,Name,Add_on_Source_Quote_Product__r.name from VCG_CPQ_Quote_Product__c where id =: newQP ];
                Map<String,id> mapPartNumberToId; 
                List<id> lstQuoteId = new list<id>();
                Map<id,List<VCG_CPQ_Quote_Product__c>> newMap = new Map<id,List<VCG_CPQ_Quote_Product__c>>();
                
                for(VCG_CPQ_Quote_Product__c newQuoteProduct : triggerNewDummy )
                {
                    lstQuoteId.add(newQuoteProduct.Quote__c);
                }
                
                list <VCG_CPQ_Quote_Product__c> lstQP = [select id,Add_on_Source_Quote_Product__c,Quote__c,Name from VCG_CPQ_Quote_Product__c where Quote__c =:lstQuoteId];
                
                for(VCG_CPQ_Quote_Product__c dataVal : lstQP)
                {
                    list<VCG_CPQ_Quote_Product__c> addQP = new list<VCG_CPQ_Quote_Product__c>();
                    if(newMap.containskey(dataVal.Quote__c))
                    {
                        addQP = newMap.get(dataVal.Quote__c);
                        addQP.add(dataVal);
                        newMap.put(dataVal.Quote__c,addQP);
                    }
                    else
                    newMap.put(dataVal.Quote__c,new list<VCG_CPQ_Quote_Product__c>{dataVal});
                }
                
                
                for(VCG_CPQ_Quote_Product__c newQPData : triggerNewDummy )
                {    
                        mapPartNumberToId = new Map<String,id>();
                        for(VCG_CPQ_Quote_Product__c innerNewQPData :newMap.get(newQPData.Quote__c))
                        {
                            mapPartNumberToId.put(innerNewQPData.Name,innerNewQPData.id);
                        }
                        
                        newQPData.Add_on_Source_Quote_Product__c =  mapPartNumberToId.get(newQPData.Add_on_Source_Quote_Product__r.name);
                        
                }
                
                try{
                update triggerNewDummy;
                }
                catch(Exception e)
                {
                    system.debug('error in QuoteProductUtil class' + e.getMessage());
                }
                
          }
}