force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <description>This object is created for QES Unity Customer Portal. It will have the details of the Applications and will have many to many relationship with Custom Object  Hardware Platform Product.</description>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Display_on_Left_Rail_as_Link__c.field-meta.xml
<CustomField>
    <fullName>Display_on_Left_Rail_as_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be used to determine whether this will be displayed as link on Left Rail of the Customer Portal or will it be the part of Picklist on Rail</description>
    <inlineHelpText>Check if it will be displayed as link on Left Rail of Site</inlineHelpText>
    <label>Display on Left Rail as Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Ordinal__c</fullName>
    <description>This is the rank of the App among the ones being displayed on the Left Rail on the Support Page of the QES Unity Portal</description>
    <inlineHelpText>This is the rank of the Application among the ones being displayed on the Left Rail on the Support Page</inlineHelpText>
    <label>Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Platform__c/Platform__c.object-meta.xml
<CustomObject>
    <description>This object is created for QES Unity Customer Portal. It will maintain the details of the Hardware Platform Products and will have many to many relationship with Custom Object Applications</description>
    <label>Platform</label>
    <nameField>
        <label>Platform Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform__c/fields/Display_on_Left_Nav_Bar__c.field-meta.xml
<CustomField>
    <fullName>Display_on_Left_Nav_Bar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be used to determine whether this will be displayed as link on Left Rail of the Customer Portal or will it be the part of Picklist on Rail</description>
    <inlineHelpText>Check if it will be displayed as link on Left Rail of Site</inlineHelpText>
    <label>Display on Left Rail as Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Platform__c/fields/Ordinal__c.field-meta.xml
<CustomField>
    <fullName>Ordinal__c</fullName>
    <description>This is the rank of the Platform among the ones being displayed on the Left Rail on the Support Page of the QES Unity Portal</description>
    <inlineHelpText>This is the rank of the Platform among the ones being displayed on the Left Rail on the Support Page</inlineHelpText>
    <label>Ordinal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestPicklistURLModeler.cls
@isTest 
private class TestPicklistURLModeler 
{  
    static testMethod void validateTestPicklistURLModeler()
    {
    Platform__c testplatform=new Platform__c(Name='test',Display_on_Left_Nav_Bar__c=true,Ordinal__c=123456789);
    
    Application__C testApp=new Application__C(Name='test',Display_on_Left_Rail_as_Link__c=true,Ordinal__c=1203456789);

    test.startTest();
    
    insert testplatform;

    insert testApp;
    
    PicklistURLModeler testPicklistURLModeler=new PicklistURLModeler();
    testPicklistURLModeler.refreshInitializationData();
    testPicklistURLModeler.redirectNow();
    
    test.stopTest();

    }
}