force-app/main/default/objects/Partner_Support_Information__c/Partner_Support_Information__c.object-meta.xml
<CustomObject>
    <description>Support contact information for Partners.</description>
    <label>Partner Support Information</label>
    <nameField>
        <displayFormat>PSI-{0000}</displayFormat>
        <label>Partner Support Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Support Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Support_Information__c/fields/Hours_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Hours_of_Service__c</fullName>
    <description>Partner Support - Hours of Service</description>
    <label>Hours of Service</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <description>URL for the logo</description>
    <label>Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Logo_Orientation__c.field-meta.xml
<CustomField>
    <fullName>Logo_Orientation__c</fullName>
    <label>Logo Orientation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Landscape</fullName>
            </value>
            <value>
                <fullName>Portrait</fullName>
            </value>
            <value>
                <fullName>Square</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Support Information</relationshipLabel>
    <relationshipName>Partner_Support_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Support_Email__c.field-meta.xml
<CustomField>
    <fullName>Support_Email__c</fullName>
    <description>Partner Support Email</description>
    <label>Support Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Support_Name__c.field-meta.xml
<CustomField>
    <fullName>Support_Name__c</fullName>
    <description>Partner Support Name</description>
    <label>Support Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Support_Phone__c.field-meta.xml
<CustomField>
    <fullName>Support_Phone__c</fullName>
    <description>Partner Support Phone</description>
    <label>Support Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/PartnerSupportInformationUtils.cls
public class PartnerSupportInformationUtils {
    private static String unityCredentials = 'sf-non-prod@service.qes.qualcomm.com:saleSm3ggs';

    @future (callout=true)
    public static void updatePartnerSupportDetails(List<String> lstAccountId) {
        List<User> lstUser = null;
        List<Partner_Support_Information__c> lstPSI = null;
        
        lstPSI = [
                    SELECT
                        id,
                        Partner_Account__c,
                        Support_Name__c,
                        Support_Phone__c,
                        Support_Email__c,
                        Hours_Of_Service__c,
                        Logo__c,
                        Logo_Orientation__c
                    FROM
                        Partner_Support_Information__c
                    WHERE
                        Partner_Account__c in :lstAccountId
                    LIMIT
                        :lstAccountId.size()
                 ];                        
                 
        lstUser = [
                    SELECT
                        id,
                        FederationIdentifier
                    FROM
                        User
                    WHERE
                        id = :UserInfo.getUserId()
                    LIMIT
                        1
                  ];
                                
        QESUnityAdminLinkWebServices.AdminServiceSoapImplPort port = null;    
        QESUnityAdminLinkWebServices.standardResponse response = null;
        Integer retries = 1;

        try {        
            port = new QESUnityAdminLinkWebServices.AdminServiceSoapImplPort();
            String authorization = EncodingUtil.base64Encode(
                                   Blob.valueOf(unityCredentials ));
            port.inputHttpHeaders_x = new Map<String, String>();
            port.inputHttpHeaders_x.put('Authorization', 'Basic ' + authorization);
            
            for(Partner_Support_Information__c psi : lstPSI) {
                List<Account> lstAccounts = null;
                lstAccounts = [
                                SELECT
                                    id,
                                    AGUID__c,
                                    ownerId
                                FROM
                                    Account
                                WHERE
                                    id = :psi.Partner_Account__c
                                LIMIT
                                    1
                              ];
                System.debug('@@@@@@@@@@@@@@@@@@..' + lstAccounts.size());
                QESUnityAdminLinkWebServices.ExtendedCompany company = new QESUnityAdminLinkWebServices.ExtendedCompany();
                if(0 != lstAccounts.size()) {
                    company.CompanyGuid = lstAccounts[0].AGUID__C;
                }
                
                company.CompanyAttributeList = new QESUnityAdminLinkWebServices.CompanyAttributeList_element();
                List<QESUnityAdminLinkWebServices.CompanyAttribute> lstCompanyAttributes = new List<QESUnityAdminLinkWebServices.CompanyAttribute>();
                
                QESUnityAdminLinkWebServices.CompanyAttribute companyAttribute = new QESUnityAdminLinkWebServices.CompanyAttribute();
                companyAttribute.AttrName = 'SUPPORT_NAME';
                companyAttribute.AttrValueString = psi.Support_Name__c;
                lstCompanyAttributes.add(companyAttribute);
                
                companyAttribute = new QESUnityAdminLinkWebServices.CompanyAttribute();
                companyAttribute.AttrName = 'SUPPORT_EMAIL';
                companyAttribute.AttrValueString = psi.Support_Email__c;
                lstCompanyAttributes.add(companyAttribute);

                companyAttribute = new QESUnityAdminLinkWebServices.CompanyAttribute();
                companyAttribute.AttrName = 'SUPPORT_PHONE';
                companyAttribute.AttrValueString = psi.Support_Phone__c;
                lstCompanyAttributes.add(companyAttribute);
                
                companyAttribute = new QESUnityAdminLinkWebServices.CompanyAttribute();
                companyAttribute.AttrName = 'SUPPORT_HOURS';
                companyAttribute.AttrValueString = psi.Hours_of_Service__c;
                lstCompanyAttributes.add(companyAttribute);
                
                companyAttribute = new QESUnityAdminLinkWebServices.CompanyAttribute();
                companyAttribute.AttrName = 'SUPPORT_LOGO_URL';
                companyAttribute.AttrValueString = psi.Logo__c;
                lstCompanyAttributes.add(companyAttribute);                

                companyAttribute = new QESUnityAdminLinkWebServices.CompanyAttribute();
                companyAttribute.AttrName = 'SUPPORT_LOGO_ORIENTATION';
                companyAttribute.AttrValueString = psi.Logo_Orientation__c;
                lstCompanyAttributes.add(companyAttribute);                
                                                                                
                company.CompanyAttributeList.CompanyAttribute = lstCompanyAttributes;
                
                response = port.updateSupportContactDetails(company, lstUser[0].FederationIdentifier);
                System.debug('@@@@@@@@..' + response.status);        
                System.debug('@@@@@@@@..' + response.message);
            }    
        }
        catch(Exception e) {
            System.debug('@@@@@@@@..' + e);        
        } // End - catch        
    }    
}