force-app/main/default/objects/Partner_Support_Information__c/Partner_Support_Information__c.object-meta.xml
<CustomObject>
    <description>Support contact information for Partners.</description>
    <label>Partner Support Information</label>
    <nameField>
        <displayFormat>PSI-{0000}</displayFormat>
        <label>Partner Support Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Support Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Support_Information__c/fields/Hours_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Hours_of_Service__c</fullName>
    <description>Partner Support - Hours of Service</description>
    <label>Hours of Service</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <description>URL for the logo</description>
    <label>Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Logo_Orientation__c.field-meta.xml
<CustomField>
    <fullName>Logo_Orientation__c</fullName>
    <label>Logo Orientation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Landscape</fullName>
            </value>
            <value>
                <fullName>Portrait</fullName>
            </value>
            <value>
                <fullName>Square</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Support Information</relationshipLabel>
    <relationshipName>Partner_Support_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Support_Email__c.field-meta.xml
<CustomField>
    <fullName>Support_Email__c</fullName>
    <description>Partner Support Email</description>
    <label>Support Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Support_Name__c.field-meta.xml
<CustomField>
    <fullName>Support_Name__c</fullName>
    <description>Partner Support Name</description>
    <label>Support Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Support_Phone__c.field-meta.xml
<CustomField>
    <fullName>Support_Phone__c</fullName>
    <description>Partner Support Phone</description>
    <label>Support Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/PartnerSupportInformationAllTest.cls
@isTest(SeeAllData=true)
public class PartnerSupportInformationAllTest {
    public static testMethod void runAllTests() {                
        Partner_Support_Information__c psi = new Partner_Support_Information__c();
        psi.Partner_Account__c = '0015000000LGKdn';
        psi.Support_Email__c = 'xyz@gmail.com';
        psi.Support_Phone__c = '8586039700';
        psi.Support_Name__c = 'Test Partner Display Name';
        psi.Hours_Of_Service__c = '08:00 - 20:00 PST';
        psi.Logo__c = 'xxxxyyyyyzzzz';
        psi.Logo_Orientation__c = 'Portrait';       
        
        test.startTest();
        insert psi;
        
        psi = new Partner_Support_Information__c();
        psi.Partner_Account__c = '0015000000LGKdn';
        psi.Support_Email__c = 'xyz@gmail.com';
        psi.Support_Phone__c = '8586039700';
        psi.Support_Name__c = 'Test Partner Display Name';
        psi.Hours_Of_Service__c = '08:00 - 20:00 PST';
        psi.Logo__c = 'xxxxyyyyyzzzz';
        psi.Logo_Orientation__c = 'Portrait';

        try {
            insert psi;                        
        }
        catch(Exception e) {
        }
        
        test.stopTest();                
    }
}