force-app/main/default/objects/Test_Case__c/Test_Case__c.object-meta.xml
<CustomObject>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Test Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Case__c/fields/Earliest_Version_PL__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Version_PL__c</fullName>
    <label>Earliest Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex-1.0</fullName>
            </value>
            <value>
                <fullName>Apex-1.1</fullName>
            </value>
            <value>
                <fullName>Apex-1.2</fullName>
            </value>
            <value>
                <fullName>Apex-Future</fullName>
            </value>
            <value>
                <fullName>CAIR-5.0</fullName>
            </value>
            <value>
                <fullName>CAIR-5.1</fullName>
            </value>
            <value>
                <fullName>CAIR-5.2</fullName>
            </value>
            <value>
                <fullName>CAIR-6.0</fullName>
            </value>
            <value>
                <fullName>RA</fullName>
            </value>
            <value>
                <fullName>RA-2.0</fullName>
            </value>
            <value>
                <fullName>RA-2.1</fullName>
            </value>
            <value>
                <fullName>RA-2.2</fullName>
            </value>
            <value>
                <fullName>RA-2.3</fullName>
            </value>
            <value>
                <fullName>RA-2.4</fullName>
            </value>
            <value>
                <fullName>RA-2.5</fullName>
            </value>
            <value>
                <fullName>RA-2.6</fullName>
            </value>
            <value>
                <fullName>RA-2.7</fullName>
            </value>
            <value>
                <fullName>RA-2.8</fullName>
            </value>
            <value>
                <fullName>RA-2.9</fullName>
            </value>
            <value>
                <fullName>RA-3.0</fullName>
            </value>
            <value>
                <fullName>RA-3.1</fullName>
            </value>
            <value>
                <fullName>RA-3.2</fullName>
            </value>
            <value>
                <fullName>RA-3.3</fullName>
            </value>
            <value>
                <fullName>RA-DEV</fullName>
            </value>
            <value>
                <fullName>RMC-1.0</fullName>
            </value>
            <value>
                <fullName>RMC-1.1</fullName>
            </value>
            <value>
                <fullName>RMC-2.0</fullName>
            </value>
            <value>
                <fullName>RMC-2.1</fullName>
            </value>
            <value>
                <fullName>RNT-5.5</fullName>
            </value>
            <value>
                <fullName>RTS-3.00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Case__c/fields/Product_Family_PL__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_PL__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Roadnet Apex</fullName>
            </value>
            <value>
                <fullName>Roadnet Transportation Suite</fullName>
            </value>
            <value>
                <fullName>Roadnet Anywhere</fullName>
            </value>
            <value>
                <fullName>RTS Management Center</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>CAIR</fullName>
            </value>
            <value>
                <fullName>RN Telematics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Run__c/Test_Run__c.object-meta.xml
<CustomObject>
    <label>Test Run</label>
    <nameField>
        <displayFormat>TR-{00000000}</displayFormat>
        <label>Test Run Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Runs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test_Run__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Runs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Test_Run__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Run Parameters</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Test_Run__c/fields/Product_Version_PL__c.field-meta.xml
<CustomField>
    <fullName>Product_Version_PL__c</fullName>
    <label>Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex-1.0</fullName>
            </value>
            <value>
                <fullName>Apex-1.1</fullName>
            </value>
            <value>
                <fullName>Apex-1.2</fullName>
            </value>
            <value>
                <fullName>Apex-Future</fullName>
            </value>
            <value>
                <fullName>CAIR-5.0</fullName>
            </value>
            <value>
                <fullName>CAIR-5.1</fullName>
            </value>
            <value>
                <fullName>CAIR-5.2</fullName>
            </value>
            <value>
                <fullName>CAIR-6.0</fullName>
            </value>
            <value>
                <fullName>RA</fullName>
            </value>
            <value>
                <fullName>RA-2.0</fullName>
            </value>
            <value>
                <fullName>RA-2.1</fullName>
            </value>
            <value>
                <fullName>RA-2.2</fullName>
            </value>
            <value>
                <fullName>RA-2.3</fullName>
            </value>
            <value>
                <fullName>RA-2.4</fullName>
            </value>
            <value>
                <fullName>RA-2.5</fullName>
            </value>
            <value>
                <fullName>RA-2.6</fullName>
            </value>
            <value>
                <fullName>RA-2.7</fullName>
            </value>
            <value>
                <fullName>RA-2.8</fullName>
            </value>
            <value>
                <fullName>RA-2.9</fullName>
            </value>
            <value>
                <fullName>RA-3.0</fullName>
            </value>
            <value>
                <fullName>RA-3.1</fullName>
            </value>
            <value>
                <fullName>RA-3.2</fullName>
            </value>
            <value>
                <fullName>RA-3.3</fullName>
            </value>
            <value>
                <fullName>RA-DEV</fullName>
            </value>
            <value>
                <fullName>RMC-1.0</fullName>
            </value>
            <value>
                <fullName>RMC-1.1</fullName>
            </value>
            <value>
                <fullName>RMC-2.0</fullName>
            </value>
            <value>
                <fullName>RMC-2.1</fullName>
            </value>
            <value>
                <fullName>RNT-5.5</fullName>
            </value>
            <value>
                <fullName>RTS-3.00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Run__c/fields/Target_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Target_Completion_Date__c</fullName>
    <label>Target Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Test_Run__c/fields/Test_Case__c.field-meta.xml
<CustomField>
    <fullName>Test_Case__c</fullName>
    <label>Test Case</label>
    <referenceTo>Test_Case__c</referenceTo>
    <relationshipLabel>Test Runs</relationshipLabel>
    <relationshipName>Test_Runs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestRunGenerator.cls
/*******************************************************************************
 * File:  TestRunGenerator
 * Date:  June 4, 2010
 * Author:  Evan Hartig
 *
 * The use, disclosure, reproduction, modification, transfer, or transmittal of
 * this work for any purpose in any form or by any means without the written 
 * permission of Roadnet Technologies is strictly prohibited.
 *
 * Confidential, unpublished property of Roadnet Technologies.
 * Use and distribution limited solely to authorized personnel.
 *
 * Copyright 2010, Roadnet Technologies, Inc.  All rights reserved.
 *
 * Purpose: 
 *   Class used for generating Test Runs from a list of Test Cases
 *******************************************************************************/

public class TestRunGenerator {
    
    public List<Test_Case__c> testCases;
    public Test_Run__c baseRun {get; set;}
    public PageReference previousPage {get; set;}
    
    //
    // Constructor
    //
    public TestRunGenerator(ApexPages.Standardsetcontroller standardList)
    {
        previousPage = standardList.cancel();
        if(standardList.getRecords() != null)
        {
            baseRun = new Test_Run__c();
            testCases = standardList.getSelected();
            baseRun.Assigned_To__c = UserInfo.getUserId();
        }
    }
    
    //
    // Creates and assigns a new Test Run in 'not yet run' status for each 
    // test case selected in the Test Case list view
    //
    public PageReference saveTestRuns()
    {
        /*
        List<Product_Version__c> defaultProductVersion = [select Id 
            from Product_Version__c 
            where Version__c = '1.0' 
            and Product_Family__r.Name = 'Roadnet Apex' limit 1];
        */
        string defaultProductVersionname = 'Apex-1.0';
        
        for(Integer i = 0; i < testCases.size(); i++)
        {
            Test_Run__c newRun = new Test_Run__c();
            newRun.Assigned_To__c = baseRun.Assigned_To__c;
            newRun.Parameters__c = baseRun.Parameters__c;
            newRun.Target_Completion_Date__c = baseRun.Target_Completion_Date__c;
            newRun.Test_Case__c = testCases[i].Id;
            
            Test_Case__c currentCase = [select Id,Earliest_Version_PL__c,Product_Family_PL__c from Test_Case__c where Id = :testCases[i].Id];
            if(currentCase != null)
            {
            /*
                List<Product_Version__c> caseProductVersion = [select Id 
                    from Product_Version__c 
                    where Name = :currentCase.Earliest_Version_PL__c];
                 
                if(caseProductVersion.size() > 0)
                {
                    newRun.Product_Version__c = caseProductVersion[0].Id;
                }
                */
                newRun.Product_Version_PL__c = currentCase.Earliest_Version_PL__c;
            }
            
            if(newRun.Product_Version_PL__c == null)
            {
                newRun.Product_Version_PL__c = defaultProductVersionname;
            }
            
            insert newRun;
            
        }
        
        return previousPage;
    }
}