force-app/main/default/objects/Support_Alert__c/Support_Alert__c.object-meta.xml
<CustomObject>
    <label>Support Alert</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Support Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Support_Alert__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Support Alerts</relationshipLabel>
    <relationshipName>Support_Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Support_Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestSupportAlert.cls
@isTest(SeeAllData=True)
public class TestSupportAlert {
    
    public static testMethod void testContactSupportAlerts(){
    
    Account newAccount = new Account();
    newAccount.Name = 'SFDC';
    newAccount.Type = 'Other';
    newAccount.BillingStreet = 'Test Address';
    newAccount.BillingCity = 'Test City';
    newAccount.BillingCountry = 'Test Country';
    insert newAccount;
    
    Support_Alert__c newSuppalert = new Support_Alert__c();
    newSuppalert.Account__c = newAccount.Id;
    newSuppalert.Description__c = 'Test Descritpion';
    newSuppalert.End_Date__c =  date.today()+4;
    insert newSuppalert;
    
    Contact newCnt=new Contact();
    newCnt.FirstName='SFDC';
    newCnt.LastName='Salesforce';
    newCnt.AccountId = newAccount.Id;
    insert newcnt;
    
    // create a new cotnact standard controller by passing the contact record
    ApexPages.StandardController contactController = new ApexPages.StandardController(newCnt);
    
    // now pass it to the extension
    SupportAlert alertController = new SupportAlert(contactController);
    
    //Test if the alertController is successfully created or not
    system.assert(alertController != null); 
    
    //Now test extension methods
    List<Support_Alert__c> alerts = alertController.getAlerts();
    
    system.assert(alerts != null);
    
    }
}