force-app/main/default/objects/Key_Business_Goal_and_Strategy__c/Key_Business_Goal_and_Strategy__c.object-meta.xml
<CustomObject>
    <label>Key Business Goal &amp; Strategy</label>
    <nameField>
        <displayFormat>GS-{0000}</displayFormat>
        <label>Goal/Strategy #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Business Goals &amp; Strategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Business_Goal_and_Strategy__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <description>Used to document the key business goals for a strategic account</description>
    <label>Goal</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Key_Business_Goal_and_Strategy__c/fields/Strategic_Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Account_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategic Account Profile</label>
    <referenceTo>Strategic_Account_Profile__c</referenceTo>
    <relationshipName>Key_Business_Goal_and_Strategy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/Strategic_Account_Profile__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the profile information on strategic accounts for the T&amp;L Organization</description>
    <label>Strategic Account Profile</label>
    <nameField>
        <label>Strategic Account Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Strategic_Account_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Mod_Key_Business_Goals_and_Strategy__c.field-meta.xml
<CustomField>
    <fullName>Last_Mod_Key_Business_Goals_and_Strategy__c</fullName>
    <label>Key Business Goals and Strategy</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_CSF__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_CSF__c</fullName>
    <label>Critical Success Factors</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Date_Time__c</fullName>
    <label>SAP Last Modified Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestUpdateKeyBusinessGandS.cls
@isTest(SeeAllData = true)
public class TestUpdateKeyBusinessGandS 
{
/***************************************************************************************************************
Date: 01/19/2009
Author: Divya Hegde, Salesforce.com Consultant
        Tata Consultancy Services Limited

Purpose: Test Method to validate the functionality of Trigger "UpdateKeyBusinessGS" on Key Business Goals and Strategies.
*******************************************************************************************************************************************/
 static testMethod void testTrigger()
  {
   Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
   Account acc = GenericTestClass.insertAccount();
   
   NewSAP.Account__c =acc.id ;
   NewSAP.Last_Mod_Key_Business_Goals_and_Strategy__c =datetime.valueOf('2008-12-02 13:52:00');
   NewSAP.Last_Modified_CSF__c=datetime.valueOf('2008-12-03 13:52:00');
   NewSAP.Last_Modified_Date_Time__c=datetime.valueOf('2008-12-03 13:51:00');
   insert NewSAP;
   Key_Business_Goal_and_Strategy__c KeyGSnew =new Key_Business_Goal_and_Strategy__c();
   KeyGSnew .Strategic_Account_Profile__c = NewSAP.Id;
   KeyGSnew .Goal__c='test1234';
   insert KeyGSnew ;
  }
  static testMethod void UpdateKeyBusinessGS()
  {
   Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
   Account acc = GenericTestClass.insertAccount();
   
   NewSAP.Account__c =acc.id ;
   insert NewSAP;
   Key_Business_Goal_and_Strategy__c KeyGSnew =new Key_Business_Goal_and_Strategy__c();
   KeyGSnew .Strategic_Account_Profile__c = NewSAP.Id;
   KeyGSnew .Goal__c='test1234';
   insert KeyGSnew ;
   update NewSAP;
  }
}