force-app/main/default/objects/Revision_Schedule__c/Revision_Schedule__c.object-meta.xml
<CustomObject>
    <label>Revision Schedule</label>
    <nameField>
        <label>Revision Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revision Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revision_Schedule__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Revision Schedules</relationshipLabel>
    <relationshipName>Revision_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revision_Schedule__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Quote Approval</fullName>
            </value>
            <value>
                <fullName>Pending Finance Approval</fullName>
            </value>
            <value>
                <fullName>Pending Legal Approval</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteLineScheduleControllerTest.cls
/**
 * Created by Yasir Arafat
 */

@IsTest
private class QuoteLineScheduleControllerTest {
    private static VistaAssetHelperUtil util = new VistaAssetHelperUtil();
    
    @testSetup
    static void SetupData() {
        TestUtils.defineCustomSettings();
    }

    @IsTest
    static void testQuoteLineScheduleManager() {
        Account account = util.createAccount('ABC Test Account');
        List<Product2> productList = new List<Product2>();
        //subPricingType = 'Fixed Price' or 'Percent Of Total'
        productList.addAll(util.initProductSet(1, 'Hardware', '', 'Fixed Price', 'Monthly'));
        productList[0].Shipment_Schedule_Required__c = TRUE;
        update productList;
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);
        Opportunity opportunity = util.createNewOpportunity('Test Opportunity 1', account, 'Products, Services and Maintenance', 'New');
        SBQQ__Quote__c sbQuote = util.createSBQuote(opportunity, account, Date.today(), true);
        List<SBQQ__Quoteline__c> sbQuoteLines = util.createSBQuoteLines(sbQuote, pricebookEntries, true, 5);

        Test.startTest();
        PageReference pageRef = Page.QuoteLineSchedules; // Specify VF page Name here
        pageRef.getParameters().put('id', String.valueOf(sbQuote.Id));
        Test.setCurrentPage(pageRef);
        ManageQuoteLineScheduleController schedulerController = new ManageQuoteLineScheduleController();
        schedulerController.initialize();
        schedulerController.addRevision();
        schedulerController.submit();
        Revision_Schedule__c revSched = [Select Id, Status__c from Revision_Schedule__c where Quote__c = :sbQuote.Id LIMIT 1];
        revSched.Status__c = 'Approved';
        update revSched;
        Test.stopTest();
    }
}