force-app/main/default/objects/Scoring_Item__c/Scoring_Item__c.object-meta.xml
<CustomObject>
    <label>Scoring Item</label>
    <nameField>
        <label>Scoring Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <label>Scoring Model</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Scoring Items</relationshipLabel>
    <relationshipName>Scoring_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/Scoring_Model__c.object-meta.xml
<CustomObject>
    <label>Scoring Model</label>
    <nameField>
        <label>Scoring Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestScoringItemEdit.cls
/*********************************************************************************
* Name: TestScoringItemEdit
* Created by Omnitracs {DateCreated 7/1/2016} 
----------------------------------------------------------------------------------
* Purpose/Methods:/ 
* This is used as test class of controller ScoringItemEdit
----------------------------------------------------------------------------------
* Unit Test: TestScoringItemEdit
---------------------------------------------------------------------------------- 
* History:
* VERSION DEVELOPER NAME DATE DETAIL FEATURES
1.0 7/1/2016 INITIAL DEVELOPMENT
 
*********************************************************************************/

@isTest
private class TestScoringItemEdit {
    
    static testMethod void myUnitTest1() {
        
        //Creating Scoring_Model__c by calling ScoringModel method of TestScoringUtility
        Scoring_Model__c sm = TestScoringUtility.createScoringModel();
        
        //Creating Scoring_Item__c by calling createScoringItem method of TestScoringUtility
        Scoring_Item__c s = TestScoringUtility.createScoringItem();
        s.Scoring_Model__c = sm.Id;
        insert s;
        
        PageReference pageRef = Page.ScoringModelEdit;
        Test.setCurrentPageReference(pageRef);
        
        ApexPages.currentPage().getParameters().put(Label.ScoringModelFieldID,sm.Id);
        
        ScoringItemEdit se = new ScoringItemEdit(new ApexPages.StandardController(s));
        
        se.DoSave();
        se.getAccountFields();
        
                
            }
    
   
}