force-app/main/default/objects/Shipment_Forecast__c/Shipment_Forecast__c.object-meta.xml
<CustomObject>
    <label>Shipment Forecast</label>
    <nameField>
        <displayFormat>SF-{0}</displayFormat>
        <label>Shipment Forecast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Forecast__c/fields/Quote_Product__c.field-meta.xml
<CustomField>
    <fullName>Quote_Product__c</fullName>
    <label>Quote Product</label>
    <referenceTo>VCG_CPQ_Quote_Product__c</referenceTo>
    <relationshipLabel>Shipment Forecasts</relationshipLabel>
    <relationshipName>Shipment_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment_Forecast__c/fields/Shipment_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Quantity__c</fullName>
    <label>Shipment Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <inlineHelpText>Contract Term in Months</inlineHelpText>
    <label>Contract Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <inlineHelpText>Will not be displayed to customer in the quote output.</inlineHelpText>
    <label>Internal Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores this Quotes Lookup for use in mapping to the Opportunity for the Primary Quote</description>
    <label>Quote ***</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/VCG_CPQ_Quote_Product__c.object-meta.xml
<CustomObject>
    <description>An individual line item on a quote</description>
    <label>Quote Product</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <description>Contract Term in months</description>
    <inlineHelpText>Contract Term in months.</inlineHelpText>
    <label>Contract Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/License_Metric_Quantity__c.field-meta.xml
<CustomField>
    <fullName>License_Metric_Quantity__c</fullName>
    <label>License Metric Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Do not modify! Always == 1. Maps to the Quantity field in the Opp Line Items so OLI.Total == Quantity * Sales Price (we set Sales Price as the total amount, not the Unit price).</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote_Product__c.field-meta.xml
<CustomField>
    <fullName>Quote_Product__c</fullName>
    <formula>Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EditShipmentScheduleExt_Test.cls
/*
 *  @author:        Mark De Chavez | mark.dechavez@cloudsherpas.com
 *  @description:   Test class for EditShipmentScheduleExt.
 *  @date-created:  September 09, 2014
 *  @revision: 
 */

@isTest(SeeAllData=True)
public class EditShipmentScheduleExt_Test {
    
    static testMethod void dataDisplayTest(){
        Account acc = new Account(Name='TestAcc', Phone='838-77-03', 
                                  Account_Type__c='Association', /*District__c='Canada',*/ 
                                  QWBS_Market__c='T&L', QWBS_Status__c='Active Prospect');
        insert acc;
       
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId = acc.Id, 
                                          CloseDate=date.today(), StageName='Sales Acceptance');
        insert opp;
        
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c(Account__c=acc.Id, Opportunity__c = opp.Id, 
                                                      Effective_Date__c = date.today(), Contract_Term__c=5);
        insert quote;
        
        VCG_CPQ_Quote_Product__c quoteProd = new VCG_CPQ_Quote_Product__c(Quote__c=quote.Id, License_Metric_Quantity__c=1);
        insert quoteProd;
        
        Test.startTest();
            Test.setCurrentPage(Page.EditShipmentSchedule);
            EditShipmentScheduleExt controller = new EditShipmentScheduleExt(new ApexPages.StandardController(quoteProd));          
        Test.stopTest();
        
        System.assert(controller.quoteProd.Id == quoteProd.Id);
        System.assert(controller.quoteProd.Quantity__c == quoteProd.Quantity__c);        
    }
    
    static testMethod void addRowTest(){
        Account acc = new Account(Name='TestAcc', Phone='838-77-03', 
                                  Account_Type__c='Association', /*District__c='Canada',*/ 
                                  QWBS_Market__c='T&L', QWBS_Status__c='Active Prospect');
        insert acc;
       
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId = acc.Id, 
                                          CloseDate=date.today(), StageName='Sales Acceptance');
        insert opp;
        
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c(Account__c=acc.Id, Opportunity__c = opp.Id, 
                                                      Effective_Date__c = date.today(), Contract_Term__c=5);
        insert quote;
        
        VCG_CPQ_Quote_Product__c quoteProd = new VCG_CPQ_Quote_Product__c(Quote__c=quote.Id, License_Metric_Quantity__c=1);
        insert quoteProd;
        
        Test.startTest();
            Test.setCurrentPage(Page.EditShipmentSchedule);
            EditShipmentScheduleExt controller = new EditShipmentScheduleExt(new ApexPages.StandardController(quoteProd));
            controller.addRow();
            System.assertEquals(2, controller.dispShipmentSched.size());
            controller.addRow();
            System.assertEquals(3, controller.dispShipmentSched.size());
        Test.stopTest();                
    }
    
    static testMethod void deleteRowTest(){
        Account acc = new Account(Name='TestAcc', Phone='838-77-03', 
                                  Account_Type__c='Association', /*District__c='Canada',*/ 
                                  QWBS_Market__c='T&L', QWBS_Status__c='Active Prospect');
        insert acc;
       
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId = acc.Id, 
                                          CloseDate=date.today(), StageName='Sales Acceptance');
        insert opp;
        
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c(Account__c=acc.Id, Opportunity__c = opp.Id, 
                                                      Effective_Date__c = date.today(), Contract_Term__c=5);
        insert quote;
        
        VCG_CPQ_Quote_Product__c quoteProd = new VCG_CPQ_Quote_Product__c(Quote__c=quote.Id, License_Metric_Quantity__c=1);
        insert quoteProd;
        
        Test.startTest();
            Test.setCurrentPage(Page.EditShipmentSchedule);
            EditShipmentScheduleExt controller = new EditShipmentScheduleExt(new ApexPages.StandardController(quoteProd));
            controller.addRow();
            System.assert(controller.dispShipmentSched.size()==2);
            System.currentPageReference().getParameters().put('rowIndex', '1');
            controller.deleteShipmentSched();
            System.assert(controller.dispShipmentSched.size()==1);
        Test.stopTest();                
    }
    
    static testMethod void savedTest(){
        Account acc = new Account(Name='TestAcc', Phone='838-77-03', 
                                  Account_Type__c='Association', /*District__c='Canada',*/ 
                                  QWBS_Market__c='T&L', QWBS_Status__c='Active Prospect');
        insert acc;
       
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId = acc.Id, 
                                          CloseDate=date.today(), StageName='Sales Acceptance');
        insert opp;
        
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c(Account__c=acc.Id, Opportunity__c = opp.Id, 
                                                      Effective_Date__c = date.today(), Contract_Term__c=5);
        insert quote;
        
        VCG_CPQ_Quote_Product__c quoteProd = new VCG_CPQ_Quote_Product__c(Quote__c=quote.Id, License_Metric_Quantity__c=15);
        insert quoteProd;
        
        Test.startTest();
            Test.setCurrentPage(Page.EditShipmentSchedule);
            EditShipmentScheduleExt controller = new EditShipmentScheduleExt(new ApexPages.StandardController(quoteProd));
            controller.addRow();
            controller.dispShipmentSched[0].Shipment_Date__c = Date.today();
            controller.dispShipmentSched[0].Shipment_Quantity__c = 5;
            controller.dispShipmentSched[0].Notes__c = 'test shipment sched';
            controller.dispShipmentSched[1].Shipment_Date__c = Date.today();
            controller.dispShipmentSched[1].Shipment_Quantity__c = 10;
            controller.dispShipmentSched[1].Notes__c = 'test shipment sched2';
            controller.saveShipmentSched();
        Test.stopTest();                
        
        List<Shipment_Forecast__c> addedSchedList = [SELECT Shipment_Date__c, Shipment_Quantity__c, Notes__c 
                                                 FROM Shipment_Forecast__c 
                                                 WHERE Quote_Product__c =: quoteProd.Id ORDER BY Shipment_Date__c];
        System.assertEquals(2, addedSchedList.size());
        System.assert(addedSchedList[0].Shipment_Quantity__c == 5);
    }
    
    static testMethod void failedSavedTest(){
        Account acc = new Account(Name='TestAcc', Phone='838-77-03', 
                                  Account_Type__c='Association', /*District__c='Canada',*/ 
                                  QWBS_Market__c='T&L', QWBS_Status__c='Active Prospect');
        insert acc;
       
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId = acc.Id, 
                                          CloseDate=date.today(), StageName='Sales Acceptance');
        insert opp;
        
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c(Account__c=acc.Id, Opportunity__c = opp.Id, 
                                                      Effective_Date__c = date.today(), Contract_Term__c=5);
        insert quote;
        
        VCG_CPQ_Quote_Product__c quoteProd = new VCG_CPQ_Quote_Product__c(Quote__c=quote.Id, License_Metric_Quantity__c=10);
        insert quoteProd;
        
        Test.startTest();
            Test.setCurrentPage(Page.EditShipmentSchedule);
            EditShipmentScheduleExt controller = new EditShipmentScheduleExt(new ApexPages.StandardController(quoteProd));
            controller.addRow();
            controller.dispShipmentSched[0].Shipment_Date__c = Date.today();
            controller.dispShipmentSched[0].Shipment_Quantity__c = 10;
            controller.dispShipmentSched[0].Notes__c = 'test shipment sched';
            controller.dispShipmentSched[1].Shipment_Date__c = Date.today();
            controller.dispShipmentSched[1].Shipment_Quantity__c = 5;
            controller.dispShipmentSched[1].Notes__c = 'test shipment sched2';
            controller.saveShipmentSched();
        Test.stopTest();
        
        List<Shipment_Forecast__c> addedSchedList = [SELECT Shipment_Date__c, Shipment_Quantity__c, Notes__c 
                                                 FROM Shipment_Forecast__c 
                                                 WHERE Quote_Product__c =: quoteProd.Id ORDER BY Shipment_Date__c];
        System.assertEquals(0, addedSchedList.size());
        
    }
}