force-app/main/default/objects/Renewal_Notifications__c/Renewal_Notifications__c.object-meta.xml
<CustomObject>
    <label>Renewal Notifications</label>
    <nameField>
        <label>Renewal Notifications Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Renewal_Notifications__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SAA_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Renewal_Notifications__c/fields/Email_Actual_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Actual_Sent_Date__c</fullName>
    <label>Email Actual Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Renewal_Notifications__c/fields/Email_Schedule_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Schedule_Send_Date__c</fullName>
    <label>Email Schedule Send Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Renewal_Notifications__c/fields/Fee_Increase_Contact__c.field-meta.xml
<CustomField>
    <fullName>Fee_Increase_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Increase Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>SAA_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Renewal_Notifications__c/fields/Uplift_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Uplift_Effective_Date__c</fullName>
    <label>Uplift Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Renewal_Notifications__c/fields/Uplift_Percent__c.field-meta.xml
<CustomField>
    <fullName>Uplift_Percent__c</fullName>
    <label>Uplift Percent</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/CreateRenewalNotificationsScheduler.cls
global class CreateRenewalNotificationsScheduler  implements Schedulable{
	
    public static string snQuery;
	public CreateRenewalNotificationsScheduler(){
    }
    
    global void execute(SchedulableContext SC)
    {
        
        /*
         CreateRenewalNotificationsScheduler crns = new CreateRenewalNotificationsScheduler();
	     String rnSch = '0 0 * * * ?';
		 system.schedule('Renewal Notifications Batch', rnSch, crns);
		 */
        String snQuery = 'select Id, Account__c from Renewal_Notifications__c where Email_Schedule_Send_Date__c = :todayDate and '+
				  'Fee_Increase_Contact__c != null and Uplift_Effective_Date__c != null and Uplift_Percent__c != null and '+
				  'Email_Actual_Sent_Date__c = null';
        CreateRenewalNotificationsBatch crcs = new CreateRenewalNotificationsBatch(snQuery);
        database.executeBatch(crcs);
    }
    
}