force-app/main/default/objects/EventsQuantityAction__c/EventsQuantityAction__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Event vs Quantity Action</description>
    <label>EventsQuantityAction</label>
</CustomObject>

force-app/main/default/objects/EventsQuantityAction__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXN_Log__c/TXN_Log__c.object-meta.xml
<CustomObject>
    <description>Transaction Log table which will hold all the Customer Asset&apos;s transactions from the UpStream systems like ERP, AUTO etc.</description>
    <label>TXN Log</label>
    <nameField>
        <displayFormat>TXN-{00000000}</displayFormat>
        <label>TXN Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TXN Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TXN_Log__c/fields/Account_Cust_ID__c.field-meta.xml
<CustomField>
    <fullName>Account_Cust_ID__c</fullName>
    <description>Account Cust ID</description>
    <label>Account Cust ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXN_Log__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>Describe the Asset Type for a transaction log record</description>
    <label>Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERP_SHIPMENT</fullName>
                <default>true</default>
                <label>ERP_SHIPMENT</label>
            </value>
            <value>
                <fullName>ERP_RECEIPT</fullName>
            </value>
            <value>
                <fullName>ERP_XRS_PLANS</fullName>
            </value>
            <value>
                <fullName>ERP_XRS_APPS</fullName>
            </value>
            <value>
                <fullName>ERP_RN_BILLING</fullName>
            </value>
            <value>
                <fullName>AUTO_FLEET_REDUCTION</fullName>
            </value>
            <value>
                <fullName>AUTO_REACTIVATION</fullName>
            </value>
            <value>
                <fullName>AUTO_TERMINATION</fullName>
            </value>
            <value>
                <fullName>AUTO_TRANSFER_FROM</fullName>
            </value>
            <value>
                <fullName>AUTO_TRANSFER_TO</fullName>
            </value>
            <value>
                <fullName>MANUAL_ES_PLANS</fullName>
            </value>
            <value>
                <fullName>MANUAL_ES_APPS</fullName>
            </value>
            <value>
                <fullName>MANUAL_XRS_PLANS</fullName>
            </value>
            <value>
                <fullName>MANUAL_XRS_APPS</fullName>
            </value>
            <value>
                <fullName>MANUAL_RN_BILLING</fullName>
            </value>
            <value>
                <fullName>SALESFORCE_CONTRACT_TRANSFER</fullName>
            </value>
            <value>
                <fullName>SALESFORCE_FRICTIONLESS</fullName>
            </value>
            <value>
                <fullName>SALESFORCE_NEW_TRANSFERS</fullName>
            </value>
            <value>
                <fullName>ERP_TRANSFER</fullName>
            </value>
            <value>
                <fullName>BILLING_ES_APPS</fullName>
            </value>
            <value>
                <fullName>BILLING_ES_PLANS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TXN_Log__c/fields/IsProcessed__c.field-meta.xml
<CustomField>
    <fullName>IsProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean to check whether the transaction log has laready been processed by Batch Apex</description>
    <label>IsProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TXN_Log__c/fields/Item_SKU_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Item_SKU_Product_Id__c</fullName>
    <description>Item/SKU/Product Id from Upstream system which maps to product Code in Salesforce</description>
    <label>Item_SKU_Product Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXN_Log__c/fields/Sub_Event__c.field-meta.xml
<CustomField>
    <fullName>Sub_Event__c</fullName>
    <label>Sub Event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sub_Event1</fullName>
            </value>
            <value>
                <fullName>Sub_Event2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TxnLogBatch.cls
global class TxnLogBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    public Map<String, String> eventsActionMap;
    global List<String> idQtys;
	global String mailCsvContent;
    
    global TxnLogBatch(){
        mailCsvContent = 'TXN Log, Cust ID, Oracle ID, Event Type, Event Quantity, Matching Customer Asset, Status, Add On Opportunity, Remarks\n';
		eventsActionMap = new Map<String, String>();
        idQtys = new List<String>();
        List<EventsQuantityAction__c> listEventsAction = EventsQuantityAction__c.getall().values();
        for(EventsQuantityAction__c eventAction : listEventsAction){
            eventsActionMap.put(eventAction.name, eventAction.Action__c);
        }
    }
   
    // Start Method
    global Database.QueryLocator start(Database.BatchableContext BC){
        //List<TXN_Log__c> txnLogList = [select Id, Name, Account_Cust_ID__c, Item_SKU_Product_Id__c, Event__c, Sub_Event__c, Quantity__c, IsProcessed__c from TXN_Log__c where IsProcessed__c = false];
        String query = 'select Id, Name, Account_Cust_ID__c, Item_SKU_Product_Id__c, Event__c, Sub_Event__c, Quantity__c, IsProcessed__c from TXN_Log__c where IsProcessed__c = false limit ' + (Test.isRunningTest() ? '4' : '500000');
		return Database.getQueryLocator(query);
    }
  
    // Execute Logic
    global void execute(Database.BatchableContext BC, List<TXN_Log__c> txnLogList){
        Map<String, List<String>> returnContent = TxnLogUtils.processTxnLogs(txnLogList, eventsActionMap);
		mailCsvContent += returnContent.get('mailCsvContent')[0];
		idQtys.addAll(returnContent.get('quoteLineIds'));
    }
 
    global void finish(Database.BatchableContext BC){
        // Logic to be Executed at finish
        System.debug('Batch Execution of Transaction Logs completed, proceeding with Quote Line Quantity update.');
		System.debug('mailCsvContent\n' + mailCsvContent);
		
		String sEmailBody='Please see the attached file for details of the Transaction Log records processing.';
		Blob csvBlob = Blob.valueOf(mailCsvContent);
		Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
		csvAttc.setFileName('Batch_Update_Result.csv');
		csvAttc.setContentType('text/csv');
        csvAttc.setBody(csvBlob);
		//Create Email      
		Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
		OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'omnitracs.sfdc.noreply@omnitracs.com'];
		if(owea.size() > 0){
			email.setOrgWideEmailAddressId(owea.get(0).Id);
		}else{
			email.setSenderDisplayName('Transaction Log Batch Job Status');
		}
		//String[] toAddresses = new list<String> {'weisheit@omnitracs.com','ichopin@omnitracs.com','usyed@omnitracs.com','alott@omnitracs.com','enovy@omnitracs.com'};
		String[] toAddresses = new list<String> {'sales.ops@omnitracs.com'};
		String[] ccAddresses = new list<String> {'weisheit@omnitracs.com','yarafat@omnitracs.com'};

		email.setSubject('Transaction Log Batch Job Status');       

		email.setToAddresses(toAddresses);
		email.setCcAddresses(ccAddresses);        

		email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});
		email.setPlainTextBody(sEmailBody);

		Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
		
        Database.executeBatch(new QuoteLineUpdate(idQtys), 1);
    }
}