force-app/main/default/objects/Product_Migration__c/Product_Migration__c.object-meta.xml
<CustomObject>
    <description>Product Migrations is to be used to capture customer information along a products end of life cycle.</description>
    <label>Product Migration</label>
    <nameField>
        <label>Product Migration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Migrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Migration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owned by Sales (Hy Mixson/Dean Bikle) and PM (Casey Crawford). Required as part of the MBO to track RTS to RNA Product Migrations.</description>
    <inlineHelpText>Customer Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Migrations</relationshipLabel>
    <relationshipName>Product_Migrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductMigrationTriggerTest.cls
@isTest
public class ProductMigrationTriggerTest {
    
    public static VistaAssetHelperUtil util = new VistaAssetHelperUtil();
    
    @testSetup
    static void SetupData() {
        TestUtils.defineCustomSettings();
    }

    static testMethod void myUnitTest() {
        Account account = util.createAccount('ABC ProductMigration Test Account');
        Test.startTest();
        Id productMigrationRecordTypeId = Schema.SObjectType.Product_Migration__c.getRecordTypeInfosByName().get('RTS to RNA Migration').getRecordTypeId();
        Product_Migration__c productMigration = new Product_Migration__c(RecordTypeId = productMigrationRecordTypeId, Account__c = account.Id);
        insert productMigration;
        try{
            Product_Migration__c duplicateProductMigration = new Product_Migration__c(RecordTypeId = productMigrationRecordTypeId, Account__c = account.Id);
            insert duplicateProductMigration;
        }catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('already exists') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }
}