force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Created for Contract Management.</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional Party Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Additional Party Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Contract Specific Address</fullName>
            </value>
            <value>
                <fullName>Express Mail Address</fullName>
            </value>
            <value>
                <fullName>Invoice Address</fullName>
            </value>
            <value>
                <fullName>Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Pricing Notice Address</fullName>
            </value>
            <value>
                <fullName>Government Specific Address</fullName>
            </value>
            <value>
                <fullName>Remit to Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Corporate HQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Created for Contract Management.</description>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ByPassTrigger__c/ByPassTrigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ByPass Trigger</label>
</CustomObject>

force-app/main/default/objects/ByPassTrigger__c/fields/isDisabled__c.field-meta.xml
<CustomField>
    <fullName>isDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDisabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountAddressTriggerTest.cls
@isTest
public class AccountAddressTriggerTest {
    private static VistaAssetHelperUtil util = new VistaAssetHelperUtil();

    @isTest 
    static void testUpdateQuoteAddresses() {
   
		insert new ByPassTrigger__c(SetupOwnerId=UserInfo.getOrganizationId(), isDisabled__c=true, Name='Testing Bypass');
        
        Account account = util.createAccount('ABC Test Account');
        List<Address__c> addressList = new List<Address__c>();
        Address__c addr1 = new Address__c(Address_Line_1__c = 'Test Address',
                                                 City__c = 'Newark',State_Province__c = 'NJ',
                                                 Zip_Postal_Code__c = '07017', Account__c = account.id, Location_Type__c='Shipping Address');  
        
        Address__c addr2 = new Address__c(Address_Line_1__c = 'Test Address1',
                                                 City__c = 'Newark',State_Province__c = 'NJ',
                                                 Zip_Postal_Code__c = '07017', Account__c = account.id, Location_Type__c='Billing Address');  
        
        Address__c addr3 = new Address__c(Address_Line_1__c = 'Test Address2',
                                                 City__c = 'Newark',State_Province__c = 'NJ',
                                                 Zip_Postal_Code__c = '07017', Account__c = account.id, Location_Type__c='Corporate HQ');  
        addressList.add(addr1);
        addressList.add(addr2);
        addressList.add(addr3);
        insert addressList;
        
        List<Product2> productList = new List<Product2>();
        productList.addAll(util.initProductSet(2, 'Hardware', '', 'Fixed Price', 'Monthly'));
        Map<Id, PricebookEntry> pricebookEntries = new Map<Id, PricebookEntry>();
        pricebookEntries = util.initPricebook(productList);
        Opportunity opportunity = util.createNewOpportunity('Test Opportunity 1', account, 'Products, Services and Maintenance', 'New');
        SBQQ__Quote__c sbQuote = util.createSBQuote(opportunity, account, Date.today(), true);
        
        addressList.get(0).Address_Line_1__c = 'test1';
        addressList.get(1).Address_Line_1__c = 'test2';
        addressList.get(2).Address_Line_1__c = 'test3';
        update addressList;
        
    }    
}