force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_ID__c.field-meta.xml
<CustomField>
    <fullName>Address_ID__c</fullName>
    <externalId>true</externalId>
    <label>Address ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Created for Contract Management.</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Created for Contract Management.</description>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/Contract_Address__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management. Allows users to add multiple types of Addresses to a Contract, such as Shipping, Notice Address, etc.</description>
    <label>Contract Address</label>
    <nameField>
        <displayFormat>CAA-{0000000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Address__c/fields/Account_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You may select an existing Account Additional Address record</inlineHelpText>
    <label>Account Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contract Addresses</relationshipLabel>
    <relationshipName>Contract_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Address_ID__c.field-meta.xml
<CustomField>
    <fullName>Address_ID__c</fullName>
    <externalId>true</externalId>
    <label>Address ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Addresses</relationshipLabel>
    <relationshipName>Contract_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContractAddressExt_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=True)
private class ContractAddressExt_Test {
    public static Account accountInstance = new Account();
        public static Contract contractInstance = new Contract();
        public static Address__c addrInstance = new Address__c();
        public static Contract_Address__c contractAddrInstance = new Contract_Address__c();
    static testMethod void ContractAddressExt_Test() {
        
         accountInstance     =   new Account(    Name    =   'testAccount',
                                                    Phone   =   '12345',
                                                    Account_Classification__c   =   'Prospect',
                                                    Account_Status__c   =   'Active',
                                                    Account_Type__c =   'Association'
         
                                                );
            insert accountInstance;    
            
            addrInstance = new Address__c(  Address_Line_1__c = 'Test Address',
                                            City__c = 'Newark',
                                            State_Province__c = 'NJ',
                                            Zip_Postal_Code__c = '07017', 
                                            Account__c = accountInstance.id 
                                            );  
                                      
            insert addrInstance;
            contractInstance    =   new Contract(   Contract_Title__c   =   'testTitle',
                                                    //recordtypeid    =   contractRtId,
                                                    AccountId  =   accountInstance.id,
                                                    Status =   'Draft',
                                                    StartDate  =   date.today(),
                                                    EndDate    =   date.today(),
                                                    ContractTerm   =   1,
                                                    //CurrencyIsoCode    =   'USD',
                                                    Contract_ID__c =   null,
                                                    Term_type__c = 'Fixed',
                                                    Agreement_type__c = 'Individual',
                                                    Contract_Type__c = 'Customer',
                                                    Affiliate_Language__c = 'Yes',                                                 
                                                    Legal_Entity_Name__c ='Omnitracs, LLC'
                                                 );
            insert contractInstance;
            
            contractAddrInstance = new Contract_Address__c(  Address_Line_1__c = 'Test Address',
                                            City__c = 'Newark',
                                            State_Province__c = 'NJ',
                                            Zip_Postal_Code__c = '07017', 
                                            Address_ID__c = addrInstance.Id,
                                            Account_Address__c = addrInstance.Id,
                                            contract__c = contractInstance.id
                                            );  
                                            
            //insert contractAddrInstance;
            ContractAddressExt  con = new ContractAddressExt (new ApexPAges.StandardController(contractAddrInstance));
            con.ca = contractAddrInstance;
     
            con.ResetAddress();
            con.SaveAndNew();                               
  
        
    }
}