force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Created for Contract Management.</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ascension Island</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional Party Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Additional Party Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Contract Specific Address</fullName>
            </value>
            <value>
                <fullName>Express Mail Address</fullName>
            </value>
            <value>
                <fullName>Invoice Address</fullName>
            </value>
            <value>
                <fullName>Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Pricing Notice Address</fullName>
            </value>
            <value>
                <fullName>Government Specific Address</fullName>
            </value>
            <value>
                <fullName>Remit to Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Corporate HQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Created for Contract Management.</description>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCG_CPQ_QuoteAddress.cls
public without sharing class VCG_CPQ_QuoteAddress {
    
    //==========================================
    public Opportunity opp{get;set;}
    public boolean bypassValidation{get;set;}
    public VCG_CPQ_QuoteAddress(ApexPages.StandardController ctl)
    {
        string oppId = ApexPages.currentPage().getParameters().get('oppid');
        
        opp = new Opportunity();
        opp = [Select Corporate_Account_Address__c, Invoice_Account_Address__c, ShippingAddress__c from Opportunity where Id = :oppId];
       
    }
    
    
    public PageReference next()
    {
        if(!bypassValidation
            && (opp.Corporate_Account_Address__c == null
                || opp.Invoice_Account_Address__c == null))
        {
            if(opp.Corporate_Account_Address__c == null) opp.Corporate_Account_Address__c.addError('Please specify a Corporate Address');
            if(opp.Invoice_Account_Address__c == null) opp.Invoice_Account_Address__c.addError('Please specify an Invoice Address');
             
            //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please specify a corporate and invoice address'));
            return null;
        }
        try{
           update opp;
        }
        catch(Exception e)
        {
           ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
           return null;
        }
        return new PageReference('/apex/VCG_CPQ_Quote?oppid='+opp.Id);
    }
    public PageReference verifyUserIsRoadnetPartnerVar()
    {
        if (isUserRoadnetPartner)//  per case no 02038661, prepoulate the oppt addreess fields with the account's if it is not set  
        {
            //  had to put the action method here as we are creating coporate address on page load and it cannot be done in the constructor
            prepopOpptAddressFields();
        }
        return null;
    }
    public void prepopOpptAddressFields()
    {
        Address__c[] addressesOfVar;
        
        //  so we need to query the account of the var and prepopuate the oppt.address fields with that of the vars
        //  we should be able to get the vars address from the user.contactid.account
        if (loggedInUser != null &&
            loggedInUser.contactId != null &&
            loggedINUser.contact.accountid != null)
        {
            //  first thing we need to do here is see if the account addresses already exist for the var (they should if they used this prompt)
             //  at least once.  we will query all account addresses then see if we get a match on the var's account address info
            
            try
            {
                addressesOfVar = [select account__c, address_line_1__c, address_line_2__c, city__c, country__c, location_type__c, phone_number__c, state_province__c, 
                   zip_postal_code__c from Address__c where account__c =: loggedInUser.Contact.AccountId order by lastmodifieddate desc];
            }
            catch(Exception e)
            {
                //  do nthing here
            }
            
            //  so two outcomes here, either we have adddressses or we have none, if we none, its simple, if we have some, its complicated...
            if (addressesOfVar == null || addressesOfVar.size() == 0)//  we'll need to create the address records and assign to the oppt fields
            {
                if (loggedInUser.Contact.Account.billingaddress != null)
                {
                    if (opp.Corporate_Account_Address__c == null)
                    {
                        opp.Corporate_Account_Address__c = createAccountAddress('Corporate HQ', 'Billing', loggedInUser);
                    }
                    if (opp.Invoice_Account_Address__c == null)
                    {
                        opp.Invoice_Account_Address__c = createAccountAddress('Invoice Address', 'Billing', loggedInUser);
                    }
                }
                if (loggedInUser.Contact.Account.ShippingAddress != null && 
                   opp.ShippingAddress__c == null)
                {
                    opp.ShippingAddress__c = createAccountAddress('Shipping Address', 'Shipping', loggedInUser);                
                }
            }
            else  // so that menas that we found 1 or more accountaddresses
            {
                //  the reason why we check is to avoid having to create dupe addresses.
                if (opp.Corporate_Account_Address__c == null)
                {
                    id corpAcctAddress = findAddressId('Corporate HQ', addressesOfVar);
                    if (corpAcctAddress != null)
                    {
                        opp.Corporate_Account_Address__c = corpAcctAddress;
                    }
                    else
                    {
                        opp.Corporate_Account_Address__c = createAccountAddress('Corporate HQ', 'Billing', loggedInUser);
                    }
                }
                
                if (opp.Invoice_Account_Address__c == null)
                {
                    id invoiceAcctAddress = findAddressId('Invoice Address', addressesOfVar);
                    if (invoiceAcctAddress != null)
                    {
                        opp.Invoice_Account_Address__c = invoiceAcctAddress;
                    }
                    else
                    {
                        opp.Invoice_Account_Address__c = createAccountAddress('Invoice Address', 'Billing', loggedInUser);
                    }
                }
                if (opp.ShippingAddress__c == null)
                {
                    id shippingAcctAddress = findAddressId('Shipping Address', addressesOfVar);
                    if (shippingAcctAddress != null)
                    {
                        opp.ShippingAddress__c = shippingAcctAddress;
                    }
                    else
                    {
                        opp.ShippingAddress__c = createAccountAddress('Shipping Address', 'Shipping', loggedInUser);
                    }
                }
            }
        }

    }
    

    public User loggedInUser
    {
        get
        {
            if (loggedInUser == null)
            {
                loggedInUser = [select id, profile.name, contactid, contact.accountid, contact.account.billingaddress, contact.account.shippingAddress, contact.account.phone from user where id =: userInfo.getUserId()];
            }
            return loggedInUser;
        }
        set;
    }
    private boolean isUserRoadnetPartner
    {
        get
        {
            
            return loggedInUser != null &&
              loggedInUser.profile.id != null &&
              loggedInUser.profile.name == 'Roadnet Partner Community User';
              
        }
    }
    private static id findAddressId(string locationType, List<Address__c> addresses)
    {
    	
        for (Address__c add : addresses)
        {
            if (add.Location_Type__c == locationType)
            {
                return add.id;
            }
        }
        return null;
    }
    private static id createAccountAddress(string locationType, string addressType, User u)
    {
        Address__c tempAdd = new Address__c();
        //  the address is a struct, we need to find the property names of the address to be able assing the variour fields on the 
        // custom object
        if (addressType == 'Billing')
        {
            tempAdd.Account__c = u.Contact.Accountid;
            tempAdd.Address_Line_1__c = u.Contact.Account.BillingAddress.getStreet();
            tempAdd.city__c = u.Contact.Account.billingAddress.getCity();
            tempAdd.country__c = u.Contact.Account.billingAddress.getCountry();
            tempAdd.Location_Type__c = locationType;
            tempAdd.phone_number__c = u.Contact.account.phone;
            tempAdd.State_province__c = u.Contact.Account.billingAddress.getState();
            tempAdd.Zip_postal_code__c = u.Contact.Account.billingAddress.getPostalCode();
        }
        else//  other address type is shipping
        {
            tempAdd.Account__c = u.Contact.Accountid;
            tempAdd.Address_Line_1__c = u.Contact.Account.ShippingAddress.getStreet();
            tempAdd.city__c = u.Contact.Account.ShippingAddress.getCity();
            tempAdd.country__c = u.Contact.Account.ShippingAddress.getCountry();
            tempAdd.Location_Type__c = locationType;
            tempAdd.phone_number__c = u.Contact.account.phone;
            tempAdd.State_province__c = u.Contact.Account.ShippingAddress.getState();
            tempAdd.Zip_postal_code__c = u.Contact.Account.ShippingAddress.getPostalCode();
        }
        
        database.insert(tempAdd);
        
        if (tempAdd != null && tempAdd.id != null)
        {
            return tempAdd.id;
        }
        return null;
    }
    
    public static void testMethodTestForPrivateStatics()
    {
    	Address__c[] testAddressList = [select id, location_type__c from Address__c limit 2];
    	id testId = findAddressId('Coporate HQ', testAddressList);
    	User testPartnerUser = [select id, profile.name, contactid, contact.accountid, contact.account.billingaddress, 
    	   contact.account.shippingAddress, contact.account.phone from user where Profile.name = 'Roadnet Partner Community User' and contactid != null limit 1];
    	id testAddress = createAccountAddress('Coporate HQ', 'Billing', testPartnerUser);
    	system.assertNotEquals(null, testAddress);
    	testAddress = createAccountAddress('Coporate HQ', 'Shipping', testPartnerUser);
    	system.assertNotEquals(null, testAddress);
    }
    
    
}