force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Created for Contract Management.</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional Party Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Additional Party Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Contract Specific Address</fullName>
            </value>
            <value>
                <fullName>Express Mail Address</fullName>
            </value>
            <value>
                <fullName>Invoice Address</fullName>
            </value>
            <value>
                <fullName>Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Pricing Notice Address</fullName>
            </value>
            <value>
                <fullName>Government Specific Address</fullName>
            </value>
            <value>
                <fullName>Remit to Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Corporate HQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Created for Contract Management.</description>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/Service_Agreement_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Service Agreement Adjustment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Agreement Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreement Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/account_Id__c.field-meta.xml
<CustomField>
    <fullName>account_Id__c</fullName>
    <description>Used to populate in the opportunity</description>
    <formula>Contract__r.Account.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Agreement Adjustments</relationshipLabel>
    <relationshipName>Service_Agreement_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Contact_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address_1__c</fullName>
    <description>Account Address Line 1 where Location Type = &apos;Corporate HQ&apos;</description>
    <label>Contact Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Contact_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address_2__c</fullName>
    <description>Account Address (City, State, Zip) where Location Type = &apos;Corporate HQ&apos;</description>
    <label>Contact Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceAgreementAdjustmentNotification.cls
/* Date : 6/25/2015
   Author : Abhishek Dey
   Functionality :
    This apex code will 
      -fetch specific contact records from the account associated with the contact for Service Agreement Adjustment(SAA) records
      -fetch specicic account address from the account associated with the contact for Service Agreement Adjustment(SAA) records
    the details will be added back to the SAA records
*/    

global class ServiceAgreementAdjustmentNotification {
  @InvocableMethod(label='Send Email')
  global static void sendEmail(List<Service_Agreement_Adjustment__c> serviceAgreementRequests) {
  
    list<id> lstSAAMapping = new list<id>();
    Map<id,id> accountMapping = new Map<id,id>();
    Map<id,id> sAAContactMapping = new Map<id,id>();
    Map<id,Address__c> sAAAddressMapping = new Map<id,Address__c>();
    
    Map<id,Address__c> accountAddressMapping = new Map<id,Address__c>();
    list<Service_Agreement_Adjustment__c> lstUpdate = new list<Service_Agreement_Adjustment__c>();
    
    
    for (Service_Agreement_Adjustment__c request : serviceAgreementRequests) {
     
      lstSAAMapping.add(request.account_Id__c);  
    }
    
  
   for(account accountData :[select id ,(select id from contacts where Notification_Type__c includes ('Price Increase') limit 1),
                                            (select  Account__c, id,Address_Line_1__c,
                                             Address_Line_2__c,
                                             City__c,
                                             State_Province__c,
                                             Zip_Postal_Code__c
                                             from Addresses__r where Location_Type__c = 'Corporate HQ' OR Location_Type__c = 'Notice Address - Primary' limit 1) 
                                             
                                             from account where id IN :lstSAAMapping ])
    {
      if(!accountData.contacts.isEmpty())
      {
      accountMapping.put(accountData.id,accountData.contacts[0].id);
      }
      if(!accountData.Addresses__r.isEmpty())
     {
       accountAddressMapping.put(accountData.id,accountData.Addresses__r[0]);
     }
    }
   
    
    for( Service_Agreement_Adjustment__c updateSAA : serviceAgreementRequests )
    {
        if(accountMapping.containsKey(updateSAA.account_Id__c))
        sAAContactMapping.put(updateSAA.id,accountMapping.get(updateSAA.account_Id__c));
        
        if(accountAddressMapping.containsKey(updateSAA.account_Id__c))
        sAAAddressMapping.put(updateSAA.id,accountAddressMapping.get(updateSAA.account_Id__c));
        
    }   
    
    for( Service_Agreement_Adjustment__c updateSAA : serviceAgreementRequests )
    {
        if((sAAContactMapping.containsKey(updateSAA.id))||(sAAAddressMapping.containskey(updateSAA.id)))
        {
                String address = '';
                Service_Agreement_Adjustment__c upsertSAA = new Service_Agreement_Adjustment__c(id= updateSAA.id);
            
            
            if(sAAContactMapping.containsKey(updateSAA.id))
            {
                upsertSAA.Contact__c = sAAContactMapping.get(updateSAA.id);
            }
            
            if(sAAAddressMapping.containskey(updateSAA.id))
            {
                        Address__c updateViaAddress = new Address__c();
                        updateViaAddress = sAAAddressMapping.get(updateSAA.id);
                       
                        
                       // Abhishek Modified the logic of Contact Address 1 population based on case - # 2102606 
                        if((updateViaAddress.Address_Line_2__c != null)&&(updateViaAddress.Address_Line_2__c != ''))
                         {
                             upsertSAA.Contact_Address_1__c = updateViaAddress.Address_Line_1__c + ', ' + updateViaAddress.Address_Line_2__c ;
                             
                         }
                        else
                         {
                         upsertSAA.Contact_Address_1__c = updateViaAddress.Address_Line_1__c;
                         }
                     
                      
                         if(updateViaAddress.City__c != null)
                         {
                             address = updateViaAddress.City__c;
                         }
                         if(updateViaAddress.State_Province__c != null)
                         {
                             if (address != '')
                             address = address +', ' + updateViaAddress.State_Province__c;
                             else
                             address = updateViaAddress.State_Province__c;
                         }
                         if(updateViaAddress.Zip_Postal_Code__c != null)
                         {
                             if (address != '')
                             address = address + ' ' + updateViaAddress.Zip_Postal_Code__c ;
                             else
                             address = updateViaAddress.Zip_Postal_Code__c ;
                         }
                        
                        upsertSAA.Contact_Address_2__c = address;
            }
            
             lstUpdate.add(upsertSAA);
        }
    }   
    
    if(!lstUpdate.isEmpty())
    {
        upsert lstUpdate;
    }
   
  } 
  }