force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Created for Contract Management.</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ascension Island</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional Party Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Additional Party Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Contract Specific Address</fullName>
            </value>
            <value>
                <fullName>Express Mail Address</fullName>
            </value>
            <value>
                <fullName>Invoice Address</fullName>
            </value>
            <value>
                <fullName>Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Pricing Notice Address</fullName>
            </value>
            <value>
                <fullName>Government Specific Address</fullName>
            </value>
            <value>
                <fullName>Remit to Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Corporate HQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Created for Contract Management.</description>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VCG_CPQ_QuoteAddressTest.cls
@isTest(SeeAllData=True)
private class VCG_CPQ_QuoteAddressTest {
    
    static testmethod void runTest() {
        
        //
        // Set up test records - account, opp, etc.
        //
        Account acct = new Account( Name = 'Test Account' );
        insert acct;
        
        // Added RecordType and StageName ='Sales Acceptance'
        Id oldProdRecType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Products, Services and Maintenance').getRecordTypeId();
        
        Opportunity opp = new Opportunity (
                                            Name = 'Test Opp',
                                            AccountId = acct.Id,
                                            RecordTypeId = oldProdRecType,
                                            CloseDate = Date.today().addDays(30),
                                            StageName = 'Sales Acceptance'
                                        );
        insert opp;
        
        
        Test.startTest(); // Do startTest() here to reset limits
        //
        // Now, set up the page parameters and call the QuoteAddress Controller
        //
        PageReference pageRef = Page.VCG_CPQ_QuoteAddress;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('oppid', opp.id);
        
        
        VCG_CPQ_QuoteAddress qa = new VCG_CPQ_QuoteAddress(new ApexPages.StandardController(opp));
        qa.bypassValidation = false;
        qa.next();
        
        Address__c invoice_addr = new Address__c(Account__c = opp.AccountId
                                               , Address_Line_1__c = 'x'
                                               , City__c = 'LA'
                                               , State_Province__c = 'CA'
                                               , Country__c = 'United States'
                                               , Zip_Postal_Code__c = '90210'
                                               , Location_Type__c = 'Invoice Address');
        insert invoice_addr;
        
        Address__c corporate_addr = new Address__c(Account__c = opp.AccountId
                                                 , Address_Line_1__c = 'x'
                                                 , City__c = 'LA'
                                                 , State_Province__c = 'CA'
                                                 , Country__c = 'United States'
                                                 , Zip_Postal_Code__c = '90210'
                                                 , Location_Type__c = 'Corporate HQ');
        insert corporate_addr;
        
        qa.opp.Corporate_Account_Address__c = corporate_addr.Id;
        qa.opp.Invoice_Account_Address__c = invoice_addr.Id;
        
        //  call the new roadnet parnter code
        system.assertNotEquals(null, qa.loggedInuser);
        qa.verifyUserIsRoadnetPartnerVar();
        qa.prepopOpptAddressFields();
        
        VCG_CPQ_QuoteAddress.testMethodTestForPrivateStatics();
        //  end tests for new roadnet aprtner code
        qa.next();
        
        Test.stopTest();
        
    }
    
}