force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Created for Contract Management.</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>Contracted Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracted Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracted Assets</relationshipLabel>
    <relationshipName>Contracted_Assets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/License_Metric_Quantity__c.field-meta.xml
<CustomField>
    <fullName>License_Metric_Quantity__c</fullName>
    <inlineHelpText>Quantity of licenses purchased at the time of contract.</inlineHelpText>
    <label>Contracted Licenses</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracted Assets</relationshipLabel>
    <relationshipName>Contracted_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <inlineHelpText>Contract Term in Months</inlineHelpText>
    <label>Contract Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Quote Valid Until</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <label>Price List</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Quote Valid From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteContractTest.cls
/*********************************************************************************
Program:        Test Class for QuoteContract Class
Programmer:     Rex David - CloudSherpas
Date:           Oct 02, 2014
**********************************************************************************/ 
@isTest (seeAllData = true)
//create 
//product
//contracted asset 
//quote
private class QuoteContractTest {
    public static List<Account> accountInstance = new List<Account>();
    public static List<Opportunity> lOpportunityInstance = new List<Opportunity>();
    public static List<Product2> lProductInstance   =   new List<Product2>();
    public static List<Asset__c> lContractedAssetInstance   =   new List<Asset__c>();
    public static List<VCG_CPQ_Quote__c> lVCGCPQQuoteInstance   =   new List<VCG_CPQ_Quote__c>();
    public static List<Address__c> lAddressInstance  =   new List<Address__c>();
    
    static{
        Schema.DescribeSObjectResult acccfrSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = acccfrSchema.getRecordTypeInfosByName();
        Map<String,Schema.RecordTypeInfo> opptyRecTypeInfo = Schema.SObjectType.Opportunity.getRecordTypeInfosByName();
        Id accountRtId = AccountRecordTypeInfo .get('T&L Sales Accounts').getRecordTypeId();
        
        Schema.DescribeSObjectResult oppcfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> OpportunityRecordTypeInfo = oppcfrSchema.getRecordTypeInfosByName();
        Id opportunityRtId = OpportunityRecordTypeInfo .get('Products, Services and Maintenance').getRecordTypeId();
        
        for(Integer i=0; i<2; i++){
            Account tempaccountInstance     =   new Account(    Name    =   'testAccount'+i,
                                                    Phone   =   '12345',
                                                    Account_Classification__c   =   'Prospect',
                                                    Account_Status__c   =   'Active',
                                                    Account_Type__c =   'Association',
                                                    recordtypeid    =   accountRtId   
                                            );
            accountInstance.add(tempaccountInstance);
        }
        //try{
            insert accountInstance;         
        /*}
        catch(Exception e){
            System.debug('ERROR '+e);
        }*/
        for(Integer i=0; i<2; i++){
            Address__c add  =   new Address__c();
            add.Account__c  =   accountInstance[i].Id;
            add.Address_Line_1__c   =   'TestAddLine1'+i;
            add.Address_Line_2__c   =   'TestAddLine2'+i;
            add.City__c =   'TestAdd'+i;
            lAddressInstance.add(add);
        }
        //try{
            insert lAddressInstance;
        /*}
        catch(Exception e){
            System.debug('ERROR '+e);
        }*/
                
        for(Integer i=0; i<2; i++){
            Opportunity opp =   new Opportunity();
            opp.Name    =   'testOpp'+i;
            opp.AccountId   =   accountInstance[i].Id;
            opp.CloseDate   =   date.today();
            opp.StageName   =   'Sales Acceptance';
            opp.CurrencyIsoCode =   'USD';
            opp.Type    =   'Existing Customer';
            opp.Sponsor_Letter_Attached__c = true;
            //opp.Sponsor__c = testContact.Id;
            opp.Order_Type__c   =   'Transfer';
            
            if (opptyRecTypeInfo.containsKey('Partner Opportunity (Reseller)')){
                opp.recordtypeid = opptyRecTypeInfo.get('Partner Opportunity (Reseller)').getRecordtypeid();
            }
            lOpportunityInstance.add(opp);
        }
       // try{
            insert lOpportunityInstance;
        /*}
        catch(Exception e){
            System.debug('ERROR '+e);
        }*/
        system.debug('***TESTlOpportunityInstance'+lOpportunityInstance.size());
        for(Integer i=0; i<lOpportunityInstance.size(); i++){
            System.debug('***TESTIteratelOpportunityInstance '+lOpportunityInstance[i].Name);
        }
        
        for(Integer i=0; i<2; i++){
            Product2 prod    =   new Product2();
            prod.Name   =   'testProd'+i;
            prod.CurrencyIsoCode    =   'USD';
            lProductInstance.add(prod);
        }
        //try{
            insert lProductInstance;
        /*}
        catch(Exception e){
            System.debug('ERROR '+e);
        }*/
        for(Integer i=0; i<2; i++){
            Asset__c ass    =   new Asset__c();
            ass.Name    =   'testAss'+i;
            ass.Account__c  =   accountInstance[i].Id;
            ass.CurrencyIsoCode =   'USD';
            ass.License_Metric_Quantity__c  =   1;
            ass.Product__c  =   lProductInstance[i].Id;
            lContractedAssetInstance.add(ass);
        }
        //try{
            insert lContractedAssetInstance;
       /* }
        catch(Exception e){
            System.debug('ERROR '+e);
        }*/
        for(Integer i=0; i<2; i++){
            VCG_CPQ_Quote__c quo    =   new VCG_CPQ_Quote__c();
            quo.Status__c   =   'Draft';
            quo.Account__c  =   accountInstance[i].Id;
            quo.Opportunity__c    =   lOpportunityInstance[i].Id;
            quo.CurrencyIsoCode =   'USD';
            quo.Price_List__c   =   '2014';
            quo.Start_Date__c   =   date.today();
            quo.Expiration_Date__c  =   date.today();
            quo.Effective_Date__c   =   date.today();
            quo.Contract_Term__c    =   36;
            lVCGCPQQuoteInstance.add(quo);
        }
        //try{
            insert lVCGCPQQuoteInstance;
        /*}
        catch(Exception e){
            System.debug('ERROR '+e);
        }*/
        
    }
    private static testMethod void testQuoteContract() {
        system.debug('entered method');
        List<VCG_CPQ_Quote__c> lVCGCPQQuoteInstanceTemp   = new List<VCG_CPQ_Quote__c>();
        for(VCG_CPQ_Quote__c quo : lVCGCPQQuoteInstance){
            VCG_CPQ_Quote__c vquo = new VCG_CPQ_Quote__c();
            vquo.Id  =  quo.Id;
            vquo.Status__c   =   'Approved';
            lVCGCPQQuoteInstanceTemp.add(vquo);
        }
    
        //try{
            update lVCGCPQQuoteInstanceTemp;
            
            //Update opportunity stage to Negotiate
            for(Opportunity oppty : lOpportunityInstance){
                oppty.StageName = 'Negotiate';
            }
            update lOpportunityInstance;
            Opportunity testOpp = [select id, StageName, Primary_Quote_Approval_Status__c from Opportunity where id IN :lOpportunityInstance limit 1];
            system.debug('testOpp: ' + testOpp);
            
            
        /*}
        catch(Exception e){
            System.debug('ERROR '+e);
        }*/
    }
}