force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>Created for Contract Management.</description>
    <label>Account Address</label>
    <nameField>
        <displayFormat>ADR-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Created for Contract Management.</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <description>Created for Contract Management.</description>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Created for Contract Management.</description>
    <label>Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that appears in output</description>
    <inlineHelpText>Contact that appears in output</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quote_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Invoice_Address__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Address__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Invoice Address (Required)</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Address__c.Location_Type__c</field>
            <operation>equals</operation>
            <value>Invoice Address</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>InvoiceAddress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/ShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Address</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Address__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Address__c</referenceTo>
    <relationshipName>ShippingShipping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/salesInfoXRSQuotes.cls
/*@@@ Created by Arindam Laik, Aug 27 2015
  @@@ This class is used by 'XRS: Sales Information from XRS Quotes' VF template
*/
public class salesInfoXRSQuotes{
public String OpportunityId{get;set;}
public String OpportunityOwnerName{get;set;}
public String OpportunityOwnerEmail{get;set;}

Public String baseURL
{
   get
   {
       baseURL = URL.getSalesforceBaseUrl().toExternalForm();
       return baseURL;
   }
   set;
}       

public VCG_CPQ_Quote__c objQuote
{
    get
    {
        List<VCG_CPQ_Quote__c> lstQuote = new List<VCG_CPQ_Quote__c>();
        objQuote = new VCG_CPQ_Quote__c();
        lstQuote =[SELECT Name,ShippingAddress__r.Address_Line_1__c,ShippingAddress__r.Address_Line_2__c,
                   ShippingAddress__r.City__c,ShippingAddress__r.State_Province__c,ShippingAddress__r.Zip_Postal_Code__c,
                   Invoice_Address__r.Address_Line_1__c,Invoice_Address__r.Address_Line_2__c,Invoice_Address__r.City__c,
                   Invoice_Address__r.State_Province__c,Invoice_Address__r.Zip_Postal_Code__c
                   FROM VCG_CPQ_Quote__c WHERE Opportunity__c =: this.OpportunityId AND Is_Primary__c = true LIMIT 1];
        
        if (!lstQuote.isEmpty())
        {
            objQuote = lstQuote[0];
        }
        return objQuote;
    }
    set;
}
public List<opportunityLineItem> lstOpportunityProduct
{
    get
    {
        lstOpportunityProduct = new List<opportunityLineItem>();
        lstOpportunityProduct = [SELECT Product2.Name, Quantity, ProductCode FROM opportunityLineItem WHERE OpportunityId =: this.OpportunityId
                                 AND Product2.Product_Type__c = 'Hardware'  and Line_Type__c != 'Decommission' LIMIT 50000];
        
        return lstOpportunityProduct;
    }
    set;
}
public opportunity objOpportunity
{
    get
    {
        List<opportunity> lstOpportunity = new List<opportunity>();
        List<user> lstUser = new List<User>();
        lstOpportunity = [SELECT Id, Name,Ownerid, Account.Name, Account.QWBS_Cust_ID__c, Host_Information__r.Host_Company_ID__c, Send_XRS_Shipment_Request__c,
                          Freight_Method__c,Host_Company_Id__c,Contact__r.Name, Contact__r.Phone, Contact__r.email FROM opportunity WHERE Id =: this.OpportunityId LIMIT 1];
        
        if(!lstOpportunity.isEmpty())
        {
            objOpportunity = lstOpportunity[0];
            lstUser = [select name , email from user where id =: lstOpportunity[0].Ownerid limit 1];
            
            if(!lstUser.isEmpty())
            {
                OpportunityOwnerName = lstUser[0].name;
                OpportunityOwnerEmail = lstUser[0].email;
            }
            
            
        }
        return objOpportunity;
    }
    set;
}
}