force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>User Stories capture initial, high-level objectives and outcomes that are desired. 

User Stories captures what a user does or needs to do as part of his or her job function.

User Stories captures the &apos;who&apos;, &apos;what&apos; and &apos;why&apos; of a requirement in a simple, concise way.

User Stories serve as the foundation from which all requirements will be built off of.</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Req. ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/User_Story_Requirement__c.object-meta.xml
<CustomObject>
    <label>User Story Requirement</label>
    <nameField>
        <displayFormat>USR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story_Requirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <referenceTo>Requirements__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements1</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story_Requirement__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Requirements</relationshipLabel>
    <relationshipName>User_Story_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewRequirement_Ctrl_Test.cls
@isTest
public class NewRequirement_Ctrl_Test{

    public static testMethod void testSave(){
        User_Story__c testUsrSty = new User_Story__c();
        insert testUsrSty;
        PageReference testPage = new PageReference('/apex/NewRequirement?id=' + testUsrSty.id);
        Test.startTest();
            Test.setCurrentPage(testPage);
            NewRequirement_Ctrl controller = new NewRequirement_Ctrl();
            controller.req.Title__c = 'Test Requirement';
            controller.save();
        Test.stopTest();
        
        System.assertEquals(1,[SELECT id, Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c = :testUsrSty.Id].size());
    }
    
    public static testMethod void testSaveAndNew(){
        User_Story__c testUsrSty = new User_Story__c();
        insert testUsrSty;
        PageReference testPage = new PageReference('/apex/NewRequirement?id=' + testUsrSty.id);
        Test.startTest();
            Test.setCurrentPage(testPage);
            NewRequirement_Ctrl controller = new NewRequirement_Ctrl();
            controller.req.Title__c = 'Test Requirement';
            controller.saveAndNew();
        Test.stopTest();
        
        System.assertEquals(1,[SELECT id, Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c = :testUsrSty.Id].size());
    }
    
    public static testMethod void testCancel(){
        User_Story__c testUsrSty = new User_Story__c();
        insert testUsrSty;
        PageReference testPage = new PageReference('/apex/NewRequirement?id=' + testUsrSty.id);
        Test.startTest();
            Test.setCurrentPage(testPage);
            NewRequirement_Ctrl controller = new NewRequirement_Ctrl();
            controller.req.Title__c = 'Test Requirement';
            controller.cancel();
        Test.stopTest();
        
        System.assertEquals(0,[SELECT id, Requirement__c FROM User_Story_Requirement__c WHERE User_Story__c = :testUsrSty.Id].size());
    }
}