force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting for State Name as key and State code as value.</description>
    <label>State</label>
</CustomObject>

force-app/main/default/objects/TIS_Detail_Opp_Lead__c/TIS_Detail_Opp_Lead__c.object-meta.xml
<CustomObject>
    <description>Capture time state details of lead and opportunity</description>
    <label>Time and State Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time and State Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TIS_Detail_Opp_Lead__c/fields/Date_Time_In__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_In__c</fullName>
    <label>Date/Time In</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TIS_Detail_Opp_Lead__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <formula>IF(Days__c&gt;0,TEXT( Days__c ) &amp; &apos; Days &apos; ,&apos;&apos;)&amp; TEXT ( MOD (Hrs__c , 24 ) ) &amp; &apos; Hours &apos; &amp; TEXT (Mins__c) &amp; &apos; Minutes&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TIS_Detail_Opp_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Time and State Details</relationshipLabel>
    <relationshipName>Time_and_State_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TIS_Detail_Opp_Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Time and State Details</relationshipLabel>
    <relationshipName>Time_and_State_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TIS_Detail_Opp_Lead__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <description>name of the owner forlead/opportunty</description>
    <label>Owner</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TIS_Detail_Opp_Lead__c/fields/Who__c.field-meta.xml
<CustomField>
    <fullName>Who__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Who</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_and_State_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ViewTISController.cls
public class ViewTISController {

    public String state {get; set;}
    private Static String OPP_PREFIX = '006';
    private Static String LEAD_PREFIX = '00Q';
    private String oppRecId;
    private String leadRecId;
    Public boolean showDetail {get; set;}
    public List<SelectOption> OptionsList{get; set;}
    public list<TIS_Detail_Opp_Lead__c> TISDetail {get; set;}
    
    public ViewTISController(ApexPages.StandardController controller) {
        String recordId = Apexpages.currentPage().getParameters().get('Id');
        system.debug('@@@@recordId'+recordId);
        if(recordId != null && recordId.startsWith(OPP_PREFIX))
            oppRecId = recordId;
        else
            leadRecId = recordId;
             
        system.debug('@@@@oppRec:::'+ oppRecId);
        ShowDetail = true;
        OptionsList = new List<SelectOption>();
        calculateOptionsList();
    }
        
    public List<SelectOption> calculateOptionsList(){
        Set<String> fieldNameList = new Set<String>();
        fieldNameList.add('Owner');
        state = 'Owner';
        OptionsList.add(new SelectOption('Owner','Owner'));
        if(oppRecId != null){
            for (TIS_Detail_Opp_Lead__c TIS :[select name from TIS_Detail_Opp_Lead__c where Opportunity__c =:oppRecId and name !='Owner' limit 1000])
            {
                System.debug('There are Field Names in TIS_Detail_Opp_Lead__c table other than "Owner"');
                if (!FieldNameList.contains(TIS.name))
                {
                    System.debug('@@Add new record:"'+TIS.name+'" in the list');
                    FieldNameList.add(TIS.name);
                    OptionsList.add(new SelectOption(TIS.name,TIS.name));
                }
            
            }
        }
        else{
            for (TIS_Detail_Opp_Lead__c TIS :[select name from TIS_Detail_Opp_Lead__c where lead__c =:leadRecId and name !='Owner' limit 1000])
            {
                System.debug('There are Field Names in TIS_Detail_Opp_Lead__c table other than "Owner"');
                if (!FieldNameList.contains(TIS.name))
                {
                    System.debug('@@Add new record:"'+TIS.name+'" in the list');
                    FieldNameList.add(TIS.name);
                    OptionsList.add(new SelectOption(TIS.name,TIS.name));
                }
            
            }
               
        }
        return OptionsList;
        
    }
    
    public void showTISDetail()
    {
        System.debug('State====>'+ State);
        system.debug('opportunity Number:'+oppRecId);
        if(oppRecId != null)
            TISDetail = [Select 
                                Date_Time_In__c,
                                Date_Time_Out__c,
                                Duration__c,
                                Owner__c,
                                State__c,
                                Who__c
                         from 
                                 TIS_Detail_Opp_Lead__c
                         where 
                                 Name =:State
                         and 
                                 Opportunity__c =:oppRecId
                         order by Date_Time_In__c desc];
        else{             
        TISDetail = [Select 
                            Date_Time_In__c,
                            Date_Time_Out__c,
                            Duration__c,
                            Owner__c,
                            State__c,
                            Who__c
                     from 
                             TIS_Detail_Opp_Lead__c
                     where 
                             Name =:State
                     and 
                             Lead__c =:leadRecId
                     order by Date_Time_In__c desc ];
        }
        system.debug('TISDetail List:'+TISDetail);
       
    }
    
    

}