force-app/main/default/objects/Product_Contract_Template__c/Product_Contract_Template__c.object-meta.xml
<CustomObject>
    <label>Product Contract Template</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Contract Templatess</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Contract_Template__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Attached Agreement</fullName>
            </value>
            <value>
                <fullName>Statement of Work (SOW)</fullName>
            </value>
            <value>
                <fullName>Addendum</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Contract_Template__c/fields/Contract_Category_1__c.field-meta.xml
<CustomField>
    <fullName>Contract_Category_1__c</fullName>
    <label>Contract Category 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Asset Tracking</fullName>
            </value>
            <value>
                <fullName>Click-Thru Global Apps</fullName>
            </value>
            <value>
                <fullName>Critical Event Video</fullName>
            </value>
            <value>
                <fullName>Dom. Perpetual</fullName>
            </value>
            <value>
                <fullName>Dom. Term</fullName>
            </value>
            <value>
                <fullName>Global Application Terms</fullName>
            </value>
            <value>
                <fullName>IVG</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>MCP100S</fullName>
            </value>
            <value>
                <fullName>MCP100S (UVP)</fullName>
            </value>
            <value>
                <fullName>MCP100T</fullName>
            </value>
            <value>
                <fullName>MCP100T (UVP)</fullName>
            </value>
            <value>
                <fullName>MCP110</fullName>
            </value>
            <value>
                <fullName>MCP110 (UVP)</fullName>
            </value>
            <value>
                <fullName>MCP200</fullName>
            </value>
            <value>
                <fullName>MCP200 (UVP)</fullName>
            </value>
            <value>
                <fullName>MCP50</fullName>
            </value>
            <value>
                <fullName>PPS (Predictive Performance Service)</fullName>
            </value>
            <value>
                <fullName>Product Evaluation</fullName>
            </value>
            <value>
                <fullName>Pro Svcs</fullName>
            </value>
            <value>
                <fullName>RN SaaS</fullName>
            </value>
            <value>
                <fullName>RN Telematics/SaaS (Lease)</fullName>
            </value>
            <value>
                <fullName>RN Telematics/SaaS (Purchase)</fullName>
            </value>
            <value>
                <fullName>RN Telematics (Lease)</fullName>
            </value>
            <value>
                <fullName>RN Telematics (Purchase)</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
            <value>
                <fullName>Sylectus</fullName>
            </value>
            <value>
                <fullName>TT150</fullName>
            </value>
            <value>
                <fullName>TT210</fullName>
            </value>
            <value>
                <fullName>Untethered Asset Management</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Contract_Template__c/fields/Contract_Category_2__c.field-meta.xml
<CustomField>
    <fullName>Contract_Category_2__c</fullName>
    <label>Contract Category 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accident Severity</fullName>
            </value>
            <value>
                <fullName>Advanced Mapping Interface</fullName>
            </value>
            <value>
                <fullName>AMBER Alert</fullName>
            </value>
            <value>
                <fullName>Analytics Manager</fullName>
            </value>
            <value>
                <fullName>Application Contingency</fullName>
            </value>
            <value>
                <fullName>BoBo</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Content Delivery</fullName>
            </value>
            <value>
                <fullName>CoPilot Truck</fullName>
            </value>
            <value>
                <fullName>Critical Event Reporting</fullName>
            </value>
            <value>
                <fullName>Critical Event Video</fullName>
            </value>
            <value>
                <fullName>Driver Fatigue</fullName>
            </value>
            <value>
                <fullName>Driver Recruiting</fullName>
            </value>
            <value>
                <fullName>Driver Retention</fullName>
            </value>
            <value>
                <fullName>Driver Risk (Workers Comp)</fullName>
            </value>
            <value>
                <fullName>Driver Safety</fullName>
            </value>
            <value>
                <fullName>Driver Workflow</fullName>
            </value>
            <value>
                <fullName>DTTS (In-Cab)</fullName>
            </value>
            <value>
                <fullName>DTTS (Trailer)</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
            <value>
                <fullName>Evaluation (Special Program)</fullName>
            </value>
            <value>
                <fullName>Exact Fuel</fullName>
            </value>
            <value>
                <fullName>Extended Productivity</fullName>
            </value>
            <value>
                <fullName>Fault Monitoring</fullName>
            </value>
            <value>
                <fullName>Fault Monitoring + Ext. Faults</fullName>
            </value>
            <value>
                <fullName>FM Extended Faults</fullName>
            </value>
            <value>
                <fullName>Hours of Service</fullName>
            </value>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>In-Cab Scanning</fullName>
            </value>
            <value>
                <fullName>Indirect</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Media Manager</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Contract_Template__c/fields/Contract_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Contract_Template_Id__c</fullName>
    <label>Contract Template Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Contract_Template__c/fields/Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Template_Type__c</fullName>
    <label>Template Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Output Eval Template</fullName>
            </value>
            <value>
                <fullName>Output MSA Template</fullName>
            </value>
            <value>
                <fullName>Output Schedule Template</fullName>
            </value>
            <value>
                <fullName>Output Standard SOW Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/MSA_Documents__c.field-meta.xml
<CustomField>
    <fullName>MSA_Documents__c</fullName>
    <inlineHelpText>GUIDs for MSA Documents generated by Drawloop.</inlineHelpText>
    <label>MSA Documents</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores this Quotes Lookup for use in mapping to the Opportunity for the Primary Quote</description>
    <label>Quote ***</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/VCG_CPQ_Quote_Product__c.object-meta.xml
<CustomObject>
    <description>An individual line item on a quote</description>
    <label>Quote Product</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteUtility_Test.cls
/**
 * Unit tests for QuoteUtility class
 *
 * @author  Lawrence Coffin <lawrence.coffin@cloudsherpas.com>
 * @since   1.Dec.2014
 */
@isTest(SeeAllData=True)
private class QuoteUtility_Test {
    
    /**
     * Test QuoteUtility.setMSADocIds() basic functionality
     *
     * @author  Lawrence Coffin <lawrence.coffin@cloudsherpas.com>
     * @since   1.Dec.2014
     */
    static testMethod void testSetMSADocIds() {
        //
        // create the Product Contract Template Objects
        //
        list<Product_Contract_Template__c> pdt 
           = new list<Product_Contract_Template__c>{
             new Product_Contract_Template__c ( Template_Type__c = 'Output MSA Template'
                                               ,Status__c        = 'Active'
                                               ,Name             = 'Omnitracs Master Contract for Equipment Software and Service'
                                               ,Description__c   = 'Test'
                                               ,Contract_Template_Id__c = '01550000001Qbby'
                                               ,Contract_Category_2__c  = 'Production'
                                               ,Contract_Category_1__c  = 'Master'
                                               ,Agreement_Type__c       = 'Master'),
             new Product_Contract_Template__c ( Template_Type__c = 'Output Schedule Template'
                                               ,Status__c        = 'Active'
                                               ,Name             = 'Omnitracs PSA Contract for Equipment Software and Service'
                                               ,Description__c   = 'Test'
                                               ,Contract_Template_Id__c = '01550000001QbgT'
                                               ,Contract_Category_2__c  = 'Advanced Mapping Interface'
                                               ,Contract_Category_1__c  = 'Global Application Terms'
                                               ,Agreement_Type__c       = 'Attached Agreement'),
             new Product_Contract_Template__c ( Template_Type__c = 'Output Schedule Template'
                                               ,Status__c        = 'Active'
                                               ,Name             = 'MCP100S Schedule'
                                               ,Description__c   = 'Test'
                                               ,Contract_Template_Id__c = '01550000001jJJy'
                                               ,Contract_Category_2__c  = 'Production'
                                               ,Contract_Category_1__c  = 'MCP100S'
                                               ,Agreement_Type__c       = 'Schedule'),
             new Product_Contract_Template__c ( Template_Type__c = 'Output Standard SOW Template'
                                               ,Status__c        = 'Active'
                                               ,Name             = 'Media Manager Service Application'
                                               ,Description__c   = 'Test'
                                               ,Contract_Template_Id__c = '01550000001QbgR'
                                               ,Contract_Category_2__c  = 'Media Manager'
                                               ,Contract_Category_1__c  = 'Global Application Terms'
                                               ,Agreement_Type__c       = 'Attached Agreement')};
        
        insert pdt;
        
        //
        // Add some products with various MSA template ids (use dummy Ids for now)
        //
        Product2 prod1 = new Product2( Name = 'Test Product A', ProductCode = 'TEST-AAA', Output_MSA_Template__c = '0x0100000000001'
                                      ,Output_MSA_Document_Template__c =pdt.get(0).Id
                                      ,Output_PSA_Document_Template__c =pdt.get(1).Id
                                      ,Output_Standard_SOW_Document_Template__c =pdt.get(3).Id
                                      ,Output_Schedule_Document_Template__c     =pdt.get(2).Id);
        Product2 prod2 = new Product2( Name = 'Test Product B', ProductCode = 'TEST-BBB', Output_MSA_Template__c = '0x0100000000002');
        Product2 prod3 = new Product2( Name = 'Test Product C', ProductCode = 'TEST-CCC', Output_MSA_Template__c = '0x0100000000003AAB');
        Product2 prod4 = new Product2( Name = 'Test Product D', ProductCode = 'TEST-DDD', Output_MSA_Template__c = '0x0100000000004');
        // use a product with a null value to confirm no blanks/empty values show up in the id list
        Product2 prod5 = new Product2( Name = 'Test Product E', ProductCode = 'TEST-EEE', Output_MSA_Template__c = null);
        
        insert new List<Product2>{ prod1, prod2, prod3, prod4, prod5 };
        
        System.assert(prod1.Id!=null,'prod1 Insertion Failed');
        System.assert(prod2.Id!=null,'prod2 Insertion Failed');
        System.assert(prod3.Id!=null,'prod4 Insertion Failed');
        System.assert(prod5.Id!=null,'prod5 Insertion Failed');
        
        
        
        List<Product2> lstProd1 = new List<Product2>();
        lstProd1.add(prod1);
        lstProd1.add(prod2);
        lstProd1.add(prod3);
        List<Product2> lstProd = [Select id,Output_MSA_Template__c from Product2 where id In : lstProd1];
        for(Product2 P: lstProd )
        {
            System.assert(P.Output_MSA_Template__c!=null,'Output_MSA_Template__c ');
        }
        //
        // Add an Account
        //
        Account acct = new Account( Name = 'Test Account' );
        insert acct;
       
        // Add an Opp
        //
        Opportunity opp = new Opportunity( Name = 'Test Opp', AccountId = acct.Id, StageName = 'Sales Acceptance', CloseDate = Date.today().addDays(7),Geo_Region__c='LATAM' );
        insert opp;
        System.assert(opp.Id!=null,'Quote Insertion Failed');
        //
        // Add a Quote
        //
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c( Opportunity__c = opp.Id, Account__c = acct.Id );
        insert quote;
        System.assert(quote.Id!=null,'Quote Insertion Failed');
        //
        // Add Quote Product records for the above products - skip prod4 to confirm that not all products are being included
        //
        VCG_CPQ_Quote_Product__c qpRec1 = new VCG_CPQ_Quote_Product__c( Quote__c = quote.Id, Product__c = prod1.Id );
        VCG_CPQ_Quote_Product__c qpRec2 = new VCG_CPQ_Quote_Product__c( Quote__c = quote.Id, Product__c = prod2.Id );
        VCG_CPQ_Quote_Product__c qpRec3 = new VCG_CPQ_Quote_Product__c( Quote__c = quote.Id, Product__c = prod3.Id );
        VCG_CPQ_Quote_Product__c qpRec5 = new VCG_CPQ_Quote_Product__c( Quote__c = quote.Id, Product__c = prod5.Id );
        insert new List<VCG_CPQ_Quote_Product__c>{ qpRec1, qpRec2, qpRec3, qpRec5 };
        
        QuoteUtility.generateContractDocumentIds(quote.Id);
        
        //
        // Confirm that the Quote MSA IDs field is set to the correct value
        //
        VCG_CPQ_Quote__c quoteCopy = [SELECT MSA_Documents__c FROM VCG_CPQ_Quote__c WHERE Id = :quote.Id][0];
        //System.assertNotEquals(null, quoteCopy.MSA_Documents__c);
        
        // Need to sort the list to make it easier to test (trigger code doesn't guarantee sort order)
        //List<String> quoteMSAsList = quoteCopy.MSA_Documents__c.split(',');
        //quoteMSAsList.sort();
        //System.assertEquals('0x0100000000001,0x0100000000002,0x0100000000003', String.join(quoteMSAsList, ','));
    }
}