force-app/main/default/objects/Source_Field__c/Source_Field__c.object-meta.xml
<CustomObject>
    <label>Source Field</label>
    <nameField>
        <displayFormat>SRC-{0000}</displayFormat>
        <label>Source ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Source_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <inlineHelpText>What is the user-friendly name of this field?</inlineHelpText>
    <label>Field Label</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source_Field__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Billing Detail</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Campaign Member</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Line Item</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source_Field__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sylectus Other</fullName>
            </value>
            <value>
                <fullName>Roadnet Salesforce</fullName>
            </value>
            <value>
                <fullName>FRA Other</fullName>
            </value>
            <value>
                <fullName>Omnitracs Salesforce</fullName>
            </value>
            <value>
                <fullName>Omnitracs Mexico Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source_Field__c/fields/System_Field__c.field-meta.xml
<CustomField>
    <fullName>System_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>System Field</label>
    <referenceTo>System_Field__c</referenceTo>
    <relationshipLabel>Source Fields</relationshipLabel>
    <relationshipName>Source_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Field__c/System_Field__c.object-meta.xml
<CustomObject>
    <description>MIBOS Requirements App: The fields that need to be configured to support requirements.</description>
    <label>System Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Field__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Field__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Campaign Member</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Case Comment</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Field__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Excel</fullName>
            </value>
            <value>
                <fullName>Great Plains</fullName>
            </value>
            <value>
                <fullName>MS Access</fullName>
            </value>
            <value>
                <fullName>MS CRM</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>SFDC (Legacy)</fullName>
            </value>
            <value>
                <fullName>SFDC (New)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ViewSystemField_Ext.cls
public class ViewSystemField_Ext {

    private System_Field__c f;
    
    public List<Source_Field__c> unassignedFields {get; set;}
    private List<Source_Field__c> assignedFields;
    
    public List<SelectOption> unassignedFieldsList {get; set;}
    public List<SelectOption> assignedFieldsList {get; set;}
    
    public List<SelectOption> filterOptions {get; set;}
    public List<SelectOption> filterOptions2 {get; set;}
    public String selectedFilter {get; set;}
    public String selectedFilter2 {get; set;}
    
    public Boolean canAccess {get; private set;}

    public ViewSystemField_Ext(ApexPages.StandardController std) {
        this.f = (System_Field__c)std.getRecord();
        
        //TODO: Store this ID in a Custom Setting or admin config
        List<PermissionSetAssignment> permSets = [SELECT Id FROM PermissionSetAssignment WHERE AssigneeId =: UserInfo.getUserId() AND PermissionSetId = '0PSR0000000CkJW'];
        if (permsets.size() == 1) {
            this.canAccess = true;
        }
        else {
            this.canAccess = false;
        }
        
        List<Schema.PicklistEntry> sourceValues = Source_Field__c.Source_System__c.getDescribe().getPicklistValues();
        filterOptions = new List<SelectOption>();
        //filterOptions.add(new SelectOption('All Sources', 'All Sources'));
        for (Schema.PicklistEntry pe : sourceValues) {
            filterOptions.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        if (filterOptions.size() > 0) {
            selectedFilter = filterOptions[0].getValue();
        }
        else {
            selectedFilter = 'All Sources';
        }
        
        List<Schema.PicklistEntry> sourceValues2 = Source_Field__c.Source_Object__c.getDescribe().getPicklistValues();
        filterOptions2 = new List<SelectOption>();
        //filterOptions2.add(new SelectOption('All Objects', 'All Objects'));
        for (Schema.PicklistEntry pe : sourceValues2) {
            filterOptions2.add(new SelectOption(pe.getValue(), pe.getLabel()));
        }
        if (filterOptions2.size() > 0) {
            selectedFilter2 = filterOptions2[0].getValue();
        }
        else {
            selectedFilter2 = 'All Objects';
        }
        
        unassignedFields = new List<Source_Field__c>();
        assignedFields = new List<Source_Field__c>();
        unassignedFieldsList = new List<SelectOption>();
        assignedFieldsList = new List<SelectOption>();
        
        //unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null ORDER BY Field_Name__c];
        
        if (selectedFilter != 'All Sources' && selectedFilter2 != 'All Objects') {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null AND Source_System__c =: selectedFilter AND Source_Object__c =: selectedFilter2];
        }
        else if (selectedFilter != 'All Sources' && selectedFilter2 == 'All Objects') {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null AND Source_System__c =: selectedFilter];
        }
        else if (selectedFilter == 'All Sources' && selectedFilter2 != 'All Objects') {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null AND Source_Object__c =: selectedFilter2];
        }
        else {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null];
        }

        assignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c =: this.f.id ORDER BY Field_Name__c];
    
        for (Source_Field__c sf : unassignedFields) {
            unassignedFieldsList.add(new SelectOption(sf.Id, sf.Field_Name__c));
        }
        
        for (Source_Field__c sf : assignedFields) {
            assignedFieldsList.add(new SelectOption(sf.Id, sf.Field_Name__c));
        }
        
        
    }

    public PageReference doSave() {
        Map<Id, Source_Field__c> fieldsToUpdateMap = new Map<Id, Source_Field__c>();
        
        // Determine Source Fields that have been assigned
        for (SelectOption sf : assignedFieldsList) {
            fieldsToUpdateMap.put(sf.getValue(), new Source_Field__c(Id = sf.getValue(), System_Field__c = this.f.Id));
        }
        
        // Determine if any Source Fields have been de-assigned
        for (Source_Field__c sf : [SELECT Id FROM Source_Field__c WHERE System_Field__c =: this.f.Id AND Id NOT IN :fieldsToUpdateMap.keySet()]) {
            fieldsToUpdateMap.put(sf.Id, new Source_Field__c(Id = sf.Id, System_Field__c = null));
        }
        
        if (fieldsToUpdateMap.values().size() > 0) {
            update fieldsToUpdateMap.values();
        }
        
        PageReference p = new PageReference('/apex/ViewSystemField?id=' + f.Id);
        p.setRedirect(true);
        
        return p;
    }

    public PageReference refreshFilter() {
        if (selectedFilter != 'All Sources' && selectedFilter2 != 'All Objects') {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null AND Source_System__c =: selectedFilter AND Source_Object__c =: selectedFilter2];
        }
        else if (selectedFilter != 'All Sources' && selectedFilter2 == 'All Objects') {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null AND Source_System__c =: selectedFilter];
        }
        else if (selectedFilter == 'All Sources' && selectedFilter2 != 'All Objects') {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null AND Source_Object__c =: selectedFilter2];
        }
        else {
            unassignedFields = [SELECT Id, Field_Name__c, Source_System__c FROM Source_Field__c WHERE System_Field__c = null];
        }
        
        this.unassignedFieldsList = new List<SelectOption>();
        for (Source_Field__c sf : unassignedFields) {
            Boolean found = false;
            for (SelectOption sf2 : assignedFieldsList) {
                if (sf2.getValue() == sf.Id) {
                    found = true;
                }
            }
            if (!found) {
                this.unassignedFieldsList.add(new SelectOption(sf.Id, sf.Field_Name__c));
            }
        }
        
        return null;
    }

}