force-app/main/default/objects/Source_Field__c/Source_Field__c.object-meta.xml
<CustomObject>
    <label>Source Field</label>
    <nameField>
        <displayFormat>SRC-{0000}</displayFormat>
        <label>Source ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Source Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Source_Field__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <inlineHelpText>What is the user-friendly name of this field?</inlineHelpText>
    <label>Field Label</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source_Field__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Billing Detail</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Campaign Member</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Line Item</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source_Field__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sylectus Other</fullName>
            </value>
            <value>
                <fullName>Roadnet Salesforce</fullName>
            </value>
            <value>
                <fullName>FRA Other</fullName>
            </value>
            <value>
                <fullName>Omnitracs Salesforce</fullName>
            </value>
            <value>
                <fullName>Omnitracs Mexico Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source_Field__c/fields/System_Field__c.field-meta.xml
<CustomField>
    <fullName>System_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>System Field</label>
    <referenceTo>System_Field__c</referenceTo>
    <relationshipLabel>Source Fields</relationshipLabel>
    <relationshipName>Source_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/System_Field__c/System_Field__c.object-meta.xml
<CustomObject>
    <description>MIBOS Requirements App: The fields that need to be configured to support requirements.</description>
    <label>System Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Field__c/fields/Source_Field__c.field-meta.xml
<CustomField>
    <fullName>Source_Field__c</fullName>
    <label>Source Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Field__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Campaign Member</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Case Comment</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Opportunity Line Item</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Field__c/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Excel</fullName>
            </value>
            <value>
                <fullName>Great Plains</fullName>
            </value>
            <value>
                <fullName>MS Access</fullName>
            </value>
            <value>
                <fullName>MS CRM</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>SFDC (Legacy)</fullName>
            </value>
            <value>
                <fullName>SFDC (New)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ViewSystemField_Ext_Test.cls
@isTest
public class ViewSystemField_Ext_Test {

    public static testMethod void testAssociateFields() {
        System_Field__c f = new System_Field__c();
        insert f;
        
        Source_Field__c sf1 = new Source_Field__c(Field_Name__c = 'Test 1', Source_System__c = 'Sylectus Other', System_Field__c = f.id, Source_Object__c = 'Account');
        Source_Field__c sf2 = new Source_Field__c(Field_Name__c = 'Test 2', Source_System__c = 'Sylectus Other', Source_Object__c = 'Account');
        insert sf1;
        insert sf2;
        
        Test.startTest();
        
        Test.setCurrentPage(Page.ViewSystemField);
        ApexPages.currentPage().getParameters().put('id',f.Id);
        ApexPages.StandardController con = new ApexPages.StandardController(f);
        ViewSystemField_Ext fieldPage = new ViewSystemField_Ext(con);
        
        System.assert(true, fieldPage.assignedFieldsList[0].getValue() == sf1.Id);
        System.assert(true, fieldPage.unassignedFieldsList[0].getValue() == sf2.Id);
        
        List<SelectOption> newAssigned = new List<SelectOption>();
        List<SelectOption> newUnassigned = new List<SelectOption>();
        newAssigned.add(new SelectOption(sf2.Id, sf2.Field_Name__c));
        newUnassigned.add(new SelectOption(sf1.Id, sf1.Field_Name__c));
                
        fieldPage.assignedFieldsList = newAssigned;
        fieldPage.unassignedFieldsList = newUnassigned;
        
        fieldPage.doSave();
        
        Source_Field__c newsf1 = [SELECT Id, System_Field__c FROM Source_Field__c WHERE Id =: sf1.Id LIMIT 1];
        Source_Field__c newsf2 = [SELECT Id, System_Field__c FROM Source_Field__c WHERE Id =: sf2.Id LIMIT 1];
        
        System.assert(true, newsf1.System_Field__c == null);
        System.assert(true, newsf2.System_Field__c == f.Id);
        
        fieldPage.refreshFilter();
        
        Test.stopTest();
    }

}