force-app/main/default/objects/Contract_Additional_Parties__c/Contract_Additional_Parties__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management. Allows users to specify additional companies related to the Contract.</description>
    <label>Contract Additional Parties</label>
    <nameField>
        <displayFormat>CAP-{0000000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Additional Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Additional_Company__c.field-meta.xml
<CustomField>
    <fullName>Additional_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Additional Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Additional Parties</relationshipLabel>
    <relationshipName>Contract_Additional_Parties</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <formula>TEXT(Contract__r.Agreement_Type__c)</formula>
    <label>Agreement Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Additional Parties</relationshipLabel>
    <relationshipName>Contract_Additional_Parties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Contract_Title__c.field-meta.xml
<CustomField>
    <fullName>Contract_Title__c</fullName>
    <formula>Contract__r.Contract_Title__c</formula>
    <label>Contract Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Import_ID__c.field-meta.xml
<CustomField>
    <fullName>Import_ID__c</fullName>
    <externalId>true</externalId>
    <label>Import ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Party_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Party_Effective_Date__c</fullName>
    <label>Party Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Party_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Party_Expiration_Date__c</fullName>
    <label>Party Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Party_Relation_Description__c.field-meta.xml
<CustomField>
    <fullName>Party_Relation_Description__c</fullName>
    <label>Party Relation Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Party_Relation_Type__c.field-meta.xml
<CustomField>
    <fullName>Party_Relation_Type__c</fullName>
    <label>Party Relation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Addl Signing Party to Contract</fullName>
            </value>
            <value>
                <fullName>Named Party to Contract</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Counterparty</fullName>
            </value>
            <value>
                <fullName>Subsidiary</fullName>
            </value>
            <value>
                <fullName>Business Unit/Segment</fullName>
            </value>
            <value>
                <fullName>Subcontractor</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Additional_Parties__c/fields/Search_Term_2__c.field-meta.xml
<CustomField>
    <fullName>Search_Term_2__c</fullName>
    <label>Search Term 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/Contract_Address__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management. Allows users to add multiple types of Addresses to a Contract, such as Shipping, Notice Address, etc.</description>
    <label>Contract Address</label>
    <nameField>
        <displayFormat>CAA-{0000000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Address__c/fields/Account_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You may select an existing Account Additional Address record</inlineHelpText>
    <label>Account Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contract Addresses</relationshipLabel>
    <relationshipName>Contract_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Address_ID__c.field-meta.xml
<CustomField>
    <fullName>Address_ID__c</fullName>
    <externalId>true</externalId>
    <label>Address ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Addresses</relationshipLabel>
    <relationshipName>Contract_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Ascension Island</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Fax_Number__c.field-meta.xml
<CustomField>
    <fullName>Fax_Number__c</fullName>
    <label>Fax Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Legacy_Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Source_ID__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Source ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional Party Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Additional Party Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Contract Specific Address</fullName>
            </value>
            <value>
                <fullName>Express Mail Address</fullName>
            </value>
            <value>
                <fullName>Invoice Address</fullName>
            </value>
            <value>
                <fullName>Notice Address - cc</fullName>
            </value>
            <value>
                <fullName>Notice Address - Primary</fullName>
            </value>
            <value>
                <fullName>Pricing Notice Address</fullName>
            </value>
            <value>
                <fullName>Government Specific Address</fullName>
            </value>
            <value>
                <fullName>Remit to Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Corporate HQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/QWBS_Cust_ID__c.field-meta.xml
<CustomField>
    <fullName>QWBS_Cust_ID__c</fullName>
    <externalId>true</externalId>
    <label>Cust ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Address__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Project__c/Contract_Project__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management. Allows users to create a Project record and link it to many Contracts.</description>
    <label>Contract Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Family_Linked_Contracts__c/Non_Family_Linked_Contracts__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management. Allows many Contracts to be tied one Project, and each Contract can be tied to multiple Projects.</description>
    <label>Non-Family Linked Contracts</label>
    <nameField>
        <displayFormat>NFLC-{000000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non-Family Linked Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Non_Family_Linked_Contracts__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Non-Family Linked Contracts</relationshipLabel>
    <relationshipName>Non_Family_Linked_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Non_Family_Linked_Contracts__c/fields/Contract_Project__c.field-meta.xml
<CustomField>
    <fullName>Contract_Project__c</fullName>
    <label>Contract Project</label>
    <referenceTo>Contract_Project__c</referenceTo>
    <relationshipLabel>Non-Family Linked Contracts</relationshipLabel>
    <relationshipName>Non_Family_Linked_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NewChildController.cls
public class NewChildController {
    public Contract c;
    public List<Contract> cList{get;set;}
    public List<Contract_Address__c> caddList{get;set;}
    public List<Contract_Additional_Parties__c> caddParty{get;set;}
    public List<Non_Family_Linked_Contracts__c> nflconList{get;set;}
    public Id cid;
    public String query{get;set;}
    public String query2{get;set;}
    public String query3{get;set;}
    public Id eCopyId{get;set;} 
    public NewChildController(ApexPages.StandardController controller){
       cid = ApexPages.currentPage().getParameters().get('Id');
    }
    
    
    public pageReference cloneContract(){
        String SobjectApiName = 'Contract';
        
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map<String, Schema.SObjectField> fieldMap = schemaMap.get(SobjectApiName).getDescribe().fields.getMap();
 
        String commaSepratedFields = '';
        for(String fieldName : fieldMap.keyset()){
            if(commaSepratedFields == null || commaSepratedFields == ''){
                commaSepratedFields = fieldName;
            }else{
                commaSepratedFields = commaSepratedFields + ', ' + fieldName;
            }
        }
 
        query = 'select ' + commaSepratedFields + ' from ' + SobjectApiName + ' Where ID =\''+cid+'\'';
        cList = Database.query(query);
        

        Contract eCopy = cList[0].clone(false, true, false, false);
        eCopy.status='Draft';
        // eCopy.CompanySigned=null;
        eCopy.Contract_Title__c=null;
        eCopy.Parent_Contract__c=cid;
        eCopy.External_Contract_Number__c=null;
        eCopy.Contract_Value__c=null;
        eCopy.TCM_Contract_Number__c=null;
        eCopy.IsActive__c=false;
        eCopy.Agreement_Type__c=null;
        eCopy.StartDate=null;
        eCopy.EndDate=null;
        eCopy.ContractTerm=null;
        eCopy.Term_Type__c=null;
        eCopy.Renewal_Term_Length_in_months__c=null;
        eCopy.Notice_Period_in_days__c=null;
        eCopy.OwnerExpirationNotice=null;
        eCopy.Original_Expiration_Date__c=null;
        eCopy.Original_Company__c=null;
        eCopy.Original_Contract_Manager__c=null;
        eCopy.Original_Attorney__c=null;
        eCopy.Legacy_Source_ID__c =null;
        
        insert eCopy;
        eCopyId=eCopy.Id;
        system.debug('***eC'+eCopy.Id);
        system.debug('***eCopyId'+eCopyId);
        cloneContractAddress(eCopy.Id);
        cloneContractAdditionalParties(eCopy.Id);
        cloneNFLinkedCon(eCopy.Id);
        PageReference newPage = new PageReference('/'+eCopy.id+'/e?retURL=%2F'+eCopy.id+'&00NW0000000Z1Mb=');
        return newPage.setRedirect(true);
    }
    
    public void cloneContractAddress(Id pContract){
        caddList = [SELECT Id,Account_Address__c,Address_ID__c,Address_Line_1__c,Address_Line_2__c,Attention__c,City__c,Country__c,QWBS_Cust_ID__c,Email_Address__c,Fax_Number__c,Legacy_Source_ID__c,Location_Type__c,Phone_Number__c,State_Province__c,Zip_Postal_Code__c FROM Contract_Address__c WHERE Contract__c =:cid];
        List<Contract_Address__c> cAddToInsert = new List<Contract_Address__c>();
        if((caddList!=null) && !(caddList.isEmpty())){
            for(Contract_Address__c c : caddList){
                c.Id=null;
                Contract_Address__c eCopy2 = new Contract_Address__c();
                eCopy2.Account_Address__c = c.Account_Address__c;
                eCopy2.Address_ID__c = c.Address_ID__c;
                eCopy2.Address_Line_1__c = c.Address_Line_1__c;
                eCopy2.Address_Line_2__c = c.Address_Line_2__c;
                eCopy2.Attention__c = c.Attention__c;
                eCopy2.City__c = c.City__c;
                eCopy2.Country__c = c.Country__c;
                eCopy2.QWBS_Cust_ID__c = c.QWBS_Cust_ID__c;
                eCopy2.Email_Address__c = c.Email_Address__c;
                eCopy2.Fax_Number__c = c.Fax_Number__c;
                eCopy2.Legacy_Source_ID__c = c.Legacy_Source_ID__c;
                eCopy2.Location_Type__c = c.Location_Type__c;
                eCopy2.Phone_Number__c = c.Phone_Number__c;
                eCopy2.State_Province__c = c.State_Province__c;
                eCopy2.Zip_Postal_Code__c = c.Zip_Postal_Code__c;
                eCopy2.Contract__c=pContract;
                cAddToInsert.add(eCopy2);
            }
            insert cAddToInsert;
        }
    }
    public void cloneContractAdditionalParties(Id pContract){
        caddParty = [SELECT Id,Additional_Company__c,Contract__c,Import_ID__c,Party_Effective_Date__c,Party_Expiration_Date__c,Party_Relation_Description__c,Party_Relation_Type__c,Relationship_Status__c,Search_Term_2__c FROM Contract_Additional_Parties__c WHERE Contract__c =:cid];
        List<Contract_Additional_Parties__c> cAddPInsert = new List<Contract_Additional_Parties__c>();
        if((caddParty!=null) && !(caddParty.isEmpty())){
            for(Contract_Additional_Parties__c c : caddParty){
                c.Id=null;
                Contract_Additional_Parties__c eCopy3 = new Contract_Additional_Parties__c();
                eCopy3.Additional_Company__c = c.Additional_Company__c;
                eCopy3.Import_ID__c = c.Import_ID__c;
                eCopy3.Party_Effective_Date__c = c.Party_Effective_Date__c;
                eCopy3.Party_Expiration_Date__c = c.Party_Expiration_Date__c;
                eCopy3.Party_Relation_Description__c = c.Party_Relation_Description__c;
                eCopy3.Party_Relation_Type__c = c.Party_Relation_Type__c;
                eCopy3.Relationship_Status__c = c.Relationship_Status__c;
                eCopy3.Search_Term_2__c = c.Search_Term_2__c;
                
                eCopy3.Contract__c=pContract;
                cAddPInsert.add(eCopy3);
            }
            insert cAddPInsert;
        }
    }
    public void cloneNFLinkedCon(Id pContract){
        nflconList = [SELECT Id,Contract_Project__c,Contract__c FROM Non_Family_Linked_Contracts__c WHERE Contract__c =: cid];
        List<Non_Family_Linked_Contracts__c> nfcInsert = new List<Non_Family_Linked_Contracts__c>();
        if((nflconList!=null) && !(nflconList.isEmpty())){
            for(Non_Family_Linked_Contracts__c c : nflconList){
                c.Id=null;
                Non_Family_Linked_Contracts__c nCopy = new Non_Family_Linked_Contracts__c();
                nCopy.Contract_Project__c = c.Contract_Project__c;
                nCopy.Contract__c = pContract;
                nfcInsert.add(nCopy);
            }
            insert nfcInsert;
        }
    }
    
}