force-app/main/default/objects/Customer_Information_Sheet__c/Customer_Information_Sheet__c.object-meta.xml
<CustomObject>
    <label>Customer Information Sheet</label>
    <nameField>
        <displayFormat>CIS{0000}</displayFormat>
        <label>CIS #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Information Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Information_Sheet__c/fields/Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Email_Status__c</fullName>
    <label>Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Sent</fullName>
                <default>true</default>
                <label>Not Sent</label>
            </value>
            <value>
                <fullName>Sent to PANA</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Information_Sheet__c/fields/Trigger_Email__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QES_NCIS_SendEmail.cls
/**
 * Class: QES_NCIS_SendEmail
 *
 * Copyright (C) 2012 EDL Consulting
 *
 * Purpose: 
 * This apex class updates the email timestamp on the record. 
 *
 *
 * Change History:
 *
 * Developer                     Date        Flag    Description
 * -----------------------------------------------------------------------
 * Prakash Ramaswamy          08/02/2012   <ID>   Initial development
 *
 */
public with sharing class QES_NCIS_SendEmail {
   
   private Customer_Information_Sheet__c cisInstance;
   
   public boolean simualteDBError;
   
   public QES_NCIS_SendEmail(Apexpages.standardcontroller cisCtrl){
      cisInstance=(Customer_Information_Sheet__c)cisCtrl.getRecord();
   }
   
   public PageReference updateEmailFields(){
     try{
         cisInstance.Trigger_Email__c=true;
         if(Test.isRunningTest()&& simualteDBError!=null && simualteDBError){
              String nullStr=null;
              Boolean test=nullStr.contains('Test');
         }
         update cisInstance;
         return new PageReference('/' + cisInstance.Id);
     }
     
     catch(Exception e){
        cisInstance.Trigger_Email__c=false;
        cisInstance.Email_Status__c='Exception';
        update cisInstance;
        return new PageReference('/' + cisInstance.Id);
     }
   }
   
}