force-app/main/default/objects/Customer_Information_Sheet__c/Customer_Information_Sheet__c.object-meta.xml
<CustomObject>
    <label>Customer Information Sheet</label>
    <nameField>
        <displayFormat>CIS{0000}</displayFormat>
        <label>CIS #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Information Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Information_Sheet__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>New_Customer_Information_Sheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Information_Sheet__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>IF(ISPICKVAL(Account__r.District__c, &quot;B2B2C&quot;), &quot;B2B2C&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Canada&quot;), &quot;Canada&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Central&quot;), &quot;Central&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;CNR Strategic&quot;), &quot;CNR Strategic&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Consumer Content Services&quot;), &quot;Consumer Content Services&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;East&quot;), &quot;East&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;East District 1&quot;), &quot;East District 1&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;East District 2&quot;), &quot;East District 2&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;East District 3&quot;), &quot;East District 3&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;East District 4&quot;), &quot;East District 4&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Industrial&quot;), &quot;Industrial&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;International&quot;), &quot;International&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;LBS&quot;), &quot;LBS&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Metro&quot;), &quot;Metro&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Midwest District 1&quot;), &quot;Midwest District 1&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Midwest District 2&quot;), &quot;Midwest District 2&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Midwest District 3&quot;), &quot;Midwest District 3&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Midwest District 4&quot;), &quot;Midwest District 4&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Mountain&quot;), &quot;Mountain&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;North&quot;), &quot;North&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Notebook and MID Management Services&quot;), &quot;Notebook and MID Management Services&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;ORMM OEM&quot;), &quot;ORMM OEM&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;QC Accounts&quot;), &quot;QC Accounts&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;QES&quot;), &quot;QES&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;QGOV&quot;), &quot;QGOV&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;South&quot;), &quot;South&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Strategic&quot;), &quot;Strategic&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;Telemedicine&quot;), &quot;Telemedicine&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;VASP&quot;), &quot;VASP&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;West&quot;), &quot;West&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;West District 1&quot;), &quot;West District 1&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;West District 2&quot;), &quot;West District 2&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;West District 3&quot;), &quot;West District 3&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;West District 4&quot;), &quot;West District 4&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;ORMM Region 1&quot;), &quot;ORMM Region 1&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;ORMM Region 2&quot;), &quot;ORMM Region 2&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;ORMM Region 3&quot;), &quot;ORMM Region 3&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;ORMM Region 4&quot;), &quot;ORMM Region 4&quot;,
IF(ISPICKVAL(Account__r.District__c, &quot;ORMM Region 5&quot;), &quot;ORMM Region 5&quot;,
&quot;Other&quot;)))))))))))))))))))))))))))))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Information_Sheet__c/fields/Installer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Installer_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Installer Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact does not exist in the Account selected.Please select a different account.</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Customer Information Sheets (Installer Contact)</relationshipLabel>
    <relationshipName>Customer_Information_Sheets_Installer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Information_Sheet__c/fields/No_6_pin_Units_Sold_PP804879__c.field-meta.xml
<CustomField>
    <fullName>No_6_pin_Units_Sold_PP804879__c</fullName>
    <defaultValue>0</defaultValue>
    <label># 6-pin Units Sold (PP804879):</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Information_Sheet__c/fields/Partner_Portal_Link__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Link__c</fullName>
    <label>Partner Portal Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/Customer_Information_Sheet_TriggerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=True)
private class Customer_Information_Sheet_TriggerTest {

    static testMethod void myUnitTest() {
        
        //Query the partner portal record type
  List<RecordType> partnerRecordType=[select Id
                                           , Name
                                       from  RecordType
                                       where Name='Partner CIS'
                                       Limit 1
                                     ];
        Test.startTest();
        
                                     
                                     
        // TO DO: implement unit test
        Account accountInstance=new Account();
        accountInstance.name='Test Account Name';
        accountInstance.phone='5643442333';
        //accountInstance.District__c='Canada';
        accountInstance.BillingStreet='Test Street';
        accountInstance.BillingCity='Test City';
        accountInstance.BillingState='NC';
        accountInstance.BillingPostalCode='23233';
        accountInstance.Account_Type__c='Association';
        insert accountInstance;
        
        Contact contactInstance=new Contact(FirstName='Test Contact', LastName='Test Last Name');
        contactInstance.AccountId=accountInstance.id;
        insert contactInstance;
        
        Customer_Information_Sheet__c cisSheet=new Customer_Information_Sheet__c();
        cisSheet.Account__c=accountInstance.Id;
        cisSheet.RecordTypeId=partnerRecordType.get(0).Id;
        cisSheet.No_6_pin_Units_Sold_PP804879__c=2;
        cisSheet.Installer_Contact__c=contactInstance.id;
        insert cisSheet;
        Test.stopTest();
        
        Customer_Information_Sheet__c cisSheetUpdated=[select Id, Partner_Portal_Link__c, Name from Customer_Information_Sheet__c where Id=:cisSheet.Id Limit 1];
        
        System.assertEquals(URL.getSalesforceBaseUrl().toExternalForm() + '/' + accountInstance.Id, cisSheetUpdated.Partner_Portal_Link__c);
        
    }
}