force-app/main/default/objects/Service_Agreement_Adjustment__c/Service_Agreement_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Service Agreement Adjustment</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Service Agreement Adjustment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Agreement Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Agreement Adjustments</relationshipLabel>
    <relationshipName>Service_Agreement_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Contact_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address_1__c</fullName>
    <description>Account Address Line 1 where Location Type = &apos;Corporate HQ&apos;</description>
    <label>Contact Address 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Contact_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address_2__c</fullName>
    <description>Account Address (City, State, Zip) where Location Type = &apos;Corporate HQ&apos;</description>
    <label>Contact Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Service Agreement Adjustments</relationshipLabel>
    <relationshipName>Service_Agreement_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Emails will be triggered to contact based on this checkbox</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Agreement_Adjustment__c/fields/SAA_Status__c.field-meta.xml
<CustomField>
    <fullName>SAA_Status__c</fullName>
    <description>Updated by job</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Negotiation</fullName>
            </value>
            <value>
                <fullName>Notification Sent</fullName>
            </value>
            <value>
                <fullName>Email Bounce Back</fullName>
            </value>
            <value>
                <fullName>Waived</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAllServiceAgreementAdjustmentTrigger.cls
@isTest(SeeAllData=True)
private class TestAllServiceAgreementAdjustmentTrigger {
    static testmethod void testSendUpliftNotification() {

        //Test data preparation
        Account testAcct = TestUtils.getAccount('Test Account');
        insert testAcct;
        
        Contact testContact = TestUtils.getContact(testAcct);
        testContact.Email = 'test@test.com';
        testContact.Title = 'Dev';
        insert testContact;
        
        Contract testContract = TestUtils.getContract(testAcct);
        insert testContract;
    
        Test.StartTest();
        Service_Agreement_Adjustment__c SAA = new Service_Agreement_Adjustment__c();
        SAA.SAA_Status__c = 'New';
        SAA.Email_Sent__c = true;
        SAA.Contact_Address_1__c = 'Addr1';
        SAA.Contact_Address_2__c = 'Addr1';
        SAA.Contract__c = testContract.Id;
        SAA.Contact__c = testContact.Id;
        
        insert SAA;
        Test.StopTest();
    }
    
}