force-app/main/default/objects/Scoring_Model__c/Scoring_Model__c.object-meta.xml
<CustomObject>
    <label>Scoring Model</label>
    <nameField>
        <label>Scoring Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Model__c/fields/Green_Overall_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Green_Overall_Score_From__c</fullName>
    <label>Green Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Green_Overall_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Green_Overall_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Red_Overall_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Red_Overall_Score_From__c</fullName>
    <label>Red Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Red_Overall_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Red_Overall_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Yellow_Overall_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Yellow_Overall_Score_From__c</fullName>
    <label>Yellow Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Yellow_Overall_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Yellow_Overall_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Subscription__c/Scoring_Subscription__c.object-meta.xml
<CustomObject>
    <label>Scoring Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Scoring Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Subscription</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scoring Subscription</relationshipLabel>
    <relationshipName>Scoring_Subscription</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Subscription__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Model</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Scoring Subscription</relationshipLabel>
    <relationshipName>Scoring_Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <description>Used to support surveys and survey data via ClickTools.</description>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Analyst_s_Technical_Skills_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Analyst_s_Technical_Skills_Knowledge__c</fullName>
    <label>Analyst&apos;s Technical Skills/Knowledge</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Very Satisfied</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Courtesy_and_Professionalism_of_Analyst__c.field-meta.xml
<CustomField>
    <fullName>Courtesy_and_Professionalism_of_Analyst__c</fullName>
    <label>Courtesy and Professionalism of Analyst</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Very Satisfied</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Overall_Service_Experience__c.field-meta.xml
<CustomField>
    <fullName>Overall_Service_Experience__c</fullName>
    <label>Overall Service Experience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Very Satisfied</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Quality_of_service_provided__c.field-meta.xml
<CustomField>
    <fullName>Quality_of_service_provided__c</fullName>
    <label>Quality of service provided</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Very Satisfied</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Timeliness_of_service_provided__c.field-meta.xml
<CustomField>
    <fullName>Timeliness_of_service_provided__c</fullName>
    <label>Timeliness of service provided</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Somewhat Dissatisfied</fullName>
            </value>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Satisfied</fullName>
            </value>
            <value>
                <fullName>Very Satisfied</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScoringDataUtilsTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seeAllData=true)
private class ScoringDataUtilsTest {

    
    
    static testMethod void testCaseEscalationsAdd ()
    {    
       //TestScoringUtility.allAccountRecordTypesCS(); 
       //TestScoringUtility.allAccountUtilCS();
         RecordType rp=[select ID from RecordType where Name='T&L Sales Accounts'];
         Account caseAccount = TestScoringUtility.createAccount();
         Database.DMLOptions dml = new Database.DMLOptions(); 
         dml.DuplicateRuleHeader.allowSave = true;
         dml.DuplicateRuleHeader.runAsCurrentUser = true;
         Database.SaveResult sr1 = Database.insert(caseAccount, dml);
         //insert caseAccount;
         TestScoringUtility.createAccountScoring();
         TestScoringUtility.createScoringModel();
         TestScoringUtility.createScoringItem();
         
        Scoring_Model__c newScoringModel = new Scoring_Model__c(Name = 'Test Data Model',
        Red_Overall_Score_To__c = 10, Red_Overall_Score_From__c = 5,Yellow_Overall_Score_To__c = 4,
        Yellow_Overall_Score_From__c = 3, Green_Overall_Score_To__c = 2, Green_Overall_Score_From__c = 0);
        
        Scoring_Subscription__C newSub = new Scoring_Subscription__c(Subscription_Status__c = 'Active', 
            Scoring_Model__c = newScoringModel.ID, Account__c = caseAccount.ID);
        
        
        insert newScoringModel;
        
        Survey__c newSurvey = new Survey__c(Quality_of_Service_Provided__c = 'Very Satisfied', Timeliness_of_service_provided__c = 'Very Satisfied', Overall_Service_Experience__c = 'Very Satisfied',
            Analyst_s_Technical_Skills_Knowledge__c = 'Very Satisfied', Courtesy_and_Professionalism_of_analyst__c = 'Very Satisfied', Account__c = caseAccount.id);

        
        test.startTest();
        /**********************************Test Case-1***********************************************************/
        
        insert newSurvey;
        insert newSub;
        
        
        test.stopTest();
}
}