force-app/main/default/objects/Business_Plan__c/Business_Plan__c.object-meta.xml
<CustomObject>
    <label>Business Plan</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Business Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Plan__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Goal</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Plan__c/fields/Strategic_Account_Profile__c.field-meta.xml
<CustomField>
    <fullName>Strategic_Account_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategic Account Profile</label>
    <referenceTo>Strategic_Account_Profile__c</referenceTo>
    <relationshipName>Business_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/Strategic_Account_Profile__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the profile information on strategic accounts for the T&amp;L Organization</description>
    <label>Strategic Account Profile</label>
    <nameField>
        <label>Strategic Account Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategic Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Strategic_Account_Profile</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_Business_Plan__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Business_Plan__c</fullName>
    <label>Business Plans</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_CSF__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_CSF__c</fullName>
    <label>Critical Success Factors</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Strategic_Account_Profile__c/fields/Last_Modified_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Modified_Date_Time__c</fullName>
    <label>SAP Last Modified Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestUpdateBP.cls
@isTest(SeeAllData = true)
public class TestUpdateBP 
{
/***************************************************************************************************************
Date: 01/19/2009
Author: Divya Hegde, Salesforce.com Consultant
        Tata Consultancy Services Limited

Purpose: Test Method to validate the functionality of Trigger "UpdateBP" on Strategic Account Profile.
**************************************************************************************************************************************************************/
static testMethod void testTrigger()
{
    Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
    Account newAccount = new Account();         
        newAccount.Name = 'SFDC';         
        newAccount.Type = 'Other';         
        newAccount.BillingStreet = 'Test Address';         
        newAccount.BillingCity = 'Test City';         
        newAccount.BillingCountry = 'Test Country';         
        newAccount.QWBS_Cust_ID__c = '4567';        
        
    insert newAccount;
    NewSAP.Account__c =newAccount.id ;
    NewSAP.Last_Modified_Business_Plan__c =datetime.valueOf('2008-12-02 13:52:00');
    NewSAP.Last_Modified_CSF__c=datetime.valueOf('2008-12-03 13:52:00');
    NewSAP.Last_Modified_Date_Time__c=datetime.valueOf('2008-12-03 13:51:00');
    
    insert NewSAP;
   
    Business_Plan__c BPnew =new Business_Plan__c();
    BPnew.Strategic_Account_Profile__c = NewSAP.Id;
    BPnew.Goal__c='test1234';
   
    insert BPnew ;
}
  static testMethod void UpdateBP()
  {
   Strategic_Account_Profile__c  NewSAP=  new  Strategic_Account_Profile__c();
    Account newAccount = new Account();         
        newAccount.Name = 'SFDC';         
        newAccount.Type = 'Other';         
        newAccount.BillingStreet = 'Test Address';         
        newAccount.BillingCity = 'Test City';         
        newAccount.BillingCountry = 'Test Country';         
        newAccount.QWBS_Cust_ID__c = '4567'; 
   
   insert newAccount;
   
   NewSAP.Account__c =newAccount.id ;
   insert NewSAP;
   Business_Plan__c BPnew =new Business_Plan__c();
   BPnew.Strategic_Account_Profile__c = NewSAP.Id;
   BPnew.Goal__c='test1234';
   insert BPnew;
   update NewSAP;
  }
}