force-app/main/default/objects/Opportunity_Stage__c/Opportunity_Stage__c.object-meta.xml
<CustomObject>
    <label>SP Opportunity Stage</label>
    <nameField>
        <label>Opportunity Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SP Opportunity Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Stage__c/fields/Next_Stage__c.field-meta.xml
<CustomField>
    <fullName>Next_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the Stage immediately following this Stage.</inlineHelpText>
    <label>Next Stage</label>
    <referenceTo>Opportunity_Stage__c</referenceTo>
    <relationshipName>Opportunity_Stages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Stage__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Stage</label>
    <referenceTo>Opportunity_Stage__c</referenceTo>
    <relationshipName>Opportunity_Stages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SP_OpportunityExtension_Test.cls
@isTest(seeAllData = true)
public class SP_OpportunityExtension_Test{
    public static testMethod void testOpportunityAdvanceStageController(){
        List<Account> acctList = TestDataFactory.createAcctList(1, 'SP Opportunity Extension Account Test');
		Account acc = acctList[0];
    	insert acc;
    	List<Contact> conList = TestDataFactory.createConList(1, 'LastName');
		Contact con = conList[0];
		con.AccountId = acc.Id;
        insert con;
        
        Opportunity_Stage__c oppStage1 = new Opportunity_Stage__c();
        oppStage1.Name = '1 - Plan';
        insert oppStage1;
        
        Opportunity_Stage__c oppStage2 = new Opportunity_Stage__c();
        oppStage2.Name = '2 - Develop';
        oppStage2.Next_Stage__c = oppStage1.id;
        insert oppStage2;
        
        Id PRODUCTSANDSERVRTYPE = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Products, Services and Maintenance').getRecordTypeId();
        Opportunity testOpportunity = new Opportunity(Name='asdasd',RecordTypeId=PRODUCTSANDSERVRTYPE,stagename='1 - Plan', closedate=Date.today(), Contact__c=con.Id, AccountId=acc.Id);
        testOpportunity.Opportunity_Stage__c = oppStage1.Id;
        insert testOpportunity;
        
        
        SP_OpportunityExtension testOpportunityExtension = new SP_OpportunityExtension(new ApexPages.StandardController(testOpportunity));
        if(testOpportunityExtension.OppStage == null){}
        if(testOpportunityExtension.nextStage == null){}
        if(testOpportunityExtension.advancementCriteria == null){}
        if(testOpportunityExtension.readyToAdvance){}
        testOpportunityExtension.advanceStage();
    }
}