force-app/main/default/objects/Custom_Report__c/Custom_Report__c.object-meta.xml
<CustomObject>
    <label>Custom Report</label>
    <nameField>
        <label>Custom Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Reports</relationshipLabel>
    <relationshipName>Custom_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/Partner_Support_Information__c.object-meta.xml
<CustomObject>
    <description>Support contact information for Partners.</description>
    <label>Partner Support Information</label>
    <nameField>
        <displayFormat>PSI-{0000}</displayFormat>
        <label>Partner Support Information Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Support Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Support_Information__c/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <description>URL for the logo</description>
    <label>Logo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Logo_Orientation__c.field-meta.xml
<CustomField>
    <fullName>Logo_Orientation__c</fullName>
    <label>Logo Orientation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Landscape</fullName>
            </value>
            <value>
                <fullName>Portrait</fullName>
            </value>
            <value>
                <fullName>Square</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Support Information</relationshipLabel>
    <relationshipName>Partner_Support_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Support_Information__c/fields/Support_Email__c.field-meta.xml
<CustomField>
    <fullName>Support_Email__c</fullName>
    <description>Partner Support Email</description>
    <label>Support Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/TestAttachmentUploadController.cls
@isTest(SeeAllData=true)
private class TestAttachmentUploadController{
    private static testMethod void testAttachUpload(){
        list<Account> lstAcct = [select id from Account where isPartner=true limit 1];
        system.debug('@@@@@lstAcct'+lstAcct);
        Partner_Support_Information__c partSuppInfo = new Partner_Support_Information__c ();
        partSuppInfo.Partner_Account__c = lstAcct[0].id;
        partSuppInfo.Logo_Orientation__c = 'Landscape';
        partSuppInfo.Support_Email__c = 'c_agang@qualcomm.com';
        insert partSuppInfo;
        
         Custom_Report__c customReport = new  Custom_Report__c();
         customReport.name = 'somename';
         customReport.Account__c = lstAcct[0].id;
         insert customReport;
        
        Attachment attch = new Attachment();
        attch.ParentId = partSuppInfo.id;
        Blob b = Blob.valueOf('Test Data');  
        attch.Name = 'Test Attachment for Parent';  
        attch.Body = b;  
        insert attch;
        
         Attachment attch1 = new Attachment();
        attch1.ParentId = customReport.id;
        Blob b1 = Blob.valueOf('Test Data');  
        attch1.Name = 'Test Attachment for Parent';  
        attch1.Body = b1;  
        insert attch1;
        
        
        partSuppInfo.logo__c = attch.id;
        
        update partSuppInfo;
        ApexPages.StandardController std = new ApexPages.StandardController(partSuppInfo);
        AttachmentUploadController  auc = new AttachmentUploadController(std);
        auc.initAll();
        auc.commitLogo();
        
        auc.upload();
        auc.editLogo();
        auc.saveEdit();
        auc.cancel();
        auc.cancelEdit();
        auc.newLogo();
        
        auc.getCurrentLogoExists();
        partSuppInfo.logo__c = '';
        
        update partSuppInfo;
        ApexPages.StandardController std1 = new ApexPages.StandardController(partSuppInfo);
        AttachmentUploadController  auc1 = new AttachmentUploadController(std1);
        auc1.initAll();
        auc1.upload();
        
        
        
    } 
}