force-app/main/default/objects/Account_Scoring__c/Account_Scoring__c.object-meta.xml
<CustomObject>
    <label>Account Scoring</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Scoring</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Scoring__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <label>Scoring Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/Account_Scoring_Item__c.object-meta.xml
<CustomObject>
    <label>Account Scoring Item</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Scoring Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scoring Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Account_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Account_Scoring__c</fullName>
    <label>Account Scoring</label>
    <referenceTo>Account_Scoring__c</referenceTo>
    <relationshipLabel>Account Scoring Items</relationshipLabel>
    <relationshipName>Account_Score_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Scoring_Item__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Item__c</fullName>
    <label>Scoring Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/Scoring_Item__c.object-meta.xml
<CustomObject>
    <label>Scoring Item</label>
    <nameField>
        <label>Scoring Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Field_API_Name__c</fullName>
    <label>Scoring Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <label>Scoring Model</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Scoring Items</relationshipLabel>
    <relationshipName>Scoring_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/Scoring_Model__c.object-meta.xml
<CustomObject>
    <label>Scoring Model</label>
    <nameField>
        <label>Scoring Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Subscription__c/Scoring_Subscription__c.object-meta.xml
<CustomObject>
    <label>Scoring Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Scoring Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Subscription</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scoring Subscription</relationshipLabel>
    <relationshipName>Scoring_Subscription</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Subscription__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Model</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Scoring Subscription</relationshipLabel>
    <relationshipName>Scoring_Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestBatchAccountScoringCalculation.cls
@isTest
private class TestBatchAccountScoringCalculation {
	public static VistaAssetHelperUtil util = new VistaAssetHelperUtil();
	@testSetup
	static void SetupData() {
		TestUtils.defineCustomSettings();
	}
    static void createTestData(){
        
        /*TestScoringUtility.allAccountRecordTypesCS(); 
        TestScoringUtility.allAccountUtilCS();*/
        
        //Creating Account by calling createAccount method of TestScoringUtility 
        Account a = util.createAccount('Batch Scoring Calculation Test Account');
        a.customer_health_nps_score__c = 5;
        a.customer_health_avg_trans_surveys__c = 500;
        update a;
        
        //Creating Scoring_Model__c by calling createScoringModel method of TestScoringUtility 
        Scoring_Model__c sm = TestScoringUtility.createScoringModel();
        
        //Creating another Scoring_Model__c by calling createScoringModel method of TestScoringUtility
        Scoring_Model__c sm2 = TestScoringUtility.createScoringModel();
        
        //Creating Scoring_Item__c by calling createScoringItem method of TestScoringUtility
        Scoring_Item__c si = TestScoringUtility.createScoringItem();
        si.Scoring_Field_API_Name__c =  'customer_health_nps_score__c';
        si.Scoring_Model__c = sm.Id;
        insert si;
        
        
        //Creating third Scoring_Item__c by calling createScoringItem method of TestScoringUtility
        Scoring_Item__c si3 = TestScoringUtility.createScoringItem();
        si3.Scoring_Field_API_Name__c =  'customer_health_avg_trans_surveys__c';
        si3.Scoring_Model__c = sm2.Id;
        insert si3;
        
        //Creating Scoring_Subscription__c object
        Scoring_Subscription__c ss = new Scoring_Subscription__c();
        ss.Scoring_Model__c = sm.Id;
        ss.Account__c = a.id;
        insert ss;
        
        //Creating second Scoring_Subscription__c object
        Scoring_Subscription__c ss2 = new Scoring_Subscription__c();
        ss2.Scoring_Model__c = sm2.Id;
        ss2.Account__c = a.id;
        insert ss2;
        
        //insert new List<sObject>{a,sm,sm2,ss,ss2, si, si2, si3};
    }
    
    static testmethod void doTest() {
    
        createTestData();
        
        Test.startTest();
        BatchAccountScoringCalculation c = new BatchAccountScoringCalculation();
        Database.executeBatch(c,1);
        Test.stopTest();
        
        List<Account_Scoring__c> acs = [Select Id From Account_Scoring__c];
        List<Account_Scoring_Item__c> acItems = [Select Id From Account_Scoring_Item__c];
        
        System.assert(acs != null && acs.size() > 0);
        System.assert(acItems != null && acItems.size() > 0);
    }
}