force-app/main/default/objects/Account_Scoring__c/Account_Scoring__c.object-meta.xml
<CustomObject>
    <label>Account Scoring</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Scoring</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Scoring__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Aggregate_Score__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Score__c</fullName>
    <formula>IF(Is_Manual_Scoring__c , IF(NOT(ISNULL( Manual_Score__c )), Manual_Score__c , 0),  Overall_Calculated_Score__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overall Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Average_Score__c.field-meta.xml
<CustomField>
    <fullName>Average_Score__c</fullName>
    <formula>IF( AND(Total_Score__c &gt; 0 , Total_Items__c &gt; 0) , Total_Score__c / Total_Items__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date Calculated Scoring</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Date_Manual_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Date_Manual_Scoring__c</fullName>
    <label>Date Manual Scoring</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Is_Manual_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Is_Manual_Scoring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manual Scoring?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Manual_Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Manual_Display_Type__c</fullName>
    <label>Manual Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Manual_Score__c.field-meta.xml
<CustomField>
    <fullName>Manual_Score__c</fullName>
    <label>Manual Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Manual_Scoring_Comments__c.field-meta.xml
<CustomField>
    <fullName>Manual_Scoring_Comments__c</fullName>
    <label>Manual Scoring Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Manual_Scoring_Reason__c.field-meta.xml
<CustomField>
    <fullName>Manual_Scoring_Reason__c</fullName>
    <label>Manual Scoring Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product reliability</fullName>
            </value>
            <value>
                <fullName>Network reliability</fullName>
            </value>
            <value>
                <fullName>Product features</fullName>
            </value>
            <value>
                <fullName>Contract Termination</fullName>
            </value>
            <value>
                <fullName>RFP / RFQ</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Overall_Calculated_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Calculated_Score__c</fullName>
    <label>Overall Calculated Score</label>
    <summarizedField>Account_Scoring_Item__c.Score__c</summarizedField>
    <summaryForeignKey>Account_Scoring_Item__c.Account_Scoring__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <label>Scoring Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/Account_Scoring_Item__c.object-meta.xml
<CustomObject>
    <label>Account Scoring Item</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Scoring Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scoring Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Account_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Account_Scoring__c</fullName>
    <label>Account Scoring</label>
    <referenceTo>Account_Scoring__c</referenceTo>
    <relationshipLabel>Account Scoring Items</relationshipLabel>
    <relationshipName>Account_Score_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Display_Type__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Normalized_Score__c.field-meta.xml
<CustomField>
    <fullName>Normalized_Score__c</fullName>
    <label>Normalized Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Scoring_Item__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Item__c</fullName>
    <label>Scoring Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Scoring_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Item_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Item ID</label>
    <referenceTo>Scoring_Item__c</referenceTo>
    <relationshipLabel>Account Scoring Items</relationshipLabel>
    <relationshipName>Account_Scoring_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/Scoring_Item__c.object-meta.xml
<CustomObject>
    <label>Scoring Item</label>
    <nameField>
        <label>Scoring Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <label>Scoring Model</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Scoring Items</relationshipLabel>
    <relationshipName>Scoring_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Weight__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Weight__c</fullName>
    <label>Scoring Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/Scoring_Model__c.object-meta.xml
<CustomObject>
    <label>Scoring Model</label>
    <nameField>
        <label>Scoring Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountLineItemsScoring.cls
/*********************************************************************************
* Name: AccountLineItemsScoring
* Created by Yogesh (Feuji) {DateCreated 6/9/2016} 
----------------------------------------------------------------------------------
* Purpose/Methods:/ 
* This class is used as controller class for VF AccountLineItemsScoring
----------------------------------------------------------------------------------
* Unit Test: TestAccountLineItemsScoring
---------------------------------------------------------------------------------- 
* History:
* VERSION DEVELOPER NAME DATE DETAIL FEATURES
1.0 Yogesh (Feuji) 6/9/2016 INITIAL DEVELOPMENT
 
*********************************************************************************/

public with sharing class AccountLineItemsScoring{
    
    public Account CurrentAccount{get;set;}
     
    public Account_Scoring__c CurrentScoring{get;set;}
    
    public List<Account_Scoring_Item__c> listScoringLines {get;set;}
    
    public string AccountScoringId {get;set;}
    
    public boolean isUpdateScoring {get;set;}
    
    public AccountLineItemsScoring( ){
    	
    	CurrentAccount = new Account();
    	CurrentScoring = new Account_Scoring__c();
    	listScoringLines = new List<Account_Scoring_Item__c>();
    	
    	// fetch current account scoring
    	if(System.currentPageReference().getParameters().get('id') != null){
    		for(Account_Scoring__c s : [Select Id, Name,Date_Manual_Scoring__c, Manual_Display_Type__c, Aggregate_Score__c,Manual_Scoring_Reason__c, Overall_Calculated_Score__c, Manual_Scoring_Comments__c,Is_Manual_Scoring__c,Manual_Score__c,Scoring_Model__c,Average_Score__c, Account__c,Date__c,Display_Type__c From Account_Scoring__c Where Id = : System.currentPageReference().getParameters().get('id')]){
    			CurrentScoring = s;
    			AccountScoringId = string.valueof(s.Account__c).substring(0,15);
    		}   		
    	}
    	
    	// associated account
    	for(Account a : [Select Id, Name From Account Where Id = : CurrentScoring.Account__c]){
			CurrentAccount = a;
		} 
		
		// fetch all scoring items
    	listScoringLines = [Select Id,Name, Scoring_Item__c, Scoring_Item_ID__r.Scoring_Weight__c, Score__c, Normalized_Score__c, Value__c, Display_Type__c From Account_Scoring_Item__c Where Account_Scoring__c = : CurrentScoring.Id  Order By Scoring_Item__c limit 1000 ];
    	
    }
    
    public PageReference BackToAccount(){
    	return new PageReference('/' + CurrentAccount.Id );
    }
    
    
}