force-app/main/default/objects/Account_Scoring__c/Account_Scoring__c.object-meta.xml
<CustomObject>
    <label>Account Scoring</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Scoring</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scoring</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Scoring__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Aggregate_Score__c.field-meta.xml
<CustomField>
    <fullName>Aggregate_Score__c</fullName>
    <formula>IF(Is_Manual_Scoring__c , IF(NOT(ISNULL( Manual_Score__c )), Manual_Score__c , 0),  Overall_Calculated_Score__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overall Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date Calculated Scoring</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/History__c.field-meta.xml
<CustomField>
    <fullName>History__c</fullName>
    <defaultValue>false</defaultValue>
    <label>History?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Is_Manual_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Is_Manual_Scoring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Manual Scoring?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Previous_Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Previous_Display_Type__c</fullName>
    <label>Previous Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <label>Scoring Model</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Scoring__c/fields/Scoring_Model_ID__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Model ID</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Account Scoring</relationshipLabel>
    <relationshipName>Account_Scoring</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/Account_Scoring_Item__c.object-meta.xml
<CustomObject>
    <label>Account Scoring Item</label>
    <nameField>
        <displayFormat>SI-{000000}</displayFormat>
        <label>Scoring Item#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Scoring Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Account_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Account_Scoring__c</fullName>
    <label>Account Scoring</label>
    <referenceTo>Account_Scoring__c</referenceTo>
    <relationshipLabel>Account Scoring Items</relationshipLabel>
    <relationshipName>Account_Score_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Display_Type__c</fullName>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Normalized_Score__c.field-meta.xml
<CustomField>
    <fullName>Normalized_Score__c</fullName>
    <label>Normalized Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Scoring_Item__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Item__c</fullName>
    <label>Scoring Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Scoring_Item__c/fields/Scoring_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Item_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Item ID</label>
    <referenceTo>Scoring_Item__c</referenceTo>
    <relationshipLabel>Account Scoring Items</relationshipLabel>
    <relationshipName>Account_Scoring_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/Scoring_Item__c.object-meta.xml
<CustomObject>
    <label>Scoring Item</label>
    <nameField>
        <label>Scoring Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Item__c/fields/Default_Score_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Score_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Default Score Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Green_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Green_Score_From__c</fullName>
    <label>Green Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Green_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Green_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Red_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Red_Score_From__c</fullName>
    <label>Red Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Red_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Red_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Field_API_Name__c</fullName>
    <label>Scoring Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <label>Scoring Model</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Scoring Items</relationshipLabel>
    <relationshipName>Scoring_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Scoring_Weight__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Weight__c</fullName>
    <label>Scoring Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Yellow_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Yellow_Score_From__c</fullName>
    <label>Yellow Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Item__c/fields/Yellow_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Yellow_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/Scoring_Model__c.object-meta.xml
<CustomObject>
    <label>Scoring Model</label>
    <nameField>
        <label>Scoring Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Model__c/fields/Green_Overall_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Green_Overall_Score_From__c</fullName>
    <label>Green Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Green_Overall_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Green_Overall_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Red_Overall_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Red_Overall_Score_From__c</fullName>
    <label>Red Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Red_Overall_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Red_Overall_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Yellow_Overall_Score_From__c.field-meta.xml
<CustomField>
    <fullName>Yellow_Overall_Score_From__c</fullName>
    <label>Yellow Scoring Range From</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Model__c/fields/Yellow_Overall_Score_To__c.field-meta.xml
<CustomField>
    <fullName>Yellow_Overall_Score_To__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Subscription__c/Scoring_Subscription__c.object-meta.xml
<CustomObject>
    <label>Scoring Subscription</label>
    <nameField>
        <displayFormat>Subscription-{00000}</displayFormat>
        <label>Scoring Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Subscription</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scoring Subscription</relationshipLabel>
    <relationshipName>Scoring_Subscription</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Subscription__c/fields/Scoring_Model__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Model__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Model</label>
    <referenceTo>Scoring_Model__c</referenceTo>
    <relationshipLabel>Scoring Subscription</relationshipLabel>
    <relationshipName>Scoring_Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Subscription__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchAccountScoringCalculation.cls
/*********************************************************************************
* Name: BatchAccountScoringCalculation
* Created by Omnitracs {DateCreated 7/1/2016} 
----------------------------------------------------------------------------------
* Purpose/Methods:/ 
* This is used as batch class for Account scoring calculations
----------------------------------------------------------------------------------
* Unit Test: TestBatchAccountScoringCalculation
---------------------------------------------------------------------------------- 
* History:
* VERSION DEVELOPER NAME DATE DETAIL FEATURES
1.0 7/1/2016 INITIAL DEVELOPMENT
 
*********************************************************************************/
 
 public class BatchAccountScoringCalculation implements database.batchable<sobject>{
        
        
    public database.querylocator start(database.batchableContext bc){
        return database.getquerylocator([Select Id From Account Where No_of_Active_Scoring_Subscription__c > 0]);
    }
    
    public void execute(database.batchablecontext bd, list<sobject> sc){ 
        
        for(Account a:(List<Account>)sc){
            
            Set<Id> scoringModel = new Set<Id>();
            Set<String> accFields = new Set<String>();
            String accountId = a.Id;
            
            string PreviousDisplayType = null;
            
            SET<ID> manualScoringModel = new SET<ID>();
            
            for(Account_Scoring__c accc: [Select Id,Display_Type__c,Scoring_Model_ID__c,Is_Manual_Scoring__c,History__c From Account_Scoring__c 
                                            Where Account__c=: a.Id AND Is_Manual_Scoring__c = true AND History__c = false]){
                    manualScoringModel.add(accc.Scoring_Model_ID__c);
            }
            
            for(Account_Scoring__c accc: [Select Id,Display_Type__c,Scoring_Model_ID__c,Is_Manual_Scoring__c,History__c From Account_Scoring__c Where Account__c=: a.Id Order By Date__c DESC limit 1]){
                PreviousDisplayType = accc.Display_Type__c;
                 
            }
            
            Map<Id,Account_Scoring__c> scoringAccountScoringMap = new Map<Id, Account_Scoring__c>();
            List<Account_Scoring_Item__c> accScoringItemToBeInserted = new List<Account_Scoring_Item__c>();
            
            for(Scoring_Subscription__c ss : [Select Id,Scoring_Model__c, Account__c from Scoring_Subscription__c 
                                                where Subscription_Status__c = 'Active' AND Account__c =: a.Id AND Scoring_Model__c NOT IN: manualScoringModel]){
                scoringModel.add(ss.Scoring_Model__c);
            }
            
            System.debug('scoringModel::'+scoringModel);
            Map<Id, Scoring_Model__c> scoringModelMap = new Map<Id, Scoring_Model__c>([Select Id, Name,Green_Overall_Score_From__c, Red_Overall_Score_From__c, Green_Overall_Score_To__c,
                                                                                        Yellow_Overall_Score_To__c, Red_Overall_Score_To__c, Yellow_Overall_Score_From__c,
                                                                                        (Select Id,Name, Default_Score_Value__c, Scoring_Field_API_Name__c, Scoring_Model__c, Scoring_Weight__c,  
                                                                                            Green_Score_From__c,Yellow_Score_From__c,Red_Score_From__c,Green_Score_To__c,Red_Score_To__c,Yellow_Score_To__c
                                                                                        From Scoring_Items__r)
                                                                                        From Scoring_Model__c Where Id IN :scoringModel]);
            // stop if no scoring model found
            if(scoringModelMap.size() == 0){
                continue;
            } 
            
            for(Scoring_Model__c sm : scoringModelMap.values()){
                for(Scoring_Item__c si:sm.Scoring_Items__r){
                    accFields.add(si.Scoring_Field_API_Name__c);
                }
            }
            
            String accQuery = 'Select '+String.join(new List<String>(accFields),', ')+' From Account Where Id = :accountId Limit 1';
            System.debug('accQuery:::'+accQuery);
            List<Account> accountInfo = Database.query(accQuery);
            
            Account_Scoring__c acs;
            for(Scoring_Model__c sm:scoringModelMap.values()){
                acs = new Account_Scoring__c(Account__c = a.Id,History__c = false, Date__c = System.today(), Scoring_Model_ID__c = sm.Id, Scoring_Model__c = sm.Name, Previous_Display_Type__c = PreviousDisplayType);
                scoringAccountScoringMap.put(sm.Id,acs);
            }
            
            if(scoringAccountScoringMap != null && scoringAccountScoringMap.keySet().size() > 0) {
                insert scoringAccountScoringMap.values();
            }
            
            // process account scoring
            for(Account acc: accountInfo){
                Account_Scoring_Item__c accScoringItem;
                
                for(Scoring_Model__c sm:scoringModelMap.values()){
                    
                    for(Scoring_Item__c si:sm.Scoring_Items__r){
                        
                        accScoringItem = new Account_Scoring_Item__c();
                        accScoringItem.Account_Scoring__c = scoringAccountScoringMap.get(sm.Id).Id;
                        accScoringItem.Scoring_Item_ID__c = si.Id;
                        accScoringItem.Scoring_Item__c = si.Name;
                        accScoringItem.Value__c = 0;
                        
                        accScoringItem.Score__c = 0;
                        
                        double maxValueOverall = 0;
                        if(maxValueOverall < sm.Green_Overall_Score_To__c){
                            maxValueOverall = sm.Green_Overall_Score_To__c;
                        }
                        if(maxValueOverall < sm.Yellow_Overall_Score_To__c){
                            maxValueOverall = sm.Yellow_Overall_Score_To__c;
                        }
                        if(maxValueOverall < sm.Red_Overall_Score_To__c){
                            maxValueOverall = sm.Red_Overall_Score_To__c;
                        }
                        
                        double maxValueMetric = 0;
                        if(maxValueMetric < si.Green_Score_To__c){
                            maxValueMetric = si.Green_Score_To__c;
                        }
                        if(maxValueMetric < si.Yellow_Score_To__c){
                            maxValueMetric = si.Yellow_Score_To__c;
                        }
                        if(maxValueMetric < si.Red_Score_To__c){
                            maxValueMetric = si.Red_Score_To__c;
                        }
                        
                        double NormalizeValue = 0;
                        if(maxValueOverall != 0 && maxValueMetric != 0){
                            NormalizeValue = maxValueOverall / maxValueMetric;
                        }
                        
                        double normalizeGreenFrom = 0;
                        double normalizeGreenTo = 0;
                        double normalizeYellowFrom = 0;
                        double normalizeYellowTo = 0;
                        double normalizeRedFrom = 0;
                        double normalizeRedTo = 0;
                        
                        if(si.Green_Score_From__c != null ){
                            normalizeGreenFrom = si.Green_Score_From__c * NormalizeValue;
                        }
                        if(si.Green_Score_To__c != null ){
                            normalizeGreenTo = si.Green_Score_To__c * NormalizeValue;
                        }
                        if(si.Yellow_Score_From__c != null ){
                            normalizeYellowFrom = si.Yellow_Score_From__c * NormalizeValue;
                        }
                        if(si.Yellow_Score_To__c != null ){
                            normalizeYellowTo = si.Yellow_Score_To__c * NormalizeValue;
                        }
                        if(si.Red_Score_From__c != null ){
                            normalizeRedFrom = si.Red_Score_From__c * NormalizeValue;
                        }
                        if(si.Red_Score_To__c != null ){
                            normalizeRedTo = si.Red_Score_To__c * NormalizeValue;
                        }
                        
                        
                        if(acc.get(si.Scoring_Field_API_Name__c) != null){ 
                        	system.debug('Pre Normalized value: ' + Double.valueOf(acc.get(si.Scoring_Field_API_Name__c)));
                        	accScoringItem.Value__c = Double.valueOf(acc.get(si.Scoring_Field_API_Name__c));
                        	system.debug('Pre Normalized value passed: ' + accScoringItem.value__c);
                       		system.debug('Normalize value used: ' + NormalizeValue);
                            accScoringItem.Score__c = Double.valueOf(acc.get(si.Scoring_Field_API_Name__c)) * NormalizeValue ; 
                            system.debug('Post Normalization value: ' + accScoringItem.score__c);
                        }
                        else if(si.Default_Score_Value__c != null ){
                        	accScoringItem.Value__c = Double.valueOf(acc.get(si.Scoring_Field_API_Name__c));
                            accScoringItem.Score__c = si.Default_Score_Value__c * NormalizeValue;
                        }
                        
                         
                        if(accScoringItem.Score__c >= normalizeRedFrom && accScoringItem.Score__c <= normalizeRedTo){
                            accScoringItem.Display_Type__c = 'Red';
                        }
                        else if(accScoringItem.Score__c >= normalizeYellowFrom && accScoringItem.Score__c <= normalizeYellowTo){
                            accScoringItem.Display_Type__c = 'Yellow';
                        }
                        else if(accScoringItem.Score__c >= normalizeGreenFrom && accScoringItem.Score__c <= normalizeGreenTo){
                            accScoringItem.Display_Type__c = 'Green';
                        }
                        
                        accScoringItem.Normalized_Score__c = accScoringItem.Score__c ;
                        if(si.Scoring_Weight__c != null && si.Scoring_Weight__c != 0 ){
                        	
                            accScoringItem.Score__c = accScoringItem.Score__c * si.Scoring_Weight__c;
                        }
                         
                        accScoringItemToBeInserted.add(accScoringItem);
                    }
                }
            }
            
            if(accScoringItemToBeInserted != null && accScoringItemToBeInserted.size() > 0) {
                // create account scoring items
                insert accScoringItemToBeInserted;
            }
            
            List<Account_Scoring__c> listAS = new List<Account_Scoring__c>();
            SET<ID> setScoringModel = new SET<ID>();
            
            for(Account_Scoring__c s: [Select Id,Scoring_Model_ID__r.Green_Overall_Score_From__c,Scoring_Model_ID__r.Red_Overall_Score_From__c,Scoring_Model_ID__r.Green_Overall_Score_To__c,
                                        Scoring_Model_ID__r.Yellow_Overall_Score_To__c,Scoring_Model_ID__r.Red_Overall_Score_To__c,Scoring_Model_ID__r.Yellow_Overall_Score_From__c,
                                        Scoring_Model_ID__c,Display_Type__c,Aggregate_Score__c From Account_Scoring__c Where Id IN: scoringAccountScoringMap.values()]){
                
                if(s.Aggregate_Score__c >= s.Scoring_Model_ID__r.Red_Overall_Score_From__c && s.Aggregate_Score__c <= s.Scoring_Model_ID__r.Red_Overall_Score_To__c){
                    s.Display_Type__c = 'Red';
                }
                else if(s.Aggregate_Score__c >= s.Scoring_Model_ID__r.Yellow_Overall_Score_From__c && s.Aggregate_Score__c <= s.Scoring_Model_ID__r.Yellow_Overall_Score_To__c){
                    s.Display_Type__c = 'Yellow';
                }
                else if(s.Aggregate_Score__c >= s.Scoring_Model_ID__r.Green_Overall_Score_From__c && s.Aggregate_Score__c <= s.Scoring_Model_ID__r.Green_Overall_Score_To__c){
                    s.Display_Type__c = 'Green';
                }
                
                setScoringModel.add(s.Scoring_Model_ID__c);
                listAS.add(s);
            }
            
            // update Account Scoring
            update listAS;
            
            
            List<Account_Scoring__c> listASHistory = new List<Account_Scoring__c>();
            
            for(Account_Scoring__c s: [Select Id,History__c From Account_Scoring__c Where Account__c =: a.Id AND Scoring_Model_ID__c IN: setScoringModel AND ID NOT IN:listAS  AND History__c = false]){
                 
                s.History__c = true;
                listASHistory.add(s);
            }
            
            // update Account Scoring history
            update listASHistory;
            
        }
    }

    public void finish(database.batchableContext bc){ 
        
    }
}