force-app/main/default/objects/VCG_CPQ_Approval_Condition__c/VCG_CPQ_Approval_Condition__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Approval Condition</label>
    <nameField>
        <label>VCG CPQ Approval Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Approval Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Approval_Group__c/VCG_CPQ_Approval_Group__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Approval Group</label>
    <nameField>
        <label>Approval Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Approval Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Approval__c/VCG_CPQ_Quote_Approval__c.object-meta.xml
<CustomObject>
    <label>Quote Approval</label>
    <nameField>
        <label>Quote Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Approval__c/fields/Approval_Condition__c.field-meta.xml
<CustomField>
    <fullName>Approval_Condition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Condition</label>
    <referenceTo>VCG_CPQ_Approval_Condition__c</referenceTo>
    <relationshipLabel>Quote Approvals</relationshipLabel>
    <relationshipName>Quote_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Approval__c/fields/Approval_Group__c.field-meta.xml
<CustomField>
    <fullName>Approval_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Group</label>
    <referenceTo>VCG_CPQ_Approval_Group__c</referenceTo>
    <relationshipLabel>Quote Approvals</relationshipLabel>
    <relationshipName>Quote_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Approval__c/fields/Approval_Reason__c.field-meta.xml
<CustomField>
    <fullName>Approval_Reason__c</fullName>
    <label>Approval Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Approval__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Approvals</relationshipLabel>
    <relationshipName>Quote_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VCG_CPQ_Approval_Email_Controller.cls
public without sharing class VCG_CPQ_Approval_Email_Controller {
    
    public String quoteId {get;set;}
    public String recipientId {get;set;}
    public boolean showEmailMessage{get;set;}

    public List<VCG_CPQ_Quote_Approval__c> quoteApprovalList {get;set;}
    
    public VCG_CPQ_Approval_Email_Controller(){
        showEmailMessage = true;
    
    }
    
    public List<VCG_CPQ_Quote_Approval__c> getQuoteApprovals(){
        System.debug('Called getQuoteApprovals');
        System.debug('Quote Id : ' + quoteId);
        System.debug('recipientId : ' + recipientId);       


        Map<Id, ProcessInstance> instanceMap = new Map<Id, ProcessInstance>([SELECT Id, TargetObject.Name, TargetObjectID, TargetObject.Type 
                                                                            FROM ProcessInstance 
                                                                            WHERE TargetObjectId= :quoteId]);
        
        //Process Instance Step  -> Queue ID
        Map<Id, ProcessInstanceWorkItem> workItemMap = new Map<Id, ProcessInstanceWorkItem>([SELECT Id, ActorId 
                                                                                        FROM ProcessInstanceWorkItem 
                                                                                        WHERE ProcessInstanceId in :instanceMap.keySet()]);

        Set<Id> groupIds = new Set<Id>();
        Set<Id> userIds = new Set<Id>();
        for(ProcessInstanceWorkItem workItem : workItemMap.values()){
            if(workItem.ActorId.getSObjectType().getDescribe().getName() == 'User'){
                userIds.add(workItem.ActorId);
            }
            else if(workItem.ActorId.getSObjectType().getDescribe().getName() == 'Group'){
                groupIds.add(workItem.ActorId); 
            }
System.debug('workItem : ' + workItem.ActorId.getSObjectType().getDescribe().getName());                        
        }

        if(groupIds != null && groupIds.size() > 0){
            showEmailMessage = false;
        }
        
        Map<Id, Group> groups = new Map<Id, Group>([SELECT Id, Name, DeveloperName, Type 
                                                    FROM Group 
                                                    WHERE Type='Queue' AND Id in :groupIds]);
                                                    
System.debug('groups : ' + groups);
        
        Map<Id, User> users = new Map<Id, User>([SELECT Id, Name 
                                                FROM User
                                                Where Id in :userIds]);
               
        
        List<String> groupNames = new List<String>();
        for(Group zgroup : groups.values()){
            groupNames.add(zgroup.DeveloperName);
        }              
        
        Map<Id, VCG_CPQ_Approval_Group__c> approvalGroups = new Map<Id, VCG_CPQ_Approval_Group__c>([SELECT Id, Queue_Name__c 
                                                                                                    FROM VCG_CPQ_Approval_Group__c 
                                                                                                    WHERE Queue_Name__c in :groupNames]);

System.debug('approvalGroups : ' + approvalGroups); 
    
        quoteApprovalList = [SELECT Id, Name, Quote__c, Approval_Reason__c, Approval_Condition__r.Name, Approval_Group__r.Id, Approval_Group__r.Name, Approver__c 
                                FROM VCG_CPQ_Quote_Approval__c 
                                WHERE Quote__c = :quoteId
                                AND (Approval_Group__c in :approvalGroups.keySet() OR Approver__c in :users.keySet())];
        
System.debug('quoteApprovalList : ' + quoteApprovalList);       
        return quoteApprovalList;
        
        
        
    }
}