force-app/main/default/objects/VCG_CPQ_Approval_Condition__c/VCG_CPQ_Approval_Condition__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Approval Condition</label>
    <nameField>
        <label>VCG CPQ Approval Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Approval Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Approval_Condition__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Mark this + Is Deployed for fully active rules. If this is set but Is Deployed is not, then this rule will be applied only to users listed in VCG_CPQ_Options.Run_Un_Deployed_Components custom setting. If Is Active is false, this rule won&apos;t run for anyone.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Approval_Condition__c/fields/Needs_Fields__c.field-meta.xml
<CustomField>
    <fullName>Needs_Fields__c</fullName>
    <description>Code begins evaluating conditions at the Quote level. Fields and Relationships should be assigned accordingly.</description>
    <inlineHelpText>Code begins evaluating conditions at the Quote level. Fields and Relationships should be assigned accordingly.</inlineHelpText>
    <label>Needs Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure__c/VCG_CPQ_Pricing_Procedure__c.object-meta.xml
<CustomObject>
    <label>VCG CPQ Pricing Procedure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VCG CPQ Pricing Procedures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure__c/fields/Quote_Line_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Type__c</fullName>
    <inlineHelpText>&apos;Header&apos; pricing procedures are applied to the quote as a whole. &apos;All&apos; pricing procedures are applied to all line items -- &apos;New&apos;, &apos;Renewal&apos;, etc.</inlineHelpText>
    <label>Quote Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Extension</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Decommission</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Pricing_Procedure__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The sequence in which the Pricing Procedure record should be executed. Allows for a mix of header calculations and line item calculations.</description>
    <label>Sequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores this Quotes Lookup for use in mapping to the Opportunity for the Primary Quote</description>
    <label>Quote ***</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Ran_Approvals__c.field-meta.xml
<CustomField>
    <fullName>Ran_Approvals__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ran Approvals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Ready_For_Approval__c.field-meta.xml
<CustomField>
    <fullName>Ready_For_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready For Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/VCG_CPQ_Quote_Product__c.object-meta.xml
<CustomObject>
    <description>An individual line item on a quote</description>
    <label>Quote Product</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCG_CPQ_NeedsFieldsUtility_Test.cls
/* This class is written to improve the coverage of Class :VCG_CPQ_NeedsFieldsUtility. 
Hence if something fails, then this class can be modified or even deleted as this doesn't validate any functionality */
@isTest(SeeAllData=True)
public class VCG_CPQ_NeedsFieldsUtility_Test 
{   
    Static Testmethod void Test1()
    {   
        
        Account acc = new Account(Name='Test Account');
        insert acc;     
        
        Opportunity Opp = new Opportunity(Name='Test Opportunity', Order_Type__c = 'New',  StageName = 'Sales Acceptance',
                                         CloseDate = System.today()+10);
        insert Opp;  
        
        VCG_CPQ_Quote__c testQuote = new VCG_CPQ_Quote__c(Account__c = acc.Id, Total__c = 1001, OwnerId = UserInfo.getUserId(), 
                                                          Ready_For_Approval__c = false, Ran_Approvals__c = false, Opportunity__c=Opp.Id);
        insert testQuote;    
        
        VCG_CPQ_Approval_Condition__c apprCondition = new VCG_CPQ_Approval_Condition__c(Name ='TestApproval',Needs_Fields__c='Account__c',IsActive__c=True);
        insert apprCondition;    
        
        List<VCG_CPQ_Pricing_Procedure__c> lstVCG_CPQ_Pricing_Procedure = new List<VCG_CPQ_Pricing_Procedure__c>();
        VCG_CPQ_Pricing_Procedure__c pricingProcedure;
        for(Integer i=0;i<2;i++)
        {
            pricingProcedure = new VCG_CPQ_Pricing_Procedure__c();
            pricingProcedure.Name='TestPricingProcedure'+i;
            pricingProcedure.Needs_Fields__c = 'Account__c';
            pricingProcedure.Active__c=True;
            pricingProcedure.Description__c='TestPricingProcedure'+i;          
            pricingProcedure.Sequence__c=0.015+i;
            if(i==0){pricingProcedure.Quote_Line_Type__c = 'Header';} 
            else {pricingProcedure.Quote_Line_Type__c = 'TestHeader';} 
            lstVCG_CPQ_Pricing_Procedure.add(pricingProcedure);
        }
        Insert lstVCG_CPQ_Pricing_Procedure;
        
        VCG_CPQ_Quote__c testQuote1=[Select id, name, Account__c, Total__c, OwnerId, Ready_For_Approval__c,Ran_Approvals__c
                                    from VCG_CPQ_Quote__c where id=: testQuote.Id];
        
        Map<SObject, String> mapToPass= new Map<SObject, String>();
        String TestString = 'Account__c;Total__c';//Account__r.Name;Opportunity__r.Name'; //Quote__r/.Total__c/; Account__c';Quote__r.Account__r.Name
        mapToPass.put(testQuote1, TestString);
        List<sObject> sObjs = new List<sObject>();
        sObjs = VCG_CPQ_NeedsFieldsUtility.getNeedsFields(mapToPass);
        String TestString1 = 'Opportunity__r/.Name;Account.Name'; 
        try
        {
            mapToPass.put(testQuote1, TestString1);
            sObjs = VCG_CPQ_NeedsFieldsUtility.getNeedsFields(mapToPass);
        }
        catch(Exception e){}
        System.assert(!sObjs.isEmpty());
        List<sObject> sObjs1 = new List<sObject>();
        sObjs1 = VCG_CPQ_NeedsFieldsUtility.getNeedsFields(sObjs,TestString);
         try
        {
            mapToPass.put(testQuote1, TestString);
            sObjs1 = VCG_CPQ_NeedsFieldsUtility.getNeedsFields(sObjs,TestString1);
        }
        catch(Exception e){}
        Map<String,List<String>> mapStrLstString = new Map<String,List<String>>();
        mapStrLstString = VCG_CPQ_NeedsFieldsUtility.getAllNeedsFields();
        Map<String,Map<String,List<sObject>>> mapMapLstSobj = new  Map<String,Map<String,List<sObject>>>();
        mapMapLstSobj = VCG_CPQ_NeedsFieldsUtility.GetNeedsFieldsSources();
        List<String> lstString = new List<String>();
        lstString = VCG_CPQ_NeedsFieldsUtility.getNeedsFields('Product2');
        lstString = VCG_CPQ_NeedsFieldsUtility.getNeedsFields('Product1');
        map<String, String> rawNeedsFields = new map<string, string>{'VCG_CPQ_Quote__c' => 'Quote_Products__r.Name ;Opportunity__r.Name',
                                                                    'VCG_CPQ_Quote_Product__c' => 'Quote__r.Opportunity__r.Name;Quote__r.Name'};
        mapStrLstString = VCG_CPQ_NeedsFieldsUtility.ProcessRawNeedsFields(rawNeedsFields);            
    }
}