force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <inlineHelpText>Contract Term in Months</inlineHelpText>
    <label>Contract Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores this Quotes Lookup for use in mapping to the Opportunity for the Primary Quote</description>
    <label>Quote ***</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/VCG_CPQ_Quote_Product__c.object-meta.xml
<CustomObject>
    <description>An individual line item on a quote</description>
    <label>Quote Product</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <description>Contract Term in months</description>
    <inlineHelpText>Contract Term in months.</inlineHelpText>
    <label>Contract Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/License_Metric_Quantity__c.field-meta.xml
<CustomField>
    <fullName>License_Metric_Quantity__c</fullName>
    <label>License Metric Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteEditShipmentScheduleController_Test.cls
/*
 *  @author:        Mark De Chavez | mark.dechavez@cloudsherpas.com
 *  @description:   Test class for QuoteEditShipmentScheduleController.
 *  @date-created:  September 23, 2014
 *  @revision: 
 */

@isTest(SeeAllData=True)
public class QuoteEditShipmentScheduleController_Test {

    static testMethod void testRedirectToEditShipmentSched(){
        Account acc = new Account(Name='TestAcc', Phone='838-77-03', 
                                  Account_Type__c='Association', /*District__c='Canada',*/ 
                                  QWBS_Market__c='T&L', QWBS_Status__c='Active Prospect', BillingCountry='USA');
        insert acc;
       
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId = acc.Id, 
                                          CloseDate=date.today(), StageName='Sales Acceptance');
        insert opp;
        
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c(Account__c=acc.Id, Opportunity__c = opp.Id, 
                                                      Effective_Date__c = date.today(), Contract_Term__c=5);
        insert quote;
        
        Product2 p2 = TestUtils.getProduct('ut prod2', 'Omnitracs');
        p2.Shipment_Schedule_Required__c = TRUE;
        p2.ProductCode = 'OMNI';
        insert p2;
        
        VCG_CPQ_Quote_Product__c quoteProd = new VCG_CPQ_Quote_Product__c(Quote__c=quote.Id, License_Metric_Quantity__c=1, Product__c=p2.Id);
        insert quoteProd;
        
        Test.startTest();
            PageReference currentPage = page.QuoteEditShipmentSchedule;
            Test.setCurrentPage(currentPage);
            //Set the URL parameter
            System.currentPageReference().getParameters().put('id', quote.Id);
        
            QuoteEditShipmentScheduleController controller = new QuoteEditShipmentScheduleController();
        
            //Verify the parameters
            System.assertEquals('/apex/EditShipmentSchedule?id='+quoteProd.id+'&passedQuoteId='+quote.id, controller.redirectToEditShipmentSched().getURL());
        Test.stopTest();
    }
    
    static testMethod void testredirectToRecordsView(){
        Account acc = new Account(Name='TestAcc', Phone='838-77-03', 
                                  Account_Type__c='Association', /*District__c='Canada',*/ 
                                  QWBS_Market__c='T&L', QWBS_Status__c='Active Prospect', BillingCountry='US');
        insert acc;
       
        Opportunity opp = new Opportunity(Name='TestOpp', AccountId = acc.Id, 
                                          CloseDate=date.today(), StageName='Sales Acceptance');
        insert opp;
        
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c(Account__c=acc.Id, Opportunity__c = opp.Id, 
                                                      Effective_Date__c = date.today(), Contract_Term__c=5);
        insert quote;
        
        VCG_CPQ_Quote_Product__c quoteProd = new VCG_CPQ_Quote_Product__c(Quote__c=quote.Id, License_Metric_Quantity__c=1);
        insert quoteProd;
        
        Test.startTest();
            PageReference currentPage = page.QuoteEditShipmentSchedule;
            Test.setCurrentPage(currentPage);
            //Set the URL parameter
            System.currentPageReference().getParameters().put('id', quote.Id);
        
            QuoteEditShipmentScheduleController controller = new QuoteEditShipmentScheduleController();
            System.assertEquals('/'+String.valueOf(quote.Id).substring(0, 15), controller.redirectToEditShipmentSched().getURL());
        Test.stopTest();
    }
    
}