force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores this Quotes Lookup for use in mapping to the Opportunity for the Primary Quote</description>
    <label>Quote ***</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/VCG_CPQ_Quote_Product__c.object-meta.xml
<CustomObject>
    <description>An individual line item on a quote</description>
    <label>Quote Product</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/VCG_CPQ_Data_Test.cls
/**
 * Test the VCG_CPQ_Data class
 *
 * @author  Lawrence Coffin <lawrence.coffin@cloudsherpas.com>
 * @since   5.Aug.2014
 */
@isTest
private class VCG_CPQ_Data_Test {

    static testMethod void testInMemoryChildren() {
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c( );
        
        Product2 prod1 = new Product2( Name = 'Test Product 1', ProductCode = 'Test-111' );
        Product2 prod2 = new Product2( Name = 'Test Product 2', ProductCode = 'Test-222' );
        Product2 prod3 = new Product2( Name = 'Test Product 3', ProductCode = 'Test-333' );
        
        VCG_CPQ_Quote_Product__c qp1 = new VCG_CPQ_Quote_Product__c( Name = 'QP 1', Quote__r = quote, Product__r = prod1 );
        VCG_CPQ_Quote_Product__c qp2 = new VCG_CPQ_Quote_Product__c( Name = 'QP 2', Quote__r = quote, Product__r = prod2 );
        VCG_CPQ_Quote_Product__c qp3 = new VCG_CPQ_Quote_Product__c( Name = 'QP 3', Quote__r = quote, Product__r = prod3 );
        
        // Test adding a single child
        VCG_CPQ_Data.addChild(quote, 'Quote_Products__r', qp1);
        
        // Test adding multiple children
        VCG_CPQ_Data.addChildren(quote, 'Quote_Products__r', new List<VCG_CPQ_Quote_Product__c>{ qp2, qp3 });
        
        // Now test retriving the children
        List<VCG_CPQ_Quote_Product__c> qps = VCG_CPQ_Data.getChildren(quote, 'Quote_Products__r');
        System.assertEquals(3, qps.size());
        System.assertEquals('QP 1', qps[0].Name);
        System.assertEquals('QP 2', qps[1].Name);
        System.assertEquals('QP 3', qps[2].Name);
    }
    
    static testMethod void testFromDatabaseChildren() {
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c();
        insert quote;
        
        Product2 prod1 = new Product2( Name = 'Test Product 1', ProductCode = 'Test-111' );
        Product2 prod2 = new Product2( Name = 'Test Product 2', ProductCode = 'Test-222' );
        Product2 prod3 = new Product2( Name = 'Test Product 3', ProductCode = 'Test-333' );
        insert new List<Product2>{ prod1, prod2, prod3 };
        
        VCG_CPQ_Quote_Product__c qp1 = new VCG_CPQ_Quote_Product__c( Name = 'QP 1', Quote__c = quote.Id, Product__c = prod1.Id );
        VCG_CPQ_Quote_Product__c qp2 = new VCG_CPQ_Quote_Product__c( Name = 'QP 2', Quote__c = quote.Id, Product__c = prod2.Id );
        VCG_CPQ_Quote_Product__c qp3 = new VCG_CPQ_Quote_Product__c( Name = 'QP 3', Quote__c = quote.Id, Product__c = prod3.Id );
        insert new List<VCG_CPQ_Quote_Product__c>{ qp1, qp2, qp3 };
        
        VCG_CPQ_Quote__c quoteCopy = [
                                        SELECT Id,
                                               Name,
                                               (
                                                    SELECT Id,
                                                           Name,
                                                           Product__c,
                                                           Product__r.Name,
                                                           Product__r.ProductCode
                                                    FROM Quote_Products__r
                                                    ORDER BY Name
                                               )
                                        FROM VCG_CPQ_Quote__c
                                        WHERE Id = :quote.Id
                                     ][0];
        
        // Now test retriving the children
        List<VCG_CPQ_Quote_Product__c> qps = VCG_CPQ_Data.getChildren(quoteCopy, 'Quote_Products__r');
        System.assertEquals(3, qps.size());
        System.assertEquals('QP 1', qps[0].Name);
        System.assertEquals('QP 2', qps[1].Name);
        System.assertEquals('QP 3', qps[2].Name);
    }
    
    /**
     * This tests that the code handles different Quote Product records that have the
     * same Product, but are in different Product Groups.
     *
     * @author  Lawrence Coffin <lawrence.coffin@cloudsherpas.com>
     * @since   5.Aug.2014
     */
    static testMethod void testGroupedProducts() {
        VCG_CPQ_Quote__c quote = new VCG_CPQ_Quote__c( );
        
        Product2 prod = new Product2( Name = 'Test Product', ProductCode = 'Test-123' );
        
        VCG_CPQ_Quote_Product__c qp1 = new VCG_CPQ_Quote_Product__c( Name = 'QP 1', Quote__r = quote, Product__r = prod, Product_Group__c = 'Group 1' );
        VCG_CPQ_Quote_Product__c qp2 = new VCG_CPQ_Quote_Product__c( Name = 'QP 1', Quote__r = quote, Product__r = prod, Product_Group__c = 'Group 2' );
        
        // Test adding multiple children
        VCG_CPQ_Data.addChildren(quote, 'Quote_Products__r', new List<VCG_CPQ_Quote_Product__c>{ qp1, qp2 });
        
        // Now test retriving the children
        List<VCG_CPQ_Quote_Product__c> qps = VCG_CPQ_Data.getChildren(quote, 'Quote_Products__r');
        System.assertEquals(2, qps.size());
        System.assertEquals('QP 1',    qps[0].Name);
        System.assertEquals('Group 1', qps[0].Product_Group__c);
        System.assertEquals('QP 1',    qps[1].Name);
        System.assertEquals('Group 2', qps[1].Product_Group__c);
    }
}