force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Is_Primary__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Primary?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Stores this Quotes Lookup for use in mapping to the Opportunity for the Primary Quote</description>
    <label>Quote ***</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/VCG_CPQ_Quote_Product__c.object-meta.xml
<CustomObject>
    <description>An individual line item on a quote</description>
    <label>Quote Product</label>
    <nameField>
        <label>Part Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Number_of_Shipment_Forecasts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Shipment_Forecasts__c</fullName>
    <label>Number of Shipment Forecasts</label>
    <summaryForeignKey>Shipment_Forecast__c.Quote_Product__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VCG_CPQ_Quote_Product__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>VCG_CPQ_Quote__c</referenceTo>
    <relationshipLabel>Quote Products</relationshipLabel>
    <relationshipName>Quote_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
    public static void onBeforeUpdate(List<Opportunity> newOppList, Map<Id, Opportunity> oldOppMap){
        oppStageOnChange(newOppList, oldOppMap);
    }
    
    private static void oppStageOnChange(List<Opportunity> newOppList, Map<Id, Opportunity> oldOppMap){
        for (Opportunity newOpp : newOppList) {
            Opportunity oldOpp = oldOppMap.get(newOpp.Id);
            if (oldOpp.StageName != newOpp.StageName && newOpp.StageName == 'Closed Won') {
                List<VCG_CPQ_Quote_Product__c> checkList  = [SELECT Id 
                                                             FROM VCG_CPQ_Quote_Product__c 
                                                             WHERE Product__r.Shipment_Schedule_Required__c = TRUE 
                                                             AND Quote__r.Is_Primary__c = TRUE 
                                                             AND Number_of_Shipment_Forecasts__c = 0 
                                                             AND Quote__r.Opportunity__c = : newOpp.Id];
                if (checkList.size() > 0){
                    newOpp.addError('Cannot change Opportunity Stage. There are missing Shipment Schedules for Products that require them.');
                }
            }
        }
    }
    
}