force-app/main/default/objects/VCG_CPQ_Quote__c/VCG_CPQ_Quote__c.object-meta.xml
<CustomObject>
    <description>A quote object storing the proposal(s) and line items.</description>
    <label>Quote_vcg</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes_vcg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VCG_CPQ_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/salesInfoXRSQuotes_Test.cls
@istest(seeAllData=true)
private class salesInfoXRSQuotes_Test{
static testmethod void salesInfoXRSQuotesTest()
{
salesInfoXRSQuotes item = new salesInfoXRSQuotes();

Opportunity oppty = new Opportunity();
List<VCG_CPQ_Quote__c> lstquot = [SELECT Id,Opportunity__c FROM VCG_CPQ_Quote__c WHERE Opportunity__c != null Limit 1];
for(VCG_CPQ_Quote__c objquot:lstquot)
{   
    item.OpportunityId = objquot.Opportunity__c;
    String baseURL = item.baseURL;
    VCG_CPQ_Quote__c newQuote = item.objQuote;
    opportunity newOppty = item.objOpportunity;
    List<opportunityLineItem> newlstOppty= item.lstOpportunityProduct;
}
}
}