force-app/main/default/objects/AR_10_Day_Demand_Letter__c/AR_10_Day_Demand_Letter__c.object-meta.xml
<CustomObject>
    <description>Tracking Accounts Receivable service shutdown approvals/processes due to outstanding customer balance.</description>
    <label>AR 10 Day Letter Request</label>
    <nameField>
        <displayFormat>REQ-{000000}</displayFormat>
        <label>AR Service Shutdowns Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AR 10 Day Letter Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AR_10_Day_Demand_Letter__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AR 10 Day Letter Request</relationshipLabel>
    <relationshipName>R00N50000001eBimEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AR_10_Day_Demand_Letter__c/fields/CSR__c.field-meta.xml
<CustomField>
    <fullName>CSR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Service Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N50000001eBioEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestAR10DayLetterRequest.cls
@isTest(SeeAllData=true)
public class TestAR10DayLetterRequest {
    
    static testmethod void testAR10DayDemandLetter() {
        
      Account sampleCustomerAcct = [SELECT Id, Name FROM Account LIMIT 1];  
      AR_10_Day_Demand_Letter__c newAR10DayRecord = new AR_10_Day_Demand_Letter__c();
      newAR10DayRecord.Account__c = sampleCustomerAcct.Id;                                  
      insert newAR10DayRecord;      
      
      AR_10_Day_Demand_Letter__c savedRecord = [Select Id, CSR__c from AR_10_Day_Demand_Letter__c where Id = :newAR10DayRecord.ID];    
      //System.assertNotEquals(null, savedRecord.CSR__c);
    }
}