force-app/main/default/objects/Serialized_Unit_Summary__c/Serialized_Unit_Summary__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for CustomObject.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Serialized Unit Summary</label>
    <nameField>
        <label>SU Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Unit Summarys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Unit Summarys</relationshipLabel>
    <relationshipName>SU_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OV</fullName>
            </value>
            <value>
                <fullName>OVT</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>OX</fullName>
            </value>
            <value>
                <fullName>OX2</fullName>
            </value>
            <value>
                <fullName>OV2</fullName>
            </value>
            <value>
                <fullName>OVM</fullName>
            </value>
            <value>
                <fullName>MCP110</fullName>
            </value>
            <value>
                <fullName>TT210</fullName>
            </value>
            <value>
                <fullName>MCP50</fullName>
            </value>
            <value>
                <fullName>IVG</fullName>
            </value>
            <value>
                <fullName>TT150</fullName>
            </value>
            <value>
                <fullName>CEVS</fullName>
            </value>
            <value>
                <fullName>AMGC</fullName>
            </value>
            <value>
                <fullName>IVG-SM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The count of the units with the specified Item Type</description>
    <label>Number of Units</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>Hidden field used to update Serialized Unit Counts</description>
    <formula>Account__c &amp;&apos;-&apos;&amp;TEXT( Item_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UniqueKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/Serialized_Unit_Summary_Archive__c.object-meta.xml
<CustomObject>
    <description>Object is used to temporarily store Serialized Units during batch processing</description>
    <label>Serialized Unit Summary Archive</label>
    <nameField>
        <label>SUS Archive</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Unit Summary Archive</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Unit Summary Archive</relationshipLabel>
    <relationshipName>SU_Summary_Archive</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>MCP110</fullName>
            </value>
            <value>
                <fullName>MCP50</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OV</fullName>
            </value>
            <value>
                <fullName>OV2</fullName>
            </value>
            <value>
                <fullName>OVM</fullName>
            </value>
            <value>
                <fullName>OVT</fullName>
            </value>
            <value>
                <fullName>OX</fullName>
            </value>
            <value>
                <fullName>OX2</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>TT210</fullName>
            </value>
            <value>
                <fullName>CEVS</fullName>
            </value>
            <value>
                <fullName>AMGC</fullName>
            </value>
            <value>
                <fullName>IVG-SM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <formula>Account__c &amp;&apos;-&apos;&amp;TEXT( Item_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UniqueKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/Serialized_Units__c.object-meta.xml
<CustomObject>
    <label>Serialized Unit</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Units__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account related to this Serialized Unit</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Units</relationshipLabel>
    <relationshipName>R00N50000001eVUXEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMGC</fullName>
            </value>
            <value>
                <fullName>CEVS</fullName>
            </value>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>GTL</fullName>
            </value>
            <value>
                <fullName>IVG</fullName>
            </value>
            <value>
                <fullName>IVG-SM</fullName>
            </value>
            <value>
                <fullName>MCP110</fullName>
            </value>
            <value>
                <fullName>MCP50</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OV</fullName>
            </value>
            <value>
                <fullName>OV2</fullName>
            </value>
            <value>
                <fullName>OVM</fullName>
            </value>
            <value>
                <fullName>OVT</fullName>
            </value>
            <value>
                <fullName>OX</fullName>
            </value>
            <value>
                <fullName>OX2</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>TT150</fullName>
            </value>
            <value>
                <fullName>TT210</fullName>
            </value>
            <value>
                <fullName>XRS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>Hidden field used to update Serialized Unit Summary counts</description>
    <formula>Account__c &amp;&apos;-&apos;&amp;TEXT( Item_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UniqueKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SerializedUnitSummaryBatch.cls
/*********************************************************************
Name : SerializedUnitSummaryBatch
Author : David Ragsdale / Shruti Karn
Date : 9 June 2011

Usage : This class is used for updating the Serialized Unit Summaries in a daily batch process
       
Dependencies : Schedule Apex Process (used to start batch)

*********************************************************************/
global class SerializedUnitSummaryBatch implements Database.Batchable<sObject> 
{
    public String query = 'SELECT Account__c, Item_Type__c, uniqueKey__c from Serialized_Units__c ';
    
    //Batch process used to gather Serialized Units       
    global database.querylocator start(Database.BatchableContext BC)
    {   
        list<Serialized_Unit_Summary__c> lstSerializedUnitSummary = new list<Serialized_Unit_Summary__c>();
        
        lstSerializedUnitSummary = [Select id from Serialized_Unit_Summary__c limit 50000];
        
        //Delete ALL Serialized Unit Summary Records in preparation of running batch to recalculate
        if(!(lstSerializedUnitSummary.isEmpty()))
        {
            delete lstSerializedUnitSummary;
        }        
                
        return Database.getQueryLocator(query); 
    }
  
    //Batch method used to process Serialized Unit records
    global void execute(Database.BatchableContext BC, List<Serialized_Units__c> scope)
    {           
        
        //Used to store Serialized Units
        map<String, list<Serialized_Units__c>> mapKeySerializedUnit = new map<String, list<Serialized_Units__c>>();
        
        //Used to store Serialized Unit Summaries
        map<String, Serialized_Unit_Summary_Archive__c> mapKeySerUnitSumm = new map<String, Serialized_Unit_Summary_Archive__c>();
        
        //List of Serialized Unit Summaries used to update table
        list<Serialized_Unit_Summary_Archive__c> lstSerialUnitSummary = new list<Serialized_Unit_Summary_Archive__c>();
                
        for(Serialized_Units__c SerializedUnit : scope)
        {             
            //Creates a map of Unique Accounts
            if(!(mapKeySerializedUnit.containsKey(SerializedUnit.uniqueKey__c)))
            { 
                mapKeySerializedUnit.put(SerializedUnit.uniqueKey__c , new list<Serialized_Units__c>{SerializedUnit});
            }else{
                mapKeySerializedUnit.get(SerializedUnit.uniqueKey__c).add(SerializedUnit);
            }
        }
 
        // Queries for all Serialized unit Summary record inserted in previous batches having same unique key 
        lstSerialUnitSummary = [Select uniqueKey__c, Number_of_Units__c from Serialized_Unit_Summary_Archive__c where uniqueKey__c in :mapKeySerializedUnit.keySet() limit 50000];
        
        //creates a map of Unique Key and Serialized Unit record
        if(!(lstSerialUnitSummary.isEmpty()))
        {
            for(Serialized_Unit_Summary_Archive__c SummObj : lstSerialUnitSummary)
            {
                mapKeySerUnitSumm.put(SummObj.uniqueKey__c , SummObj );       
            }
            
        }

               
        lstSerialUnitSummary.clear();  
        
        for(String uniqueKey : mapKeySerializedUnit.keySet())
        {
            //Check if the Serialized Unit Summary record exists,
            //i.e, Serialized Unit Summary record  was inserted in any of the previous batches and then update it.
            if(mapKeySerUnitSumm.containsKey(uniqueKey))
            {
                mapKeySerUnitSumm.get(uniqueKey).Number_of_Units__c += mapKeySerializedUnit.get(uniqueKey).size(); 
                lstSerialUnitSummary.add(mapKeySerUnitSumm.get(uniqueKey));
            }
            else
            {
                Serialized_Unit_Summary_Archive__c newSerializedUnitSummary = new Serialized_Unit_Summary_Archive__c();
                newSerializedUnitSummary.Number_of_Units__c = mapKeySerializedUnit.get(uniqueKey).size();
                newSerializedUnitSummary.Account__c = mapKeySerializedUnit.get(uniqueKey).get(0).Account__c;
                newSerializedUnitSummary.item_type__c = mapKeySerializedUnit.get(uniqueKey).get(0).item_type__c;
                
                if(mapKeySerializedUnit.get(uniqueKey).get(0).Account__c != null)
                {
                    lstSerialUnitSummary.add(newSerializedUnitSummary);
                }
            }
        }

        if (lstSerialUnitSummary.size() > 0)
        {        
            try{
                upsert lstSerialUnitSummary;
            }
            catch(Exception e)
            {
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
               String[] toAddresses = new String[] {'c_skarn@qualcomm.com'};
               mail.setToAddresses(toAddresses);
               mail.setSubject('Error in Batch Apex ');
               mail.setPlainTextBody ('Error in :'+ scope);
               Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
        }
    }
         
    global void finish(Database.BatchableContext BC)
    {
        SerializedUnitSummaryUtils.updateSerializedUnitSummary();
    }   
}