force-app/main/default/objects/Serialized_Unit_Summary__c/Serialized_Unit_Summary__c.object-meta.xml
<CustomObject>
    <description>This is a generic template for CustomObject.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <label>Serialized Unit Summary</label>
    <nameField>
        <label>SU Summary</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Unit Summarys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Unit Summarys</relationshipLabel>
    <relationshipName>SU_Summaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OV</fullName>
            </value>
            <value>
                <fullName>OVT</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>OX</fullName>
            </value>
            <value>
                <fullName>OX2</fullName>
            </value>
            <value>
                <fullName>OV2</fullName>
            </value>
            <value>
                <fullName>OVM</fullName>
            </value>
            <value>
                <fullName>MCP110</fullName>
            </value>
            <value>
                <fullName>TT210</fullName>
            </value>
            <value>
                <fullName>MCP50</fullName>
            </value>
            <value>
                <fullName>IVG</fullName>
            </value>
            <value>
                <fullName>TT150</fullName>
            </value>
            <value>
                <fullName>CEVS</fullName>
            </value>
            <value>
                <fullName>AMGC</fullName>
            </value>
            <value>
                <fullName>IVG-SM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/NMC_System__c.field-meta.xml
<CustomField>
    <fullName>NMC_System__c</fullName>
    <label>NMC System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The count of the units with the specified Item Type</description>
    <label>Number of Units</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/Serialized_Unit_Summary_Archive__c.object-meta.xml
<CustomObject>
    <description>Object is used to temporarily store Serialized Units during batch processing</description>
    <label>Serialized Unit Summary Archive</label>
    <nameField>
        <label>SUS Archive</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Unit Summary Archive</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Unit Summary Archive</relationshipLabel>
    <relationshipName>SU_Summary_Archive</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>MCP110</fullName>
            </value>
            <value>
                <fullName>MCP50</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OV</fullName>
            </value>
            <value>
                <fullName>OV2</fullName>
            </value>
            <value>
                <fullName>OVM</fullName>
            </value>
            <value>
                <fullName>OVT</fullName>
            </value>
            <value>
                <fullName>OX</fullName>
            </value>
            <value>
                <fullName>OX2</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>TT210</fullName>
            </value>
            <value>
                <fullName>CEVS</fullName>
            </value>
            <value>
                <fullName>AMGC</fullName>
            </value>
            <value>
                <fullName>IVG-SM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Serialized_Unit_Summary_Archive__c/fields/Number_of_Units__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Units__c</fullName>
    <label>Number of Units</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/Serialized_Units__c.object-meta.xml
<CustomObject>
    <label>Serialized Unit</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serialized Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Serialized_Units__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Account related to this Serialized Unit</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Serialized Units</relationshipLabel>
    <relationshipName>R00N50000001eVUXEA2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMGC</fullName>
            </value>
            <value>
                <fullName>CEVS</fullName>
            </value>
            <value>
                <fullName>GT</fullName>
            </value>
            <value>
                <fullName>GTL</fullName>
            </value>
            <value>
                <fullName>IVG</fullName>
            </value>
            <value>
                <fullName>IVG-SM</fullName>
            </value>
            <value>
                <fullName>MCP110</fullName>
            </value>
            <value>
                <fullName>MCP50</fullName>
            </value>
            <value>
                <fullName>OT</fullName>
            </value>
            <value>
                <fullName>OV</fullName>
            </value>
            <value>
                <fullName>OV2</fullName>
            </value>
            <value>
                <fullName>OVM</fullName>
            </value>
            <value>
                <fullName>OVT</fullName>
            </value>
            <value>
                <fullName>OX</fullName>
            </value>
            <value>
                <fullName>OX2</fullName>
            </value>
            <value>
                <fullName>T2</fullName>
            </value>
            <value>
                <fullName>TT150</fullName>
            </value>
            <value>
                <fullName>TT210</fullName>
            </value>
            <value>
                <fullName>XRS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Serialized_Units__c/fields/NMC_System__c.field-meta.xml
<CustomField>
    <fullName>NMC_System__c</fullName>
    <label>NMC System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SerializedUnitSummaryUtils.cls
/*********************************************************************
Name : SerializedUnitSummaryUtils
Author : David Ragsdale / Shruti Karn
Date : 9 June 2011

Usage : Utility class for Serialized Unit Summary
       
Dependencies : SerializedUnitSummaryBatch.cls
 
*********************************************************************/
public class SerializedUnitSummaryUtils 
{   
//================  
//TEMP VALUE - REMOVE WHEN ALL CODE IS DEPLOYED 
public static string GetIDString(Serialized_Units__c serializedUnit) {
//  public static string GetIDString(Serialized_Unit__c serializedUnit) {

    string IdString = serializedUnit.Account__c == null ? ' _': serializedUnit.Account__c + '_';
    IdString += serializedUnit.Item_Type__c == null ? ' _' : serializedUnit.Item_Type__c;
    //IdString += serializedUnit.Item_Type__c == null ? ' _' : serializedUnit.Item_Type__c + '_';
    //IdString += serializedUnit.NMC_System__c == null ? ' ' : serializedUnit.NMC_System__c;
     return IdString;
  }
  public static string GetIDStringSummary(Serialized_Unit_Summary__c summary) {

    string IdString = summary.Account__c == null ? ' _' : summary.Account__c + '_';
    IdString += summary.Item_Type__c == null ? ' _' : summary.Item_Type__c;
    //IdString += summary.Item_Type__c == null ? ' _' : summary.Item_Type__c + '_';
    //IdString += summary.NMC_System__c == null ? ' ' : summary.NMC_System__c;
    return IdString;
  }
  public static void UpsertSummaryUnits(Map<string,Double> mpIdCountPair) {

    Map<string,Serialized_Unit_Summary__c> mpOriginal = GetSummaryUnits(mpIdCountPair);
    List<Serialized_Unit_Summary__c> lstInsertList = new List<Serialized_Unit_Summary__c>();
    List<Serialized_Unit_Summary__c> lstUpdateList = new List<Serialized_Unit_Summary__c>();
    List<Serialized_Unit_Summary__c> lstDeleteList = new List<Serialized_Unit_Summary__c>();

    Set<string> newKeySet = mpIdCountPair.keySet();
    string[] splitArr = null;

    Double value = 0;

    for(string key :newKeySet) {
      if(mpOriginal.containsKey(key))
      {
        Serialized_Unit_Summary__c tempSummary = mpOriginal.get(key);
        value = tempSummary.Number_of_Units__c + mpIdCountPair.get(key);
        if(value < 1)
        {
          system.debug('DELETE ==>'+ tempSummary);
          lstDeleteList.add(tempSummary);
        }
        else
        {
          tempSummary.Number_of_Units__c = value;
          system.debug('UPDATE ==>'+ tempSummary);
          lstUpdateList.add(tempSummary);
        }
      }
      else ///new record in summary
      {
         splitArr = key.split('_');

        Serialized_Unit_Summary__c serializedUnit = new Serialized_Unit_Summary__c();
        serializedUnit.Account__c = splitArr[0] != ' ' ? splitArr[0] : null;
        serializedUnit.Item_Type__c = splitArr[1] != ' ' ? splitArr[1] : null;
        //serializedUnit.NMC_System__c = splitArr[2] != ' ' ? splitArr[2] : null;
        serializedUnit.Number_of_Units__c = mpIdCountPair.get(key);

        if(!(serializedUnit.Number_of_Units__c < 1))
        {
          system.debug('INSERT ==>'+ serializedUnit);
          lstInsertList.add(serializedUnit);
        }
      }
    }

    UpdateAccountTeam.setAlreadyExecuted();
    if(lstInsertList.size() > 0) insert lstInsertList;
    if(lstUpdateList.size() > 0) update lstUpdateList;
    if(lstDeleteList.size() > 0) delete lstDeleteList;

  }
  
  public static Map<string,Serialized_Unit_Summary__c> GetSummaryUnits(Map<string,Double> mpIdCountPair) {

    System.debug('Map Parameter (mpIdCountPair) ==>'+ mpIdCountPair);
    List<string> lstAccounts = new List<string>();
    List<string> lstItemTypes = new List<string>();
   // List<string> lstNMCSystems = new List<string>();

    Set<string> keySet = mpIdCountPair.keySet();

    List<string> splitArr = new List<string>();
    for(string key :keySet) {
      splitArr = key.split('_');


      if(splitArr[0] != ' ') {
        lstAccounts.add(splitArr[0]);
      }
      else {
        lstAccounts.add(null);
      }

      if(splitArr[1] != ' ') {
        lstItemTypes.add(splitArr[1]);
      }
      else {
        lstItemTypes.add(null);
      }

     // if(splitArr[2] != ' ') {
       // lstNMCSystems.add(splitArr[2]);
      //}
      //else {
        //lstNMCSystems.add(null);
      //}
    }

   List<Serialized_Unit_Summary__c> lstSummary = new List<Serialized_Unit_Summary__c>(
                                    [SELECT Id,Account__c,Item_Type__c,Number_of_Units__c
                                     FROM  Serialized_Unit_Summary__c
                                     WHERE
                                     Account__c in :lstAccounts AND
                                     Item_Type__c in :lstItemTypes
                                      limit 1000]);


   Map<string,Serialized_Unit_Summary__c> mpIdNumber = new Map<string,Serialized_Unit_Summary__c>();
   string key = '';

   for(Serialized_Unit_Summary__c serializedSummary :lstSummary) {
     key = GetIDStringSummary(serializedSummary);
     if(!mpIdNumber.containsKey(key)) {
      mpIdNumber.put(key,serializedSummary);
     }
   }

   System.debug('####### Summary Map #######');
   System.debug(mpIdNumber);
   return mpIdNumber;
  }

//====================

    //After Archive is created, This method will delete existing records in Serialized Summary Utils table
    //and then update that table from the Archive.
    //This method is called from the finish method of the batch process
    public static void updateSerializedUnitSummary()
    {
        list<Serialized_Unit_Summary__c> lstSerializedUnitSummary = new list<Serialized_Unit_Summary__c>();

        for (Serialized_Unit_Summary_Archive__c serializedUnitSummaryArchive :
            [SELECT Account__c,Number_of_Units__c, Item_Type__c FROM Serialized_Unit_Summary_Archive__c limit 50000] )
        {
            Serialized_Unit_Summary__c newSerializedUnitSummary = new Serialized_Unit_Summary__c();
            
            newSerializedUnitSummary.Account__c = serializedUnitSummaryArchive.Account__c;
            newSerializedUnitSummary.Item_Type__c = serializedUnitSummaryArchive.Item_Type__c;
            newSerializedUnitSummary.Number_of_Units__c = serializedUnitSummaryArchive.Number_of_Units__c;
        
            lstSerializedUnitSummary.add(newSerializedUnitSummary);
        }
       
        if (lstSerializedUnitSummary.size() >0)
        {
            insert lstSerializedUnitSummary;
        }
    }
    
    /*****************************************************************************************************
    * USED ONLY FOR TEST METHODS 
    ********************************************************************************************************/
    public static void checkCount(Integer counter, Id accountId, string itemType, string nmcSystem) {

        List<Serialized_Unit_Summary__c> summary = 
            [Select Number_of_Units__c
                from Serialized_Unit_Summary__c
                where Account__c = :accountId 
                AND
                    Item_Type__c = :itemType 
                AND
                    NMC_System__c = :nmcSystem limit 1];

        if(counter == 0) 
        {
            //System.assertEquals(0,summary.size());
            return;
        }

        //System.assertEquals(counter, summary[0].Number_of_Units__c);
    }
    
    /*****************************************************************************************************
    * USED ONLY FOR TEST METHODS 
    ********************************************************************************************************/
    public static Serialized_Units__c GetSerializedUnit(Id accountId, String itemType, String nmcSystem) 
    {
        Serialized_Units__c serializedUnit = new Serialized_Units__c();
        serializedUnit.Account__c = accountId;
        serializedUnit.Item_Type__c = itemType;
        serializedUnit.NMC_System__c = nmcSystem;

        return serializedUnit;
    } 
}