force-app/main/default/objects/Contract_Term_Report__c/Contract_Term_Report__c.object-meta.xml
<CustomObject>
    <description>Created for Reporting Snaphot to allow Executive Reporting on Active Contracts in this Quarter vs. Previous Quarters (trend analysis) - Contract Term Reporting.  Populated from Informatica Cloud monthly.</description>
    <label>Contract Term Report</label>
    <nameField>
        <displayFormat>CTR--{0000000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Term Report</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Term_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/contractTermReportTest.cls
@isTest

public class contractTermReportTest {
    static testMethod void testContractTermReport(){
        Contract_Term_Report__c obj = new Contract_Term_Report__c();
        obj.Status__c = 'Active'; 
        insert obj;
        Test.startTest();
            ContractTermReportBatchClass obj1 = new ContractTermReportBatchClass();
            Id batchId = Database.executeBatch(obj1,200);
         Test.stopTest(); 
         System.assert(true);
    }
}