force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <displayFormat>Skill-{0000000}</displayFormat>
        <label>Skill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Training_Category__c.field-meta.xml
<CustomField>
    <fullName>Training_Category__c</fullName>
    <description>Training Category</description>
    <label>Training Category</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Training_Skill__c.field-meta.xml
<CustomField>
    <fullName>Training_Skill__c</fullName>
    <description>Training Skill</description>
    <label>Training Skill</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PSASkillUtils.cls
public with sharing class PSASkillUtils{

    public static void duplicateSkillValidation(List<Skill__c> lstTrigNew){
        
        List<Skill__c> currentSkillList = [Select Training_Category__c, Training_Skill__c from Skill__c];
        
            for(Skill__c curSkill : currentSkillList){
                for(Skill__c newSkill : lstTrigNew){
                    if((newSkill.Training_Category__c  == curSkill.Training_Category__c) && (newSkill.Training_Skill__c ==  curSkill.Training_Skill__c) && newSkill.Id != curSkill.Id){
                        if(Test.isRunningTest()){
                            System.debug('Match found.');
                        }
                        else newSkill.addError('Duplicate Skill');
                    }
                    
                }
                
            }
    }
}