force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <displayFormat>Skill-{0000000}</displayFormat>
        <label>Skill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Training_Category__c.field-meta.xml
<CustomField>
    <fullName>Training_Category__c</fullName>
    <description>Training Category</description>
    <label>Training Category</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Training_Skill__c.field-meta.xml
<CustomField>
    <fullName>Training_Skill__c</fullName>
    <description>Training Skill</description>
    <label>Training Skill</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PSASkillUtils_Test.cls
@isTest
private class PSASkillUtils_Test {
	static testMethod void myUnitTest() {
		// TO DO: implement unit test
		Skill__c testSkill1 = new Skill__c();
		testSkill1.Training_Category__c = 'Test Category';
		testSkill1.Training_Skill__c = 'Test Skill';
		insert testSkill1;
		
		Test.startTest();
			Skill__c testSkill2 = new Skill__c();
			testSkill2.Training_Category__c = 'Test Category';
			testSkill2.Training_Skill__c = 'Test Skill';
			insert testSkill2;
		Test.stopTest();
		}
}