force-app/main/default/objects/Objective_Action__c/Objective_Action__c.object-meta.xml
<CustomObject>
    <label>SP Action</label>
    <nameField>
        <label>SP Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SP Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective_Action__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <inlineHelpText>Drives color highlighting:
1.       Required (light green background)
2.       Not-Required (white/no background)
3.       Recommended (light yellow background)</inlineHelpText>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
                <default>true</default>
                <label>Not Required</label>
            </value>
            <value>
                <fullName>Highly Recommended</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective_Action__c/fields/Opportunity_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Order_Type__c</fullName>
    <inlineHelpText>If Required to Advance is checked, specify the Order Types for which it is required.</inlineHelpText>
    <label>Opportunity Order Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AddOn</fullName>
            </value>
            <value>
                <fullName>Annual Increase Within Term</fullName>
            </value>
            <value>
                <fullName>Auto Renewal With Increase</fullName>
            </value>
            <value>
                <fullName>Auto Renewal Without Increase</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Contract Renewal</fullName>
            </value>
            <value>
                <fullName>Customer Portal</fullName>
            </value>
            <value>
                <fullName>Data Clean-Up</fullName>
            </value>
            <value>
                <fullName>Decommission</fullName>
            </value>
            <value>
                <fullName>Eval</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Services</fullName>
            </value>
            <value>
                <fullName>Reactivation</fullName>
            </value>
            <value>
                <fullName>Renewal Within Term (No Increase)</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Subscription Renewal</fullName>
            </value>
            <value>
                <fullName>Term License</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective_Action__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Order # of this Action across all Actions in all Objectives.</inlineHelpText>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Objective_Action__c/fields/Stage_Objective__c.field-meta.xml
<CustomField>
    <fullName>Stage_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the Objective this Action is related to.</inlineHelpText>
    <label>SP Objective</label>
    <referenceTo>Stage_Objective__c</referenceTo>
    <relationshipLabel>SP Actions</relationshipLabel>
    <relationshipName>Objective_Action</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Stage__c/Opportunity_Stage__c.object-meta.xml
<CustomObject>
    <label>SP Opportunity Stage</label>
    <nameField>
        <label>Opportunity Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SP Opportunity Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Stage__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Stage</label>
    <referenceTo>Opportunity_Stage__c</referenceTo>
    <relationshipName>Opportunity_Stages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Stage__c/fields/Stage_Number__c.field-meta.xml
<CustomField>
    <fullName>Stage_Number__c</fullName>
    <inlineHelpText>Order # of this Stage in the list of Stages.</inlineHelpText>
    <label>Stage Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>Capture the oracle order information</description>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stage_Objective__c/Stage_Objective__c.object-meta.xml
<CustomObject>
    <label>SP Objective</label>
    <nameField>
        <label>SP Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SP Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Objective__c/fields/Opportunity_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Order_Type__c</fullName>
    <label>Opportunity Order Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AddOn</fullName>
            </value>
            <value>
                <fullName>Annual Increase Within Term</fullName>
            </value>
            <value>
                <fullName>Auto Renewal With Increase</fullName>
            </value>
            <value>
                <fullName>Auto Renewal Without Increase</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Contract Renewal</fullName>
            </value>
            <value>
                <fullName>Customer Portal</fullName>
            </value>
            <value>
                <fullName>Data Clean-Up</fullName>
            </value>
            <value>
                <fullName>Decommission</fullName>
            </value>
            <value>
                <fullName>Eval</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Services</fullName>
            </value>
            <value>
                <fullName>Reactivation</fullName>
            </value>
            <value>
                <fullName>Renewal Within Term (No Increase)</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Subscription Renewal</fullName>
            </value>
            <value>
                <fullName>Term License</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stage_Objective__c/fields/Opportunity_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type__c</fullName>
    <label>Opportunity Record Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CNR Sales</fullName>
            </value>
            <value>
                <fullName>Data Migration</fullName>
            </value>
            <value>
                <fullName>Eval</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>FleetRisk Advisors</fullName>
            </value>
            <value>
                <fullName>GSS Opportunity</fullName>
            </value>
            <value>
                <fullName>Indirect (Partner)</fullName>
            </value>
            <value>
                <fullName>Partner Opportunity (Reseller)</fullName>
            </value>
            <value>
                <fullName>Products, Services and Maintenance</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Services Only</fullName>
            </value>
            <value>
                <fullName>Sylectus Opportunity</fullName>
            </value>
            <value>
                <fullName>Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stage_Objective__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Opportunity Stage this Objective is related to. Required Actions cannot leave this Stage unless they have been completed.</inlineHelpText>
    <label>Opportunity Stage</label>
    <referenceTo>Opportunity_Stage__c</referenceTo>
    <relationshipName>Stage_Objective</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stage_Objective__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>Order # of this Objective.</inlineHelpText>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SP_SalesPlanValidations_Test.cls
@isTest(seeAllData = true)
public class SP_SalesPlanValidations_Test {

    public static testMethod void testAdvanceStage() {
        
        //Set up test data
        List<Account> acctList = TestDataFactory.createAcctList(1, 'SP SalesPlan Validations Account Test');
        Account acc = acctList[0];
        insert acc;
        
        Id productsAndServicesType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Products, Services and Maintenance').getRecordTypeId();
        
        Opportunity opp = new Opportunity(Name = 'Test Oppty',recordTypeID = productsAndServicesType, AccountId = acc.id, StageName = '1 - Plan', Order_Type__c = 'New', CloseDate = Date.Today());
        insert opp;
        
        Schema.DescribeFieldResult F = Opportunity.Stagename.getDescribe();
        List<Schema.PicklistEntry> P = F.getPicklistValues();  

        map<integer,string> pMap = new map<integer,string>();

        list<string> pVal = new list<string>();
        for(Schema.PicklistEntry o: P){
            pVal.add(o.getValue());   
        }
        for(integer i = 0; i<pVal.size() ;i++){
               pMap.put(i+1,pVal[i]);            
        }
        List<Opportunity_Stage__c> stgList = new List<Opportunity_Stage__c>();
        for(Integer seq : pMap.keySet()) {
            Opportunity_Stage__c stg = new Opportunity_Stage__c(Name = pMap.get(seq), Stage_Number__c = seq);
            stgList.add(stg);
        }
        insert stgList;
        /*Opportunity_Stage__c stg1 = new Opportunity_Stage__c(Name = '1 - Plan', Stage_Number__c = 1);
        Opportunity_Stage__c stg2 = new Opportunity_Stage__c(Name = '2 - Create', Stage_Number__c = 2);
        Opportunity_Stage__c stg3 = new Opportunity_Stage__c(Name = '3 - Qualify', Stage_Number__c = 3);*/
        
        
        Stage_Objective__c obj1 = new Stage_Objective__c(Name = 'Objective 1', Opportunity_Stage__c = stgList[0].Id, Order__c = 1);
        Stage_Objective__c obj2 = new Stage_Objective__c(Name = 'Objective 2', Opportunity_Stage__c = stgList[1].Id, Order__c = 2);
        Stage_Objective__c obj3 = new Stage_Objective__c(Name = 'Objective 3', Opportunity_Stage__c = stgList[2].Id, Order__c = 3);
        List<Stage_Objective__c> objList = new List<Stage_Objective__c>();
        objList.add(obj1);
        objList.add(obj2);
        objList.add(obj3);
        insert objList;
        
        Objective_Action__c act1 = new Objective_Action__c(Name = 'Not Required Action', Order__c = 1, Stage_Objective__c = obj1.Id);
        Objective_Action__c act2 = new Objective_Action__c(Name = 'Required Action', Order__c = 2, Stage_Objective__c = obj2.Id, Action_Type__c = 'Required', Opportunity_Order_Type__c = 'New');
        act2.Opportunity_Record_Type__c = 'Products, Services and Maintenance';
        List<Objective_Action__c> actList = new List<Objective_Action__c>();
        actList.add(act1);
        actList.add(act2);
        insert actList;
        
        // Begin test
        Test.startTest();
        opp.StageName = pMap.get(2);
        update opp;
        
        System.assertEquals(pMap.get(2), opp.StageName);
        
        opp.StageName = pMap.get(3);
        try {
            update opp;
        }
        catch (Exception e) {
            System.debug('Caught exception');
        }
        
        Opportunity getOpp = [SELECT StageName FROM Opportunity WHERE Id = :opp.Id LIMIT 1];
        System.assertNotEquals(pMap.get(3), getOpp.StageName);
        
        Task tsk = new Task(WhatId = opp.Id, StageObjectiveId__c = obj2.Id, ObjectiveActionID__c = act2.Id);
        tsk.Status = 'Completed';
        insert tsk;
        
        update opp;
        
        getOpp = [SELECT StageName FROM Opportunity WHERE Id = :opp.Id LIMIT 1];
        System.assertEquals(pMap.get(3), getOpp.StageName);
        
        Test.stopTest();
    }

}