force-app/main/default/objects/Objective_Action__c/Objective_Action__c.object-meta.xml
<CustomObject>
    <label>SP Action</label>
    <nameField>
        <label>SP Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SP Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective_Action__c/fields/Stage_Objective__c.field-meta.xml
<CustomField>
    <fullName>Stage_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Lookup to the Objective this Action is related to.</inlineHelpText>
    <label>SP Objective</label>
    <referenceTo>Stage_Objective__c</referenceTo>
    <relationshipLabel>SP Actions</relationshipLabel>
    <relationshipName>Objective_Action</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stage_Objective__c/Stage_Objective__c.object-meta.xml
<CustomObject>
    <label>SP Objective</label>
    <nameField>
        <label>SP Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SP Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stage_Objective__c/fields/Opportunity_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Type__c</fullName>
    <label>Opportunity Record Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CNR Sales</fullName>
            </value>
            <value>
                <fullName>Data Migration</fullName>
            </value>
            <value>
                <fullName>Eval</fullName>
            </value>
            <value>
                <fullName>Fast Track</fullName>
            </value>
            <value>
                <fullName>FleetRisk Advisors</fullName>
            </value>
            <value>
                <fullName>GSS Opportunity</fullName>
            </value>
            <value>
                <fullName>Indirect (Partner)</fullName>
            </value>
            <value>
                <fullName>Partner Opportunity (Reseller)</fullName>
            </value>
            <value>
                <fullName>Products, Services and Maintenance</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Services Only</fullName>
            </value>
            <value>
                <fullName>Sylectus Opportunity</fullName>
            </value>
            <value>
                <fullName>Transportation &amp; Logistics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SP_OpportunityActionManager_Test.cls
@isTest(seeAllData = true)
public class SP_OpportunityActionManager_Test{
    public static testMethod void testOpportunityActionManagerClass(){
    	List<Account> acctList = TestDataFactory.createAcctList(1, 'SP Account Manager Account Test');
		Account acc = acctList[0];
		insert acc;
    	List<Contact> conList = TestDataFactory.createConList(1, 'LastName');
		Contact con = conList[0];
		con.AccountId = acc.Id;
        insert con;
        Id PRODUCTSANDSERVRTYPE = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Products, Services and Maintenance').getRecordTypeId();
        Opportunity opp = new Opportunity(Name='asdasd',RecordTypeId=PRODUCTSANDSERVRTYPE,stagename='Prospecting', closedate=Date.today(), Contact__c=con.Id, AccountId=acc.Id);
        system.debug('@opp'+opp);
        insert opp;
        
        Stage_Objective__c testStageObject = new Stage_Objective__c(name='Prospecting');
        testStageObject.Opportunity_Record_Type__c = 'Products, Services and Maintenance';
        insert testStageObject;
        
        Objective_Action__c testObjectiveAction = new Objective_Action__c();
        testObjectiveAction.Stage_Objective__c = testStageObject.Id;
        testObjectiveAction.Opportunity_Record_Type__c = 'Products, Services and Maintenance';
        insert testObjectiveAction;
        
        List<Stage_Objective__c> testListStageObjective = new List<Stage_Objective__c>(); 
        testListStageObjective.add(testStageObject);
        List<Task> testListTask = new list<Task>();
        Task testTask = new Task();
  
        //insert testTask;
        
        Map<Id,Objective_Action__c> testMap = new Map<Id,Objective_Action__c>();
        Id testId;
        //OpportunityActionManager main class
        SP_OpportunityActionManager testOpportunityActionManager = new SP_OpportunityActionManager(testListStageObjective, testListTask, testMap, opp.Id);
        list<Task> opActs = testOpportunityActionManager.oppActions;
        if(testOpportunityActionManager.stageObjectives == null){}
        testOpportunityActionManager.clear();
        if(testOpportunityActionManager.commitObjectives == null){}
        if(testOpportunityActionManager.advancementCriteria == null){}
        testOpportunityActionManager.resetTasks(testListTask);
        //Objective inner class
        //system.debug('@Select Id,contact__c,Name,StageName,RecordTypeId from Opportunity'+[Select Id,contact__c,Name,StageName,RecordTypeId from Opportunity]);
        Id conId = [Select Id,contact__c,Name,StageName,RecordTypeId from Opportunity where Id =: opp.Id].contact__c;
        
        SP_OpportunityActionManager.Objective testObjective = new SP_OpportunityActionManager.Objective(testStageObject, opp.Id,conId);
        if(testObjective.actions == null){}
        if(testObjective.isEmpty){}
        testObjective.add(testTask,testObjectiveAction,0);
        //Action inner class
        SP_OpportunityActionManager.Action testAction = new SP_OpportunityActionManager.Action(testObjectiveAction, opp.Id,conId);
        if(testAction.subject == null){}
        if(testAction.committed == null){}
        testAction.linkToView();
        String testVal = '';
        Boolean testBol = testAction.requiredToAdvance;
        testVal = testAction.relatedStage;
        testVal = testAction.oppTypes;
        testVal = testAction.orderTypes;
        testVal = testAction.orderSubTypes;
        testVal = testAction.actionType;
        testBol = testAction.exemptProds;
        testVal = testAction.bgColor;
        
    }
}