force-app/main/default/objects/Partner_Scorecard__c/Partner_Scorecard__c.object-meta.xml
<CustomObject>
    <description>Captures the Scorecard values of the parent Partner Account (master) in fields</description>
    <label>Partner Scorecard</label>
    <nameField>
        <displayFormat>PS - {00000}</displayFormat>
        <label>Partner Scorecard Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Scorecard__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Refers to the Partner Account, the scorecard values of which are stored</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Scorecards</relationshipLabel>
    <relationshipName>Partner_Scorecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Current_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>Current_Scorecard__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the Partner Scorecard for a Account is the current one or not</description>
    <inlineHelpText>Enable this check-box to make the values of this Scorecard visible on the Account detail page</inlineHelpText>
    <label>Current Scorecard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Current_Year_Units_Goal__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Units_Goal__c</fullName>
    <description>Number field where the user will input the year&apos;s goal of Activated Units for the Partner</description>
    <label>Current Year Units Goal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Goal_Attainment__c.field-meta.xml
<CustomField>
    <fullName>Goal_Attainment__c</fullName>
    <description>Calculated field that is the % of the YTD Activated/Current Year Unit Goal</description>
    <formula>IF( YTD_Customer_Activated_Units__c &gt; 0, YTD_Customer_Activated_Units__c / Current_Year_Units_Goal__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Goal Attainment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Lead_Converion_Rate__c.field-meta.xml
<CustomField>
    <fullName>Lead_Converion_Rate__c</fullName>
    <description>Calculated field that determines the percent of leads that are converted to an account. Number of leads converted/ number of leads total</description>
    <formula>IF( Number_of_Leads_Total__c &gt; 0, Number_of_Leads_converted__c / Number_of_Leads_Total__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Converion Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Number_of_Leads_Active__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads_Active__c</fullName>
    <description>Count of the Number of leads that are currently active and assigned to this partner</description>
    <label>Number of Leads Active</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Number_of_Leads_converted__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads_converted__c</fullName>
    <description>Count of the Leads that were converted to an Account</description>
    <label>Number of Leads converted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Number_of_Leads_Total__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads_Total__c</fullName>
    <description>Number of Leads that are associated to this partner</description>
    <label>Number of Leads Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Number_of_Qualcomm_provided_leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Qualcomm_provided_leads__c</fullName>
    <description>Number of Leads that were generated internally (Qualcomm)</description>
    <label>Number of Omnitracs provided leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Scorecard_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_End_Date__c</fullName>
    <description>The scorecard &apos;year&apos; end date</description>
    <label>Scorecard End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Scorecard_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Start_Date__c</fullName>
    <description>The scorecard &apos;year&apos; start date</description>
    <label>Scorecard Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Total_Number_of_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Accounts__c</fullName>
    <description>Count of all the accounts owned by the Partner</description>
    <label>Total Number of Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Total_Number_of_Contracted_Customers__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Contracted_Customers__c</fullName>
    <description>Count of the number of customers who have signed a contract (those account that have a customer ID from Oracle)</description>
    <label>Total Number of Contracted Customers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Units_Closed_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Units_Closed_Won_Opportunities__c</fullName>
    <description>Count of the units on the opportunities that are in closed won status for this partner</description>
    <label>Units Closed Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/Value_Closed_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Value_Closed_Won_Opportunities__c</fullName>
    <description>Dollar Summary of the Opportunities that are in closed Won status for this Partner (Agent Only)</description>
    <label>Value Closed Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/YTD_Customer_Activated_Units__c.field-meta.xml
<CustomField>
    <fullName>YTD_Customer_Activated_Units__c</fullName>
    <description>No. of Units with an Activation Date since the start of the year</description>
    <label>YTD Customer Activated Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Scorecard__c/fields/YTD_Customer_Shipped_Units__c.field-meta.xml
<CustomField>
    <fullName>YTD_Customer_Shipped_Units__c</fullName>
    <description>Count of the number of units that were shipped to customers owned by the partner</description>
    <label>YTD Customer Total Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PartnerScorecardController.cls
/**
 * @author Avinash Kaltari, SF Developer, TCS
 * @date Sep 6, 2011
 * @description : This is a Controller to the PartnerScorecard VF Page (displayed within the Account Detail Page)& in PartnerProfile Page.
 */


public class PartnerScorecardController 
{

    public Account acc {get; set;} {acc = new Account();}
    public string partnerScoreId{get;set;}{partnerScoreId = '';}
    public List<Partner_Scorecard__c> lstPS = new List<Partner_Scorecard__c>();
    public Partner_Scorecard__c ps {get;set;} {ps= new Partner_Scorecard__c();}
    
    public PartnerScorecardController(ApexPages.StandardController controller) 
    {
//Get the current Account
        acc = (Account) controller.getRecord(); 
        
//Query to get the Current Partner Scorecard values for the current Account
        lstPS = [select name, Goal_Attainment__c, Account__c, Current_Scorecard__c, Current_Year_Units_Goal__c, Lead_Converion_Rate__c, Number_of_Leads_Active__c, Number_of_Leads_converted__c, Number_of_Leads_Total__c, Number_of_Qualcomm_provided_leads__c, Scorecard_End_Date__c, Scorecard_Start_Date__c, Total_Number_of_Accounts__c, Total_Number_of_Contracted_Customers__c, Units_Closed_Won_Opportunities__c, Value_Closed_Won_Opportunities__c, YTD_Customer_Activated_Units__c, YTD_Customer_Shipped_Units__c,LastModifiedDate,LastModifiedById from Partner_Scorecard__c where Account__c = :acc.id and Current_Scorecard__c = true limit 1];
        
//Assigning the Current Partner Scorecard(PS) record to a local variable (Used if the Page is being viewed on Detail Page)
        if(lstPS.size() > 0)
        {
            ps = lstPS[0];
            
        }
//Used if page is viewed in PartnerProfile page (which had Account ID in url)
        else if (Apexpages.CurrentPage().getParameters().containskey('id'))
        {
            lstPS = [select name, Goal_Attainment__c, Account__c, Current_Scorecard__c, Current_Year_Units_Goal__c, Lead_Converion_Rate__c, Number_of_Leads_Active__c, Number_of_Leads_converted__c, Number_of_Leads_Total__c, Number_of_Qualcomm_provided_leads__c, Scorecard_End_Date__c, Scorecard_Start_Date__c, Total_Number_of_Accounts__c, Total_Number_of_Contracted_Customers__c, Units_Closed_Won_Opportunities__c, Value_Closed_Won_Opportunities__c, YTD_Customer_Activated_Units__c, YTD_Customer_Shipped_Units__c,LastModifiedDate,LastModifiedById from Partner_Scorecard__c where Account__c = :Apexpages.CurrentPage().getParameters().get('id') and Current_Scorecard__c = true limit 1];
            if(lstPS.size() > 0)
            {
                ps = lstPS[0];
            }
        }
    }
    
    public pageReference updatePartnerScoreCard()
    {
       // system.debug('@@@@Current score card' + ps.id);
        string partnerScoreId = ps.id;
       // List<Partner_Scorecard__c> lstPS = new List<Partner_Scorecard__c>();
        if(partnerScoreId != null && partnerScoreId != '')
        {
            
          /*  lstPS = [SELECT 
                         Name
                     FROM
                         Partner_Scorecard__c
                     WHERE
                         id = :partnerScoreId
                     AND
                         Current_Scorecard__c = true 
                     LIMIT
                         50000];
            if(lstPS != null && lstPS.size() > 0) 
            {*/
                try{
                    update ps;
                    lstPS = [
                                select 
                                    name, 
                                    Goal_Attainment__c, 
                                    Account__c, 
                                    Current_Scorecard__c, 
                                    Current_Year_Units_Goal__c, 
                                    Lead_Converion_Rate__c, 
                                    Number_of_Leads_Active__c, 
                                    Number_of_Leads_converted__c, 
                                    Number_of_Leads_Total__c, 
                                    Number_of_Qualcomm_provided_leads__c, 
                                    Scorecard_End_Date__c, 
                                    Scorecard_Start_Date__c, 
                                    Total_Number_of_Accounts__c, 
                                    Total_Number_of_Contracted_Customers__c, 
                                    Units_Closed_Won_Opportunities__c, 
                                    Value_Closed_Won_Opportunities__c, 
                                    YTD_Customer_Activated_Units__c, 
                                    YTD_Customer_Shipped_Units__c,
                                    LastModifiedDate,
                                    LastModifiedById 
                                from 
                                    Partner_Scorecard__c 
                                where 
                                    ID = :ps.id 
                                limit 
                                    1
                            ];  
                    ps = lstPs[0];  
                }
                catch(Exception e)
                {
                    system.debug('Update failed......');    
                }
          // } 
            
        }
        return null;
    }
}